"""Repo observation writers and readers.

This module owns the per-session maintenance of current archive
``repos`` and ``session_repos`` rows. Repo is the deterministic
``repo_id = origin_url || char(31) || root_path`` generated by SQLite.

Population is invoked from the session-insight refresh path so the
canonical projection stays in lockstep with attribution rebuilds. The
data lives outside the session content-hash boundary by
construction — re-deriving from actions is deterministic.
"""

from __future__ import annotations

import sqlite3
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime

import aiosqlite

from polylogue.archive.session.attribution import SessionAttribution
from polylogue.archive.session.repo_identity import normalize_repo_name

__all__ = [
    "RepoObservation",
    "attribution_to_observations",
    "list_sessions_for_repo",
    "list_repos",
    "refresh_session_repos",
    "refresh_session_repos_sync",
]


@dataclass(frozen=True, slots=True)
class RepoObservation:
    """One (session, repo) observation prepared for upsert."""

    origin_url: str
    root_path: str
    repo_name: str
    branch_name: str


def _utc_now_ms() -> int:
    return int(datetime.now(UTC).timestamp() * 1000)


def _repo_id(observation: RepoObservation) -> str:
    return f"{observation.origin_url}\x1f{observation.root_path}"


def attribution_to_observations(
    attribution: SessionAttribution,
    *,
    git_repository_url: str | None = None,
) -> tuple[RepoObservation, ...]:
    """Translate an attribution bundle into deduplicated repo observations.

    A single session that touched multiple repo roots yields one
    observation per root. ``git_repository_url`` (typed sessions
    column) is associated with every root because the parsers cannot
    currently tell which root the origin URL points at — the join
    surface treats this as best-effort attribution.
    """
    origin_url = (git_repository_url or "").strip()
    branch_name = attribution.branch_names[0] if attribution.branch_names else ""
    observations: list[RepoObservation] = []
    seen: set[tuple[str, str]] = set()
    for root_path in attribution.repo_paths:
        root = root_path.strip()
        if not root:
            continue
        key = (origin_url, root)
        if key in seen:
            continue
        seen.add(key)
        observations.append(
            RepoObservation(
                origin_url=origin_url,
                root_path=root,
                repo_name=normalize_repo_name(root) or root.rstrip("/").rsplit("/", 1)[-1],
                branch_name=branch_name,
            )
        )
    # Some sources (e.g. ChatGPT mentions of GitHub URLs) carry an
    # origin URL but no resolvable local root. Surface the origin
    # anyway so the cross-source "all sessions touching repo X"
    # query can find them, keyed by an empty root_path.
    if origin_url and not observations:
        observations.append(
            RepoObservation(
                origin_url=origin_url,
                root_path="",
                repo_name=normalize_repo_name(origin_url) or "",
                branch_name=branch_name,
            )
        )
    return tuple(observations)


async def _upsert_repo_async(
    conn: aiosqlite.Connection,
    observation: RepoObservation,
    *,
    observed_at_ms: int,
) -> str:
    await conn.execute(
        """
        INSERT INTO repos (origin_url, root_path, repo_name, first_seen_at_ms, last_seen_at_ms)
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT(origin_url, root_path) DO UPDATE SET
            repo_name = COALESCE(excluded.repo_name, repos.repo_name),
            first_seen_at_ms = MIN(repos.first_seen_at_ms, excluded.first_seen_at_ms),
            last_seen_at_ms = MAX(repos.last_seen_at_ms, excluded.last_seen_at_ms)
        """,
        (
            observation.origin_url,
            observation.root_path,
            observation.repo_name,
            observed_at_ms,
            observed_at_ms,
        ),
    )
    return _repo_id(observation)


async def refresh_session_repos(
    conn: aiosqlite.Connection,
    session_id: str,
    observations: Sequence[RepoObservation],
    *,
    now_iso: str | None = None,
) -> int:
    """Replace the repo observations for ``session_id``.

    Returns the number of observation rows written. Existing rows for
    this session are deleted before insertion so the projection
    cannot drift on rebuild.
    """
    timestamp = _utc_now_ms()
    await conn.execute(
        "DELETE FROM session_repos WHERE session_id = ?",
        (session_id,),
    )
    if not observations:
        return 0
    written = 0
    for observation in observations:
        repo_id = await _upsert_repo_async(conn, observation, observed_at_ms=timestamp)
        await conn.execute(
            "INSERT OR REPLACE INTO session_repos "
            "(session_id, repo_id, branch_name, observed_at_ms) "
            "VALUES (?, ?, ?, ?)",
            (session_id, repo_id, observation.branch_name, timestamp),
        )
        written += 1
    return written


def _upsert_repo_sync(
    conn: sqlite3.Connection,
    observation: RepoObservation,
    *,
    observed_at_ms: int,
) -> str:
    conn.execute(
        """
        INSERT INTO repos (origin_url, root_path, repo_name, first_seen_at_ms, last_seen_at_ms)
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT(origin_url, root_path) DO UPDATE SET
            repo_name = COALESCE(excluded.repo_name, repos.repo_name),
            first_seen_at_ms = MIN(repos.first_seen_at_ms, excluded.first_seen_at_ms),
            last_seen_at_ms = MAX(repos.last_seen_at_ms, excluded.last_seen_at_ms)
        """,
        (
            observation.origin_url,
            observation.root_path,
            observation.repo_name,
            observed_at_ms,
            observed_at_ms,
        ),
    )
    return _repo_id(observation)


def refresh_session_repos_sync(
    conn: sqlite3.Connection,
    session_id: str,
    observations: Sequence[RepoObservation],
    *,
    now_iso: str | None = None,
) -> int:
    """Sync sibling of :func:`refresh_session_repos`."""
    timestamp = _utc_now_ms()
    conn.execute(
        "DELETE FROM session_repos WHERE session_id = ?",
        (session_id,),
    )
    if not observations:
        return 0
    written = 0
    for observation in observations:
        repo_id = _upsert_repo_sync(conn, observation, observed_at_ms=timestamp)
        conn.execute(
            "INSERT OR REPLACE INTO session_repos "
            "(session_id, repo_id, branch_name, observed_at_ms) "
            "VALUES (?, ?, ?, ?)",
            (session_id, repo_id, observation.branch_name, timestamp),
        )
        written += 1
    return written


async def list_repos(
    conn: aiosqlite.Connection,
    *,
    repo_name: str | None = None,
) -> tuple[dict[str, object], ...]:
    """Enumerate repos, optionally filtered by ``repo_name``."""
    if repo_name:
        cursor = await conn.execute(
            "SELECT repo_id AS id, origin_url, root_path, repo_name, first_seen_at_ms, last_seen_at_ms "
            "FROM repos WHERE repo_name = ? ORDER BY repo_id",
            (repo_name,),
        )
    else:
        cursor = await conn.execute(
            "SELECT repo_id AS id, origin_url, root_path, repo_name, first_seen_at_ms, last_seen_at_ms FROM repos ORDER BY repo_id",
        )
    rows = await cursor.fetchall()
    # sqlite3.Row iteration yields values, not keys — surface columns
    # by name through ``.keys()``.
    return tuple({key: row[key] for key in list(row.keys())} for row in rows)


async def list_sessions_for_repo(
    conn: aiosqlite.Connection,
    *,
    origin_url: str | None = None,
    root_path: str | None = None,
    repo_name: str | None = None,
) -> tuple[str, ...]:
    """Return session IDs touching the matching repo.

    At least one of ``origin_url``, ``root_path``, or ``repo_name`` must
    be supplied; results are the union across all matching repos.
    """
    conditions: list[str] = []
    params: list[object] = []
    if origin_url is not None:
        conditions.append("r.origin_url = ?")
        params.append(origin_url)
    if root_path is not None:
        conditions.append("r.root_path = ?")
        params.append(root_path)
    if repo_name is not None:
        conditions.append("r.repo_name = ?")
        params.append(repo_name)
    if not conditions:
        raise ValueError("list_sessions_for_repo requires at least one filter")
    where = " AND ".join(conditions)
    cursor = await conn.execute(
        "SELECT DISTINCT sr.session_id "
        "FROM session_repos sr "
        "JOIN repos r ON r.repo_id = sr.repo_id "
        f"WHERE {where} "
        "ORDER BY sr.session_id",
        params,
    )
    rows = await cursor.fetchall()
    return tuple(str(row["session_id"]) for row in rows)
