"""Render `polylogue --help` (and every subcommand help) as Markdown (#1274).

Used by the root ``--help-markdown`` flag and by ``devtools render-cli-reference``
so docs can transclude the same source of truth that the terminal renders.
"""

from __future__ import annotations

from collections.abc import Iterable

import click


def _command_path(parts: Iterable[str]) -> str:
    pieces = ["polylogue", *parts]
    return " ".join(pieces)


def _heading_level(parts: tuple[str, ...]) -> int:
    # Root help is H1, every subcommand level is one deeper, capped at H6.
    return min(1 + len(parts), 6)


def _emit(command: click.Command, ctx: click.Context, path: tuple[str, ...], parts: list[str]) -> None:
    help_text = command.get_help(ctx).rstrip()
    level = _heading_level(path)
    parts.append(f"{'#' * level} `{_command_path(path)}`")
    parts.append("")
    parts.append("```text")
    parts.append(help_text)
    parts.append("```")
    parts.append("")

    if isinstance(command, click.Group):
        for sub_name in sorted(command.list_commands(ctx)):
            sub = command.get_command(ctx, sub_name)
            if sub is None or sub.hidden:
                continue
            sub_ctx = click.Context(sub, info_name=sub_name, parent=ctx)
            _emit(sub, sub_ctx, path + (sub_name,), parts)


def render_help_markdown(root: click.Command, *, prog_name: str = "polylogue") -> str:
    """Render ``root`` and every subcommand's ``--help`` text as Markdown.

    The output begins with an H1 heading and contains one fenced code block
    per command. Suitable for transclusion into ``docs/cli-reference.md`` or
    similar documentation surfaces.
    """
    parts: list[str] = [
        f"<!-- Generated by `{prog_name} --help-markdown`. -->",
        "",
    ]
    ctx = click.Context(root, info_name=prog_name)
    _emit(root, ctx, (), parts)
    return "\n".join(parts).rstrip() + "\n"


__all__ = ["render_help_markdown"]
