"""First-run setup: auto-detect chat sources and write a starter config.

The ``polylogue init`` command is a turnkey onboarding step. It scans
known chat-export locations (Claude Code, Codex, Gemini CLI, Hermes,
Antigravity, agent hook spool) and writes a starter ``polylogue.toml``
into ``$XDG_CONFIG_HOME/polylogue/`` so the daemon and CLI agree on
the source set without the user reading docs.

The command is read-only with respect to source directories — it only
records what already exists. Writing the config file is the single
side effect. Existing files are preserved unless ``--force`` is given.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import click

from polylogue.cli.shared.types import AppEnv


@dataclass(frozen=True, slots=True)
class DetectedSource:
    """One auto-detected chat-export source root.

    ``present`` is the boolean evidence that decides whether the
    source ends up in the rendered TOML. ``family`` mirrors the
    provider/source family token used by the live watcher so the
    daemon and the CLI use the same vocabulary.
    """

    family: str
    path: Path
    present: bool
    description: str


def detect_chat_sources() -> tuple[DetectedSource, ...]:
    """Return the canonical chat-source candidates with presence flags.

    The presence check is ``Path.is_dir()``. Symlinks count if they
    resolve to a directory. The function never raises — missing
    parents simply produce ``present=False`` entries so callers can
    distinguish "didn't look" from "looked, nothing there".
    """
    from polylogue.paths import (
        antigravity_path,
        claude_code_path,
        codex_path,
        gemini_cli_path,
        hermes_sessions_path,
        hooks_sidecar_dir,
    )

    candidates: tuple[tuple[str, Path, str], ...] = (
        ("claude-code", claude_code_path(), "Claude Code session JSONL"),
        ("codex", codex_path(), "Codex session JSONL"),
        ("gemini-cli", gemini_cli_path(), "Gemini CLI workspace exports"),
        ("hermes", hermes_sessions_path(), "Hermes agent state.db and fallback session exports"),
        ("antigravity", antigravity_path(), "Antigravity brain artifacts"),
        ("hooks", hooks_sidecar_dir(), "Agent hook sidecar spool"),
    )
    detected: list[DetectedSource] = []
    for family, path, description in candidates:
        try:
            present = path.is_dir()
        except OSError:
            present = False
        detected.append(
            DetectedSource(
                family=family,
                path=path,
                present=present,
                description=description,
            )
        )
    return tuple(detected)


def render_starter_toml(detected: tuple[DetectedSource, ...]) -> str:
    """Render a ``polylogue.toml`` body from the detected sources.

    Only present sources are emitted as active entries; absent
    sources are written as commented hints so the user can uncomment
    them once the chat tool is installed without having to re-read
    docs to know the path.
    """
    from polylogue.paths import archive_root

    lines: list[str] = [
        "# Polylogue configuration — generated by `polylogue init`.",
        "# Edit freely; the CLI and the daemon both read this file.",
        "",
        "[archive]",
        f'root = "{archive_root()}"',
        "",
        "[sources]",
        "# Auto-detected chat source roots. Add or remove freely.",
    ]
    present = [d for d in detected if d.present]
    absent = [d for d in detected if not d.present]
    if present:
        rendered = ", ".join(f'"{d.path}"' for d in present)
        lines.append(f"roots = [{rendered}]")
    else:
        lines.append("roots = []")
    if absent:
        lines.append("")
        lines.append("# Absent on this machine. Uncomment after installing the tool:")
        for d in absent:
            lines.append(f'#   "{d.path}"   # {d.description}')
    lines.append("")
    lines.append("[daemon]")
    lines.append('host = "127.0.0.1"')
    lines.append("port = 8766")
    lines.append("")
    return "\n".join(lines)


def starter_config_path() -> Path:
    """Return the XDG path where ``polylogue init`` writes the starter file."""
    from polylogue.paths import config_home

    return config_home() / "polylogue.toml"


@click.command("init")
@click.option(
    "--force",
    is_flag=True,
    help="Overwrite an existing polylogue.toml.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Print what would be written without touching the filesystem.",
)
@click.option(
    "--format",
    "-f",
    "output_format",
    type=click.Choice(["text", "json"]),
    default="text",
    help="Output format.",
)
@click.pass_obj
def init_command(
    env: AppEnv,
    force: bool,
    dry_run: bool,
    output_format: str,
) -> None:
    """Detect chat sources and write a starter polylogue.toml.

    Run once on a fresh install. Looks for Claude Code, Codex, Gemini
    CLI, Hermes, Antigravity, and the agent hook spool under your home
    directory and records the present ones in
    ``$XDG_CONFIG_HOME/polylogue/polylogue.toml``. The daemon and the
    CLI both pick the file up automatically.
    """
    detected = detect_chat_sources()
    target = starter_config_path()
    body = render_starter_toml(detected)

    present_families = [d.family for d in detected if d.present]
    payload: dict[str, object] = {
        "config_path": str(target),
        "exists": target.exists(),
        "force": force,
        "dry_run": dry_run,
        "detected": [
            {
                "family": d.family,
                "path": str(d.path),
                "present": d.present,
                "description": d.description,
            }
            for d in detected
        ],
        "present_families": present_families,
    }

    will_write = not dry_run and (force or not target.exists())
    payload["written"] = False
    if will_write:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        payload["written"] = True
    payload["body"] = body

    if output_format == "json":
        env.ui.console.print(json.dumps(payload, indent=2, default=str), markup=False, highlight=False)
        return

    console = env.ui.console
    console.print("\n[bold]polylogue init[/bold]")
    for d in detected:
        marker = "[green]✓[/green]" if d.present else "[dim]·[/dim]"
        console.print(f"  {marker} {d.family:<12s} {d.path}")
    if not present_families:
        console.print(
            "\n[yellow]No chat directories detected.[/yellow]"
            " The starter config will list the canonical paths as comments."
        )
    if dry_run:
        console.print(f"\n[dim](dry-run)[/dim] Would write {target}:")
        console.print(body, markup=False, highlight=False)
        return
    if target.exists() and not force:
        console.print(
            f"\n[yellow]Config already exists at {target}.[/yellow]"
            " Re-run with [bold]--force[/bold] to overwrite, or edit by hand."
        )
        return
    console.print(f"\n[green]Wrote starter config to {target}[/green]")
    console.print(
        "\nNext steps:\n"
        "  1. [bold]polylogued run[/bold]   — start the ingest daemon\n"
        "  2. [bold]polylogue ops status[/bold] — check archive health\n"
        "  3. [bold]polylogue 'query terms'[/bold] — search\n"
    )


__all__ = [
    "DetectedSource",
    "detect_chat_sources",
    "init_command",
    "render_starter_toml",
    "starter_config_path",
]
