"""Small public root for conversation query families."""

from __future__ import annotations

from polylogue.storage.sqlite.queries.conversations_identity import (
    add_mark,
    conversation_id_query,
    count_conversation_ids,
    delete_recall_pack,
    delete_view,
    get_last_sync_timestamp,
    get_metadata,
    get_recall_pack,
    get_view,
    get_view_by_name,
    iter_conversation_ids,
    list_marks,
    list_recall_packs,
    list_tags,
    list_views,
    remove_mark,
    resolve_id,
    save_recall_pack,
    save_view,
    set_metadata,
    update_metadata_raw,
)
from polylogue.storage.sqlite.queries.conversations_reads import (
    count_conversations,
    get_conversation,
    get_conversations_batch,
    list_conversation_summaries,
    list_conversations,
    list_conversations_by_parent,
)
from polylogue.storage.sqlite.queries.conversations_search import (
    search_action_conversation_hits,
    search_action_conversations,
    search_conversation_evidence_hits,
    search_conversation_hits,
    search_conversations,
)
from polylogue.storage.sqlite.queries.conversations_writes import (
    conversation_exists_by_hash,
    delete_conversation_sql,
    save_conversation_record,
)

__all__ = [
    "add_mark",
    "conversation_exists_by_hash",
    "conversation_id_query",
    "count_conversation_ids",
    "count_conversations",
    "delete_conversation_sql",
    "delete_recall_pack",
    "delete_view",
    "get_conversation",
    "get_conversations_batch",
    "get_last_sync_timestamp",
    "get_metadata",
    "get_recall_pack",
    "get_view",
    "get_view_by_name",
    "iter_conversation_ids",
    "list_conversation_summaries",
    "list_conversations",
    "list_conversations_by_parent",
    "list_marks",
    "list_recall_packs",
    "list_tags",
    "list_views",
    "remove_mark",
    "resolve_id",
    "save_conversation_record",
    "save_recall_pack",
    "save_view",
    "search_action_conversation_hits",
    "search_action_conversations",
    "search_conversation_evidence_hits",
    "search_conversation_hits",
    "search_conversations",
    "set_metadata",
    "update_metadata_raw",
]
