"""Small public root for session query families."""

from __future__ import annotations

from polylogue.storage.sqlite.queries.sessions_identity import (
    add_mark,
    count_session_ids,
    delete_annotation,
    delete_recall_pack,
    delete_view,
    delete_workspace,
    get_annotation,
    get_last_sync_timestamp,
    get_metadata,
    get_recall_pack,
    get_view,
    get_view_by_name,
    get_workspace,
    iter_session_ids,
    list_annotations,
    list_marks,
    list_recall_packs,
    list_tags,
    list_views,
    list_workspaces,
    remove_mark,
    resolve_id,
    save_annotation,
    save_recall_pack,
    save_view,
    save_workspace,
    session_id_query,
    set_metadata,
    update_metadata_raw,
)
from polylogue.storage.sqlite.queries.sessions_reads import (
    count_sessions,
    get_session,
    get_sessions_batch,
    list_session_summaries,
    list_sessions,
    list_sessions_by_parent,
)
from polylogue.storage.sqlite.queries.sessions_search import (
    search_action_session_hits,
    search_action_sessions,
    search_session_evidence_hits,
    search_session_hits,
    search_sessions,
)
from polylogue.storage.sqlite.queries.sessions_writes import (
    delete_session_sql,
    save_session_record,
    session_exists_by_hash,
)

__all__ = [
    "add_mark",
    "session_exists_by_hash",
    "session_id_query",
    "count_session_ids",
    "delete_annotation",
    "count_sessions",
    "delete_session_sql",
    "delete_recall_pack",
    "delete_view",
    "delete_workspace",
    "get_session",
    "get_sessions_batch",
    "get_last_sync_timestamp",
    "get_annotation",
    "get_metadata",
    "get_recall_pack",
    "get_view",
    "get_view_by_name",
    "get_workspace",
    "iter_session_ids",
    "list_annotations",
    "list_session_summaries",
    "list_sessions",
    "list_sessions_by_parent",
    "list_marks",
    "list_recall_packs",
    "list_tags",
    "list_views",
    "list_workspaces",
    "remove_mark",
    "resolve_id",
    "save_session_record",
    "save_annotation",
    "save_recall_pack",
    "save_view",
    "save_workspace",
    "search_action_session_hits",
    "search_action_sessions",
    "search_session_evidence_hits",
    "search_session_hits",
    "search_sessions",
    "set_metadata",
    "update_metadata_raw",
]
