"""Proof-obligation kernel for Polylogue verification surfaces."""

from polylogue.proof.catalog import (
    VerificationCatalog,
    build_verification_catalog,
    catalog_quality_checks,
    compile_obligations,
    default_claims,
    default_runner_bindings,
)
from polylogue.proof.models import (
    And,
    AttrContains,
    AttrEq,
    AttrIn,
    BreakerMetadata,
    Claim,
    EnvironmentContract,
    EvidenceEnvelope,
    Kind,
    Not,
    Or,
    ProofObligation,
    RunnerBinding,
    SourceSpan,
    SubjectQuery,
    SubjectRef,
    TrustMetadata,
    subject_query_from_payload,
)
from polylogue.proof.subjects import (
    SELECTED_SCHEMA_ANNOTATIONS,
    build_catalog_subjects,
    command_subjects,
    schema_annotation_subjects,
)

__all__ = [
    "And",
    "AttrContains",
    "AttrEq",
    "AttrIn",
    "BreakerMetadata",
    "Claim",
    "EnvironmentContract",
    "EvidenceEnvelope",
    "Kind",
    "Not",
    "Or",
    "ProofObligation",
    "RunnerBinding",
    "SELECTED_SCHEMA_ANNOTATIONS",
    "SourceSpan",
    "SubjectQuery",
    "SubjectRef",
    "TrustMetadata",
    "VerificationCatalog",
    "build_catalog_subjects",
    "build_verification_catalog",
    "catalog_quality_checks",
    "command_subjects",
    "compile_obligations",
    "default_claims",
    "default_runner_bindings",
    "schema_annotation_subjects",
    "subject_query_from_payload",
]
