"""Markdown rendering for the verification catalog."""

from __future__ import annotations

from collections import Counter

from devtools.command_catalog import control_plane_command
from polylogue.lib.outcomes import OutcomeCheck
from polylogue.proof.catalog import VerificationCatalog
from polylogue.proof.models import Claim, RunnerBinding, SubjectRef


def build_catalog_markdown(catalog: VerificationCatalog) -> str:
    """Render a concise human-readable catalog document."""
    lines = [
        "[← Back to README](../README.md)",
        "",
        f"<!-- Generated by `{control_plane_command('render-verification-catalog')}`. Edit polylogue/proof/ and devtools/render_verification_catalog.py instead. -->",
        "",
        "# Verification Catalog",
        "",
        "This catalog is generated from the proof-obligation kernel. It records subjects, claims, runner bindings, and compiled proof obligations without executing evidence runners.",
        "",
        "## Snapshot",
        "",
        f"- subjects: `{len(catalog.subjects)}`",
        f"- claims: `{len(catalog.claims)}`",
        f"- runner bindings: `{len(catalog.runner_bindings)}`",
        f"- proof obligations: `{len(catalog.obligations)}`",
        "",
        "## Quality Checks",
        "",
        *_render_quality_checks(catalog.quality_checks),
        "",
        "## Subject Summary",
        "",
        *_render_subject_summary(catalog),
        "",
        "## Command Subjects",
        "",
        *_render_command_subjects(catalog.subjects),
        "",
        "## Schema Annotation Subjects",
        "",
        *_render_schema_subject_summary(catalog.subjects),
        "",
        "## Provider Capability Subjects",
        "",
        *_render_provider_capability_subjects(catalog.subjects),
        "",
        "## Generated Scenario Subjects",
        "",
        *_render_generated_scenario_subjects(catalog.subjects),
        "",
        "## Assurance Coverage Subjects",
        "",
        *_render_coverage_subjects(catalog.subjects),
        "",
        "## Claims",
        "",
        *_render_claims(catalog.claims),
        "",
        "## Runner Bindings",
        "",
        *_render_runner_bindings(catalog.runner_bindings),
        "",
        "## Proof Obligations",
        "",
        *_render_obligation_summary(catalog),
        "",
    ]
    return "\n".join(lines)


def _render_quality_checks(checks: tuple[OutcomeCheck, ...]) -> list[str]:
    lines = [
        "| Check | Status | Detail |",
        "| --- | --- | --- |",
    ]
    for check in checks:
        lines.append(f"| `{check.name}` | `{check.status.value}` | {check.summary} |")
    return lines


def _render_subject_summary(catalog: VerificationCatalog) -> list[str]:
    lines = [
        "| Kind | Count |",
        "| --- | ---: |",
    ]
    for kind, count in sorted(catalog.subjects_by_kind().items()):
        lines.append(f"| `{kind}` | {count} |")
    return lines


def _render_command_subjects(subjects: tuple[SubjectRef, ...]) -> list[str]:
    command_subjects = [subject for subject in subjects if subject.kind == "cli.command"]
    lines = [
        "| Command | Source |",
        "| --- | --- |",
    ]
    for subject in command_subjects:
        source = _format_source(subject)
        lines.append(f"| `{subject.id}` | {source} |")
    return lines


def _render_schema_subject_summary(subjects: tuple[SubjectRef, ...]) -> list[str]:
    rows: Counter[tuple[str, str, str]] = Counter()
    examples: dict[tuple[str, str, str], str] = {}
    for subject in subjects:
        if subject.kind != "schema.annotation":
            continue
        provider = _string_attr(subject, "provider")
        element_kind = _string_attr(subject, "element_kind")
        annotation = _string_attr(subject, "annotation")
        key = (provider, element_kind, annotation)
        rows[key] += 1
        examples.setdefault(key, subject.id)

    lines = [
        "| Provider | Element | Annotation | Count | Example Subject |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for (provider, element_kind, annotation), count in sorted(rows.items()):
        lines.append(
            f"| `{provider}` | `{element_kind}` | `{annotation}` | {count} | `{examples[(provider, element_kind, annotation)]}` |"
        )
    return lines


def _render_provider_capability_subjects(subjects: tuple[SubjectRef, ...]) -> list[str]:
    provider_subjects = [subject for subject in subjects if subject.kind == "provider.capability"]
    lines = [
        "| Provider | Parser Identity | Reasoning | Streaming | Sidecars | Explicit Gaps |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for subject in provider_subjects:
        coverage = subject.attrs.get("coverage_facets")
        sidecars = ""
        if isinstance(coverage, dict):
            sidecar_value = coverage.get("sidecars")
            sidecars = sidecar_value if isinstance(sidecar_value, str) else ""
        gaps = subject.attrs.get("partial_coverage")
        gap_list = tuple(str(item) for item in gaps) if isinstance(gaps, list) else ()
        lines.append(
            f"| `{_string_attr(subject, 'provider')}` | {_string_attr(subject, 'parser_identity')} | "
            f"{_string_attr(subject, 'reasoning_capability')} | {_string_attr(subject, 'streaming_capability')} | "
            f"`{sidecars}` | {_code_list(gap_list)} |"
        )
    return lines


def _render_generated_scenario_subjects(subjects: tuple[SubjectRef, ...]) -> list[str]:
    generated_subjects = [subject for subject in subjects if subject.kind == "generated.scenario_family"]
    lines = [
        "| Scenario Family | Status | Generated World | Workload | Claims |",
        "| --- | --- | --- | --- | --- |",
    ]
    for subject in generated_subjects:
        semantic_claims = subject.attrs.get("semantic_claims")
        claim_names: tuple[str, ...] = ()
        if isinstance(semantic_claims, list):
            claim_names = tuple(
                str(claim.get("family", ""))
                for claim in semantic_claims
                if isinstance(claim, dict) and str(claim.get("family", "")).strip()
            )
        lines.append(
            f"| `{subject.id}` | `{_string_attr(subject, 'status')}` | {_string_attr(subject, 'generated_world')} | "
            f"{_string_attr(subject, 'workload_family')} | {_code_list(claim_names[:4])} |"
        )
    return lines


def _render_coverage_subjects(subjects: tuple[SubjectRef, ...]) -> list[str]:
    rows: Counter[tuple[str, str]] = Counter()
    for subject in subjects:
        if not subject.kind.startswith("assurance.coverage_"):
            continue
        domain = _string_attr(subject, "assurance_domain") or "unclassified"
        rows[(domain, subject.kind)] += 1

    lines = [
        "| Domain | Subject Kind | Count |",
        "| --- | --- | ---: |",
    ]
    for (domain, kind), count in sorted(rows.items()):
        lines.append(f"| `{domain}` | `{kind}` | {count} |")
    return lines


def _render_claims(claims: tuple[Claim, ...]) -> list[str]:
    lines = [
        "| Claim | Severity | Bug Classes | Breaker / Exception |",
        "| --- | --- | --- | --- |",
    ]
    for claim in claims:
        bug_classes = _code_list(claim.bug_classes)
        breaker = claim.breaker.description if claim.breaker is not None else f"tracked: {claim.tracked_exception}"
        lines.append(f"| `{claim.id}` | `{claim.severity}` | {bug_classes} | {breaker} |")
    return lines


def _render_runner_bindings(runners: tuple[RunnerBinding, ...]) -> list[str]:
    lines = [
        "| Runner Binding | Claim | Evidence | Cost | Environment | Trust |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for runner in runners:
        env_bits = [
            f"commands={_code_list(runner.environment.required_commands)}",
            f"controlled_dims=`{len(runner.environment.controlled_dimensions)}`",
            f"uncontrolled_dims=`{len(runner.environment.uncontrolled_dimensions)}`",
            f"network=`{runner.environment.network}`",
            f"live_archive=`{runner.environment.live_archive}`",
        ]
        trust = f"`{runner.trust.level}` by `{runner.trust.producer}` at `{runner.trust.reviewed_at}`"
        lines.append(
            f"| `{runner.id}` | `{runner.claim_id}` | `{runner.evidence_class}` | `{runner.cost_tier}` | {'; '.join(env_bits)} | {trust} |"
        )
    return lines


def _render_obligation_summary(catalog: VerificationCatalog) -> list[str]:
    lines = [
        "| Claim | Obligations |",
        "| --- | ---: |",
    ]
    for claim_id, count in sorted(catalog.obligations_by_claim().items()):
        lines.append(f"| `{claim_id}` | {count} |")
    return lines


def _format_source(subject: SubjectRef) -> str:
    if subject.source_span is None:
        return "`<missing>`"
    line = "" if subject.source_span.line is None else f":{subject.source_span.line}"
    symbol = "" if subject.source_span.symbol is None else f" `{subject.source_span.symbol}`"
    return f"`{subject.source_span.path}{line}`{symbol}"


def _string_attr(subject: SubjectRef, name: str) -> str:
    value = subject.attrs.get(name)
    return value if isinstance(value, str) else ""


def _code_list(items: tuple[str, ...]) -> str:
    if not items:
        return "—"
    return "<br>".join(f"`{item}`" for item in items)


__all__ = ["build_catalog_markdown"]
