"""Session-profile inference and builder runtime."""

from __future__ import annotations

import json as _json
import time
from collections import Counter
from collections.abc import Callable
from dataclasses import replace
from datetime import datetime
from typing import TYPE_CHECKING, NamedTuple

from polylogue.archive.actions.parsing import tool_result_block_outcome
from polylogue.archive.phase.extraction import extract_phases
from polylogue.archive.semantic.facts import build_session_semantic_facts
from polylogue.archive.semantic.timing import compute_session_timing, compute_tool_active_duration_ms
from polylogue.archive.session.attribution import extract_attribution
from polylogue.archive.session.extraction import extract_work_events
from polylogue.archive.session.models import SessionAnalysis, SessionProfile
from polylogue.core.enums import Origin

if TYPE_CHECKING:
    from polylogue.archive.models import Session
    from polylogue.archive.semantic.cost_records import SessionCostBreakdown, SessionCostSummary
    from polylogue.archive.semantic.facts import SessionSemanticFacts


def _primary_model(cost_summary: SessionCostSummary) -> tuple[str | None, str | None]:
    """Return (primary_model_name, primary_model_family): the SESSION-WIDE
    dominant model by assistant output-token share, and its canonical
    family. This is a session-level aggregate, not a per-turn claim --
    polylogue-4c27 explicitly excludes it from dispatch-turn/requested/
    child-observed model identity in the `delegations` view; it remains the
    named fallback (`parent_session_dominant_model`/
    `child_session_dominant_model`) for when no finer-grained attribution is
    available. Reuses the per-model tally cost_compute already builds -- no
    separate pass over messages."""
    from polylogue.archive.semantic.pricing import canonical_model_family

    dominant: SessionCostBreakdown | None = None
    for breakdown in cost_summary.per_model:
        if dominant is None or breakdown.output_tokens > dominant.output_tokens:
            dominant = breakdown
    if dominant is None or dominant.output_tokens <= 0:
        return None, None
    model_name = dominant.provider_model_name or dominant.normalized_model
    return model_name, canonical_model_family(model_name)


def _profile_timestamp_bounds(
    session: Session,
    facts: SessionSemanticFacts,
) -> tuple[datetime | None, datetime | None, str]:
    """Resolve (first_message_at, last_message_at, source) for a session.

    Order of preference:
      1. facts.{first,last}_message_at — provider-supplied per-message
         timestamps, the strongest signal.
      2. session_event timestamps — codex pre-Dec-2025 has empty
         message-level timestamps but rich session_events with timestamps.
         Mining those yields a real session window instead of forcing a
         single-instant fallback.
      3. session.{created,updated}_at — last resort when neither
         messages nor events have timestamps.
    """
    if facts.first_message_at is not None or facts.last_message_at is not None:
        return (
            facts.first_message_at or facts.last_message_at,
            facts.last_message_at or facts.first_message_at,
            "provider_supplied",
        )
    # Codex pre-Dec-2025: messages carry no timestamps, but session_events
    # (function_call, response_item, session_meta) do. Use them to derive
    # a real session window rather than collapsing to a single session
    # timestamp.
    event_timestamps: list[datetime] = [
        event.timestamp for event in session.session_events if event.timestamp is not None
    ]
    if event_timestamps:
        return (
            min(event_timestamps),
            max(event_timestamps),
            "session_events_fallback",
        )
    session_start = session.created_at or session.updated_at
    session_end = session.updated_at or session.created_at
    if session_start is not None or session_end is not None:
        return (
            session_start or session_end,
            session_end or session_start,
            "session_timestamp_fallback",
        )
    return (None, None, "absent")


_TOPIC_PREFIXES = (
    "Caveat: The messages below were generated by the user while running local commands.",
    "Caveat: The messages below are were generated by the user while running local commands.",
    "[SUGGESTION MODE: Suggest what the user might naturally type next into Claude Code.",
    "This session is being continued from a previous session that ran out of context.",
    "Base directory for this skill:",
)
_TOPIC_MAX_CHARS = 120
_CODEX_TOPIC_TEXT_CHARS = 60


def _clean_topic_text(value: str | None, *, width: int = _TOPIC_MAX_CHARS) -> str | None:
    text = " ".join(str(value or "").split()).strip()
    if not text:
        return None
    for prefix in _TOPIC_PREFIXES:
        if text.startswith(prefix):
            text = text[len(prefix) :].strip(" :-")
            break
    if not text:
        return None
    return text[:width].rstrip()


def _first_substantive_user_turn(analysis: SessionAnalysis) -> str | None:
    fallback_user_turn: str | None = None
    for message in analysis.facts.message_facts:
        # Accept HUMAN_AUTHORED|UNKNOWN user turns: a genuine unmarked prompt is
        # now UNKNOWN (not fabricated HUMAN_AUTHORED), but known non-human user
        # rows (tool results, runtime context/protocol, generated packs) are
        # still excluded. Topic inference is a heuristic, not an authorship claim.
        if not message.is_candidate_human_authored:
            continue
        cleaned = _clean_topic_text(message.text)
        if cleaned is None:
            continue
        if fallback_user_turn is None:
            fallback_user_turn = cleaned
        if message.is_substantive and not message.is_noise:
            return cleaned
    if fallback_user_turn is not None:
        return fallback_user_turn
    return None


def _infer_topic(
    session: Session,
    analysis: SessionAnalysis,
    *,
    repo_names: tuple[str, ...],
) -> tuple[str | None, str]:
    first_user_turn = _first_substantive_user_turn(analysis)
    if session.origin == Origin.CODEX_SESSION and first_user_turn and repo_names:
        return (f"{repo_names[0]} — {first_user_turn[:_CODEX_TOPIC_TEXT_CHARS].rstrip()}", "repo_plus_first_user_turn")
    if first_user_turn:
        return (first_user_turn, "first_substantive_user_turn")
    cleaned_title = _clean_topic_text(session.title)
    if cleaned_title:
        return (cleaned_title, "cleaned_title")
    return (None, "absent")


def _workflow_shape(
    analysis: SessionAnalysis, *, compaction_count: int, tool_active_duration_ms: int
) -> tuple[str, float, dict[str, int | float | str]]:
    facts = analysis.facts
    message_count = max(facts.total_messages, 1)
    category_counts = facts.tool_category_counts
    tool_call_count = sum(category_counts.values())
    tool_ratio = round(tool_call_count / message_count, 4)
    thinking_ratio = round(facts.thinking_messages / message_count, 4)
    read_count = sum(category_counts.get(name, 0) for name in ("file_read", "search", "web"))
    edit_count = sum(category_counts.get(name, 0) for name in ("file_write", "file_edit"))
    run_count = sum(category_counts.get(name, 0) for name in ("shell", "git"))
    dispatch_count = category_counts.get("subagent", 0)
    user_count = facts.text_role_counts.get("user", 0)
    assistant_count = facts.text_role_counts.get("assistant", 0)
    features: dict[str, int | float | str] = {
        "message_count": facts.total_messages,
        "tool_call_count": tool_call_count,
        "tool_message_count": facts.tool_messages,
        "tool_ratio": tool_ratio,
        "read_count": read_count,
        "edit_count": edit_count,
        "run_count": run_count,
        "dispatch_count": dispatch_count,
        "compaction_count": compaction_count,
        "thinking_ratio": thinking_ratio,
        "user_turn_count": user_count,
        "assistant_turn_count": assistant_count,
        "tool_active_duration_ms": tool_active_duration_ms,
    }
    if dispatch_count:
        return "subagent_dispatch", 0.92, features
    if tool_ratio < 0.1 and (user_count or assistant_count):
        confidence = 0.76 if facts.total_messages <= 8 else 0.72
        return "chat", confidence, features
    if read_count >= 3 and edit_count == 0 and user_count <= 2:
        return "batch_review", 0.82, features
    if (edit_count > 0 or run_count >= 3) and tool_ratio >= 0.2 and facts.total_messages >= 10:
        return "agentic_loop", 0.86, features
    if read_count > 0 or tool_ratio >= 0.1:
        return "exploratory", 0.66, features
    return "unknown", 0.2, features


_TOOL_START_TYPES = {"function_call", "custom_tool_call", "web_search_call", "tool_search_call"}
_TOOL_OUTPUT_TYPES = {"function_call_output", "custom_tool_call_output", "web_search_output", "tool_search_output"}
_ERROR_MARKERS = ("error", "failed", "failure", "traceback", "exception", "panic")


def _tool_block_id(block: object) -> str | None:
    if not isinstance(block, dict):
        return None
    for key in ("tool_id", "tool_use_id", "id", "call_id"):
        value = block.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _pending_tool_blocks(session: Session) -> int:
    uses: Counter[str] = Counter()
    results: Counter[str] = Counter()
    unidentified_uses = 0
    unidentified_results = 0
    for message in session.messages:
        for block in message.blocks:
            if not isinstance(block, dict):
                continue
            block_type = str(block.get("type") or "").strip().lower()
            if block_type == "tool_use":
                tool_id = _tool_block_id(block)
                if tool_id is None:
                    unidentified_uses += 1
                else:
                    uses[tool_id] += 1
            elif block_type == "tool_result":
                tool_id = _tool_block_id(block)
                if tool_id is None:
                    unidentified_results += 1
                else:
                    results[tool_id] += 1
    pending_identified = sum(max(count - results.get(tool_id, 0), 0) for tool_id, count in uses.items())
    pending_unidentified = max(unidentified_uses - unidentified_results, 0)
    return pending_identified + pending_unidentified


class _ToolResultSummary(NamedTuple):
    outcome: str
    text: str | None


def _session_tool_results(session: Session) -> dict[str, _ToolResultSummary]:
    """Session-wide ``tool_id -> (structural outcome, result text)`` map.

    Mirrors ``_pending_tool_blocks``'s session-wide (not per-message)
    ``tool_use``/``tool_result`` pairing and
    ``insights/transforms.py::_extract_events``'s identical pairing strategy:
    Claude/Codex-style transcripts near-always place a ``tool_use`` in one
    message and its paired ``tool_result`` in a *later* message, which
    :func:`polylogue.archive.actions.parsing.build_tool_calls_from_content_blocks`
    (and therefore ``Action.output_text``, per-message only) cannot see.
    Reading blocks directly session-wide here is what makes both the
    structural error signal and its tagged text fallback in
    :func:`_terminal_state` actually fire for the common shape, not just the
    rare same-message case.
    """
    results: dict[str, _ToolResultSummary] = {}
    for message in session.messages:
        for block in message.blocks:
            if not isinstance(block, dict):
                continue
            if str(block.get("type") or "").strip().lower() != "tool_result":
                continue
            tool_id = _tool_block_id(block)
            if tool_id is None:
                continue
            text = block.get("text")
            results[tool_id] = _ToolResultSummary(
                outcome=tool_result_block_outcome(block),
                text=text if isinstance(text, str) and text else None,
            )
    return results


def _terminal_state(
    session: Session, analysis: SessionAnalysis
) -> tuple[str, float, dict[str, int | float | str | None]]:
    """Classify how a session's tool/turn activity ended.

    polylogue-b0b: the action-level error signal below prefers the
    structural, session-wide ``tool_id -> outcome`` map from
    :func:`_session_tool_results` (sourced from the keystone
    ``blocks.tool_result_is_error``/``tool_result_exit_code`` columns, index
    schema v16) over prose. That structural signal is origin-gated -- absent
    for most origins (polylogue-9e5.3 audit) -- so a ``_ERROR_MARKERS`` text
    scan over ``action.output_text`` remains as an explicit, tagged fallback
    only when the structural signal is absent for that action's tool_id,
    never silently substituted for it. Every returned ``evidence_class``
    entry in the features dict is ``"raw_evidence"`` (grounded in
    structure/role, never guessed from prose) or ``"text_derived"`` (a
    keyword/prose judgment) so callers can filter or caveat accordingly --
    see ``polylogue.insights.transforms.FieldEvidenceClass`` for the sibling
    convention this mirrors.
    """
    pending_block_count = _pending_tool_blocks(session)
    if pending_block_count:
        return (
            "tool_left",
            0.9,
            {"pending_tool_count": pending_block_count, "evidence_class": "raw_evidence"},
        )
    tool_results = _session_tool_results(session)
    latest_error_action_id: str | None = None
    latest_error_action_evidence_class: str | None = None
    for action in analysis.facts.actions:
        result = tool_results.get(action.tool_id) if action.tool_id else None
        outcome = result.outcome if result is not None else None
        if outcome == "failed":
            latest_error_action_id = action.action_id
            latest_error_action_evidence_class = "raw_evidence"
        elif outcome in (None, "unknown"):
            # No structural tool_result_is_error/exit_code for this origin's
            # result (polylogue-9e5.3) -- fall back to a tagged prose scan
            # over the session-wide tool_result text (falling back further to
            # the per-message Action.output_text if no session-wide result
            # text was found at all) instead of reporting a false "no error"
            # negative.
            fallback_text = (result.text if result is not None else None) or action.output_text or ""
            if any(marker in fallback_text.lower() for marker in _ERROR_MARKERS):
                latest_error_action_id = action.action_id
                latest_error_action_evidence_class = "text_derived"
        # outcome == "ok" is a structural negative -- do not fall through to
        # a prose scan that could misclassify a benign mention of the word
        # "error" (e.g. "0 errors found") as a failure.

    pending: set[str] = set()
    pending_without_id = 0
    latest_error_event_id: str | None = None
    for event in sorted(session.session_events, key=lambda item: item.event_index):
        event_type = str(event.event_type).strip().lower()
        call_id_value = event.payload.get("call_id")
        call_id = call_id_value.strip() if isinstance(call_id_value, str) and call_id_value.strip() else None
        if event_type in _TOOL_START_TYPES:
            if call_id is None:
                pending_without_id += 1
            else:
                pending.add(call_id)
        elif event_type in _TOOL_OUTPUT_TYPES:
            if call_id is None and pending_without_id:
                pending_without_id -= 1
            elif call_id is not None:
                pending.discard(call_id)
            # Structural: a typed status key on the provider's own tool-call
            # protocol event payload (e.g. Codex function_call_output), not
            # a prose scan -- see sources/parsers/codex.py:_compact_response_payload.
            status = str(event.payload.get("status") or "").lower()
            if status in {"error", "failed", "failure"}:
                latest_error_event_id = str(event.id)
    if pending or pending_without_id:
        return (
            "tool_left",
            0.9,
            {"pending_tool_count": len(pending) + pending_without_id, "evidence_class": "raw_evidence"},
        )

    meaningful = [
        message for message in analysis.facts.message_facts if message.text.strip() and not message.is_protocol_artifact
    ]
    last = meaningful[-1] if meaningful else None
    if last is None:
        if latest_error_action_id is not None:
            return (
                "error_left",
                0.78,
                {"action_id": latest_error_action_id, "evidence_class": latest_error_action_evidence_class},
            )
        if latest_error_event_id is not None:
            return "error_left", 0.78, {"event_id": latest_error_event_id, "evidence_class": "raw_evidence"}
        return "unknown", 0.1, {}
    text_lower = last.text.lower()
    if last.is_candidate_human_authored:
        return "question_left", 0.72, {"message_id": last.message_id, "evidence_class": "raw_evidence"}
    if last.is_assistant and any(marker in text_lower for marker in _ERROR_MARKERS):
        if latest_error_action_id is not None:
            return (
                "error_left",
                0.78,
                {"action_id": latest_error_action_id, "evidence_class": latest_error_action_evidence_class},
            )
        if latest_error_event_id is not None:
            return "error_left", 0.78, {"event_id": latest_error_event_id, "evidence_class": "raw_evidence"}
        return "error_left", 0.7, {"message_id": last.message_id, "evidence_class": "text_derived"}
    if last.is_assistant:
        # No structural "did the last turn conclude cleanly" signal exists;
        # this is the complement of the text-marker scan above, so it is
        # text_derived too, not a grounded positive.
        return "clean_finish", 0.68, {"message_id": last.message_id, "evidence_class": "text_derived"}
    return "unknown", 0.2, {"message_id": last.message_id}


def build_session_analysis(
    session: Session,
    *,
    facts: SessionSemanticFacts | None = None,
    stage_timing_add: Callable[[str, float], None] | None = None,
) -> SessionAnalysis:
    def add_timing(name: str, started_at: float) -> None:
        if stage_timing_add is not None:
            stage_timing_add(name, started_at)

    t0 = time.perf_counter()
    semantic_facts = facts or build_session_semantic_facts(session, stage_timing_add=stage_timing_add)
    add_timing("analysis.facts", t0)
    t0 = time.perf_counter()
    phases = tuple(extract_phases(session, facts=semantic_facts))
    add_timing("analysis.phases", t0)
    t0 = time.perf_counter()
    attribution = extract_attribution(session, facts=semantic_facts)
    add_timing("analysis.attribution", t0)
    t0 = time.perf_counter()
    work_events = tuple(extract_work_events(session, facts=semantic_facts, phases=phases))
    add_timing("analysis.work_events", t0)
    return SessionAnalysis(
        facts=semantic_facts,
        attribution=attribution,
        work_events=work_events,
        phases=phases,
    )


def infer_auto_tags(profile: SessionProfile) -> tuple[str, ...]:
    tags: list[str] = [f"origin:{profile.origin}"]
    for repo_name in list(profile.repo_names)[:3]:
        tags.append(f"repo:{repo_name}")
    if profile.is_continuation:
        tags.append("continuation")
    if profile.continuation_depth >= 3:
        tags.append("deep-thread")
    if len(profile.repo_names) > 1:
        tags.append("multi-repo")
    if profile.total_cost_usd >= 1.0:
        tags.append("costly")
    return tuple(sorted(set(tags)))


def build_session_profile(
    session: Session,
    *,
    analysis: SessionAnalysis | None = None,
    compaction_count: int | None = None,
    stage_timing_add: Callable[[str, float], None] | None = None,
) -> SessionProfile:
    from polylogue.archive.semantic.cost_compute import compute_session_cost

    def add_timing(name: str, started_at: float) -> None:
        if stage_timing_add is not None:
            stage_timing_add(name, started_at)

    t0 = time.perf_counter()
    session_analysis = analysis or build_session_analysis(session, stage_timing_add=stage_timing_add)
    add_timing("profile.ensure_analysis", t0)
    facts = session_analysis.facts
    attribution = session_analysis.attribution
    t0 = time.perf_counter()
    cost_summary = compute_session_cost(session, estimate_if_missing=False)
    add_timing("profile.cost_summary", t0)
    cost_usd = cost_summary.total_api_cost_usd
    cost_is_estimated = cost_summary.cost_confidence != "reported"
    primary_model_name, primary_model_family = _primary_model(cost_summary)
    t0 = time.perf_counter()
    resolved_compaction_count = (
        compaction_count
        if compaction_count is not None
        else sum(1 for event in session.session_events if event.event_type == "compaction")
    )
    add_timing("profile.compactions", t0)
    t0 = time.perf_counter()
    engaged_duration_ms = sum(int(phase.duration_ms or 0) for phase in session_analysis.phases)
    if engaged_duration_ms <= 0:
        engaged_duration_ms = max(int(session.total_duration_ms or 0), 0)
    tool_active_duration_ms = compute_tool_active_duration_ms(session.session_events)
    add_timing("profile.durations", t0)
    t0 = time.perf_counter()
    workflow_shape, workflow_shape_confidence, workflow_shape_features = _workflow_shape(
        session_analysis,
        compaction_count=resolved_compaction_count,
        tool_active_duration_ms=tool_active_duration_ms,
    )
    add_timing("profile.workflow_shape", t0)
    t0 = time.perf_counter()
    terminal_state, terminal_state_confidence, terminal_state_evidence = _terminal_state(
        session,
        session_analysis,
    )
    add_timing("profile.terminal_state", t0)
    t0 = time.perf_counter()
    first_message_at, last_message_at, timestamp_source = _profile_timestamp_bounds(session, facts)
    canonical_session_at = first_message_at or last_message_at
    add_timing("profile.timestamp_bounds", t0)
    t0 = time.perf_counter()
    timing = compute_session_timing(
        list(session.messages),
        tool_use_count=facts.tool_messages,
        wall_duration_ms=facts.wall_duration_ms,
    )
    add_timing("profile.session_timing", t0)
    t0 = time.perf_counter()
    inferred_topic, inferred_topic_source = _infer_topic(
        session,
        session_analysis,
        repo_names=attribution.repo_names,
    )
    add_timing("profile.infer_topic", t0)
    t0 = time.perf_counter()
    partial = SessionProfile(
        session_id=str(session.id),
        origin=str(session.origin),
        title=session.title,
        inferred_topic=inferred_topic,
        inferred_topic_source=inferred_topic_source,
        created_at=session.created_at,
        updated_at=session.updated_at,
        message_count=facts.total_messages,
        substantive_count=facts.substantive_messages,
        tool_use_count=facts.tool_messages,
        thinking_count=facts.thinking_messages,
        attachment_count=facts.attachment_count,
        word_count=facts.word_count,
        total_cost_usd=cost_usd,
        total_duration_ms=session.total_duration_ms,
        tool_categories=facts.tool_category_counts,
        repo_paths=attribution.repo_paths,
        cwd_paths=attribution.cwd_paths,
        branch_names=attribution.branch_names,
        file_paths_touched=attribution.file_paths_touched,
        languages_detected=attribution.languages_detected,
        repo_names=attribution.repo_names,
        work_events=session_analysis.work_events,
        phases=session_analysis.phases,
        first_message_at=first_message_at,
        last_message_at=last_message_at,
        timestamp_source=timestamp_source,
        timestamped_message_count=facts.timestamped_messages,
        untimestamped_message_count=facts.untimestamped_messages,
        timestamp_coverage=facts.timestamp_coverage,
        canonical_session_date=canonical_session_at.date() if canonical_session_at else None,
        engaged_duration_ms=engaged_duration_ms,
        tool_active_duration_ms=tool_active_duration_ms,
        wall_duration_ms=facts.wall_duration_ms,
        workflow_shape=workflow_shape,
        workflow_shape_confidence=workflow_shape_confidence,
        workflow_shape_features=workflow_shape_features,
        terminal_state=terminal_state,
        terminal_state_confidence=terminal_state_confidence,
        terminal_state_evidence=terminal_state_evidence,
        cost_is_estimated=cost_is_estimated,
        total_input_tokens=cost_summary.total_input_tokens,
        total_output_tokens=cost_summary.total_output_tokens,
        total_cache_read_tokens=cost_summary.total_cache_read_tokens,
        total_cache_write_tokens=cost_summary.total_cache_write_tokens,
        total_credit_cost=cost_summary.total_credit_cost,
        cost_provenance=cost_summary.cost_provenance,
        per_model_cost_json=_json.dumps(
            [b.model_dump(mode="json") for b in cost_summary.per_model] if cost_summary.per_model else [],
            default=str,
        ),
        primary_model_name=primary_model_name,
        primary_model_family=primary_model_family,
        compaction_count=resolved_compaction_count,
        tags=tuple(session.tags),
        is_continuation=session.is_continuation,
        parent_id=str(session.parent_id) if session.parent_id else None,
        thinking_duration_ms=timing.thinking_duration_ms,
        output_duration_ms=timing.output_duration_ms,
        tool_duration_ms=timing.tool_duration_ms,
        latency_percentiles_ms=timing.latency_percentiles_ms,
        tool_calls_per_minute=timing.tool_calls_per_minute,
        timing_provenance=timing.timing_provenance,
    )
    add_timing("profile.construct", t0)
    t0 = time.perf_counter()
    result = replace(partial, auto_tags=infer_auto_tags(partial))
    add_timing("profile.auto_tags", t0)
    return result


__all__ = ["build_session_analysis", "build_session_profile", "infer_auto_tags"]
