"""Session-profile inference and builder runtime."""

from __future__ import annotations

import json as _json
from dataclasses import replace
from datetime import datetime
from typing import TYPE_CHECKING

from polylogue.archive.conversation.attribution import extract_attribution
from polylogue.archive.conversation.extraction import extract_work_events
from polylogue.archive.phase.extraction import extract_phases
from polylogue.archive.semantic.facts import build_conversation_semantic_facts
from polylogue.archive.semantic.timing import compute_session_timing, compute_tool_active_duration_ms
from polylogue.archive.session.models import SessionAnalysis, SessionProfile
from polylogue.core.timestamps import parse_timestamp

if TYPE_CHECKING:
    from polylogue.archive.models import Conversation
    from polylogue.archive.semantic.facts import ConversationSemanticFacts


def _profile_timestamp_bounds(
    conversation: Conversation,
    facts: ConversationSemanticFacts,
) -> tuple[datetime | None, datetime | None, str]:
    """Resolve (first_message_at, last_message_at, source) for a session.

    Order of preference:
      1. facts.{first,last}_message_at — provider-supplied per-message
         timestamps, the strongest signal.
      2. provider_event timestamps — codex pre-Dec-2025 has empty
         message-level timestamps but rich provider_events with timestamps.
         Mining those yields a real session window instead of forcing a
         single-instant fallback.
      3. conversation.{created,updated}_at — last resort when neither
         messages nor events have timestamps.
    """
    if facts.first_message_at is not None or facts.last_message_at is not None:
        return (
            facts.first_message_at or facts.last_message_at,
            facts.last_message_at or facts.first_message_at,
            "provider_supplied",
        )
    # Codex pre-Dec-2025: messages carry no timestamps, but provider_events
    # (function_call, response_item, session_meta) do. Use them to derive
    # a real session window rather than collapsing to a single conversation
    # timestamp.
    event_timestamps: list[datetime] = []
    for event in conversation.provider_events:
        parsed = parse_timestamp(event.timestamp) if event.timestamp else None
        if parsed is not None:
            event_timestamps.append(parsed)
    if event_timestamps:
        return (
            min(event_timestamps),
            max(event_timestamps),
            "provider_events_fallback",
        )
    conversation_start = conversation.created_at or conversation.updated_at
    conversation_end = conversation.updated_at or conversation.created_at
    if conversation_start is not None or conversation_end is not None:
        return (
            conversation_start or conversation_end,
            conversation_end or conversation_start,
            "conversation_timestamp_fallback",
        )
    return (None, None, "absent")


_TOPIC_PREFIXES = (
    "Caveat: The messages below were generated by the user while running local commands.",
    "Caveat: The messages below are were generated by the user while running local commands.",
    "[SUGGESTION MODE: Suggest what the user might naturally type next into Claude Code.",
    "This session is being continued from a previous conversation that ran out of context.",
    "Base directory for this skill:",
)
_TOPIC_MAX_CHARS = 120
_CODEX_TOPIC_TEXT_CHARS = 60


def _clean_topic_text(value: str | None, *, width: int = _TOPIC_MAX_CHARS) -> str | None:
    text = " ".join(str(value or "").split()).strip()
    if not text:
        return None
    for prefix in _TOPIC_PREFIXES:
        if text.startswith(prefix):
            text = text[len(prefix) :].strip(" :-")
            break
    if not text:
        return None
    return text[:width].rstrip()


def _first_substantive_user_turn(analysis: SessionAnalysis) -> str | None:
    fallback_user_turn: str | None = None
    for message in analysis.facts.message_facts:
        if not message.is_user or message.is_protocol_artifact:
            continue
        cleaned = _clean_topic_text(message.text)
        if cleaned is None:
            continue
        if fallback_user_turn is None and not message.is_noise:
            fallback_user_turn = cleaned
        if message.is_substantive and not message.is_noise:
            return cleaned
    if fallback_user_turn is not None:
        return fallback_user_turn
    for message in analysis.facts.message_facts:
        if message.is_user:
            cleaned = _clean_topic_text(message.text)
            if cleaned is not None:
                return cleaned
    return None


def _infer_topic(
    conversation: Conversation,
    analysis: SessionAnalysis,
    *,
    repo_names: tuple[str, ...],
) -> tuple[str | None, str]:
    first_user_turn = _first_substantive_user_turn(analysis)
    if str(conversation.provider) == "codex" and first_user_turn and repo_names:
        return (f"{repo_names[0]} — {first_user_turn[:_CODEX_TOPIC_TEXT_CHARS].rstrip()}", "repo_plus_first_user_turn")
    if first_user_turn:
        return (first_user_turn, "first_substantive_user_turn")
    cleaned_title = _clean_topic_text(conversation.title)
    if cleaned_title:
        return (cleaned_title, "cleaned_title")
    return (None, "absent")


def _workflow_shape(
    analysis: SessionAnalysis, *, compaction_count: int, tool_active_duration_ms: int
) -> tuple[str, float, dict[str, int | float | str]]:
    facts = analysis.facts
    message_count = max(facts.total_messages, 1)
    category_counts = facts.tool_category_counts
    tool_call_count = sum(category_counts.values())
    tool_ratio = round(tool_call_count / message_count, 4)
    thinking_ratio = round(facts.thinking_messages / message_count, 4)
    read_count = sum(category_counts.get(name, 0) for name in ("file_read", "search", "web"))
    edit_count = sum(category_counts.get(name, 0) for name in ("file_write", "file_edit"))
    run_count = sum(category_counts.get(name, 0) for name in ("shell", "git"))
    dispatch_count = category_counts.get("subagent", 0)
    user_count = facts.text_role_counts.get("user", 0)
    assistant_count = facts.text_role_counts.get("assistant", 0)
    features: dict[str, int | float | str] = {
        "message_count": facts.total_messages,
        "tool_call_count": tool_call_count,
        "tool_message_count": facts.tool_messages,
        "tool_ratio": tool_ratio,
        "read_count": read_count,
        "edit_count": edit_count,
        "run_count": run_count,
        "dispatch_count": dispatch_count,
        "compaction_count": compaction_count,
        "thinking_ratio": thinking_ratio,
        "user_turn_count": user_count,
        "assistant_turn_count": assistant_count,
        "tool_active_duration_ms": tool_active_duration_ms,
    }
    if dispatch_count:
        return "subagent_dispatch", 0.92, features
    if facts.total_messages <= 8 and tool_ratio < 0.1:
        return "chat", 0.76, features
    if read_count >= 3 and edit_count == 0 and user_count <= 2:
        return "batch_review", 0.82, features
    if (edit_count > 0 or run_count >= 3) and tool_ratio >= 0.2 and facts.total_messages >= 10:
        return "agentic_loop", 0.86, features
    if read_count > 0 or tool_ratio >= 0.1:
        return "exploratory", 0.66, features
    return "unknown", 0.2, features


_TOOL_START_TYPES = {"function_call", "custom_tool_call", "web_search_call", "tool_search_call"}
_TOOL_OUTPUT_TYPES = {"function_call_output", "custom_tool_call_output", "web_search_output", "tool_search_output"}
_ERROR_MARKERS = ("error", "failed", "failure", "traceback", "exception", "panic")


def _terminal_state(
    conversation: Conversation, analysis: SessionAnalysis
) -> tuple[str, float, dict[str, int | float | str | None]]:
    pending: set[str] = set()
    pending_without_id = 0
    trailing_error_event_id: str | None = None
    for event in sorted(conversation.provider_events, key=lambda item: item.event_index):
        event_type = str(event.event_type).strip().lower()
        call_id_value = event.payload.get("call_id")
        call_id = call_id_value.strip() if isinstance(call_id_value, str) and call_id_value.strip() else None
        if event_type in _TOOL_START_TYPES:
            if call_id is None:
                pending_without_id += 1
            else:
                pending.add(call_id)
        elif event_type in _TOOL_OUTPUT_TYPES:
            if call_id is None and pending_without_id:
                pending_without_id -= 1
            elif call_id is not None:
                pending.discard(call_id)
            status = str(event.payload.get("status") or "").lower()
            if status in {"error", "failed", "failure"}:
                trailing_error_event_id = str(event.id)
    if pending or pending_without_id:
        return "tool_left", 0.9, {"pending_tool_count": len(pending) + pending_without_id}

    meaningful = [
        message for message in analysis.facts.message_facts if message.text.strip() and not message.is_protocol_artifact
    ]
    last = meaningful[-1] if meaningful else None
    if trailing_error_event_id is not None:
        return "error_left", 0.78, {"event_id": trailing_error_event_id}
    if last is None:
        return "unknown", 0.1, {}
    text_lower = last.text.lower()
    if last.is_user:
        return "question_left", 0.72, {"message_id": last.message_id}
    if last.is_assistant and any(marker in text_lower for marker in _ERROR_MARKERS):
        return "error_left", 0.7, {"message_id": last.message_id}
    if last.is_assistant:
        return "clean_finish", 0.68, {"message_id": last.message_id}
    return "unknown", 0.2, {"message_id": last.message_id}


def build_session_analysis(
    conversation: Conversation,
    *,
    facts: ConversationSemanticFacts | None = None,
) -> SessionAnalysis:
    semantic_facts = facts or build_conversation_semantic_facts(conversation)
    phases = tuple(extract_phases(conversation, facts=semantic_facts))
    return SessionAnalysis(
        facts=semantic_facts,
        attribution=extract_attribution(conversation, facts=semantic_facts),
        work_events=tuple(extract_work_events(conversation, facts=semantic_facts, phases=phases)),
        phases=phases,
    )


def infer_auto_tags(profile: SessionProfile) -> tuple[str, ...]:
    tags: list[str] = [f"provider:{profile.provider}"]
    for repo_name in list(profile.repo_names)[:3]:
        tags.append(f"repo:{repo_name}")
    if profile.is_continuation:
        tags.append("continuation")
    if profile.continuation_depth >= 3:
        tags.append("deep-thread")
    if len(profile.repo_names) > 1:
        tags.append("multi-repo")
    if profile.total_cost_usd >= 1.0:
        tags.append("costly")
    return tuple(sorted(set(tags)))


def build_session_profile(
    conversation: Conversation,
    *,
    analysis: SessionAnalysis | None = None,
    compaction_count: int | None = None,
) -> SessionProfile:
    from polylogue.archive.semantic.cost_compute import compute_session_cost
    from polylogue.archive.semantic.pricing import harmonize_session_cost

    session_analysis = analysis or build_session_analysis(conversation)
    facts = session_analysis.facts
    attribution = session_analysis.attribution
    cost_usd, cost_is_estimated = harmonize_session_cost(conversation)
    cost_summary = compute_session_cost(conversation)
    resolved_compaction_count = (
        compaction_count
        if compaction_count is not None
        else sum(1 for event in conversation.provider_events if event.event_type == "compaction")
    )
    engaged_duration_ms = sum(int(phase.duration_ms or 0) for phase in session_analysis.phases)
    if engaged_duration_ms <= 0:
        engaged_duration_ms = max(int(conversation.total_duration_ms or 0), 0)
    tool_active_duration_ms = compute_tool_active_duration_ms(conversation.provider_events)
    workflow_shape, workflow_shape_confidence, workflow_shape_features = _workflow_shape(
        session_analysis,
        compaction_count=resolved_compaction_count,
        tool_active_duration_ms=tool_active_duration_ms,
    )
    terminal_state, terminal_state_confidence, terminal_state_evidence = _terminal_state(
        conversation,
        session_analysis,
    )
    first_message_at, last_message_at, timestamp_source = _profile_timestamp_bounds(conversation, facts)
    canonical_session_at = first_message_at or last_message_at
    timing = compute_session_timing(
        list(conversation.messages),
        tool_use_count=facts.tool_messages,
        wall_duration_ms=facts.wall_duration_ms,
    )
    inferred_topic, inferred_topic_source = _infer_topic(
        conversation,
        session_analysis,
        repo_names=attribution.repo_names,
    )
    partial = SessionProfile(
        conversation_id=str(conversation.id),
        provider=str(conversation.provider),
        title=conversation.title,
        inferred_topic=inferred_topic,
        inferred_topic_source=inferred_topic_source,
        created_at=conversation.created_at,
        updated_at=conversation.updated_at,
        message_count=facts.total_messages,
        substantive_count=facts.substantive_messages,
        tool_use_count=facts.tool_messages,
        thinking_count=facts.thinking_messages,
        attachment_count=facts.attachment_count,
        word_count=facts.word_count,
        total_cost_usd=cost_usd,
        total_duration_ms=conversation.total_duration_ms,
        tool_categories=facts.tool_category_counts,
        repo_paths=attribution.repo_paths,
        cwd_paths=attribution.cwd_paths,
        branch_names=attribution.branch_names,
        file_paths_touched=attribution.file_paths_touched,
        languages_detected=attribution.languages_detected,
        repo_names=attribution.repo_names,
        work_events=session_analysis.work_events,
        phases=session_analysis.phases,
        first_message_at=first_message_at,
        last_message_at=last_message_at,
        timestamp_source=timestamp_source,
        timestamped_message_count=facts.timestamped_messages,
        untimestamped_message_count=facts.untimestamped_messages,
        timestamp_coverage=facts.timestamp_coverage,
        canonical_session_date=canonical_session_at.date() if canonical_session_at else None,
        engaged_duration_ms=engaged_duration_ms,
        tool_active_duration_ms=tool_active_duration_ms,
        wall_duration_ms=facts.wall_duration_ms,
        workflow_shape=workflow_shape,
        workflow_shape_confidence=workflow_shape_confidence,
        workflow_shape_features=workflow_shape_features,
        terminal_state=terminal_state,
        terminal_state_confidence=terminal_state_confidence,
        terminal_state_evidence=terminal_state_evidence,
        cost_is_estimated=cost_is_estimated,
        total_input_tokens=cost_summary.total_input_tokens,
        total_output_tokens=cost_summary.total_output_tokens,
        total_cache_read_tokens=cost_summary.total_cache_read_tokens,
        total_cache_write_tokens=cost_summary.total_cache_write_tokens,
        total_credit_cost=cost_summary.total_credit_cost,
        cost_provenance=cost_summary.cost_provenance,
        per_model_cost_json=_json.dumps(
            [b.model_dump(mode="json") for b in cost_summary.per_model] if cost_summary.per_model else [],
            default=str,
        ),
        compaction_count=resolved_compaction_count,
        tags=tuple(conversation.tags),
        is_continuation=conversation.is_continuation,
        parent_id=str(conversation.parent_id) if conversation.parent_id else None,
        thinking_duration_ms=timing.thinking_duration_ms,
        output_duration_ms=timing.output_duration_ms,
        tool_duration_ms=timing.tool_duration_ms,
        latency_percentiles_ms=timing.latency_percentiles_ms,
        tool_calls_per_minute=timing.tool_calls_per_minute,
        timing_provenance=timing.timing_provenance,
    )
    return replace(partial, auto_tags=infer_auto_tags(partial))


__all__ = ["build_session_analysis", "build_session_profile", "infer_auto_tags"]
