"""Adjudicate a failed pytest run by rerunning its failures alone, once.

One mechanism, two callers. ``devtools verify`` has had this since the
workstation pytest pool made contention normal: a run beside six sibling jobs
can fail on load alone, and that is not a verdict on the head. ``devtools
test`` -- the command every parallel worker actually uses for its inner loop
-- had no equivalent, so the mitigation existed and was bypassed by the
command that needed it most.

The rule is the same on both routes: a test that fails twice is red and
decides the run. A test that passes alone is flaky, recorded with both
outcomes in the canonical report, where it counts as passed. Nothing here can
turn a run that pytest itself could not finish (exit 2/3/4, a signal) into a
pass -- only exit 1, "tests failed", is adjudicable.
"""

from __future__ import annotations

import json
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from devtools.pytest_invocation import (
    CLEAR_CONFIGURED_ADDOPTS,
    MANAGED_PLUGIN_ARGS,
    REPORT_PLUGIN_ARGS,
)
from devtools.pytest_slot import PytestSlotUnavailableError, run_pytest, run_pytest_isolated
from devtools.pytest_stream_report import report_file_argument
from devtools.toolchain import venv_python

__all__ = [
    "semantic_rerun_options",
    "MAX_RERUN_NODEIDS",
    "RERUN_IN_SLOT_ENV",
    "RERUN_IN_SLOT_RESULT",
    "adjudicate_rerun",
    "build_rerun",
    "rerun_environment",
    "read_json",
    "report_nodeid_to_selector",
    "rerun_failed_once",
]

#: Above this the failure is systemic, not contention, and rerunning it one
#: node at a time costs more than it can ever clear.
MAX_RERUN_NODEIDS = 300


def read_json(path: Path) -> dict[str, Any] | None:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def report_nodeid_to_selector(nodeid: str) -> str:
    """Strip xdist's ``@<group>`` suffix so a report node id selects again.

    ``--dist=loadgroup`` reports ``path::test[param]@group``; pytest cannot
    collect that literal, so a rerun built from it errors before running.
    A parametrization id may itself contain ``@``, so only a suffix after the
    closing bracket (or after the bare test name) is removed.
    """
    head, sep, tail = nodeid.rpartition("@")
    if not sep or "::" not in head:
        return nodeid
    if "[" in tail or "]" in tail or "/" in tail or "::" in tail:
        return nodeid
    if head.endswith("]") or "[" not in head.rsplit("::", 1)[-1]:
        return head
    return nodeid


def _path_for_receipt(path: Path, *, root: Path) -> Path:
    try:
        return path.relative_to(root)
    except ValueError:
        return path


#: Set on a queued focused run: the slot job adjudicates its own failures
#: while it still holds the slot, instead of the client queueing a second
#: job for the rerun. The value names the report and step directory.
RERUN_IN_SLOT_ENV = "POLYLOGUE_PYTEST_RERUN_IN_SLOT"
#: Written by the slot job beside the step's artifacts once its in-slot rerun
#: has finished: ``{"attempted": [...], "rerun_exit": int}``.
RERUN_IN_SLOT_RESULT = "pytest-rerun-in-slot.json"


#: Options that choose or order tests, place outputs, or fan work out. The
#: rerun names its own node ids and report and runs in one process, so these
#: are dropped; every other option (``-W error``, ``-p``, ``-o``,
#: ``--import-mode``) changes how a test executes and is kept.
_RERUN_DROPPED_WITH_VALUE = frozenset(
    {
        "-k",
        "-m",
        "-n",
        "--numprocesses",
        "--dist",
        "--deselect",
        "--ignore",
        "--ignore-glob",
        "--junitxml",
        "--junit-xml",
        "--basetemp",
        "--maxfail",
        "--log-file",
    }
)
_RERUN_DROPPED_FLAGS = frozenset(
    {
        "-x",
        "--exitfirst",
        "--lf",
        "--last-failed",
        "--ff",
        "--failed-first",
        "--nf",
        "--new-first",
        "--sw",
        "--stepwise",
        "--sw-skip",
        "--stepwise-skip",
        "-q",
        "--quiet",
        "-v",
        "--verbose",
        "-vv",
        "-s",
    }
)


def semantic_rerun_options(command: list[str]) -> list[str]:
    """The options of a pytest ``command`` a rerun of its failures must keep.

    Reads the argument list after ``-m pytest``: devtools' own plugin and
    report arguments are regenerated by the rerun, and path operands are
    replaced by the failed node ids.
    """
    arguments = command[command.index("pytest") + 1 :] if "pytest" in command else list(command)
    kept: list[str] = []
    index = 0
    while index < len(arguments):
        argument = arguments[index]
        if argument == "--":
            break
        name = argument.split("=", 1)[0]
        takes_value = "=" not in argument and name in _RERUN_KEPT_WITH_VALUE | _RERUN_DROPPED_WITH_VALUE
        if not argument.startswith("-"):
            index += 1
            continue
        if name in _RERUN_DROPPED_WITH_VALUE or argument in _RERUN_DROPPED_FLAGS or _is_managed(argument):
            index += 2 if takes_value else 1
            continue
        if argument == "-p" and index + 1 < len(arguments) and not arguments[index + 1].startswith("no:"):
            # Plugin loads are the managed profile, which the rerun supplies
            # itself; only a caller's ``-p no:...`` changes execution.
            index += 2
            continue
        kept.append(argument)
        if takes_value and index + 1 < len(arguments):
            kept.append(arguments[index + 1])
            index += 2
            continue
        index += 1
    return kept


_RERUN_KEPT_WITH_VALUE = frozenset(
    {
        "-W",
        "--pythonwarnings",
        "-p",
        "-o",
        "--override-ini",
        "-c",
        "--import-mode",
        "--confcutdir",
        "--rootdir",
        "--hypothesis-profile",
        "--hypothesis-seed",
        "--timeout",
        "--capture",
        "--tb",
    }
)


def _is_managed(argument: str) -> bool:
    """Arguments devtools itself adds to every managed pytest command."""
    return argument.startswith(("--polylogue-report-file=", "--override-ini=addopts=", "--basetemp="))


def build_rerun(
    *, report_path: Path, step_dir: Path, root: Path, options: list[str] | None = None
) -> tuple[list[str], list[str], Path] | None:
    """Return ``(failed, command, rerun_report)`` for a failed run, or ``None``.

    ``None`` means there is nothing to adjudicate: no readable report, no
    failures, or more than :data:`MAX_RERUN_NODEIDS`.
    """
    report = read_json(report_path)
    if not isinstance(report, Mapping):
        return None
    failed = [
        report_nodeid_to_selector(str(test["nodeid"]))
        for test in report.get("tests", [])
        if isinstance(test, Mapping) and test.get("outcome") in {"failed", "error"} and test.get("nodeid")
    ]
    if not failed or len(failed) > MAX_RERUN_NODEIDS:
        return None
    rerun_report = step_dir / "pytest-rerun.json"
    command = [
        venv_python(root=root),
        "-m",
        "pytest",
        "-q",
        "--tb=short",
        report_file_argument(rerun_report),
        *REPORT_PLUGIN_ARGS,
        *MANAGED_PLUGIN_ARGS,
        "-p",
        "no:testmon",
        "-p",
        "no:randomly",
        CLEAR_CONFIGURED_ADDOPTS,
        *(options or []),
        *failed,
    ]
    return failed, command, rerun_report


def rerun_environment(env: Mapping[str, str]) -> dict[str, str]:
    """The rerun is one process: drop the xdist worker settings."""
    return {key: value for key, value in env.items() if not key.startswith("PYTEST_XDIST")}


def adjudicate_rerun(
    *,
    report_path: Path,
    step_dir: Path,
    failed: list[str],
    rerun_report: Path,
    rerun_exit: int,
    root: Path,
) -> dict[str, Any]:
    """Fold one finished rerun into the run's report and return the verdict."""
    report = read_json(report_path) or {}
    second = read_json(rerun_report)
    if not isinstance(second, Mapping) or rerun_exit not in (0, 1):
        # No report, or pytest itself did not finish cleanly (exit 3 is an
        # internal error): nothing here clears a failure.
        return {
            "attempted": failed,
            "still_failed": failed,
            "flaky": [],
            "rerun_report": None,
            "rerun_exit": rerun_exit,
        }
    second_outcome = {
        str(test["nodeid"]): str(test.get("outcome"))
        for test in second.get("tests", [])
        if isinstance(test, Mapping) and test.get("nodeid")
    }
    still_failed = [nodeid for nodeid in failed if second_outcome.get(nodeid) != "passed"]
    flaky = [nodeid for nodeid in failed if second_outcome.get(nodeid) == "passed"]
    if not still_failed and rerun_exit != 0:
        # Every node passed but the process did not: the run is not green.
        still_failed, flaky = failed, []
    if flaky:
        patched = dict(report)
        tests = []
        for test in report.get("tests", []):
            # xdist ``loadgroup`` reports ``node@group``; the rerun names the
            # plain node, so the report row is matched on the same spelling.
            if isinstance(test, Mapping) and report_nodeid_to_selector(str(test.get("nodeid"))) in flaky:
                test = {**test, "first_outcome": test.get("outcome"), "outcome": "passed", "flaky": True}
            tests.append(test)
        patched["tests"] = tests
        summary = dict(report.get("summary") or {})
        for key in ("failed", "error"):
            if key in summary:
                summary[key] = max(
                    0,
                    int(summary[key])
                    - sum(
                        1
                        for t in report.get("tests", [])
                        if isinstance(t, Mapping)
                        and report_nodeid_to_selector(str(t.get("nodeid"))) in flaky
                        and t.get("outcome") == key
                    ),
                )
        summary["passed"] = int(summary.get("passed", 0)) + len(flaky)
        summary["flaky"] = len(flaky)
        if not still_failed:
            summary["exitstatus"] = 0
            # The report carries its exit status twice. A consumer reading the
            # top-level field would still see the pre-rerun failure.
            patched["exitcode"] = 0
        patched["summary"] = summary
        patched["flaky_nodeids"] = list(flaky)
        report_path.write_text(json.dumps(patched), encoding="utf-8")
        # The progress plugin's own summary carries the first exit status;
        # evidence evaluation compares the two, so both tell the same story.
        plugin_summary_path = step_dir / "summary.json"
        plugin_summary = read_json(plugin_summary_path)
        if isinstance(plugin_summary, Mapping):
            updated = dict(plugin_summary)
            updated["flaky"] = len(flaky)
            if not still_failed:
                updated["exitstatus"] = 0
            plugin_summary_path.write_text(json.dumps(updated), encoding="utf-8")
    return {
        "attempted": failed,
        "still_failed": still_failed,
        "flaky": flaky,
        # Reported relative to the checkout when it lies inside one, absolute
        # otherwise. A step directory can sit outside the root -- a configured
        # basetemp root, or a caller that supplies its own artifact directory --
        # and a rerun that adjudicated flakes correctly must not then die
        # formatting its own path.
        "rerun_report": str(_path_for_receipt(rerun_report, root=root)),
    }


def _content_moved(first: object, rerun: object) -> dict[str, Any] | None:
    """The refusal when a rerun executed different worktree content, else ``None``."""
    if not isinstance(first, Mapping) or not isinstance(rerun, Mapping):
        return None
    identity_keys = ("git_head", "git_branch", "git_worktree_content_sha256")
    if all(first.get(key) == rerun.get(key) for key in identity_keys):
        return None
    sys.stderr.write("\n  rerun ran different worktree content; the failures stand\n")
    return {"flaky": [], "rerun_report": None, "content_moved": True}


def rerun_failed_once(
    *,
    report_path: Path,
    step_dir: Path,
    env: Mapping[str, str],
    root: Path,
    runner: str = "managed",
    first_provenance: Mapping[str, Any] | None = None,
    options: list[str] | None = None,
) -> dict[str, Any] | None:
    """Rerun exactly the failed tests once, alone and unselected.

    ``options`` are the first run's execution-changing pytest options
    (:func:`semantic_rerun_options`), so the rerun adjudicates the same
    semantics -- a ``-W error`` failure is not cleared under default warnings.

    ``first_provenance`` is the worktree identity the failing run executed.
    A rerun that executed different content or another branch adjudicates
    nothing: its pass would clear a failure of content it never ran.

    ``report_path`` is the just-finished run's JSON report; it is patched in
    place when a failure clears, so the caller's downstream statistics read
    the adjudicated outcome. Returns ``None`` when there is nothing to
    adjudicate. A queued run whose slot job already reran its failures (see
    :data:`RERUN_IN_SLOT_ENV`) is adjudicated from that record, without
    queueing again for the slot.
    """
    in_slot = read_json(step_dir / RERUN_IN_SLOT_RESULT)
    if isinstance(in_slot, Mapping) and isinstance(in_slot.get("attempted"), list):
        attempted = [str(nodeid) for nodeid in in_slot["attempted"]]
        moved = _content_moved(first_provenance, in_slot.get("worktree_provenance"))
        if moved is not None:
            return {**moved, "attempted": attempted, "still_failed": attempted, "rerun_exit": in_slot.get("rerun_exit")}
        return adjudicate_rerun(
            report_path=report_path,
            step_dir=step_dir,
            failed=[str(nodeid) for nodeid in in_slot["attempted"]],
            rerun_report=step_dir / "pytest-rerun.json",
            rerun_exit=int(in_slot.get("rerun_exit", 3)),
            root=root,
        )
    plan = build_rerun(report_path=report_path, step_dir=step_dir, root=root, options=options)
    if plan is None:
        return None
    failed, rerun_command, rerun_report = plan
    sys.stderr.write(f"\n  rerun {len(failed)} failed test(s) alone ... ")
    sys.stderr.flush()
    # The rerun is pytest too, so it holds the host's pytest slot like the run
    # it is adjudicating.
    try:
        executor = run_pytest if runner == "managed" else run_pytest_isolated
        rerun_completed = executor(
            rerun_command, cwd=str(root), env=rerun_environment(env), root=root, stdout=sys.stderr
        )
    except PytestSlotUnavailableError as exc:
        sys.stderr.write(f"\n  rerun could not acquire the pytest slot: {exc}\n")
        return {"attempted": failed, "still_failed": failed, "flaky": [], "rerun_report": None, "rerun_exit": 125}
    rerun_receipt = getattr(rerun_completed, "receipt", None)
    moved = _content_moved(
        first_provenance,
        rerun_receipt.get("worktree_provenance") if isinstance(rerun_receipt, Mapping) else None,
    )
    if moved is not None:
        return {**moved, "attempted": failed, "still_failed": failed, "rerun_exit": rerun_completed.returncode}
    return adjudicate_rerun(
        report_path=report_path,
        step_dir=step_dir,
        failed=failed,
        rerun_report=rerun_report,
        rerun_exit=rerun_completed.returncode,
        root=root,
    )
