"""Render the exhaustive MCP tool-name index into docs/mcp-reference.md.

``docs/mcp-reference.md`` hand-curates a representative sample of tools by
category; that stays. This adds a generated appendix enumerating every
declared tool name (``polylogue.mcp.declarations.registry``), so each
tool is individually reachable from the docs tree (polylogue-3tl.9's
docs-coverage lint checks exactly this) without hand-duplicating the list.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed

MARKER = "mcp-tool-index"
DEFAULT_DOC_PATH = Path("docs/mcp-reference.md")


def _tool_names() -> tuple[str, ...]:
    from polylogue.mcp.declarations.registry import declared_tool_names

    return tuple(sorted(declared_tool_names("admin")))


def build_tool_index_section(tool_names: tuple[str, ...] | None = None) -> str:
    names = tool_names if tool_names is not None else _tool_names()
    generated_note = f"<!-- Generated by `{control_plane_command('render mcp-tool-index')}`. Do not edit by hand. -->"
    lines = [
        f"<!-- BEGIN GENERATED: {MARKER} -->",
        "## All Registered Tools",
        "",
        generated_note,
        "",
        f"Every currently-registered MCP tool name ({len(names)} total), for lookup and doc-coverage "
        "purposes. See the category breakdown above for what each group is for.",
        "",
    ]
    lines.extend(f"- `{name}`" for name in names)
    lines.append("")
    lines.append(f"<!-- END GENERATED: {MARKER} -->")
    return "\n".join(lines)


def replace_marked_section(text: str, *, replacement: str) -> str:
    begin, end = f"<!-- BEGIN GENERATED: {MARKER} -->", f"<!-- END GENERATED: {MARKER} -->"
    start = text.find(begin)
    if start == -1:
        # No existing block: append at end of file (after a trailing blank line).
        return text.rstrip("\n") + "\n\n" + replacement + "\n"
    finish = text.find(end, start)
    if finish == -1:
        raise ValueError(f"marker block malformed: {MARKER}")
    return text[:start] + replacement + text[finish + len(end) :]


def render_output(doc_path: Path) -> str:
    current = doc_path.read_text(encoding="utf-8") if doc_path.exists() else ""
    return replace_marked_section(current, replacement=build_tool_index_section())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the generated MCP tool-name index appendix.")
    parser.add_argument("--doc-path", default=str(DEFAULT_DOC_PATH), help=f"target doc (default: {DEFAULT_DOC_PATH})")
    parser.add_argument("--check", action="store_true", help="Exit non-zero when the doc target is out of sync.")
    args = parser.parse_args(argv)
    doc_path = Path(args.doc_path)

    rendered = render_output(doc_path)

    if args.check:
        current = doc_path.read_text(encoding="utf-8") if doc_path.exists() else ""
        if current != rendered:
            print("render mcp-tool-index: out of sync:", file=sys.stderr)
            print(f"  - {doc_path}", file=sys.stderr)
            print(f"render mcp-tool-index: run: {control_plane_command('render mcp-tool-index')}", file=sys.stderr)
            return 1
        print("render mcp-tool-index: sync OK")
        return 0

    write_if_changed(doc_path, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
