"""Render the insight rigor contracts into docs/insights-rigor-matrix.md.

The document already declared ``polylogue/analysis/rigor.py:list_rigor_contracts()``
its source of truth while hand-maintaining the rows beside it. The copy had
drifted: it carried eleven of thirteen contracts, omitted ``command_shapes``
and ``tool_episodes`` entirely, and named ``threads`` as ``work_threads`` --
an insight type no registry entry answers to. Every bullet in a row is a
projection of one contract field, so the matrix is generated rather than
restated.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed
from polylogue.analysis.rigor import list_rigor_contracts

GENERATED_BEGIN = "<!-- BEGIN GENERATED: insights-rigor-matrix -->"
GENERATED_END = "<!-- END GENERATED: insights-rigor-matrix -->"


def _paths(values: Sequence[object]) -> str:
    items = tuple(str(value) for value in values or ())
    if not items:
        return "_(none)_"
    return ", ".join(f"`{item}`" for item in items)


def _versions(contract: object) -> str:
    fields = getattr(contract, "version_fields", ()) or ()
    if not fields:
        return "_(none)_"
    return ", ".join(f"`{field.name}` (current `{field.current_version}`)" for field in fields)


def _readiness(text: str) -> str:
    return " ".join(str(text).split()) or "_(none)_"


def build_block() -> str:
    contracts = sorted(list_rigor_contracts(), key=lambda contract: contract.insight_name)
    lines = [
        GENERATED_BEGIN,
        "## Matrix",
        "",
        (
            f"Generated by `{control_plane_command('render insights-rigor-matrix')}` from "
            "`polylogue/analysis/rigor.py`. The registry declares "
            f"{len(contracts)} rigor contracts; every row below is a projection of one of them, "
            "so an insight added to the registry appears here without an edit to this file."
        ),
        "",
    ]
    for contract in contracts:
        lines.extend(
            [
                f"### `{contract.insight_name}` — {contract.display_name}",
                "",
                f"- Evidence payload: {_paths(contract.evidence_payload)}",
                f"- Inference payload: {_paths(contract.inference_payload)}",
                f"- Fallback markers: {_paths(contract.fallback_markers)}",
                f"- Confidence field: {_paths(contract.confidence_field)}",
                f"- Versions: {_versions(contract)}",
                f"- Readiness: {_readiness(contract.readiness_semantics)}",
                f"- Consumer-facing fields: {_paths(contract.consumer_fields)}",
                "",
            ]
        )
    lines.append(GENERATED_END)
    return "\n".join(lines)


def render_document(current: str) -> str:
    block = build_block()
    if GENERATED_BEGIN not in current or GENERATED_END not in current:
        raise ValueError("docs/insights-rigor-matrix.md is missing insights-rigor-matrix generated markers")
    prefix, remainder = current.split(GENERATED_BEGIN, 1)
    _, suffix = remainder.split(GENERATED_END, 1)
    return prefix.rstrip() + "\n\n" + block + "\n\n" + suffix.lstrip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render insight rigor contracts into docs/insights-rigor-matrix.md.")
    parser.add_argument("--output", default="docs/insights-rigor-matrix.md")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    output = Path(args.output)
    try:
        current = output.read_text(encoding="utf-8")
        rendered = render_document(current)
    except (OSError, ValueError) as exc:
        print(f"render insights-rigor-matrix: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if current != rendered:
            print(f"render insights-rigor-matrix: out of sync: {output}", file=sys.stderr)
            return 1
        return 0

    write_if_changed(output, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
