"""Render the CLI reference from live `polylogue --help` output."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed

SECTIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Top-Level Command", ()),
    ("List Verb", ("list",)),
    ("Stats Verb", ("stats",)),
    ("Count Verb", ("count",)),
    ("Open Verb", ("open",)),
    ("Delete Verb", ("delete",)),
    ("Run", ("run",)),
    ("Run Embed", ("run", "embed")),
    ("Run Site", ("run", "site")),
    ("Products", ("products",)),
    ("Audit", ("audit",)),
    ("Doctor", ("doctor",)),
    ("Tags", ("tags",)),
    ("Auth", ("auth",)),
    ("Reset", ("reset",)),
    ("Schema", ("schema",)),
    ("Completions", ("completions",)),
    ("Dashboard", ("dashboard",)),
    ("MCP", ("mcp",)),
)


def render_help(command: tuple[str, ...]) -> str:
    argv = ["polylogue", "--plain", *command, "--help"]
    env = {**os.environ, "POLYLOGUE_FORCE_PLAIN": "1"}
    completed = subprocess.run(argv, check=True, capture_output=True, text=True, env=env)
    return completed.stdout.rstrip()


def build_document(sections: list[tuple[str, str]]) -> str:
    parts = [
        "[← Back to README](../README.md)",
        "",
        f"<!-- Generated by `{control_plane_command('render-cli-reference')}`. Edit devtools/render_cli_reference.py instead. -->",
        "",
        "# CLI Reference",
        "",
        "This reference is generated from the live `polylogue --help` surface inside the project devshell.",
        "",
    ]
    for title, body in sections:
        parts.extend([f"## {title}", "", "```text", body, "```", ""])
    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docs/cli-reference.md from live CLI help.")
    parser.add_argument(
        "--output",
        default="docs/cli-reference.md",
        help="Output file path or '-' for stdout (default: docs/cli-reference.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the output file is out of sync with the rendered content.",
    )
    args = parser.parse_args(argv)

    output_path = None if args.output == "-" else Path(args.output).expanduser()

    try:
        sections = [(title, render_help(command)) for title, command in SECTIONS]
    except FileNotFoundError:
        print("render-cli-reference: `polylogue` not found in PATH", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.strip() if exc.stderr else ""
        detail = f": {stderr}" if stderr else ""
        print(f"render-cli-reference: failed to render help for {' '.join(exc.cmd)}{detail}", file=sys.stderr)
        return exc.returncode or 1

    rendered = build_document(sections)

    if args.output == "-":
        if args.check:
            print("render-cli-reference: --check does not support --output -", file=sys.stderr)
            return 2
        sys.stdout.write(rendered)
        return 0

    assert output_path is not None
    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != rendered:
            print(f"render-cli-reference: out of sync: {output_path}", file=sys.stderr)
            print(
                f"render-cli-reference: run: {control_plane_command('render-cli-reference', '--output', str(output_path))}",
                file=sys.stderr,
            )
            return 1
        print(f"render-cli-reference: sync OK: {output_path}")
        return 0

    write_if_changed(output_path, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
