"""Render Markdown transclusions from CLAUDE.md into a flat agent document."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed

INCLUDE_RE = re.compile(r"^\s*@(.+?)\s*$")
ESCAPED_CHAR_RE = re.compile(r"\\(.)")
FENCE_RE = re.compile(r"^\s*(```|~~~)")


def decode_include(token: str) -> str:
    token = token.strip().strip('"').strip("'")
    return ESCAPED_CHAR_RE.sub(r"\1", token)


def resolve_include(base_dir: Path, include_ref: str) -> Path:
    if include_ref.startswith("~/"):
        return Path.home() / include_ref[2:]
    include_path = Path(include_ref)
    if include_path.is_absolute():
        return include_path
    return base_dir / include_path


def expand(path: Path, stack: list[Path]) -> str:
    resolved_path = path.expanduser().resolve()
    if resolved_path in stack:
        cycle = " -> ".join(str(part) for part in [*stack, resolved_path])
        raise RuntimeError(f"circular include detected: {cycle}")

    try:
        lines = path.expanduser().read_text(encoding="utf-8").splitlines(keepends=True)
    except FileNotFoundError as exc:
        raise RuntimeError(f"include file not found: {path}") from exc

    stack.append(resolved_path)
    out: list[str] = []
    in_fence = False
    for line in lines:
        if FENCE_RE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        match = INCLUDE_RE.match(line)
        if not match:
            out.append(line)
            continue

        include_ref = decode_include(match.group(1))
        include_path = resolve_include(path.parent, include_ref)
        include_real = include_path.expanduser().resolve()
        out.append(f"<!-- begin include: {include_real} -->\n")
        expanded = expand(include_path, stack)
        out.append(expanded)
        if not expanded.endswith("\n"):
            out.append("\n")
        out.append(f"<!-- end include: {include_real} -->\n")

    stack.pop()
    return "".join(out)


def render_document(*, input_path: Path, output_path: Path | None) -> str:
    body = expand(input_path, [])
    if output_path is None:
        display_input = str(input_path)
    else:
        display_input = os.path.relpath(input_path.resolve(), output_path.parent.resolve())
    header = (
        f"<!-- Generated by `{control_plane_command('render-agents')}`. "
        f"Edit {display_input} and included files instead. -->\n\n"
    )
    return header + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render @include directives into a flat instruction file.")
    parser.add_argument("--input", default="CLAUDE.md", help="Source instruction file (default: CLAUDE.md)")
    parser.add_argument(
        "--output",
        default="AGENTS.md",
        help="Output file path or '-' for stdout (default: AGENTS.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when output file is out of sync with rendered content.",
    )
    args = parser.parse_args(argv)

    input_path = Path(args.input).expanduser()
    if not input_path.exists():
        print(f"render-agents: input file not found: {input_path}", file=sys.stderr)
        return 1

    output_path = None if args.output == "-" else Path(args.output).expanduser()

    try:
        rendered = render_document(input_path=input_path, output_path=output_path)
    except RuntimeError as exc:
        print(f"render-agents: {exc}", file=sys.stderr)
        return 1

    if args.output == "-":
        if args.check:
            print("render-agents: --check does not support --output -", file=sys.stderr)
            return 2
        sys.stdout.write(rendered)
        return 0

    assert output_path is not None
    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != rendered:
            print(f"render-agents: out of sync: {output_path}", file=sys.stderr)
            print(
                f"render-agents: run: {control_plane_command('render-agents', '--input', str(input_path), '--output', str(output_path))}",
                file=sys.stderr,
            )
            return 1
        print(f"render-agents: sync OK: {output_path}")
        return 0

    write_if_changed(output_path, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
