"""Render the quality workflow reference from live registries."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from devtools.quality_registry import (
    BenchmarkCampaignEntry,
    MutationCampaignEntry,
    QualityRegistry,
    ValidationLaneEntry,
    build_quality_registry,
)


def _format_code_list(items: tuple[str, ...]) -> str:
    if not items:
        return "—"
    return "<br>".join(f"`{item}`" for item in items)


def _render_lane_table(entries: tuple[ValidationLaneEntry, ...]) -> list[str]:
    lines = [
        "| Lane | Timeout (s) | Description |",
        "| --- | ---: | --- |",
    ]
    for entry in entries:
        lines.append(f"| `{entry.name}` | {entry.timeout_s} | {entry.description} |")
    return lines


def _render_composite_lane_table(entries: tuple[ValidationLaneEntry, ...]) -> list[str]:
    lines = [
        "| Lane | Timeout (s) | Includes | Description |",
        "| --- | ---: | --- | --- |",
    ]
    for entry in entries:
        includes = _format_code_list(entry.sub_lanes)
        lines.append(f"| `{entry.name}` | {entry.timeout_s} | {includes} | {entry.description} |")
    return lines


def _render_mutation_table(entries: tuple[MutationCampaignEntry, ...]) -> list[str]:
    lines = [
        "| Campaign | Mutates | Tests | Description |",
        "| --- | --- | --- | --- |",
    ]
    for entry in entries:
        lines.append(
            f"| `{entry.name}` | {_format_code_list(entry.paths_to_mutate)} | "
            f"{_format_code_list(entry.tests)} | {entry.description} |"
        )
    return lines


def _render_benchmark_table(entries: tuple[BenchmarkCampaignEntry, ...]) -> list[str]:
    lines = [
        "| Campaign | Tests | Warn | Fail | Description |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for entry in entries:
        lines.append(
            f"| `{entry.name}` | {_format_code_list(entry.tests)} | "
            f"{entry.warn_pct:.1f}% | {entry.fail_pct:.1f}% | {entry.description} |"
        )
    return lines


def build_document(registry: QualityRegistry) -> str:
    parts = [
        "[← Back to README](../README.md)",
        "",
        "<!-- Generated by scripts/render-quality-reference. Edit devtools/render_quality_reference.py and devtools/quality_registry.py instead. -->",
        "",
        "# Test Quality Workflows",
        "",
        "This reference is generated from the live validation-lane, mutation-campaign, and benchmark-campaign registries.",
        "",
        "Current registry snapshot:",
        "",
        f"- contract lanes: `{len(registry.contract_lanes)}`",
        f"- live lanes: `{len(registry.live_lanes)}`",
        f"- composite lanes: `{len(registry.composite_lanes)}`",
        f"- mutation campaigns: `{len(registry.mutation_campaigns)}`",
        f"- benchmark campaigns: `{len(registry.benchmark_campaigns)}`",
        "",
        "## Canonical Commands",
        "",
        "### Full correctness run",
        "",
        "```bash",
        "nix develop -c pytest -q -n 0",
        "```",
        "",
        "### Fast local run",
        "",
        "Use this when iterating locally and you do not need the explicit slow proofs or benchmarks.",
        "",
        "```bash",
        'nix develop -c pytest -q -n 0 -m "not slow and not benchmark"',
        "```",
        "",
        "### Validation lanes",
        "",
        "```bash",
        "nix develop -c python -m devtools.run_validation_lanes --list",
        "nix develop -c python -m devtools.run_validation_lanes --lane frontier-local",
        "nix develop -c python -m devtools.run_validation_lanes --lane live-exercises --dry-run",
        "```",
        "",
        "### Mutation campaigns",
        "",
        "```bash",
        "nix develop -c python -m devtools.mutmut_campaign list",
        "nix develop -c python -m devtools.mutmut_campaign run <campaign>",
        "nix develop -c python -m devtools.mutmut_campaign index",
        "```",
        "",
        "### Benchmark campaigns",
        "",
        "```bash",
        "nix develop -c python -m devtools.benchmark_campaign list",
        "nix develop -c python -m devtools.benchmark_campaign run <campaign>",
        "nix develop -c python -m devtools.benchmark_campaign compare \\",
        "  artifacts/benchmark-campaigns/<baseline>.json \\",
        "  artifacts/benchmark-campaigns/<candidate>.json",
        "nix develop -c python -m devtools.benchmark_campaign index",
        "```",
        "",
        "### Fast pipeline probes",
        "",
        "```bash",
        "nix develop -c python -m devtools.pipeline_probe --provider chatgpt --count 5 --stage parse --workdir /tmp/polylogue-probe",
        "nix develop -c python -m devtools.pipeline_probe --input-mode archive-subset --source-db /home/sinity/.local/share/polylogue/polylogue.db_ --sample-per-provider 50 --stage parse --workdir /tmp/polylogue-probe-real --manifest-out /tmp/polylogue-probe-real.json",
        "nix develop -c python -m devtools.pipeline_probe --input-mode archive-subset --manifest-in /tmp/polylogue-probe-real.json --stage parse --workdir /tmp/polylogue-probe-replay",
        "```",
        "",
        "### Showcase baseline drift",
        "",
        "```bash",
        "nix develop -c python -m devtools.verify_showcase",
        "nix develop -c python -m devtools.verify_showcase --update",
        "```",
        "",
        "## Validation Lane Catalog",
        "",
        "The lane names below are the stable operator surface. Use the runner rather than copying the underlying pytest command lines into ad-hoc scripts.",
        "",
        "### Contract Lanes",
        "",
        *_render_lane_table(registry.contract_lanes),
        "",
        "### Live Lanes",
        "",
        *_render_lane_table(registry.live_lanes),
        "",
        "### Composite Lanes",
        "",
        *_render_composite_lane_table(registry.composite_lanes),
        "",
        "## Mutation Campaign Catalog",
        "",
        "Durable mutation ledgers live in [mutation-testing-baseline.md](./mutation-testing-baseline.md) and under `artifacts/mutation-campaigns/`.",
        "",
        *_render_mutation_table(registry.mutation_campaigns),
        "",
        "## Benchmark Campaign Catalog",
        "",
        "Benchmark comparisons are intentionally operator-run rather than default hosted-CI jobs.",
        "",
        *_render_benchmark_table(registry.benchmark_campaigns),
        "",
        "## Artifact Locations",
        "",
        "- mutation campaigns: `artifacts/mutation-campaigns/`",
        "- benchmark campaigns: `artifacts/benchmark-campaigns/`",
        "- pipeline probe manifests and replay bundles: operator-selected paths outside the repo by default",
        "",
        "## Slow-Test Policy",
        "",
        "- keep the default correctness lane representative of real archive/storage invariants",
        "- mark a test `slow` only when it is an optional heavy proof rather than a core correctness contract",
        "- review `pytest --durations` output when a new heavy test appears instead of freezing timing tables in docs",
        "",
        "## Operator Guidance",
        "",
        "When changing code in a narrow domain:",
        "",
        "1. run the targeted `pytest -q -n 0` slice for that domain",
        "2. run the corresponding mutation campaign if that domain has one",
        "3. run the corresponding benchmark campaign only if the change touches a hot path already represented in `tests/benchmarks`",
        "4. rerun the full correctness lane before closing the work",
        "",
        "When a new validation lane, mutation campaign, or benchmark campaign is added, regenerate this document instead of editing it by hand.",
        "",
    ]
    return "\n".join(parts)


def write_if_changed(output_path: Path, content: str) -> None:
    try:
        current = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current == content:
        return
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_suffix(output_path.suffix + ".tmp")
    tmp_path.write_text(content, encoding="utf-8")
    tmp_path.replace(output_path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docs/test-quality-workflows.md from live quality registries.")
    parser.add_argument(
        "--output",
        default="docs/test-quality-workflows.md",
        help="Output file path or '-' for stdout (default: docs/test-quality-workflows.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the output file is out of sync with the rendered content.",
    )
    args = parser.parse_args(argv)

    output_path = None if args.output == "-" else Path(args.output).expanduser()
    rendered = build_document(build_quality_registry())
    if not rendered.endswith("\n"):
        rendered += "\n"

    if args.output == "-":
        if args.check:
            print("render-quality-reference: --check does not support --output -", file=sys.stderr)
            return 2
        sys.stdout.write(rendered)
        return 0

    assert output_path is not None
    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != rendered:
            print(f"render-quality-reference: out of sync: {output_path}", file=sys.stderr)
            print(
                f"render-quality-reference: run: render-quality-reference --output {output_path}",
                file=sys.stderr,
            )
            return 1
        print(f"render-quality-reference: sync OK: {output_path}")
        return 0

    write_if_changed(output_path, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
