"""Render parser-gated query discovery declarations into docs/search.md."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed
from polylogue.archive.query.discovery import (
    QUERY_DISCOVERY_EXAMPLES,
    QUERY_DISCOVERY_GRAMMAR,
    QUERY_DISCOVERY_NEGATIVE_EXAMPLES,
    RESULT_SEMANTICS_TEACHING,
    query_discovery_examples,
)
from polylogue.archive.query.metadata import structural_query_units, terminal_query_sources

GENERATED_BEGIN = "<!-- BEGIN GENERATED: query-discovery -->"
GENERATED_END = "<!-- END GENERATED: query-discovery -->"


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def build_block() -> str:
    featured = query_discovery_examples(featured=True)
    shipped_invalid = tuple(row for row in QUERY_DISCOVERY_NEGATIVE_EXAMPLES if row.shipped_at)
    lines = [
        GENERATED_BEGIN,
        "### Executable discovery corpus",
        "",
        (
            f"Generated by `{control_plane_command('render query-discovery')}` from "
            "`polylogue/archive/query/discovery.py`. The corpus contains "
            f"{len(QUERY_DISCOVERY_EXAMPLES)} positive and {len(QUERY_DISCOVERY_NEGATIVE_EXAMPLES)} negative "
            "declarations. Every positive expression is parsed by the production Lark/compiler route in tests; "
            "every negative declaration pins the production diagnostic and a parser-valid correction."
        ),
        "",
        "Executable forms projected from the declarations:",
        "",
        "| Form | Syntax |",
        "|---|---|",
        *(f"| `{name}` | `{_cell(syntax)}` |" for name, syntax in QUERY_DISCOVERY_GRAMMAR.items()),
        "",
        f"Terminal sources: `{_cell(' / '.join(terminal_query_sources()))}`.",
        f"Structural `exists` units: `{_cell(' / '.join(structural_query_units()))}`.",
        "",
        "Result coverage and `total` must be read with the declared semantics:",
        "",
        "| Class | Total | Continuation | Discovery wording |",
        "|---|---|---|---|",
    ]
    for contract in RESULT_SEMANTICS_TEACHING:
        lines.append(
            f"| `{contract.coverage}` | `{contract.total}` | `{contract.continuation}` | {_cell(contract.phrase)} |"
        )
    lines.extend(
        [
            "",
            "Featured parser-gated examples:",
            "",
            "| Semantics | Source | Expression | What it answers | Projection | Cost |",
            "|---|---|---|---|---|---|",
        ]
    )
    for row in featured:
        projection = ", ".join(row.projection_columns)
        lines.append(
            f"| `{row.result_semantics}` | `{row.unit_source}` | `{_cell(row.expression)}` | "
            f"{_cell(row.answers)} | `{_cell(projection)}` | `{row.cost_class}` |"
        )
    lines.extend(
        [
            "",
            "Invalid examples found in shipped teaching surfaces at the snapshot boundary:",
            "",
            "| Shipped at | Rejected expression | Actual diagnostic | Corrected form |",
            "|---|---|---|---|",
        ]
    )
    for negative in shipped_invalid:
        lines.append(
            f"| `{_cell(', '.join(negative.shipped_at))}` | `{_cell(negative.expression)}` | "
            f"{_cell(negative.diagnostic)} | `{_cell(negative.corrected_form)}` |"
        )
    lines.extend(
        [
            "",
            "Machine clients can request parser-gated positives with MCP/CLI "
            '`query_completions(kind="example")` and real diagnostics/corrections with '
            '`query_completions(kind="error")`. The query capability resource carries corpus counts and '
            "the six shared semantics contracts.",
            GENERATED_END,
        ]
    )
    return "\n".join(lines)


def render_document(current: str) -> str:
    block = build_block()
    if GENERATED_BEGIN not in current or GENERATED_END not in current:
        raise ValueError("docs/search.md is missing query-discovery generated markers")
    prefix, remainder = current.split(GENERATED_BEGIN, 1)
    _, suffix = remainder.split(GENERATED_END, 1)
    return prefix.rstrip() + "\n\n" + block + "\n\n" + suffix.lstrip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render parser-gated query discovery into docs/search.md.")
    parser.add_argument("--output", default="docs/search.md")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    output = Path(args.output)
    try:
        current = output.read_text(encoding="utf-8")
        rendered = render_document(current)
    except (OSError, ValueError) as exc:
        print(f"render query-discovery: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if current != rendered:
            print(f"render query-discovery: out of sync: {output}", file=sys.stderr)
            return 1
        return 0

    write_if_changed(output, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
