"""Render the deterministic demo corpus construct datasheet."""

from __future__ import annotations

import argparse
import asyncio
import shutil
import sqlite3
import sys
from dataclasses import dataclass
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed
from polylogue.demo import DemoSeedResult, DemoVerifyResult, seed_demo_archive, verify_demo_archive
from polylogue.scenarios import DEMO_CORPUS_FAMILIES

GENERATED_NOTE = (
    f"<!-- Generated by `{control_plane_command('render demo-corpus-datasheet')}`. "
    "Edit devtools/render_demo_corpus_datasheet.py, polylogue/demo/constructs.py, "
    "and polylogue/scenarios/corpus.py instead. -->"
)


@dataclass(frozen=True, slots=True)
class DemoCorpusMeasurement:
    """SQLite row counts that make the datasheet concrete."""

    blocks: int
    origins: tuple[str, ...]
    run_rows: int
    observed_event_rows: int
    context_snapshot_rows: int


RESIDUAL_GAPS: tuple[tuple[str, str, str], ...] = (
    (
        "Abandoned / censored sessions",
        "temporary-session coverage exists; no abandoned/censored variants yet",
        "`polylogue-cfk`, temporal-analysis beads",
    ),
    (
        "Browser-capture convergence cases",
        "capture-gap event coverage exists; no multi-capture convergence/debt scenario yet",
        "`polylogue-b5l`, capture-completeness work",
    ),
    (
        "Subagent run projection collision",
        "parent subagent run currently collides with the child main `run_ref`; tracked as `polylogue-85z0`",
        "`polylogue-37t.11`, `polylogue-4ts.1`",
    ),
)


def _code_list(items: tuple[str, ...]) -> str:
    if not items:
        return "—"
    return "<br>".join(f"`{item}`" for item in items)


def _measure_archive(archive_root: Path) -> DemoCorpusMeasurement:
    with sqlite3.connect(f"file:{archive_root / 'index.db'}?mode=ro", uri=True) as conn:
        origins = tuple(
            str(row[0]) for row in conn.execute("SELECT DISTINCT origin FROM sessions ORDER BY origin").fetchall()
        )
        return DemoCorpusMeasurement(
            blocks=int(conn.execute("SELECT COUNT(*) FROM blocks").fetchone()[0]),
            origins=origins,
            run_rows=int(conn.execute("SELECT COUNT(*) FROM session_runs").fetchone()[0]),
            observed_event_rows=int(conn.execute("SELECT COUNT(*) FROM session_observed_events").fetchone()[0]),
            context_snapshot_rows=int(conn.execute("SELECT COUNT(*) FROM session_context_snapshots").fetchone()[0]),
        )


async def seed_datasheet_archive(work_root: Path) -> tuple[DemoSeedResult, DemoVerifyResult, DemoCorpusMeasurement]:
    """Build the deterministic demo archive used to render this datasheet."""

    archive_root = work_root / "archive"
    if archive_root.exists():
        shutil.rmtree(archive_root)
    seed = await seed_demo_archive(archive_root, force=True, with_overlays=True)
    verify = verify_demo_archive(archive_root, require_overlays=True)
    measurement = _measure_archive(archive_root)
    return seed, verify, measurement


def _render_family_table() -> list[str]:
    lines = [
        "| Family | Provider | Source paths | Construct IDs | Synthetic |",
        "| --- | --- | --- | --- | --- |",
    ]
    for family in DEMO_CORPUS_FAMILIES:
        lines.append(
            f"| `{family.family_id}` | `{family.provider}` | {_code_list(family.source_paths)} | "
            f"{_code_list(family.construct_ids)} | `{str(family.synthetic).lower()}` |"
        )
    return lines


def _render_construct_table(seed: DemoSeedResult) -> list[str]:
    lines = [
        "| Construct | Observed | Minimum | Status |",
        "| --- | ---: | ---: | --- |",
    ]
    for row in seed.construct_coverage:
        status = "ok" if row.ok else "missing"
        lines.append(f"| {row.label} (`{row.construct_id}`) | {row.observed} | {row.minimum} | `{status}` |")
    return lines


def _render_residual_table() -> list[str]:
    lines = [
        "| Gap | Current evidence | Driver beads |",
        "| --- | --- | --- |",
    ]
    for gap, evidence, beads in RESIDUAL_GAPS:
        lines.append(f"| {gap} | {evidence} | {beads} |")
    return lines


def build_document(
    seed: DemoSeedResult,
    verify: DemoVerifyResult,
    measurement: DemoCorpusMeasurement,
) -> str:
    """Render the datasheet from declared families plus measured archive rows."""

    parts = [
        "# Demo Corpus Construct Audit",
        "",
        GENERATED_NOTE,
        "",
        "This datasheet is generated from the deterministic demo family registry, "
        "the declared construct registry, and a fresh no-daemon seed/verify run. "
        "It exists to keep demo claims construct-valid instead of relying on a "
        "hand-maintained table.",
        "",
        "## Evidence Snapshot",
        "",
        f"- Seed command: `{control_plane_command('render demo-corpus-datasheet')}` "
        "seeds a throwaway archive under `.cache/demo-corpus-datasheet/archive` "
        "with overlays enabled.",
        "- Verifier: `polylogue demo verify --require-overlays` semantics via `verify_demo_archive`.",
        f"- Verifier result: `{'ok' if verify.ok else 'failed'}`.",
        f"- Problems: {'—' if not verify.problems else '; '.join(verify.problems)}",
        "",
        "## Current Demo Archive Coverage",
        "",
        "| Fact | Current |",
        "| --- | ---: |",
        f"| Sessions | {seed.session_count} |",
        f"| Messages | {seed.message_count} indexed |",
        f"| Blocks | {measurement.blocks} |",
        f"| Session profiles | {next((row.observed for row in seed.construct_coverage if row.construct_id == 'session_profiles'), 0)} |",
        f"| Origins | {', '.join(measurement.origins)} |",
        f"| Run rows | {measurement.run_rows} |",
        f"| Observed-event rows | {measurement.observed_event_rows} |",
        f"| Context-snapshot rows | {measurement.context_snapshot_rows} |",
        "",
        "## Declared Source Families",
        "",
        *_render_family_table(),
        "",
        "## Declared Construct Coverage",
        "",
        *_render_construct_table(seed),
        "",
        "## Interpretation Notes",
        "",
        "- Families go through normal parser/storage paths; the demo does not patch rows directly into the index tier.",
        "- Codex `forked_from_id` is measured as a generic `branch` link with "
        "`prefix-sharing` inheritance because source evidence proves parentage "
        "and shared prefix, not fork-vs-resume.",
        "- Claude Code `agent-acompact-*` measures a continuation link and "
        "compaction event; the sidechain source measures typed sidechain session "
        "state.",
        "- Embedding coverage uses deterministic synthetic vectors over authored "
        "demo prose; it proves non-empty embedding-tier/status surfaces without "
        "contacting an external provider.",
        "",
        "## Residual Gaps",
        "",
        *_render_residual_table(),
        "",
    ]
    return "\n".join(parts)


def render_datasheet(*, work_root: Path) -> str:
    seed, verify, measurement = asyncio.run(seed_datasheet_archive(work_root.resolve()))
    rendered = build_document(seed, verify, measurement)
    if not rendered.endswith("\n"):
        rendered += "\n"
    return rendered


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the deterministic demo corpus construct datasheet.")
    parser.add_argument(
        "--output",
        default="docs/plans/demo-corpus-construct-audit.md",
        help="Output file path or '-' for stdout (default: docs/plans/demo-corpus-construct-audit.md)",
    )
    parser.add_argument(
        "--work-root",
        default=".cache/demo-corpus-datasheet",
        help="Scratch root for the throwaway measured demo archive.",
    )
    parser.add_argument("--check", action="store_true", help="Exit non-zero when the output is out of sync.")
    args = parser.parse_args(argv)

    rendered = render_datasheet(work_root=Path(args.work_root))

    if args.output == "-":
        if args.check:
            print("render demo-corpus-datasheet: --check does not support --output -", file=sys.stderr)
            return 2
        sys.stdout.write(rendered)
        return 0

    output_path = Path(args.output).expanduser().resolve()
    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != rendered:
            print(f"render demo-corpus-datasheet: out of sync: {output_path}", file=sys.stderr)
            print(
                f"render demo-corpus-datasheet: run: {control_plane_command('render demo-corpus-datasheet')}",
                file=sys.stderr,
            )
            return 1
        print("render demo-corpus-datasheet: sync OK")
        return 0

    write_if_changed(output_path, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
