"""Render the declaration-derived six-tier schema disposition artifacts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import cast

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed
from polylogue.storage.sqlite.archive_tiers.schema_disposition import schema_disposition_report


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_json(report: dict[str, object]) -> str:
    return json.dumps(report, indent=2, sort_keys=True) + "\n"


def render_markdown(report: dict[str, object]) -> str:
    tier_counts = cast("dict[str, dict[str, int]]", report["tier_counts"])
    disposition_counts = cast("dict[str, int]", report["disposition_counts"])
    objects = cast("list[dict[str, object]]", report["objects"])
    total = report["object_count"]
    lines = [
        "# Six-tier schema disposition (gvzkr)",
        "",
        f"Generated by `{control_plane_command('render schema-disposition')}` from the canonical SQLite declarations. The report classifies every declared table, column, index, trigger, and view without reading an operator archive. A `PURGE` row marks an approved retirement; durable objects remain declared until their authenticated change train completes.",
        "",
        "## Coverage",
        "",
        "| tier | objects | tables | columns | indexes | triggers | views |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for tier, counts in sorted(tier_counts.items()):
        lines.append(
            f"| {tier}.db | {counts['objects']} | {counts['tables']} | {counts['columns']} | "
            f"{counts['indexes']} | {counts['triggers']} | {counts['views']} |"
        )
    lines.extend(
        [
            f"| **total** | **{total}** | **{sum(count['tables'] for count in tier_counts.values())}** | **{sum(count['columns'] for count in tier_counts.values())}** | **{sum(count['indexes'] for count in tier_counts.values())}** | **{sum(count['triggers'] for count in tier_counts.values())}** | **{sum(count['views'] for count in tier_counts.values())}** |",
            "",
            "| disposition | objects |",
            "|---|---:|",
        ]
    )
    lines.extend(f"| {disposition} | {count} |" for disposition, count in sorted(disposition_counts.items()))
    lines.extend(
        [
            f"| **unknown** | **{report['unknown_count']}** |",
            "",
            "## Full object disposition",
            "",
            "| Object | Type | Disposition | Owner | Producer | Consumer | Live denominator | Action | Successor or authorization | Definition SHA-256 |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for obj in objects:
        lines.append(
            "| "
            + " | ".join(
                _cell(obj[key])
                for key in (
                    "object_ref",
                    "object_type",
                    "disposition",
                    "semantic_owner",
                    "producer",
                    "consumer",
                    "live_row_denominator",
                    "campaign_action",
                    "successor_or_authorization",
                    "definition_sha256",
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the six-tier schema disposition artifacts.")
    parser.add_argument("--markdown-output", type=Path, default=Path("docs/schema-disposition-2026-08-19.md"))
    parser.add_argument("--json-output", type=Path, default=Path("docs/evidence/schema-disposition-2026-08-31.json"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    report = schema_disposition_report()
    outputs = ((args.markdown_output, render_markdown(report)), (args.json_output, render_json(report)))
    if args.check:
        for path, content in outputs:
            try:
                current = path.read_text(encoding="utf-8")
            except OSError as exc:
                print(f"render schema-disposition: {exc}", file=sys.stderr)
                return 1
            if current != content:
                print(f"render schema-disposition: out of sync: {path}", file=sys.stderr)
                return 1
        return 0
    for path, content in outputs:
        write_if_changed(path, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
