"""Render the WebUI TypeScript client from the generated daemon OpenAPI schema.

The OpenAPI document is the only input contract. Component schemas become
TypeScript aliases, operation declarations become thin typed methods, and the
``x-polylogue-page`` extension declares which operations support opaque
continuation iteration. The generated file is committed so TypeScript builds
fail when the daemon contract changes without regeneration.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed

DEFAULT_SCHEMA_PATH = Path("docs/openapi/search.yaml")
DEFAULT_OUTPUT_PATH = Path("webui/src/api/generated.ts")
_HTTP_METHODS = ("delete", "get", "patch", "post", "put")
_TS_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
_COVERAGE_QUALIFICATIONS = frozenset({"page", "capped", "sampled", "estimate", "unknown"})


class ContractGenerationError(ValueError):
    """Raised when the OpenAPI document cannot produce a sound client."""


@dataclass(frozen=True, slots=True)
class Parameter:
    name: str
    location: str
    required: bool
    schema: Mapping[str, Any]


@dataclass(frozen=True, slots=True)
class Operation:
    operation_id: str
    method: str
    path: str
    parameters: tuple[Parameter, ...]
    success_schema: Mapping[str, Any] | None
    error_schemas: tuple[Mapping[str, Any], ...]
    page: Mapping[str, Any] | None

    @property
    def type_stem(self) -> str:
        return _pascal_case(self.operation_id)


class TypeScriptRenderer:
    """Small deterministic OpenAPI 3.1 to TypeScript renderer.

    It intentionally implements the JSON Schema constructs emitted by the
    repository's Pydantic models instead of importing a second generator
    framework. Unsupported constructs fail closed with a source location.
    """

    def __init__(self, document: Mapping[str, Any], *, source_label: str) -> None:
        self.document = document
        self.source_label = source_label
        components = _mapping(document.get("components"), "components")
        self.schemas = _mapping(components.get("schemas"), "components.schemas")
        self.operations = self._collect_operations()

    def render(self) -> str:
        lines = [
            "// Generated by `devtools render webui-client`. Do not edit by hand.",
            f"// Source: {self.source_label}",
            "",
            "import {",
            "  FetchTransport,",
            "  iteratePages,",
            "  type ClientTransport,",
            "  type Page,",
            "  type RequestOptions,",
            '} from "./runtime.js";',
            "",
        ]

        for name in sorted(self.schemas):
            lines.extend(self._render_component(name, _mapping(self.schemas[name], f"schema {name}")))
            lines.append("")

        for operation in self.operations:
            lines.extend(self._render_operation_types(operation))
            lines.append("")

        rendered_guards: set[str] = set()
        for operation in self.operations:
            if operation.page is None:
                continue
            page = operation.page
            items_property = page.get("items_property")
            if not isinstance(items_property, str):
                raise ContractGenerationError(f"{operation.operation_id}: page items_property must be a string")
            for schema_name in _string_list(
                page.get("response_schemas"),
                f"{operation.operation_id}.x-polylogue-page.response_schemas",
            ):
                if schema_name in rendered_guards:
                    continue
                rendered_guards.add(schema_name)
                lines.extend(self._render_page_guard(schema_name, items_property))
                lines.append("")

        lines.extend(self._render_client())
        return "\n".join(lines).rstrip() + "\n"

    def _collect_operations(self) -> tuple[Operation, ...]:
        paths = _mapping(self.document.get("paths"), "paths")
        operations: list[Operation] = []
        seen_ids: set[str] = set()
        seen_iterators: set[str] = set()
        for path in sorted(paths):
            path_item = _mapping(paths[path], f"paths.{path}")
            inherited = self._parameters(path_item.get("parameters"), f"paths.{path}.parameters")
            for method in _HTTP_METHODS:
                raw = path_item.get(method)
                if raw is None:
                    continue
                operation = _mapping(raw, f"paths.{path}.{method}")
                if "requestBody" in operation:
                    raise ContractGenerationError(
                        f"{path} {method}: request bodies are not supported by the generated client"
                    )
                operation_id = operation.get("operationId")
                if not isinstance(operation_id, str) or not _TS_IDENTIFIER.fullmatch(operation_id):
                    raise ContractGenerationError(f"{path} {method}: operationId must be a TypeScript identifier")
                if operation_id in seen_ids:
                    raise ContractGenerationError(f"duplicate operationId: {operation_id}")
                seen_ids.add(operation_id)
                own = self._parameters(operation.get("parameters"), f"paths.{path}.{method}.parameters")
                parameters_by_key = {(item.location, item.name): item for item in (*inherited, *own)}
                responses = _mapping(operation.get("responses"), f"paths.{path}.{method}.responses")
                success_schema = self._success_schema(responses, path=path, method=method)
                errors = self._error_schemas(responses)
                page = operation.get("x-polylogue-page")
                if page is not None:
                    page = _mapping(page, f"paths.{path}.{method}.x-polylogue-page")
                    iterator = page.get("iterator")
                    if not isinstance(iterator, str) or not _TS_IDENTIFIER.fullmatch(iterator):
                        raise ContractGenerationError(
                            f"{path} {method}: x-polylogue-page.iterator must be a TypeScript identifier"
                        )
                    if iterator in seen_iterators:
                        raise ContractGenerationError(f"duplicate x-polylogue-page iterator: {iterator}")
                    seen_iterators.add(iterator)
                operations.append(
                    Operation(
                        operation_id=operation_id,
                        method=method.upper(),
                        path=path,
                        parameters=tuple(
                            sorted(parameters_by_key.values(), key=lambda item: (item.location, item.name))
                        ),
                        success_schema=success_schema,
                        error_schemas=errors,
                        page=page,
                    )
                )
        return tuple(sorted(operations, key=lambda item: item.operation_id))

    def _parameters(self, raw: object, location: str) -> tuple[Parameter, ...]:
        if raw is None:
            return ()
        if not isinstance(raw, list):
            raise ContractGenerationError(f"{location} must be a list")
        parameters: list[Parameter] = []
        for index, item in enumerate(raw):
            value = _mapping(item, f"{location}[{index}]")
            if "$ref" in value:
                raise ContractGenerationError(f"{location}[{index}]: parameter references are not supported")
            name = value.get("name")
            parameter_location = value.get("in")
            schema = value.get("schema", {})
            if not isinstance(name, str) or parameter_location not in {"path", "query"}:
                raise ContractGenerationError(f"{location}[{index}]: expected a path or query parameter")
            parameters.append(
                Parameter(
                    name=name,
                    location=str(parameter_location),
                    required=bool(value.get("required")) or parameter_location == "path",
                    schema=_mapping(schema, f"{location}[{index}].schema"),
                )
            )
        return tuple(parameters)

    def _success_schema(
        self,
        responses: Mapping[str, Any],
        *,
        path: str,
        method: str,
    ) -> Mapping[str, Any] | None:
        statuses = sorted(status for status in responses if str(status).startswith("2"))
        if not statuses:
            raise ContractGenerationError(f"{path} {method}: operation has no 2xx response")
        response = _mapping(responses[statuses[0]], f"{path} {method} response {statuses[0]}")
        return self._response_schema(response)

    def _error_schemas(self, responses: Mapping[str, Any]) -> tuple[Mapping[str, Any], ...]:
        schemas: list[Mapping[str, Any]] = []
        for status in sorted(responses):
            if str(status).startswith("2"):
                continue
            response = _mapping(responses[status], f"response {status}")
            schema = self._response_schema(response)
            if schema is not None:
                schemas.append(schema)
        return tuple(schemas)

    @staticmethod
    def _response_schema(response: Mapping[str, Any]) -> Mapping[str, Any] | None:
        content = response.get("content")
        if not isinstance(content, Mapping):
            return None
        application_json = content.get("application/json")
        if not isinstance(application_json, Mapping):
            return None
        schema = application_json.get("schema")
        return schema if isinstance(schema, Mapping) else None

    def _render_component(self, name: str, schema: Mapping[str, Any]) -> list[str]:
        if not _TS_IDENTIFIER.fullmatch(name):
            raise ContractGenerationError(f"component schema name is not a TypeScript identifier: {name}")
        return [f"export type {name} = {self._type(schema, location=f'components.schemas.{name}')};"]

    def _render_operation_types(self, operation: Operation) -> list[str]:
        parameters_name = f"{operation.type_stem}Parameters"
        lines = [f"export type {parameters_name} = {self._parameter_object(operation.parameters)};"]
        success = self._type(operation.success_schema, location=f"{operation.operation_id}.success")
        lines.append(f"export type {operation.type_stem}Response = {success};")
        errors = [self._type(schema, location=f"{operation.operation_id}.error") for schema in operation.error_schemas]
        lines.append(f"export type {operation.type_stem}Error = {_union(errors) if errors else 'unknown'};")
        if operation.page is not None:
            page = operation.page
            iterator = str(page["iterator"])
            initial_required = _string_list(
                page.get("initial_required_parameters", []),
                f"{operation.operation_id}.x-polylogue-page.initial_required_parameters",
            )
            parameter_names = {parameter.name for parameter in operation.parameters}
            missing = sorted(set(initial_required) - parameter_names)
            if missing:
                raise ContractGenerationError(
                    f"{operation.operation_id}: iterator requires undeclared parameters: {', '.join(missing)}"
                )
            initial_name = f"{_pascal_case(iterator)}Parameters"
            required_properties = " & ".join(
                f"{{ readonly {_property_name(name)}: {self._parameter_type(operation, name)} }}"
                for name in initial_required
            )
            omitted = sorted(set(initial_required) | {str(page.get("cursor_parameter", ""))})
            omitted = [name for name in omitted if name]
            omit_literal = " | ".join(_literal(name) for name in omitted)
            base = f"Omit<{parameters_name}, {omit_literal}>" if omitted else parameters_name
            suffix = " & " + required_properties if required_properties else ""
            lines.append(f"export type {initial_name} = {base}{suffix};")
            envelope_names = _string_list(
                page.get("response_schemas"),
                f"{operation.operation_id}.x-polylogue-page.response_schemas",
            )
            if not envelope_names:
                raise ContractGenerationError(f"{operation.operation_id}: page response_schemas must not be empty")
            for envelope_name in envelope_names:
                if envelope_name not in self.schemas:
                    raise ContractGenerationError(
                        f"{operation.operation_id}: unknown page response schema {envelope_name}"
                    )
            envelope = _union(envelope_names)
            item_types = [self._page_item_type(name, page, operation) for name in envelope_names]
            page_type = _pascal_case(iterator) + "Page"
            lines.append(f"export type {page_type} = Page<{_union(item_types)}, {envelope}>;")
        return lines

    def _parameter_type(self, operation: Operation, name: str) -> str:
        for parameter in operation.parameters:
            if parameter.name == name:
                return self._type(parameter.schema, location=f"{operation.operation_id}.parameter.{name}")
        raise AssertionError(name)

    def _parameter_object(self, parameters: tuple[Parameter, ...]) -> str:
        if not parameters:
            return "Record<string, never>"
        lines = ["{"]
        for parameter in parameters:
            marker = "" if parameter.required else "?"
            value = self._type(parameter.schema, location=f"parameter {parameter.name}")
            lines.append(f"  readonly {_property_name(parameter.name)}{marker}: {value};")
        lines.append("}")
        return "\n".join(lines)

    def _page_item_type(self, schema_name: str, page: Mapping[str, Any], operation: Operation) -> str:
        schema = _mapping(self.schemas[schema_name], f"components.schemas.{schema_name}")
        properties = _mapping(schema.get("properties"), f"components.schemas.{schema_name}.properties")
        items_property = page.get("items_property")
        if not isinstance(items_property, str) or items_property not in properties:
            raise ContractGenerationError(
                f"{operation.operation_id}: items_property must name a property on {schema_name}"
            )
        item_schema = _mapping(properties[items_property], f"{schema_name}.{items_property}")
        return self._array_item_type(item_schema, location=f"{schema_name}.{items_property}")

    def _render_page_guard(self, schema_name: str, items_property: str) -> list[str]:
        return [
            f"function is{schema_name}(value: unknown): value is {schema_name} {{",
            "  return (",
            '    typeof value === "object" &&',
            "    value !== null &&",
            f"    Array.isArray((value as {{ readonly {_property_name(items_property)}?: unknown }}).{items_property})",
            "  );",
            "}",
        ]

    def _array_item_type(self, schema: Mapping[str, Any], *, location: str) -> str:
        candidates = schema.get("anyOf") or schema.get("oneOf")
        if isinstance(candidates, list):
            arrays = [
                candidate
                for candidate in candidates
                if isinstance(candidate, Mapping) and candidate.get("type") == "array"
            ]
            if len(arrays) == 1:
                schema = arrays[0]
        if schema.get("type") != "array":
            raise ContractGenerationError(f"{location}: page items property must be an array")
        items = _mapping(schema.get("items", {}), f"{location}.items")
        return self._type(items, location=f"{location}.items")

    def _render_client(self) -> list[str]:
        lines = [
            "export class PolylogueClient {",
            "  readonly #transport: ClientTransport;",
            "",
            "  constructor(transport: ClientTransport = new FetchTransport()) {",
            "    this.#transport = transport;",
            "  }",
        ]
        for operation in self.operations:
            lines.append("")
            lines.extend(self._render_method(operation))
            if operation.page is not None:
                lines.append("")
                lines.extend(self._render_iterator(operation))
        lines.append("}")
        return lines

    def _render_method(self, operation: Operation) -> list[str]:
        parameters_name = f"{operation.type_stem}Parameters"
        required = any(parameter.required for parameter in operation.parameters)
        default = "" if required else " = {}"
        response = f"{operation.type_stem}Response"
        error = f"{operation.type_stem}Error"
        lines = [
            f"  {operation.operation_id}(",
            f"    parameters: {parameters_name}{default},",
            "    options: RequestOptions = {},",
            f"  ): Promise<{response}> {{",
        ]
        path = operation.path
        for parameter in operation.parameters:
            if parameter.location == "path":
                path_token = "{" + parameter.name + "}"
                if path_token not in path:
                    raise ContractGenerationError(
                        f"{operation.operation_id}: path parameter {parameter.name} is not present in {path}"
                    )
                path = path.replace(path_token, f"${{encodeURIComponent(String(parameters.{parameter.name}))}}")
        path_expression = f"`{path}`" if "${" in path else json.dumps(path)
        query_parameters = [parameter for parameter in operation.parameters if parameter.location == "query"]
        lines.append(f"    return this.#transport.request<{response}, {error}>(")
        lines.append("      {")
        lines.append(f"        method: {_literal(operation.method)},")
        lines.append(f"        path: {path_expression},")
        if query_parameters:
            lines.append("        query: {")
            for parameter in query_parameters:
                lines.append(f"          {_property_name(parameter.name)}: parameters.{parameter.name},")
            lines.append("        },")
        lines.append("      },")
        lines.append("      options,")
        lines.append("    );")
        lines.append("  }")
        return lines

    def _render_iterator(self, operation: Operation) -> list[str]:
        page = operation.page
        assert page is not None
        iterator = str(page["iterator"])
        iterator_stem = _pascal_case(iterator)
        initial_name = f"{iterator_stem}Parameters"
        page_type = f"{iterator_stem}Page"
        response_schemas = _string_list(page.get("response_schemas"), f"{operation.operation_id}.response_schemas")
        envelope_union = _union(response_schemas)
        cursor_parameter = page.get("cursor_parameter")
        items_property = page.get("items_property")
        cursor_property = page.get("cursor_property")
        if not all(isinstance(value, str) and value for value in (cursor_parameter, items_property, cursor_property)):
            raise ContractGenerationError(f"{operation.operation_id}: page properties must be non-empty strings")
        mode = page.get("continuation_request")
        if mode not in {"cursor_only", "merge"}:
            raise ContractGenerationError(
                f"{operation.operation_id}: continuation_request must be cursor_only or merge"
            )
        response_guards = " || ".join(f"is{schema_name}(envelope)" for schema_name in response_schemas)
        lines = [
            f"  {iterator}(",
            f"    parameters: {initial_name},",
            "    options: RequestOptions = {},",
            f"  ): AsyncIterable<{page_type}> {{",
            f"    return iteratePages<{page_type}>(async (cursor) => {{",
        ]
        if mode == "cursor_only":
            retained = [
                f"{parameter.name}: parameters.{parameter.name}"
                for parameter in operation.parameters
                if parameter.location == "path"
            ]
            retained.append(f"{cursor_parameter}: cursor")
            continuation_parameters = "{ " + ", ".join(retained) + " }"
            lines.extend(
                [
                    "      const requestParameters =",
                    f"        cursor === null ? parameters : {continuation_parameters};",
                ]
            )
        else:
            reset_parameters = _string_list(
                page.get("reset_parameters", []),
                f"{operation.operation_id}.reset_parameters",
            )
            if reset_parameters:
                bindings = ", ".join(f"{name}: _{name}" for name in reset_parameters)
                lines.append(f"      const {{ {bindings}, ...continuedParameters }} = parameters;")
            else:
                lines.append("      const continuedParameters = parameters;")
            lines.append("      const requestParameters =")
            lines.append("        cursor === null")
            lines.append("          ? parameters")
            lines.append(f"          : {{ ...continuedParameters, {cursor_parameter}: cursor }};")
        lines.append(f"      const envelope = await this.{operation.operation_id}(requestParameters, options);")
        lines.append(f"      if (!({response_guards})) {{")
        lines.append(
            f"        throw new TypeError({_literal(operation.operation_id + ' returned a non-page envelope')});"
        )
        lines.append("      }")
        coverage = _mapping(page.get("coverage"), f"{operation.operation_id}.coverage")
        lines.extend(self._render_coverage(coverage, indent="      "))
        query_ref = page.get("query_ref_property")
        result_ref = page.get("result_ref_property")
        lines.extend(
            [
                "      return {",
                f"        items: envelope.{items_property},",
                f"        cursor: envelope.{cursor_property} ?? null,",
                "        coverage,",
                f"        queryRef: {f'envelope.{query_ref} ?? null' if isinstance(query_ref, str) else 'null'},",
                f"        resultRef: {f'envelope.{result_ref} ?? null' if isinstance(result_ref, str) else 'null'},",
                f"        envelope: envelope as {envelope_union},",
                "      };",
                "    });",
                "  }",
            ]
        )
        return lines

    def _render_coverage(self, coverage: Mapping[str, Any], *, indent: str) -> list[str]:
        total_property = coverage.get("total_property")
        if not isinstance(total_property, str) or not total_property:
            raise ContractGenerationError("x-polylogue-page.coverage.total_property must be a string")
        if coverage.get("kind") == "qualified":
            qualification = coverage.get("qualification")
            if qualification not in _COVERAGE_QUALIFICATIONS:
                raise ContractGenerationError("qualified page coverage requires a supported qualification")
            return [
                f"{indent}const coverage = {{",
                f'{indent}  kind: "qualified" as const,',
                f'{indent}  total: typeof envelope.{total_property} === "number" ? envelope.{total_property} : null,',
                f"{indent}  qualification: {_literal(qualification)} as const,",
                f"{indent}}};",
            ]
        exactness_property = coverage.get("exactness_property")
        if not isinstance(exactness_property, str) or not exactness_property:
            raise ContractGenerationError("dynamic page coverage requires exactness_property")
        exact_values = _string_list(coverage.get("exact_values", []), "coverage.exact_values")
        qualified_values = _string_list(coverage.get("qualified_values", []), "coverage.qualified_values")
        unsupported_qualifications = sorted(set(qualified_values) - _COVERAGE_QUALIFICATIONS)
        if unsupported_qualifications:
            raise ContractGenerationError(
                "dynamic page coverage has unsupported qualifications: " + ", ".join(unsupported_qualifications)
            )
        overlap = sorted(set(exact_values) & set(qualified_values))
        if overlap:
            raise ContractGenerationError(
                "dynamic page coverage values must be exact or qualified, not both: " + ", ".join(overlap)
            )
        default_exact = bool(coverage.get("default_exact"))
        exact_condition_parts = [f"envelope.{exactness_property} === {_literal(value)}" for value in exact_values]
        if default_exact:
            exact_condition_parts.append(f"envelope.{exactness_property} == null")
        exact_condition = " || ".join(exact_condition_parts) or "false"
        qualified_set = json.dumps(qualified_values, separators=(",", ":"))
        qualification_type = _union([*(_literal(value) for value in qualified_values), '"unknown"'])
        return [
            f'{indent}const exactTotal = typeof envelope.{total_property} === "number";',
            f"{indent}const exactCoverage = exactTotal && ({exact_condition});",
            f"{indent}const qualificationValues = new Set<string>({qualified_set});",
            f"{indent}const qualification =",
            f'{indent}  typeof envelope.{exactness_property} === "string" &&',
            f"{indent}  qualificationValues.has(envelope.{exactness_property})",
            f"{indent}    ? envelope.{exactness_property}",
            f'{indent}    : "unknown";',
            f"{indent}const coverage = exactCoverage",
            f'{indent}  ? {{ kind: "exact" as const, total: envelope.{total_property} as number }}',
            f"{indent}  : {{",
            f'{indent}      kind: "qualified" as const,',
            f"{indent}      total: exactTotal ? (envelope.{total_property} as number) : null,",
            f"{indent}      qualification: qualification as {qualification_type},",
            f"{indent}    }};",
        ]

    def _type(self, schema: Mapping[str, Any] | None, *, location: str) -> str:
        if schema is None:
            return "void"
        reference = schema.get("$ref")
        if isinstance(reference, str):
            prefix = "#/components/schemas/"
            if not reference.startswith(prefix):
                raise ContractGenerationError(f"{location}: unsupported reference {reference}")
            name = reference.removeprefix(prefix)
            if name not in self.schemas:
                raise ContractGenerationError(f"{location}: unknown schema reference {reference}")
            return name
        if "const" in schema:
            return _literal(schema["const"])
        enum = schema.get("enum")
        if isinstance(enum, list):
            return _union([_literal(value) for value in enum])
        for keyword, operator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
            variants = schema.get(keyword)
            if isinstance(variants, list):
                rendered = [
                    self._type(_mapping(value, f"{location}.{keyword}"), location=f"{location}.{keyword}")
                    for value in variants
                ]
                return operator.join(_parenthesize(value) for value in _dedupe(rendered)) or "unknown"
        raw_type = schema.get("type")
        if isinstance(raw_type, list):
            return _union([self._type({**schema, "type": item}, location=location) for item in raw_type])
        if raw_type == "array":
            items = _mapping(schema.get("items", {}), f"{location}.items")
            return f"ReadonlyArray<{self._type(items, location=f'{location}.items')}>"
        if raw_type == "object" or "properties" in schema or "additionalProperties" in schema:
            return self._object_type(schema, location=location)
        if raw_type in {"integer", "number"}:
            return "number"
        if raw_type == "string":
            return "string"
        if raw_type == "boolean":
            return "boolean"
        if raw_type == "null":
            return "null"
        if raw_type is None:
            return "unknown"
        raise ContractGenerationError(f"{location}: unsupported JSON Schema type {raw_type!r}")

    def _object_type(self, schema: Mapping[str, Any], *, location: str) -> str:
        raw_properties = schema.get("properties", {})
        properties = _mapping(raw_properties, f"{location}.properties")
        required = set(_string_list(schema.get("required", []), f"{location}.required"))
        lines = ["{"]
        for name in sorted(properties):
            property_schema = _mapping(properties[name], f"{location}.properties.{name}")
            marker = "" if name in required else "?"
            value = self._type(property_schema, location=f"{location}.properties.{name}")
            lines.append(f"  readonly {_property_name(name)}{marker}: {value};")
        additional = schema.get("additionalProperties")
        if additional is True:
            lines.append("  readonly [key: string]: unknown;")
        elif isinstance(additional, Mapping):
            value = self._type(additional, location=f"{location}.additionalProperties")
            lines.append(f"  readonly [key: string]: {value};")
        lines.append("}")
        return "\n".join(lines)


def _mapping(value: object, location: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ContractGenerationError(f"{location} must be an object")
    return value


def _string_list(value: object, location: str) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ContractGenerationError(f"{location} must be a list of strings")
    return list(value)


def _literal(value: object) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, int | float):
        return str(value)
    raise ContractGenerationError(f"unsupported literal value: {value!r}")


def _property_name(name: str) -> str:
    return name if _TS_IDENTIFIER.fullmatch(name) else json.dumps(name, ensure_ascii=False)


def _pascal_case(value: str) -> str:
    words = re.findall(r"[A-Z]?[a-z]+|[A-Z]+(?![a-z])|\d+", value.replace("-", "_").replace("_", " "))
    return "".join(word[:1].upper() + word[1:] for word in words) or "Generated"


def _dedupe(values: Sequence[str]) -> list[str]:
    return list(dict.fromkeys(values))


def _union(values: Sequence[str]) -> str:
    flattened: list[str] = []
    for value in values:
        if "\n" not in value and " & " not in value and " | " in value:
            flattened.extend(value.split(" | "))
        else:
            flattened.append(value)
    unique = _dedupe(flattened)
    return " | ".join(_parenthesize(value) for value in unique) if unique else "never"


def _parenthesize(value: str) -> str:
    if "\n" in value or " & " in value:
        return f"({value})"
    return value


def load_document(schema_path: Path) -> Mapping[str, Any]:
    try:
        loaded = yaml.safe_load(schema_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ContractGenerationError(f"schema not found: {schema_path}") from exc
    except yaml.YAMLError as exc:
        raise ContractGenerationError(f"invalid YAML in {schema_path}: {exc}") from exc
    document = _mapping(loaded, str(schema_path))
    if document.get("openapi") != "3.1.0":
        raise ContractGenerationError(f"{schema_path}: expected OpenAPI 3.1.0")
    return document


def generate(schema_path: Path) -> str:
    document = load_document(schema_path)
    return TypeScriptRenderer(document, source_label=schema_path.as_posix()).render()


def render(schema_path: Path, output_path: Path, *, check: bool) -> int:
    try:
        body = generate(schema_path)
    except ContractGenerationError as exc:
        print(f"render webui-client: {exc}", file=sys.stderr)
        return 2
    if check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != body:
            print(f"render webui-client: out of sync: {output_path}", file=sys.stderr)
            print(
                "render webui-client: run: " + control_plane_command("render webui-client"),
                file=sys.stderr,
            )
            return 1
        print(f"render webui-client: sync OK: {output_path}")
        return 0
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_if_changed(output_path, body)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the WebUI TypeScript client from generated OpenAPI.")
    parser.add_argument(
        "--schema",
        type=Path,
        default=DEFAULT_SCHEMA_PATH,
        help=f"Input OpenAPI path (default: {DEFAULT_SCHEMA_PATH}).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"Output TypeScript path (default: {DEFAULT_OUTPUT_PATH}).",
    )
    parser.add_argument("--check", action="store_true", help="Exit non-zero when committed output is stale.")
    args = parser.parse_args(list(argv) if argv is not None else None)
    return render(args.schema, args.output, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["ContractGenerationError", "TypeScriptRenderer", "generate", "main", "render"]
