"""Render the shared documentation surface into README targets."""

from __future__ import annotations

import argparse
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.docs_surface import (
    DOCS_REFERENCE_ENTRIES,
    DOCS_TIER_TITLES,
    README_DOC_TITLES,
    REPO_GUIDE_ENTRIES,
    DocsEntry,
)
from devtools.render_support import write_if_changed

README_MARKER = "docs-surface"
GENERATED_NOTE = (
    f"<!-- Generated by `{control_plane_command('render docs-surface')}`. Edit devtools/docs_surface.py instead. -->"
)
GENERATED_DOC_PATHS = frozenset({"docs/README.md"})


def _rebase_path(path: str, *, from_dir: str) -> str:
    target = Path(path)
    if not from_dir:
        return target.as_posix()
    if target.is_relative_to(from_dir):
        return target.relative_to(from_dir).as_posix()
    return Path(os.path.relpath(target.as_posix(), from_dir)).as_posix()


def _render_table(entries: tuple[DocsEntry, ...], *, from_dir: str = "") -> str:
    lines = ["| Document | Description |", "|----------|-------------|"]
    lines.extend(
        f"| [{entry.title}]({_rebase_path(entry.path, from_dir=from_dir)}) | {entry.description} |" for entry in entries
    )
    return "\n".join(lines)


def _select_entries(entries: tuple[DocsEntry, ...], titles: tuple[str, ...]) -> tuple[DocsEntry, ...]:
    by_title = {entry.title: entry for entry in entries}
    return tuple(by_title[title] for title in titles)


def undocumented_paths(docs_entries: tuple[DocsEntry, ...], *, docs_root: Path) -> set[str]:
    """Return Markdown files that have no deliberate place in the docs map."""
    expected = {f"docs/{path.relative_to(docs_root).as_posix()}" for path in docs_root.rglob("*.md")}
    documented = {entry.path for entry in docs_entries}
    return expected - documented - GENERATED_DOC_PATHS


def documentation_registry_errors(docs_entries: tuple[DocsEntry, ...], *, docs_root: Path) -> tuple[str, ...]:
    """Return catalog violations that would make the generated map dishonest."""
    missing = undocumented_paths(docs_entries, docs_root=docs_root)
    path_counts = Counter(entry.path for entry in docs_entries)
    duplicate_paths = sorted(path for path, count in path_counts.items() if count > 1)
    nonexistent_paths = sorted(
        path for path in path_counts if path not in GENERATED_DOC_PATHS and not (docs_root.parent / path).is_file()
    )

    errors: list[str] = []
    if missing:
        errors.append(f"unindexed documentation: {', '.join(sorted(missing))}")
    if duplicate_paths:
        errors.append(f"duplicate documentation entries: {', '.join(duplicate_paths)}")
    if nonexistent_paths:
        errors.append(f"nonexistent documentation entries: {', '.join(nonexistent_paths)}")
    return tuple(errors)


def build_docs_readme(
    docs_entries: tuple[DocsEntry, ...] = DOCS_REFERENCE_ENTRIES,
    repo_entries: tuple[DocsEntry, ...] = REPO_GUIDE_ENTRIES,
) -> str:
    entries_by_tier: dict[str, list[DocsEntry]] = defaultdict(list)
    for entry in docs_entries:
        entries_by_tier[entry.tier].append(entry)
    sections = [
        GENERATED_NOTE,
        "",
        "# Polylogue Docs Map",
        "",
        "Start with **Guides** for a task, **Reference** for a surface contract, and "
        "**Architecture and Internals** for the substrate. The remaining tiers preserve "
        "operational, evidence, design, and historical material without presenting it as "
        "a first-read path.",
    ]
    for tier, title in DOCS_TIER_TITLES:
        sections.extend(["", f"## {title}", "", _render_table(tuple(entries_by_tier[tier]), from_dir="docs")])
    sections.extend(["", "## Contributor Workflow", "", _render_table(repo_entries, from_dir="docs"), ""])
    return "\n".join(sections)


def build_readme_section(
    docs_entries: tuple[DocsEntry, ...] = DOCS_REFERENCE_ENTRIES,
    repo_entries: tuple[DocsEntry, ...] = REPO_GUIDE_ENTRIES,
) -> str:
    featured_docs = _select_entries(docs_entries, README_DOC_TITLES)
    return "\n".join(
        [
            "<!-- BEGIN GENERATED: docs-surface -->",
            "## Documentation",
            "",
            "Live site: <https://sinity.github.io/polylogue/>.",
            "",
            "Start with the task-oriented guides below; [docs/README.md](docs/README.md) "
            "separates guides, reference, internals, operations, evidence, design, and "
            "historical records. Current sequencing and active workstreams live in the Beads "
            "backlog (`bd ready`, `bd list --status open`).",
            "",
            _render_table(featured_docs),
            "",
            "<!-- END GENERATED: docs-surface -->",
        ]
    )


def replace_marked_section(text: str, *, marker: str, replacement: str) -> str:
    begin, end = f"<!-- BEGIN GENERATED: {marker} -->", f"<!-- END GENERATED: {marker} -->"
    start, finish = text.find(begin), text.find(end)
    if start == -1 or finish == -1 or finish < start:
        raise ValueError(f"marker block not found: {marker}")
    return text[:start] + replacement + text[finish + len(end) :]


def render_outputs(*, readme_path: Path, docs_readme_path: Path) -> tuple[str, str]:
    errors = documentation_registry_errors(DOCS_REFERENCE_ENTRIES, docs_root=docs_readme_path.parent)
    if errors:
        raise ValueError("; ".join(errors))
    docs_readme = build_docs_readme()
    readme = replace_marked_section(
        readme_path.read_text(encoding="utf-8"), marker=README_MARKER, replacement=build_readme_section()
    )
    return readme, docs_readme


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render README docs surfaces from the shared docs registry.")
    parser.add_argument("--readme", default="README.md", help="README path (default: README.md)")
    parser.add_argument("--docs-readme", default="docs/README.md", help="Docs map path (default: docs/README.md)")
    parser.add_argument("--check", action="store_true", help="Exit non-zero when README targets are out of sync.")
    args = parser.parse_args(argv)
    readme_path, docs_readme_path = Path(args.readme), Path(args.docs_readme)
    try:
        readme_content, docs_readme_content = render_outputs(readme_path=readme_path, docs_readme_path=docs_readme_path)
    except ValueError as exc:
        print(f"render docs-surface: {exc}", file=sys.stderr)
        return 1
    if args.check:
        docs_current = docs_readme_path.read_text(encoding="utf-8") if docs_readme_path.exists() else ""
        out_of_sync = [
            str(path)
            for path, current, rendered in (
                (readme_path, readme_path.read_text(encoding="utf-8"), readme_content),
                (docs_readme_path, docs_current, docs_readme_content),
            )
            if current != rendered
        ]
        if out_of_sync:
            print("render docs-surface: out of sync:", file=sys.stderr)
            for path in out_of_sync:
                print(f"  - {path}", file=sys.stderr)
            print(f"render docs-surface: run: {control_plane_command('render docs-surface')}", file=sys.stderr)
            return 1
        print("render docs-surface: sync OK")
        return 0
    write_if_changed(readme_path, readme_content)
    write_if_changed(docs_readme_path, docs_readme_content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
