"""Render docs/topology-status.md — the structural-cohesion drift dashboard.

Reads ``docs/plans/topology-target.yaml`` and the realized polylogue tree.
Emits a checked-in markdown table that shows per-issue migration progress.
Drift fails ``devtools render-all --check``.

See `#429 Phase 3 <https://github.com/Sinity/polylogue/issues/429>`_.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from collections.abc import Iterable
from pathlib import Path

from devtools.verify_topology import parse_yaml as parse_topology_yaml

ROOT = Path(__file__).resolve().parents[1]
DASHBOARD = ROOT / "docs" / "topology-status.md"
PROJECTION = ROOT / "docs" / "plans" / "topology-target.yaml"

GENERATED_BEGIN = "<!-- BEGIN GENERATED: topology-status -->"
GENERATED_END = "<!-- END GENERATED: topology-status -->"

ISSUE_TITLES = {
    "#403": "rationalize source and test module structure",
    "#413": "retire public audit qa showcase surfaces",
    "#414": "rationalize product ownership and package boundary",
    "#420": "group schema generation and inference modules",
    "#424": "group lib by domain cluster",
    "#425": "group storage by ownership domain",
    "#426": "rationalize package-root layout and consolidate facade surface",
}

NON_OWNER_TAGS = {"stable", "kernel", "lib-root", "storage-root"}


def realized_paths() -> set[str]:
    return {p.relative_to(ROOT).as_posix() for p in ROOT.glob("polylogue/**/*.py") if "__pycache__" not in p.parts}


def render_dashboard(rows: Iterable[dict[str, object]], realized: set[str]) -> str:
    """Build the dashboard markdown body."""
    by_owner: dict[str, list[dict[str, object]]] = defaultdict(list)
    tbd: list[dict[str, object]] = []
    stable_count = 0
    kernel_count = 0
    primitive_count = 0

    for row in rows:
        owner = str(row.get("owner") or "")
        target = str(row.get("target") or "")
        if owner == "stable":
            stable_count += 1
            continue
        if owner == "kernel":
            kernel_count += 1
            continue
        if owner in {"lib-root", "storage-root"}:
            primitive_count += 1
            continue
        if target == "TBD":
            tbd.append(row)
            continue
        if owner.startswith("#"):
            by_owner[owner].append(row)

    realized_targets = realized

    parts: list[str] = ["## Topology drift dashboard", ""]
    parts.append(
        "Generated by `devtools render-topology-status`. Reads "
        "`docs/plans/topology-target.yaml` and the realized `polylogue/` tree."
    )
    parts.append("")
    parts.append("### Per-issue migration progress")
    parts.append("")
    parts.append("| Issue | Title | Cells | At target | Pending | Conflicts |")
    parts.append("| --- | --- | --: | --: | --: | --: |")

    issue_keys = sorted(by_owner.keys())
    for owner in issue_keys:
        cells = by_owner[owner]
        total = len(cells)
        pending = sum(1 for cell in cells if str(cell.get("path")) in realized_targets)
        at_target = total - pending
        title = ISSUE_TITLES.get(owner, "—")
        # Conflicts: rows whose target collides with another row's target.
        targets = [str(cell.get("target") or "") for cell in cells]
        conflicts = len([t for t in targets if targets.count(t) > 1 and t])
        parts.append(f"| {owner} | {title} | {total} | {at_target} | {pending} | {conflicts} |")

    parts.append("")
    parts.append("### Summary")
    parts.append("")
    parts.append(f"- **Stable** (no move scoped): {stable_count}")
    parts.append(f"- **Kernel** (polylogue/ root): {kernel_count}")
    parts.append(f"- **Primitives** (lib-root + storage-root): {primitive_count}")
    parts.append(f"- **TBD** (cell needs explicit assignment): {len(tbd)}")
    parts.append(
        f"- **Total declared**: {sum(len(v) for v in by_owner.values()) + stable_count + kernel_count + primitive_count + len(tbd)}"
    )
    parts.append(f"- **Realized polylogue/**/*.py**: {len(realized_targets)} files declared")

    if tbd:
        parts.append("")
        parts.append("### TBD cells (require explicit routing)")
        parts.append("")
        parts.append(
            "These rows in the projection have no resolved target yet. Each must be assigned by the owning issue's PR."
        )
        parts.append("")
        for row in sorted(tbd, key=lambda r: str(r.get("path"))):
            path = str(row.get("path"))
            reason = str(row.get("reason") or "")
            parts.append(f"- `{path}` — {reason or 'no rule yet'}")

    parts.append("")
    return "\n".join(parts)


def write_dashboard(path: Path, body: str) -> None:
    header = "# Topology status\n\n"
    explainer = (
        "This file is generated by `devtools render-topology-status`. Do not edit by hand. "
        "It tracks per-issue progress against `docs/plans/topology-target.yaml`. Drift fails "
        "`devtools render-all --check`.\n\n"
    )
    contents = header + explainer + GENERATED_BEGIN + "\n" + body + GENERATED_END + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the dashboard is out of sync.")
    parser.add_argument("--yaml", type=Path, default=PROJECTION)
    parser.add_argument("--output", type=Path, default=DASHBOARD)
    args = parser.parse_args(argv)

    rows = parse_topology_yaml(args.yaml.read_text())
    realized = realized_paths()
    body = render_dashboard(rows, realized)

    if args.check:
        if not args.output.exists():
            print(f"render-topology-status: {args.output} missing", file=sys.stderr)
            return 1
        existing = args.output.read_text(encoding="utf-8")
        expected_header = "# Topology status\n\n"
        if expected_header not in existing:
            print(f"render-topology-status: {args.output} header missing", file=sys.stderr)
            return 1
        existing_body = existing.split(GENERATED_BEGIN, 1)[-1].split(GENERATED_END, 1)[0].strip("\n")
        if existing_body != body.strip("\n"):
            print(f"render-topology-status: {args.output} out of sync", file=sys.stderr)
            return 1
        return 0

    write_dashboard(args.output, body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
