"""Render the shared documentation surface into README targets."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.docs_surface import (
    DOCS_REFERENCE_ENTRIES,
    README_DOC_TITLES,
    REPO_GUIDE_ENTRIES,
    DocsEntry,
)
from devtools.render_support import write_if_changed

README_MARKER = "docs-surface"
GENERATED_NOTE = (
    f"<!-- Generated by `{control_plane_command('render-docs-surface')}`. Edit devtools/docs_surface.py instead. -->"
)


def _rebase_path(path: str, *, from_dir: str) -> str:
    target = Path(path)
    if not from_dir:
        return target.as_posix()
    if target.is_relative_to(from_dir):
        return target.relative_to(from_dir).as_posix()
    return Path(os.path.relpath(target.as_posix(), from_dir)).as_posix()


def _render_table(entries: tuple[DocsEntry, ...], *, from_dir: str = "") -> str:
    lines = [
        "| Document | Description |",
        "|----------|-------------|",
    ]
    for entry in entries:
        lines.append(f"| [{entry.title}]({_rebase_path(entry.path, from_dir=from_dir)}) | {entry.description} |")
    return "\n".join(lines)


def _select_entries(entries: tuple[DocsEntry, ...], titles: tuple[str, ...]) -> tuple[DocsEntry, ...]:
    by_title = {entry.title: entry for entry in entries}
    return tuple(by_title[title] for title in titles)


def _docs_by_title(entries: tuple[DocsEntry, ...]) -> dict[str, DocsEntry]:
    return {entry.title: entry for entry in entries}


def _render_named_table(by_title: dict[str, DocsEntry], titles: tuple[str, ...], *, from_dir: str = "") -> str:
    return _render_table(tuple(by_title[title] for title in titles), from_dir=from_dir)


def build_docs_readme(
    docs_entries: tuple[DocsEntry, ...] = DOCS_REFERENCE_ENTRIES,
    repo_entries: tuple[DocsEntry, ...] = REPO_GUIDE_ENTRIES,
) -> str:
    docs_by_title = _docs_by_title(docs_entries)
    repo_by_title = _docs_by_title(repo_entries)
    return "\n".join(
        [
            GENERATED_NOTE,
            "",
            "# Polylogue Docs Map",
            "",
            "Use this map when you need the complete repository documentation surface. "
            "The top-level README links the shortest public path; this page keeps "
            "operator, architecture, verification, and contributor references separate.",
            "",
            "## Orientation",
            "",
            _render_named_table(
                docs_by_title,
                ("Architecture", "Data Model", "Internals", "Configuration"),
                from_dir="docs",
            ),
            "",
            "## User and Integration Surfaces",
            "",
            _render_named_table(
                docs_by_title,
                ("CLI Reference", "Library API", "MCP Integration", "Browser Capture", "Generate", "Providers"),
                from_dir="docs",
            ),
            "",
            "## Verification and Quality",
            "",
            _render_named_table(
                docs_by_title,
                ("Developer Tools", "Verification Lab", "Verification Catalog", "Test Quality Workflows"),
                from_dir="docs",
            ),
            "",
            "## Contributor Workflow",
            "",
            _render_named_table(repo_by_title, ("Contributing", "Testing", "Agent Guide"), from_dir="docs"),
            "",
            "## Local State",
            "",
            _render_named_table(repo_by_title, ("Local Cache Layout", "Local Working Outputs"), from_dir="docs"),
            "",
        ]
    )


def build_readme_section(
    docs_entries: tuple[DocsEntry, ...] = DOCS_REFERENCE_ENTRIES,
    repo_entries: tuple[DocsEntry, ...] = REPO_GUIDE_ENTRIES,
) -> str:
    featured_docs = _select_entries(docs_entries, README_DOC_TITLES)
    return "\n".join(
        [
            "<!-- BEGIN GENERATED: docs-surface -->",
            "## Documentation",
            "",
            "Start with the generated command and architecture references; "
            "use [docs/README.md](docs/README.md) for the complete map.",
            "",
            _render_table(featured_docs),
            "",
            "<!-- END GENERATED: docs-surface -->",
        ]
    )


def replace_marked_section(text: str, *, marker: str, replacement: str) -> str:
    begin = f"<!-- BEGIN GENERATED: {marker} -->"
    end = f"<!-- END GENERATED: {marker} -->"
    start = text.find(begin)
    finish = text.find(end)
    if start == -1 or finish == -1 or finish < start:
        raise ValueError(f"marker block not found: {marker}")
    finish += len(end)
    return text[:start] + replacement + text[finish:]


def render_outputs(*, readme_path: Path, docs_readme_path: Path) -> tuple[str, str]:
    docs_readme = build_docs_readme()
    readme = replace_marked_section(
        readme_path.read_text(encoding="utf-8"),
        marker=README_MARKER,
        replacement=build_readme_section(),
    )
    return readme, docs_readme


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render README docs surfaces from the shared docs registry.")
    parser.add_argument("--readme", default="README.md", help="README path (default: README.md)")
    parser.add_argument("--docs-readme", default="docs/README.md", help="Docs map path (default: docs/README.md)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when README targets are out of sync.",
    )
    args = parser.parse_args(argv)

    readme_path = Path(args.readme)
    docs_readme_path = Path(args.docs_readme)

    try:
        readme_content, docs_readme_content = render_outputs(
            readme_path=readme_path,
            docs_readme_path=docs_readme_path,
        )
    except ValueError as exc:
        print(f"render-docs-surface: {exc}", file=sys.stderr)
        return 1

    if args.check:
        readme_current = readme_path.read_text(encoding="utf-8")
        try:
            docs_current = docs_readme_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            docs_current = ""
        out_of_sync: list[str] = []
        if readme_current != readme_content:
            out_of_sync.append(str(readme_path))
        if docs_current != docs_readme_content:
            out_of_sync.append(str(docs_readme_path))
        if out_of_sync:
            print("render-docs-surface: out of sync:", file=sys.stderr)
            for path in out_of_sync:
                print(f"  - {path}", file=sys.stderr)
            print(
                f"render-docs-surface: run: {control_plane_command('render-docs-surface')}",
                file=sys.stderr,
            )
            return 1
        print("render-docs-surface: sync OK")
        return 0

    write_if_changed(readme_path, readme_content)
    write_if_changed(docs_readme_path, docs_readme_content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
