"""Render the shared documentation surface into README targets."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from devtools.docs_surface import DOCS_REFERENCE_ENTRIES, REPO_GUIDE_ENTRIES, DocsEntry

README_MARKER = "docs-surface"
GENERATED_NOTE = (
    "<!-- Generated by `python -m devtools render-docs-surface`. Edit devtools/docs_surface.py instead. -->"
)


def _render_table(entries: tuple[DocsEntry, ...]) -> str:
    lines = [
        "| Document | Description |",
        "|----------|-------------|",
    ]
    for entry in entries:
        lines.append(f"| [{entry.title}]({entry.path}) | {entry.description} |")
    return "\n".join(lines)


def build_docs_readme(
    docs_entries: tuple[DocsEntry, ...] = DOCS_REFERENCE_ENTRIES,
    repo_entries: tuple[DocsEntry, ...] = REPO_GUIDE_ENTRIES,
) -> str:
    return "\n".join(
        [
            GENERATED_NOTE,
            "",
            "# Polylogue Docs Map",
            "",
            "This directory holds the current repository-facing documentation.",
            "",
            "## Core References",
            "",
            _render_table(docs_entries),
            "",
            "## Repository Guides",
            "",
            _render_table(repo_entries),
            "",
        ]
    )


def build_readme_section(
    docs_entries: tuple[DocsEntry, ...] = DOCS_REFERENCE_ENTRIES,
    repo_entries: tuple[DocsEntry, ...] = REPO_GUIDE_ENTRIES,
) -> str:
    return "\n".join(
        [
            "<!-- BEGIN GENERATED: docs-surface -->",
            "## Documentation",
            "",
            _render_table(docs_entries),
            "",
            "## Contributor Guides",
            "",
            _render_table(repo_entries),
            "",
            "<!-- END GENERATED: docs-surface -->",
        ]
    )


def replace_marked_section(text: str, *, marker: str, replacement: str) -> str:
    begin = f"<!-- BEGIN GENERATED: {marker} -->"
    end = f"<!-- END GENERATED: {marker} -->"
    start = text.find(begin)
    finish = text.find(end)
    if start == -1 or finish == -1 or finish < start:
        raise ValueError(f"marker block not found: {marker}")
    finish += len(end)
    return text[:start] + replacement + text[finish:]


def write_if_changed(output_path: Path, content: str) -> None:
    try:
        current = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current == content:
        return
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_suffix(output_path.suffix + ".tmp")
    tmp_path.write_text(content, encoding="utf-8")
    tmp_path.replace(output_path)


def render_outputs(*, readme_path: Path, docs_readme_path: Path) -> tuple[str, str]:
    docs_readme = build_docs_readme()
    readme = replace_marked_section(
        readme_path.read_text(encoding="utf-8"),
        marker=README_MARKER,
        replacement=build_readme_section(),
    )
    return readme, docs_readme


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render README docs surfaces from the shared docs registry.")
    parser.add_argument("--readme", default="README.md", help="README path (default: README.md)")
    parser.add_argument("--docs-readme", default="docs/README.md", help="Docs map path (default: docs/README.md)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when README targets are out of sync.",
    )
    args = parser.parse_args(argv)

    readme_path = Path(args.readme)
    docs_readme_path = Path(args.docs_readme)

    try:
        readme_content, docs_readme_content = render_outputs(
            readme_path=readme_path,
            docs_readme_path=docs_readme_path,
        )
    except ValueError as exc:
        print(f"render-docs-surface: {exc}", file=sys.stderr)
        return 1

    if args.check:
        readme_current = readme_path.read_text(encoding="utf-8")
        try:
            docs_current = docs_readme_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            docs_current = ""
        out_of_sync: list[str] = []
        if readme_current != readme_content:
            out_of_sync.append(str(readme_path))
        if docs_current != docs_readme_content:
            out_of_sync.append(str(docs_readme_path))
        if out_of_sync:
            print("render-docs-surface: out of sync:", file=sys.stderr)
            for path in out_of_sync:
                print(f"  - {path}", file=sys.stderr)
            print("render-docs-surface: run: python -m devtools render-docs-surface", file=sys.stderr)
            return 1
        print("render-docs-surface: sync OK")
        return 0

    write_if_changed(readme_path, readme_content)
    write_if_changed(docs_readme_path, docs_readme_content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
