"""Render or check the declaration-generated six-tool agent manual assets."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path

_REPO_ROOT = str(Path(__file__).resolve().parents[1])
if sys.path[0] != _REPO_ROOT:
    sys.path.insert(0, _REPO_ROOT)

from polylogue.agent_integration.spec import (  # noqa: E402
    ALL_TARGET_TOOLS,
    ASSET_VERSION,
    CAPABILITY_FAMILIES,
    CLIENT_DELIVERIES,
    CLIENTS,
    DEFAULT_READ_TOOLS,
    ORIGIN_MEANINGS,
    PRIVILEGED_TOOLS,
    QUERY_EXAMPLES,
    RECIPES,
    ROLE_ORDER,
    ROLES,
    TARGET_SCHEMA_STATUS,
    TOOL_CONTRACT_BY_NAME,
    TOOL_CONTRACTS,
    integration_spec_payload,
    recipe_payload,
    tool_contract_payload,
)
from polylogue.archive.query.transaction import QueryContinuation, QueryTransactionRequest  # noqa: E402
from polylogue.mcp.declarations import TARGET_PROMPTS, TARGET_RESOURCES  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "polylogue" / "agent_integration" / "data"
MANUAL_DATA_PATH = DATA_DIR / "standing-manual.md"
REFERENCE_DATA_PATH = DATA_DIR / "deep-reference.md"
MANUAL_DOC_PATH = REPO_ROOT / "docs" / "agent-manual.md"
REFERENCE_DOC_PATH = REPO_ROOT / "docs" / "agent-integration-reference.md"


def _json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _compact_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def _pretty_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True)


def continuation_example_token() -> str:
    """Return a real deterministic token produced by the production codec."""

    request = QueryTransactionRequest(
        operation="query",
        arguments={
            "expression": "actions where action:file_edit AND path:polylogue/archive/query | sort by time desc | limit 20",
            "projection": "action-evidence",
        },
        page_size=20,
        offset=20,
        projection="action-evidence",
        stable_order="time-desc",
    )
    return QueryContinuation(request=request, result_ref="result:0123456789abcdef01234567").encode()


def _call_payload(tool: str, arguments: Mapping[str, object]) -> dict[str, object]:
    return {"name": tool, "arguments": dict(arguments)}


def _fenced_json(payload: object) -> list[str]:
    return ["```json", _pretty_json(payload), "```", ""]


def _semantics(contract_name: str) -> str:
    return ", ".join(item.value for item in TOOL_CONTRACT_BY_NAME[contract_name].result_semantics)


def _render_tool_calls(tool_names: Iterable[str]) -> list[str]:
    lines: list[str] = []
    for name in tool_names:
        contract = TOOL_CONTRACT_BY_NAME[name]
        example = contract.examples[0]
        lines.extend(
            [
                f"### `{name}` — {example.title}",
                "",
                contract.purpose,
                "",
                f"Result semantics declared by the t46.8 source rows: `{_semantics(name)}`.",
                "",
            ]
        )
        lines.extend(_fenced_json(_call_payload(name, example.arguments_dict())))
        lines.extend([f"Expected discipline: {example.result_note}", ""])
    return lines


def render_standing_manual() -> str:
    """Render the complete cache-stable standing manual from typed declarations."""

    token = continuation_example_token()
    continuation_call = _call_payload("query", {"continuation": token})
    lines: list[str] = [
        f"<!-- Generated by `devtools render agent-manual` from Polylogue declarations. Content version: {ASSET_VERSION}. -->",
        "# Polylogue standing agent manual",
        "",
        "Polylogue is the local evidence system for prior AI work. Use it whenever the task depends on what was tried, decided, changed, observed, paid for, or left unfinished. Do not wait for the operator to say “search the archive.” First establish archive authority, then retrieve evidence, then cite stable refs. Do not use Polylogue for facts that the current repository or live system can answer more directly.",
        "",
        "This manual targets the six-tool default read surface: `query`, `read`, `get`, `explain`, `context`, and `status`. The current source snapshot still carries an in-flight seven-row declaration (`graph` is separate) and calls the administrative transaction `maintenance`; this generated contract folds graph into `read` and names the administrative transaction `operate`. Final FastMCP signatures remain a post-cutover verification gate.",
        "",
        "## Cold-start decision route",
        "",
        "1. Call `status` before any broad, freshness-sensitive, or source-completeness claim.",
        "2. Call `explain` when grammar, fields, values, result semantics, refs, or recovery are uncertain. Never guess a field or tool name.",
        "3. Call `query` to discover sets or aggregates. Preserve its `query_ref` and `result_ref`.",
        "4. Call `read` for bounded context around a stable ref or retained result set; call `get` for one exact object.",
        "5. Call `context` only after discovery when a bounded resume/postmortem/prior-art packet is useful. Its receipt states what was included and omitted.",
        "6. Continue any exhaustive result until the response has no continuation when the claim requires logical completeness.",
        "",
        "## Source coverage",
        "",
        "The authoritative `Origin` enum currently contains 11 tokens. Older plans that say ten predate `beads-issue`.",
        "",
        "| Origin token | Meaning |",
        "|---|---|",
    ]
    lines.extend(f"| `{item.token}` | {item.meaning} |" for item in ORIGIN_MEANINGS)
    lines.extend(
        [
            "",
            "Coverage is not implied by token existence. `status` must report whether the requested origins are configured, ingested, fresh, converged, and suitable for the requested evidence type. State missing or stale coverage in the answer.",
            "",
            "## The six tools",
            "",
            "| Tool | Use it for | Role | Result semantics |",
            "|---|---|---|---|",
        ]
    )
    for name in DEFAULT_READ_TOOLS:
        contract = TOOL_CONTRACT_BY_NAME[name]
        lines.append(
            f"| `{name}` | {contract.purpose} | `{contract.minimum_role}` | "
            f"{', '.join(f'`{item.value}`' for item in contract.result_semantics)} |"
        )
    lines.extend(["", "## Normal invocations", ""])
    lines.extend(_render_tool_calls(DEFAULT_READ_TOOLS))
    lines.extend(
        [
            "## Continuation and result limits",
            "",
            "Multi-row results are bounded by declared page limits, workload controls, and the MCP transport budget. A bounded response is not evidence that the underlying set is complete. Read the response’s `result_semantics`, coverage metadata, `has_more`, and `continuation` fields.",
            "",
            "For `exhaustive_page`, resume the same logical result by calling the same tool with **only** the returned opaque token. Do not replay filters, combine the token with other arguments, decode or edit the token, or cite the token as evidence. The production token binds the exact request and `result_ref`.",
            "",
        ]
    )
    lines.extend(_fenced_json(continuation_call))
    lines.extend(
        [
            "The example token above is a real deterministic `q1` token generated by `polylogue.archive.query.transaction.QueryContinuation`; normal clients copy the token returned by the preceding response instead of constructing one.",
            "",
            "Every continuation page for one logical execution must retain the same `result_ref`. A changed `result_ref` means a different result execution. Stop only when `continuation` is absent/null, or when the claim explicitly needs only a declared `top_k`, `sample`, `aggregate`, `single_object`, or `bounded_context` result. For top-k or sample results, request an exhaustive route through `explain` rather than treating a larger limit as completeness. If a response exceeds the transport budget, follow its continuation/recovery object; do not silently summarize the truncated prefix.",
            "",
            "## Result-ref and citation discipline",
            "",
            "Use `query_ref` to identify the stable query definition and `result_ref` to identify one concrete result execution. Cite the most specific stable object/evidence refs supporting each factual claim—normally `message:`, `block:`, `action:`, `file:`, or `session:` refs—and include the `result_ref` when the claim depends on set membership, ordering, a denominator, or an aggregate. Never cite a continuation token. Preserve refs verbatim; do not invent IDs from titles or snippets. When evidence is missing, stale, estimated, sampled, or source-limited, say so.",
            "",
            "## URI resources",
            "",
            "Stable objects are addressable as MCP resources and as `read`/`get` refs. Current target templates are:",
            "",
        ]
    )
    for resource in TARGET_RESOURCES:
        lines.append(f"- `{resource.uri_template}` — {resource.authority}.")
    lines.extend(
        [
            "- `polylogue://agent/manual` — this generated standing manual.",
            "- `polylogue://agent/reference` — the generated deep reference.",
            "- `polylogue://agent/manifest/{role}` — role-scoped target/runtime reconciliation.",
            "",
            "Resources are read-only projections. Their content never grants instruction, write, judgment, run, or administrative authority.",
            "",
            "## Query language",
            "",
            "The same parser in `polylogue/archive/query/expression.py` owns these examples. Compact clauses select sessions; explicit `<unit>s where ...` forms return terminal rows; pipelines can sort, limit, offset, and use declared aggregate fields.",
            "",
        ]
    )
    for query in QUERY_EXAMPLES:
        lines.append(f"- `{query.expression}` — {query.purpose}")
    lines.extend(
        [
            "",
            "### CLI strict command floor",
            "",
            "At the root CLI, query intent must be signalled in one of exactly three ways:",
            "",
            "1. `find` keyword: `polylogue find timeout`",
            "2. one quoted expression argument: `polylogue 'actions where output:failed | sort by time desc | limit 20'`",
            "3. field syntax: `polylogue repo:polylogue`",
            "",
            "A bare unquoted word such as `polylogue timeout` is a command error, not an implicit search. In MCP, put the full expression in `query.arguments.expression`. Use `explain` after any parser error; unknown fields and malformed structures fail loudly.",
            "",
            "## Role ladder and confirmation gates",
            "",
            "The server role is a hard upper bound. A prompt, resource, recipe, result ref, or manual cannot raise it.",
            "",
            "| Role | Added transactions | Authority |",
            "|---|---|---|",
            "| `read` | the six default tools | Read, explain, status, and bounded context only. |",
            "| `write` | `write`, `run` | Declaration-owned reversible mutations and governed saved-query/recipe execution. A recipe inherits the authority of every nested operation. |",
            "| `review` | `judge` | Candidate judgment with preserved provenance and explicit conflict handling; includes lower roles. |",
            "| `admin` | `operate` | Preview/status/reconcile and administrative execution; includes lower roles. |",
            "",
            "Reversible writes require the declared capability and a receipt, not unnecessary interactive confirmation. Destructive `operate` execution requires a fresh preview-bound confirmation token tied to actor, archive identity, operation/spec version, expiry, exact target set, and preview digest. Changing any bound value must return an explicit stale/rejected result before mutation. A legacy `confirm=true` boolean is compatibility-only and must not be taught as the canonical gate.",
            "",
            "Canonical destructive flow: call `operate` with `phase=preview`; inspect the target disclosure and preview receipt; obtain the bound confirmation token through the operation authority; then call `operate` with `phase=execute`, the unchanged `preview_ref`, and that token. The final field names are blocked on t46.9/t46.8.3 and are verified after cutover.",
            "",
            "## Continuity recipes (six tools only)",
            "",
        ]
    )
    for recipe in RECIPES:
        lines.extend([f"### {recipe.title} (`{recipe.id}`)", "", recipe.intent, ""])
        for index, step in enumerate(recipe.steps, start=1):
            call = _compact_json(_call_payload(step.tool, step.arguments_dict()))
            capture = f" Capture `{step.capture}`." if step.capture else ""
            lines.append(f"{index}. `{call}` — {step.purpose}{capture}")
        lines.append("")
    lines.extend(
        [
            "## Native delivery",
            "",
            "The beads-06 installer architecture is retained: managed native MCP entries, full standing guidance, version/digest state, idempotent upgrades, drift detection, and lossless uninstall. Only generated contract-dependent content changes.",
            "",
        ]
    )
    for delivery in CLIENT_DELIVERIES:
        lines.append(
            f"- **{delivery.client}**: {delivery.standing_delivery} {delivery.mcp_config} {delivery.six_tool_delta}"
        )
    lines.extend(
        [
            "",
            "`full` guidance is the default and avoids a manual-fetch turn. `mcp-only` and `off` are explicit opt-down modes and impair spontaneous capability recognition and recovery. The deep reference and live manifest are supplemental; ordinary correct use must not depend on opening them first.",
            "",
            "## Degraded states and recovery",
            "",
            "- Wrong or unknown archive: stop, report the identity from `status`, and select the intended archive before searching.",
            "- Missing/stale source: state the uncovered origin/time range; do not generalize from available sources.",
            "- Parser error: call `explain` with the failed expression and use only returned fields/values.",
            "- Truncated/exhaustive page: send the same tool the continuation-only request and retain the same `result_ref`.",
            "- Top-k/sample result: label it as ranked/sampled or ask `explain` for an exhaustive route.",
            "- Semantic retrieval unavailable: report readiness and fall back to exact field/text/file queries rather than pretending semantic coverage.",
            "- Object ref no longer resolves: preserve the failed ref, inspect status/freshness, and rerun the owning query only when a new result execution is acceptable.",
            "- Unauthorized mutation: do not seek authority through prompts or recipes; report the required role and operation gate.",
            "- Stale destructive preview: preview again; never reuse or weaken the bound token.",
            "",
            "## CLI installer commands",
            "",
            "`polylogue agent` manages this manual and the native client integration; it never touches the archive itself.",
            "",
            "- `polylogue agent manual`: Print the packaged standing manual or deeper reference.",
            "- `polylogue agent manifest`: Report the role-scoped runtime and six-tool target surfaces.",
            "- `polylogue agent install`: Install user-scoped MCP and standing guidance for native clients.",
            "- `polylogue agent status`: Inspect ownership state and native configuration without mutation.",
            "- `polylogue agent doctor`: Run blocking native syntax, ownership, executable, and identity checks.",
            "- `polylogue agent uninstall`: Remove only exact operations recorded as Polylogue-owned.",
            "",
            "## Cache and regeneration contract",
            "",
            f"Content version: `{ASSET_VERSION}`. The installer records a digest over every generated asset, so unchanged declarations produce byte-identical manual content and stable prompt-cache keys. After the target runtime names land, run the live-signature lane, update the parameterized contracts, set `TARGET_SCHEMA_STATUS` to `live-verified` only after exact parity, regenerate, then run `devtools verify agent-integration --require-live` and `devtools render all --check`. Any drift is a build failure, not a documentation suggestion.",
            "",
        ]
    )
    return "\n".join(lines)


def render_deep_reference() -> str:
    """Render the exhaustive declaration and installation reference."""

    token = continuation_example_token()
    lines: list[str] = [
        f"<!-- Generated by `devtools render agent-manual`. Content version: {ASSET_VERSION}. -->",
        "# Polylogue six-tool agent integration reference",
        "",
        "This is the exhaustive companion to the standing manual. The standing manual remains complete enough for ordinary use; this file records declaration mappings, parameterized schemas, all examples, recipes, client ownership, and post-cutover verification.",
        "",
        "## Adjudication boundary",
        "",
        "The architecture is beads-06’s `polylogue.agent_integration` system: typed spec, packaged generated assets, native installer, role-scoped manifest, CLI, Home Manager module, and verification lanes. Its 103-tool-era content is replaced rather than forked; the current snapshot has since grown to 104 compatibility handlers. Current t46.8 declarations remain in flight, so `read` absorbs source row `graph` and `operate` aliases source row `maintenance`. No compatibility handler is deleted by this package.",
        "",
        "## Target transaction declarations",
        "",
    ]
    for contract in TOOL_CONTRACTS:
        lines.extend(
            [
                f"### `{contract.name}`",
                "",
                f"- role: `{contract.minimum_role}`",
                f"- source declarations: {', '.join(f'`{item}`' for item in contract.source_declarations)}",
                f"- schema status: `{contract.schema_status}`",
                f"- result semantics: {', '.join(f'`{item.value}`' for item in contract.result_semantics)}",
                f"- continuation: `{'same-tool continuation-only request' if contract.supports_continuation else 'none'}`",
                f"- emits result ref: `{'yes' if contract.emits_result_ref else 'no'}`",
                f"- purpose: {contract.purpose}",
                "",
                "Arguments:",
                "",
                "| Name | Kind | Required initially | Meaning |",
                "|---|---|---:|---|",
            ]
        )
        for argument in contract.arguments:
            lines.append(
                f"| `{argument.name}` | `{argument.kind}` | {'yes' if argument.required_initial else 'no'} | {argument.description} |"
            )
        lines.append("")
        for example in contract.examples:
            lines.extend([f"Example — {example.title}:", ""])
            lines.extend(_fenced_json(_call_payload(contract.name, example.arguments_dict())))
            lines.extend([example.result_note, ""])
    lines.extend(
        [
            "## Exact continuation contract",
            "",
            "The continuation request is the same tool plus exactly one `continuation` argument. This generated example is codec-valid:",
            "",
        ]
    )
    lines.extend(_fenced_json(_call_payload("query", {"continuation": token})))
    lines.extend(
        [
            "The token decodes to offset 20 and `result:0123456789abcdef01234567`; the verifier checks both. Any final cutover adapter that accepts reconstructed filters instead of the opaque token, changes result_ref across pages, or requires an old tool name fails the live lane.",
            "",
            "## Parser catalog",
            "",
        ]
    )
    for query in QUERY_EXAMPLES:
        lines.extend(
            [
                f"- `{query.expression}`",
                f"  - surface: `{query.surface}`",
                f"  - purpose: {query.purpose}",
                f"  - source evidence: `{query.source_test}`",
            ]
        )
    lines.extend(["", "## Continuity recipes", ""])
    for recipe in RECIPES:
        lines.extend([f"### {recipe.title} (`{recipe.id}`)", "", recipe.intent, ""])
        for index, step in enumerate(recipe.steps, start=1):
            lines.extend([f"{index}. `{step.tool}` — {step.purpose}", ""])
            lines.extend(_fenced_json(_call_payload(step.tool, step.arguments_dict())))
        if recipe.resources:
            lines.append("Resources: " + ", ".join(f"`{item}`" for item in recipe.resources) + ".")
        if recipe.prompts:
            lines.append("Prompts: " + ", ".join(f"`{item}`" for item in recipe.prompts) + ".")
        lines.append("")
    lines.extend(
        [
            "## Resource and prompt declarations",
            "",
            "### Stable target resources",
            "",
        ]
    )
    for resource in TARGET_RESOURCES:
        lines.append(
            f"- `{resource.uri_template}` — objects {', '.join(resource.object_kinds)}; role `{resource.minimum_role}`; owner `{resource.migration_owner}`; {resource.authority}."
        )
    lines.extend(["", "### Workflow prompts", ""])
    for prompt in TARGET_PROMPTS:
        lines.append(
            f"- `{prompt.name}` — workflow `{prompt.workflow}`; role `{prompt.minimum_role}`; mutation authority `{prompt.mutation_authority}`; owner `{prompt.migration_owner}`."
        )
    lines.extend(["", "## Source origins", ""])
    for origin in ORIGIN_MEANINGS:
        lines.append(f"- `{origin.token}` — {origin.meaning}")
    lines.extend(["", "## Native client delivery and deltas", ""])
    for delivery in CLIENT_DELIVERIES:
        lines.extend(
            [
                f"### {delivery.client}",
                "",
                f"- MCP config: {delivery.mcp_config}",
                f"- standing manual: {delivery.standing_delivery}",
                f"- reference: {delivery.reference_delivery}",
                f"- unchanged: {delivery.unchanged}",
                f"- six-tool delta: {delivery.six_tool_delta}",
                "",
            ]
        )
    lines.extend(
        [
            "## Packaging and ownership invariants",
            "",
            "The wheel/sdist package contains the generated text and JSON assets under `polylogue.agent_integration.data`. Installation records content version, aggregate digest, client, role, archive/config identity, and exact native operations in a self-digested state file. Upgrade rewrites only previously owned values or marked blocks. Uninstall removes only unchanged owned operations; operator drift is retained and reported. Symlinked configs and conflicting operator-owned Polylogue entries fail closed. Secrets are never written into generated assets.",
            "",
            "The Home Manager module remains separate from daemon lifecycle. Enabling agent integration does not start ingestion, grant a higher MCP role, or weaken operation confirmation. `guidance=full` remains the behaviorally complete default; `mcp-only` and `off` are explicit opt-downs.",
            "",
            "## Post-cutover regeneration checklist",
            "",
            "1. Rebase after t46.8.2/t46.8.3 finalize the six read handlers and privileged names.",
            "2. Replace/verify every `cutover-parameterized` argument against the registered FastMCP input signatures. In particular confirm continuation-only input, `read` graph/topology selection, context result-ref input, and preview/execute fields for `operate`.",
            "3. Confirm t46.9’s preview receipt and confirmation token field names, binding rules, stale response, and receipt schema; do not preserve the compatibility boolean as canonical guidance.",
            "4. Run `devtools verify agent-integration --lane live-fastmcp-signatures --json`; use its exact signature diff to update the parameterized contracts.",
            "5. Only after that lane reports exact signature parity, set `TARGET_SCHEMA_STATUS` in `polylogue/agent_integration/spec.py` to `live-verified` and run `devtools render agent-manual`; commit all packaged assets and docs mirrors.",
            "6. Run `devtools verify agent-integration --require-live`; it must see the role-scoped target tools, the live schema marker, and exact FastMCP signature parity.",
            "7. Run `devtools render all --check`, focused agent-integration/MCP tests, topology verification, and package build checks.",
            "8. Run clean-home Claude Code, Codex, Gemini, and Hermes installation smoke tests and one cold-agent trial per continuity recipe.",
            "",
            "Blocked until those schemas land: exact live FastMCP signature parity, live continuation invocation, preview-bound operate execution, and cold-model trials after the current 104-tool compatibility discovery surface is retired. The generated parser, declaration mapping, asset determinism, installer, and static manual compilation are testable now.",
            "",
        ]
    )
    return "\n".join(lines)


def _static_manifest() -> dict[str, object]:
    return {
        "schema_version": 2,
        "content_version": ASSET_VERSION,
        "description": "Static six-tool target manifest. `polylogue agent manifest --role ROLE` also reports current declaration reconciliation.",
        "default_role": "read",
        "clients": list(CLIENTS),
        "roles": list(ROLES),
        "role_order": ROLE_ORDER,
        "default_read_tools": list(DEFAULT_READ_TOOLS),
        "privileged_tools": list(PRIVILEGED_TOOLS),
        "target_tools": list(ALL_TARGET_TOOLS),
        "resources": [item.uri_template for item in TARGET_RESOURCES],
        "manual_resources": [
            "polylogue://agent/manual",
            "polylogue://agent/reference",
            "polylogue://agent/manifest/{role}",
        ],
        "prompts": [item.name for item in TARGET_PROMPTS],
        "capability_families": [item.id for item in CAPABILITY_FAMILIES],
        "recipe_ids": [item.id for item in RECIPES],
        "schema_status": TARGET_SCHEMA_STATUS,
    }


def expected_outputs() -> dict[Path, str]:
    """Return every generated target and its expected UTF-8 text."""

    manual = render_standing_manual()
    reference = render_deep_reference()
    return {
        MANUAL_DATA_PATH: manual,
        REFERENCE_DATA_PATH: reference,
        MANUAL_DOC_PATH: manual,
        REFERENCE_DOC_PATH: reference,
        DATA_DIR / "recipes.json": _json_text(recipe_payload()),
        DATA_DIR / "integration-spec.json": _json_text(integration_spec_payload()),
        DATA_DIR / "tool-contracts.json": _json_text(tool_contract_payload()),
        DATA_DIR / "integration-manifest.json": _json_text(_static_manifest()),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when any generated target differs.")
    args = parser.parse_args(argv)
    drift: list[str] = []
    for path, expected in expected_outputs().items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual == expected:
            continue
        if args.check:
            drift.append(str(path.relative_to(REPO_ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"rendered {path.relative_to(REPO_ROOT)}")
    if drift:
        for relative_path in drift:
            print(f"out of date: {relative_path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
