"""Render executable product query-action workflows from the live registry (#2305)."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable
from pathlib import Path

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed
from polylogue.operations.action_contracts import ACTION_CONTRACTS, CliActionContract
from polylogue.product.workflows import (
    ACTION_UNIT_EVIDENCE,
    EXECUTABLE_WORKFLOW_GOLDEN_PATHS,
    PRODUCT_VERB_MATRIX_EXTRA_ROWS,
    QUERY_ACTION_WORKFLOWS,
    ActionUnitEvidence,
    ExecutableWorkflowGoldenPath,
    ProductVerbMatrixRow,
    QueryActionWorkflow,
)
from polylogue.surfaces.action_affordances import ActionAffordancePayload

GENERATED_NOTE = (
    f"<!-- Generated by `{control_plane_command('render product-workflows')}`. "
    "Edit polylogue/product/workflows.py and polylogue/operations/action_contracts.py instead. -->"
)


def _escape_table(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _code(value: str) -> str:
    return f"`{value}`"


def _code_list(items: Iterable[str]) -> str:
    values = tuple(items)
    if not values:
        return "—"
    return "<br>".join(_code(item) for item in values)


def _command(value: str) -> str:
    return "`" + value.replace("`", "\\`") + "`"


def _path_label(path: tuple[str, ...]) -> str:
    return " ".join(path)


def _action_index() -> dict[str, CliActionContract]:
    return {contract.action_id: contract for contract in ACTION_CONTRACTS}


def _render_workflow_table(workflows: tuple[QueryActionWorkflow, ...]) -> list[str]:
    lines = [
        "| Workflow | Query/action shape | Selector + cardinality | Output + evidence | Surfaces |",
        "| --- | --- | --- | --- | --- |",
    ]
    for workflow in workflows:
        selector = f"{workflow.selector_policy}<br>{workflow.cardinality_policy}"
        output = f"{workflow.output_policy}<br>{workflow.evidence_policy}"
        lines.append(
            "| "
            + _escape_table(f"{workflow.title} (`{workflow.id}`)")
            + " | "
            + _escape_table(_command(workflow.query_shape))
            + " | "
            + _escape_table(selector)
            + " | "
            + _escape_table(output)
            + " | "
            + _code_list(workflow.surfaces)
            + " |"
        )
    return lines


def _render_product_verb_matrix_row(row: ProductVerbMatrixRow) -> str:
    return (
        f"| `{row.action_id}` | {_escape_table(row.target_input)} | `{row.cardinality}` | "
        f"`{row.safety}` | {_code_list(row.formats)} | {_code_list(row.destinations)} | "
        f"{_escape_table(row.selection_confirmation)} | {_code_list(row.next_actions)} |"
    )


def _render_action_matrix(
    contracts: tuple[CliActionContract, ...],
    extra_rows: tuple[ProductVerbMatrixRow, ...] = PRODUCT_VERB_MATRIX_EXTRA_ROWS,
) -> list[str]:
    lines = [
        "| Action | Target / input | Cardinality | Safety | Formats | Destinations | Selection / confirmation | Next actions |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for contract in contracts:
        selection = contract.selection_command or "—"
        if contract.confirmation_command:
            selection = f"{selection}<br>confirm: `{contract.confirmation_command}`"
        if contract.disabled_reason:
            selection = f"{selection}<br>disabled: {contract.disabled_reason}"
        lines.append(
            f"| `{contract.action_id}` | `{contract.target}` / `{contract.input_unit}` | `{contract.cardinality}` | "
            f"`{contract.safety_level}` | {_code_list(sorted(contract.formats))} | "
            f"{_code_list(contract.destination_support)} | {_escape_table(selection)} | "
            f"{_code_list(contract.next_actions)} |"
        )
    lines.extend(_render_product_verb_matrix_row(row) for row in extra_rows)
    return lines


def _render_action_unit_table(rows: tuple[ActionUnitEvidence, ...]) -> list[str]:
    lines = [
        "| Action unit | Evidence unit | Proof surface | Negative guard |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| `{row.action_id}` | {_escape_table(row.evidence_unit)} | "
            f"{_escape_table(row.proof_surface)} | {_escape_table(row.negative_guard)} |"
        )
    return lines


def _render_golden_path_table(goldens: tuple[ExecutableWorkflowGoldenPath, ...]) -> list[str]:
    lines = [
        "| Golden path | Workflow | Command | Output | Structural assertions | Human/string checks |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for golden in goldens:
        json_assertions = "—"
        if golden.json_expectations:
            json_assertions = "<br>".join(
                _code(".".join(str(part) for part in expectation.path) or "$") + f" is {expectation.kind}"
                for expectation in golden.json_expectations
            )
        human_checks = _code_list(golden.stdout_contains)
        lines.append(
            f"| `{golden.id}` | `{golden.workflow_id}` | {_command(golden.command_text)} | "
            f"`{golden.output_kind}` | {json_assertions} | {human_checks} |"
        )
    return lines


def _render_affordance_fields() -> list[str]:
    fields = tuple(ActionAffordancePayload.model_fields)
    return [
        "The shared action affordance DTO is the finite envelope consumed by CLI, daemon/API, MCP, docs, and browser rails.",
        "It must keep these operator-visible fields:",
        "",
        _code_list(fields),
        "",
        "Load-bearing fields for workflow execution are `target`, `input_unit`, `execution`-adjacent metadata "
        "(`cardinality_state`, `safety_level`, `guards`, `requires_daemon`), output metadata "
        "(`destination_support`, `format_support`, `default_format`, `machine_envelope`), and safety/availability "
        "metadata (`confirmation_command`, `selection_command`, `disabled_reason`, `estimated_cost`, `next_actions`).",
        "",
    ]


def _render_repeatable_template() -> list[str]:
    return [
        "## Repeatable Workflow Template",
        "",
        "1. **Select intentionally.** Start with `polylogue find QUERY`. `find` declares query intent; command words after "
        "`then` are actions. A bare `read` at the start remains a read command, not hidden query text.",
        "2. **Preserve exact refs.** `id:...`, `session:...`, message refs, assertion refs, and operation refs are identity "
        "filters. If an exact ref misses, the workflow returns no target or an unresolved ref instead of falling back to FTS.",
        "3. **Apply cardinality before execution.** Singleton actions select one target; explicit multi actions need `--all`, "
        "`--first`, a bounded export mode, or an action-specific multi contract. Multi-match `then read` must be explicit.",
        "4. **Expose the output contract.** Human output is default where available; JSON/NDJSON only exist when the action/read-view "
        "declares that format. Unsupported syntax or formats fail loudly.",
        "5. **Surface safety and availability.** Mutating/destructive actions carry `safety_level`, guards, and a "
        "`confirmation_command` or `selection_command`. Disabled or daemon-required actions report that posture in the affordance.",
        "6. **Return next action affordances.** A workflow result should tell the operator what can happen next, rather than requiring "
        "the UI to invent a second truth ledger.",
        "",
    ]


def build_document(
    workflows: tuple[QueryActionWorkflow, ...] = QUERY_ACTION_WORKFLOWS,
    contracts: tuple[CliActionContract, ...] = ACTION_CONTRACTS,
    goldens: tuple[ExecutableWorkflowGoldenPath, ...] = EXECUTABLE_WORKFLOW_GOLDEN_PATHS,
) -> str:
    action_by_id = _action_index()
    missing_actions = sorted(
        {
            _path_label(path)
            for workflow in workflows
            for path in workflow.action_paths
            if _path_label(path) not in action_by_id
        }
        - {"find"}
    )
    if missing_actions:
        raise ValueError(f"workflow registry references actions with no contract: {missing_actions}")

    lines: list[str] = [
        "[← Back to README](../README.md)",
        "",
        GENERATED_NOTE,
        "",
        "# Executable Query-Action Workflows",
        "",
        "This product contract is generated from the live workflow registry and CLI action contracts. The registry drives the "
        "table below and the demo-archive golden-path tests, so the workflow map cannot drift into decorative metadata.",
        "",
        *_render_repeatable_template(),
        "## Workflow Registry",
        "",
        *_render_workflow_table(workflows),
        "",
        "## Verb Matrix",
        "",
        "The matrix is rendered from `ACTION_CONTRACTS`, the same source used by `polylogue config action-affordances`, "
        "`GET /api/action-affordances`, MCP affordance exposure, and completion descriptions.",
        "",
        *_render_action_matrix(contracts),
        "",
        "## Action-Unit Evidence",
        "",
        "Action units are the proof grain for query-action execution. They define the target evidence, proof surface, and negative "
        "guard that keeps a workflow honest.",
        "",
        *_render_action_unit_table(ACTION_UNIT_EVIDENCE),
        "",
        "## Shared Affordance DTO",
        "",
        *_render_affordance_fields(),
        "## Exact-Ref and Multi-Match Rules",
        "",
        "Exact refs are identity coordinates, not search suggestions. `id:` and `session:` filters route through the compiled query "
        "spec and must not broaden to FTS when absent. Text query matches are candidate result sets; downstream actions then apply "
        "the action cardinality. In particular, `find QUERY then read` reads one selected session unless the operator chooses "
        "`--all` or an explicit bounded export/read mode.",
        "",
        "## Completion Contract",
        "",
        "Shell completions are part of the workflow contract. They must cover `find QUERY then ACTION`, the action verbs "
        "(`select`, `read`, `continue`, `analyze`, `mark`, `delete`), read views, destinations and view-scoped formats, "
        "mutating/destructive guards (`mark --all|--first`, `delete --dry-run|--yes|--all`), `mark candidates` subcommands, "
        "and `continue --candidates` options. Unsupported query syntax must fail loudly and must not be completed as broad FTS.",
        "",
        "## Daemon and Browser Workbench Contract",
        "",
        "`GET /api/sessions` returns the same `action_affordances` list as the CLI action-affordance payload for query-result "
        "actions, while `GET /api/action-affordances` returns the complete action floor. The browser workbench renders those "
        "affordances as operator-visible action rails; it may disable actions by availability, but it must not invent hidden "
        "redaction or silently remove safe actions.",
        "",
        "## Demo-Archive Golden Paths",
        "",
        "The following commands are parametrized tests over `polylogue demo seed --with-overlays`. They verify at least one JSON "
        "shape and one human-rendered surface from the same registry that generates this document.",
        "",
        *_render_golden_path_table(goldens),
        "",
        "## Regeneration and Verification",
        "",
        "```bash",
        control_plane_command("render product-workflows"),
        control_plane_command("render product-workflows", "--check"),
        control_plane_command("test", "tests/unit/product/test_query_action_workflows.py"),
        control_plane_command("test", "tests/unit/cli/test_completion_matrix.py", "-k", "query_action"),
        "```",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render docs/product/workflows.md from executable query-action registries."
    )
    parser.add_argument("--output", default="docs/product/workflows.md", help="Output path.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero when the output is out of sync.")
    args = parser.parse_args(argv)

    output_path = Path(args.output)
    try:
        content = build_document()
    except ValueError as exc:
        print(f"render product-workflows: {exc}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != content:
            print(f"render product-workflows: out of sync: {output_path}", file=sys.stderr)
            print(
                f"render product-workflows: run: {control_plane_command('render product-workflows')}", file=sys.stderr
            )
            return 1
        print("render product-workflows: sync OK")
        return 0

    write_if_changed(output_path, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
