"""Render the CLI reference from live `polylogue --help` output."""

from __future__ import annotations

import argparse
import sys
from functools import cache
from pathlib import Path

from click import Command, Context, Group

from devtools.command_catalog import control_plane_command
from devtools.render_support import write_if_changed

SECTIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Top-Level Command", ()),
    ("List Verb", ("list",)),
    ("Stats Verb", ("stats",)),
    ("Count Verb", ("count",)),
    ("Read Verb", ("read",)),
    ("Delete Verb", ("delete",)),
    ("Insights", ("insights",)),
    ("Operations", ("ops",)),
    ("Doctor", ("ops", "doctor")),
    ("Tags", ("tags",)),
    ("User State", ("user-state",)),
    ("Auth", ("ops", "auth")),
    ("Reset", ("ops", "reset")),
    ("Schema", ("ops", "schema")),
    ("Completions", ("ops", "completions")),
    ("Dashboard", ("dashboard",)),
)


class HelpRenderError(RuntimeError):
    """Raised when live Click help rendering fails."""

    def __init__(self, command: tuple[str, ...], output: str, exit_code: int) -> None:
        super().__init__(" ".join(("polylogue", *command, "--help")))
        self.command = command
        self.output = output
        self.exit_code = exit_code


@cache
def _cli() -> Command:
    from polylogue.cli.click_app import cli

    return cli


def render_help(command: tuple[str, ...]) -> str:
    current = _cli()
    ctx = Context(current, info_name="polylogue")
    for part in command:
        if not isinstance(current, Group):
            raise HelpRenderError(command, f"{current.name} is not a group", 2)
        child = current.get_command(ctx, part)
        if child is None:
            raise HelpRenderError(command, f"unknown command: {part}", 2)
        current = child
        ctx = Context(current, info_name=part, parent=ctx)
    return current.get_help(ctx).rstrip()


def build_document(sections: list[tuple[str, str]]) -> str:
    from devtools.action_contract_report import render_action_contract_report

    parts = [
        "[← Back to README](../README.md)",
        "",
        f"<!-- Generated by `{control_plane_command('render cli-reference')}`. Edit devtools/render_cli_reference.py instead. -->",
        "",
        "# CLI Reference",
        "",
        "This reference is generated from the live `polylogue --help` surface inside the project devshell.",
        "",
    ]
    for title, body in sections:
        parts.extend([f"## {title}", "", "```text", body, "```", ""])
    parts.append(render_action_contract_report())
    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docs/cli-reference.md from live CLI help.")
    parser.add_argument(
        "--output",
        default="docs/cli-reference.md",
        help="Output file path or '-' for stdout (default: docs/cli-reference.md)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the output file is out of sync with the rendered content.",
    )
    args = parser.parse_args(argv)

    output_path = None if args.output == "-" else Path(args.output).expanduser()

    try:
        sections = [(title, render_help(command)) for title, command in SECTIONS]
    except HelpRenderError as exc:
        detail = f": {exc.output.strip()}" if exc.output.strip() else ""
        print(f"render cli-reference: failed to render help for {exc}{detail}", file=sys.stderr)
        return exc.exit_code or 1

    rendered = build_document(sections)

    if args.output == "-":
        if args.check:
            print("render cli-reference: --check does not support --output -", file=sys.stderr)
            return 2
        sys.stdout.write(rendered)
        return 0

    assert output_path is not None
    if args.check:
        try:
            current = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != rendered:
            print(f"render cli-reference: out of sync: {output_path}", file=sys.stderr)
            print(
                f"render cli-reference: run: {control_plane_command('render cli-reference', '--output', str(output_path))}",
                file=sys.stderr,
            )
            return 1
        print(f"render cli-reference: sync OK: {output_path}")
        return 0

    write_if_changed(output_path, rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["SECTIONS", "build_document", "main", "render_help", "write_if_changed"]
