"""Render the reviewable provider/tool → semantic-card registry surface."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

from polylogue.rendering.semantic_card_models import CARD_SCHEMA_VERSION, SemanticCardKind
from polylogue.rendering.semantic_card_registry import (
    ToolMapping,
    provider_namespace_documents,
    semantic_type_policy_documents,
    tool_mapping_rows,
)

DEFAULT_JSON = Path("docs/generated/semantic-card-tool-map.json")
DEFAULT_MARKDOWN = Path("docs/generated/semantic-card-tool-map.md")
MAP_SCHEMA_VERSION = "semantic-card-tool-map.v1"


def build_json_document() -> dict[str, object]:
    rows = tool_mapping_rows()
    counts = Counter(row.rendering_status for row in rows)
    providers = sorted({row.provider_family for row in rows})
    return {
        "schema_version": MAP_SCHEMA_VERSION,
        "card_schema_version": CARD_SCHEMA_VERSION,
        "classification_policy": {
            "precedence": ["persisted_semantic_type", "exact_provider_tool_alias", "fallback"],
            "unknown_tool": "fallback_raw_evidence",
            "outcome_policy": "structural_fields_only",
            "null_outcome": "unknown",
        },
        "provider_families": providers,
        "card_kinds": [item.value for item in SemanticCardKind],
        "status_counts": dict(sorted(counts.items())),
        "provider_namespace_policies": provider_namespace_documents(),
        "semantic_type_policies": semantic_type_policy_documents(),
        "provider_semantic_coverage": [
            {
                "provider_family": provider,
                "semantic_types": sorted({row.semantic_type for row in rows if row.provider_family == provider}),
                "exact_alias_count": sum(1 for row in rows if row.provider_family == provider),
            }
            for provider in providers
        ],
        "rows": [row.to_document() for row in rows],
    }


def build_markdown() -> str:
    grouped: dict[str, list[ToolMapping]] = defaultdict(list)
    for row in tool_mapping_rows():
        grouped[row.provider_family].append(row)
    lines = [
        "<!-- Generated by `python -m devtools.render_semantic_card_registry --write`. -->",
        "",
        "# Semantic card tool map",
        "",
        "This is the review surface for the provider-neutral `semantic-card.v1` registry. ",
        "Persisted semantic type wins, then a repository-grounded exact provider/tool alias. ",
        "Provider namespaces are open: an unlisted tool always becomes a raw fallback card, ",
        "and names or prose are never fuzzily classified.",
        "",
        "`launch` means the CLI launch slice has a specialized card. `model_only` means the ",
        "shared card model exists but public-surface completion is a follow-on. `fallback` ",
        "is intentional raw evidence, not a missing hidden heuristic.",
        "",
    ]
    lines.extend(
        [
            "## Persisted semantic-family policy",
            "",
            "This table is exhaustive over `SemanticBlockType`. It is the provider-neutral path used ",
            "when a parser has already persisted a trusted family, including provider-private names ",
            "that cannot be enumerated in the exact-alias tables.",
            "",
            "| Persisted semantic type | Card kind | Status |",
            "|---|---|---|",
        ]
    )
    for policy in semantic_type_policy_documents():
        lines.append(f"| `{policy['semantic_type']}` | `{policy['card_kind']}` | `{policy['rendering_status']}` |")
    lines.extend(["", "## Provider exact-alias census", ""])

    for provider in sorted(grouped):
        lines.extend(
            [
                f"## {provider}",
                "",
                "| Exact tool name | Semantic type | Card kind | Status | Basis | Evidence |",
                "|---|---|---|---|---|---|",
            ]
        )
        for row in sorted(grouped[provider], key=lambda item: item.tool_name.casefold()):
            lines.append(
                f"| `{row.tool_name}` | `{row.semantic_type}` | `{row.card_kind.value}` | "
                f"`{row.rendering_status}` | `{row.evidence_kind}` | `{row.evidence}` |"
            )
        lines.append("")
    lines.extend(
        [
            "## Gap-reading rules",
            "",
            "- Every provider namespace is treated as open; the finite table is evidence-backed rather than aspirational.",
            "- A provider can emit tool names not listed here. Those cards preserve exact raw input and result evidence.",
            "- A persisted `semantic_type` can safely specialize a provider-private name because classification already happened upstream.",
            "- `NULL` structural result fields remain `unknown`; a success-like sentence is not a success signal.",
            "- Web visual wiring, task deep links, richer attachment actions, and streaming cross-page pairing are bounded follow-ons.",
            "",
        ]
    )
    return "\n".join(line.rstrip() for line in lines)


def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if check:
        return current == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MARKDOWN)
    args = parser.parse_args(argv)

    json_text = json.dumps(build_json_document(), indent=2, ensure_ascii=False) + "\n"
    markdown_text = build_markdown()
    results = {
        args.json: _write_or_check(args.json, json_text, check=args.check),
        args.markdown: _write_or_check(args.markdown, markdown_text, check=args.check),
    }
    stale = [path for path, ok in results.items() if not ok]
    if stale:
        print("semantic-card registry: generated surfaces are stale", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        return 1
    action = "verified" if args.check else "wrote"
    print(f"semantic-card registry: {action} {len(results)} surface(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
