"""``devtools schema new`` -- generate a typed declaration and its adapter scaffolding.

The scaffold is domain-pluggable, not a universal code generator. Each
:class:`ScaffoldFamily` owns its own templates and its own reuse question; the
shared half is the unification interview (the five
:class:`~polylogue.declarations.models.CompatibilityKey` dimensions), the
reuse/justification refusal, and the write protocol (plan -> collision check ->
atomic apply with rollback).

Every generated bundle contains:

* ``declaration.py`` -- a compiling module that builds a real ``DeclarationSpec``
* ``adapter.py``     -- an implementation stub bound to the production adapter
* ``test_route_contract.py`` -- a contract skeleton that pushes the generated
  minimal-valid and invalid example arguments through the *production* adapter
* ``PLAN.md``        -- the exact repository paths and generated-surface
  commands needed to land the scaffold

Generation is deterministic: the same answers produce byte-identical output.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from devtools import repo_root as _get_root
from polylogue.declarations import CompatibilityKey, DeclarationRegistryProtocol

ROOT = _get_root()
DEFAULT_OUTPUT_ROOT = Path(".cache/scaffold")

COMPATIBILITY_DIMENSIONS: tuple[str, ...] = (
    "identity",
    "lifecycle",
    "authority",
    "access_result_shape",
    "durability",
)

#: Durability answers that assert a *new* durable object or registry. Creating
#: one without a justification is refused: durable state is the one decision a
#: scaffold must never make silently.
DURABLE_ANSWERS: frozenset[str] = frozenset({"durable", "durable-new-object", "new-registry"})


class ScaffoldError(RuntimeError):
    """An actionable refusal: what is wrong, and which flag repairs it."""


@dataclass(frozen=True, slots=True)
class ScaffoldFile:
    """One planned output file."""

    relative_path: str
    content: str


@dataclass(frozen=True, slots=True)
class ScaffoldAnswers:
    """The recorded unification interview for one scaffold run."""

    family: str
    name: str
    compatibility: CompatibilityKey
    reuse_family: str | None
    justification: str

    def as_dict(self) -> dict[str, object]:
        return {
            "family": self.family,
            "name": self.name,
            "compatibility": {
                dimension: getattr(self.compatibility, dimension) for dimension in COMPATIBILITY_DIMENSIONS
            },
            "reuse_family": self.reuse_family,
            "justification": self.justification,
        }


@dataclass(frozen=True, slots=True)
class ScaffoldPlan:
    """A complete, inspectable generation plan."""

    answers: ScaffoldAnswers
    output_root: str
    files: tuple[ScaffoldFile, ...]
    instructions: tuple[str, ...]

    def as_dict(self) -> dict[str, object]:
        return {
            "answers": self.answers.as_dict(),
            "output_root": self.output_root,
            "files": [item.relative_path for item in self.files],
            "instructions": list(self.instructions),
        }


@dataclass(frozen=True, slots=True)
class ScaffoldFamily:
    """One domain's scaffold templates and registry ownership."""

    name: str
    description: str
    #: Callable returning the live registry whose families may be reused.
    registry: Callable[[], DeclarationRegistryProtocol]
    render: Callable[[ScaffoldAnswers, str], tuple[ScaffoldFile, ...]]
    instructions: tuple[str, ...]
    owner_path: str


def _module_name(name: str) -> str:
    return name.replace("-", "_")


def _mcp_registry() -> DeclarationRegistryProtocol:
    from polylogue.mcp.declarations.registry import MCP_KERNEL_REGISTRY

    return MCP_KERNEL_REGISTRY


def _daemon_registry() -> DeclarationRegistryProtocol:
    from polylogue.daemon.route_contracts import DAEMON_ROUTE_REGISTRY

    return DAEMON_ROUTE_REGISTRY


def _compatibility_literal(compatibility: CompatibilityKey) -> str:
    fields = ",\n".join(
        f"        {dimension}={getattr(compatibility, dimension)!r}" for dimension in COMPATIBILITY_DIMENSIONS
    )
    return f"CompatibilityKey(\n{fields},\n    )"


def _declaration_module(
    answers: ScaffoldAnswers,
    bundle_path: str,
    *,
    declaration_id: str,
    owner_path: str,
    producer: str,
    role_gate: str,
    handler_surface: str,
    handler_symbol: str,
    binding_key: str,
    output_kind: str,
    output_target: str,
    consumer: str,
    repair_command: str,
) -> str:
    module = _module_name(answers.name)
    family = answers.reuse_family or declaration_id
    return f'''"""Generated declaration scaffold for {answers.name!r}.

Generated by `devtools schema new {answers.family} {answers.name}`. Move this record
into {owner_path} once the handler below is real; the scaffold never edits a
production registry on your behalf.

Unification answers recorded at generation time:
{json.dumps(answers.as_dict(), indent=2, sort_keys=True)}
"""

from __future__ import annotations

from polylogue.declarations import (
    CompatibilityKey,
    CompletenessEdge,
    DeclarationSpec,
    ExampleSpec,
    HandlerBinding,
    OutputSpec,
)

COMPATIBILITY = {_compatibility_literal(answers.compatibility)}

DECLARATION = DeclarationSpec(
    declaration_id={declaration_id!r},
    family_id={family!r},
    public_name={answers.name!r},
    owner_path={owner_path!r},
    compatibility=COMPATIBILITY,
    producer={producer!r},
    role_gate={role_gate!r},
    schema_ref={f"{producer}:inspect.signature"!r},
    discovery_text={f"TODO: one-line discovery text for {answers.name}."!r},
    repair_command={repair_command!r},
    handlers=(
        HandlerBinding(
            surface={handler_surface!r},
            owner_path={f"{bundle_path}/adapter.py"!r},
            symbol={handler_symbol!r},
            binding_key={binding_key!r},
        ),
    ),
    outputs=(
        OutputSpec(
            name="runtime-contract",
            kind={output_kind!r},
            schema_ref={f"tests/unit/{answers.family.split('-')[0]}/test_{module}_route_contract.py"!r},
            target_path={output_target!r},
        ),
    ),
    examples=(
        ExampleSpec(
            name="minimal-valid-call",
            summary={f"Minimal valid invocation for {answers.name}."!r},
            arguments=(),
        ),
        ExampleSpec(
            name="invalid-call",
            summary={f"Invocation {answers.name} must refuse."!r},
            arguments=(("__unknown_argument__", "refused"),),
        ),
    ),
    completeness_edges=(
        CompletenessEdge(
            producer={declaration_id!r},
            consumer={consumer!r},
            kind="discovery-name-equivalence",
            owner_path={consumer.split(":")[0]!r},
        ),
    ),
)

__all__ = ["COMPATIBILITY", "DECLARATION"]
'''


def _render_mcp(answers: ScaffoldAnswers, bundle_path: str) -> tuple[ScaffoldFile, ...]:
    module = _module_name(answers.name)
    declaration_id = f"mcp.tool.{answers.name}"
    declaration = _declaration_module(
        answers,
        bundle_path,
        declaration_id=declaration_id,
        owner_path="polylogue/mcp/declarations/registry.py",
        producer=f"polylogue.api.Polylogue.{module}",
        role_gate="mcp.capability:read",
        handler_surface="mcp",
        handler_symbol=module,
        binding_key=f"polylogue.mcp.server_cutover:{answers.name}",
        output_kind="envelope:items,total,unit,limit,offset",
        output_target=f"mcp://tool/{answers.name}",
        consumer="tests/infra/mcp.py:EXPECTED_TOOL_NAMES",
        repair_command="devtools test tests/unit/mcp/test_tool_declarations.py",
    )
    adapter = f'''"""Implementation stub for the {answers.name!r} MCP tool.

Register this handler through the production adapter
(:class:`polylogue.mcp.declarations.adapter.DeclaredToolRegistrar`) so the
declaration, the capability gate, and the live handler are validated together.
"""

from __future__ import annotations

from typing import Any

from polylogue.mcp.declarations.adapter import DeclaredToolRegistrar


def register(registrar: DeclaredToolRegistrar) -> None:
    """Register the scaffolded tool on a capability-filtered registrar."""

    @registrar.tool({answers.name!r})
    async def {module}(**arguments: Any) -> dict[str, Any]:
        raise NotImplementedError("TODO: implement {answers.name} and return a declared envelope")


__all__ = ["register"]
'''
    contract = f'''"""Route contract skeleton for the {answers.name!r} MCP tool.

Both the minimal-valid and the invalid invocation run through the *production*
registration adapter (``DeclaredToolRegistrar``), never a local validator.

Until the declaration is landed in ``polylogue/mcp/declarations/registry.py``,
the production adapter correctly refuses the tool: that refusal is the first
assertion here, and it names the landing step. Once the declaration lands, the
minimal-valid registration assertion takes over automatically.

Anti-vacuity: land the declaration but register the tool under a capability set
that does not allow it, or rename it, and this goes red.
"""

from __future__ import annotations

import pytest

from polylogue.mcp.declarations.adapter import DeclaredToolRegistrar, MCPRegistrationError
from polylogue.mcp.declarations.models import MCPCapabilities
from polylogue.mcp.declarations.registry import declared_tool_names

TOOL_NAME = {answers.name!r}
LANDING_STEP = (
    "add the generated DECLARATION to polylogue/mcp/declarations/registry.py, "
    "then re-run this contract"
)


class _Recorder:
    """Minimal MCPServer stand-in: the adapter under test is production code."""

    def __init__(self) -> None:
        self.registered: dict[str, object] = {{}}

    def tool(self, name=None, *, description=None):
        def decorate(handler):
            self.registered[name] = handler
            return handler

        return decorate


def _registrar() -> DeclaredToolRegistrar:
    return DeclaredToolRegistrar(_Recorder(), capabilities=MCPCapabilities())


def test_minimal_valid_invocation_through_the_production_adapter() -> None:
    registrar = _registrar()
    if TOOL_NAME not in declared_tool_names():
        with pytest.raises(MCPRegistrationError) as excinfo:

            @registrar.tool(TOOL_NAME)
            async def undeclared(**arguments: object) -> dict[str, object]:
                return {{}}

        assert TOOL_NAME in str(excinfo.value), LANDING_STEP
        pytest.skip(f"{{TOOL_NAME}} is not declared yet: {{LANDING_STEP}}")

    @registrar.tool(TOOL_NAME)
    async def {module}(**arguments: object) -> dict[str, object]:
        return {{"ok": True}}

    assert TOOL_NAME in registrar.registered_names


def test_invalid_invocation_is_refused_by_the_production_adapter() -> None:
    registrar = _registrar()
    with pytest.raises(MCPRegistrationError):

        @registrar.tool("__unknown_argument__")
        async def unknown(**arguments: object) -> dict[str, object]:
            return {{}}
'''
    return (
        ScaffoldFile("declaration.py", declaration),
        ScaffoldFile("adapter.py", adapter),
        ScaffoldFile(f"test_{module}_route_contract.py", contract),
    )


def _render_daemon_route(answers: ScaffoldAnswers, bundle_path: str) -> tuple[ScaffoldFile, ...]:
    module = _module_name(answers.name)
    declaration_id = f"daemon.{answers.name}"
    declaration = _declaration_module(
        answers,
        bundle_path,
        declaration_id=declaration_id,
        owner_path="polylogue/daemon/route_contracts.py",
        producer=f"polylogue.daemon.http.DaemonAPIHandler._handle_{module}",
        role_gate="credential_if_configured",
        handler_surface="daemon-http",
        handler_symbol=f"handle_{module}",
        binding_key=f"GET /api/{answers.name}",
        output_kind="json",
        output_target=f"/api/{answers.name}",
        consumer="docs/openapi/search.yaml:paths",
        repair_command="devtools render openapi",
    )
    adapter = f'''"""Implementation stub for the ``/api/{answers.name}`` daemon route.

Land the handler on ``polylogue.daemon.http.DaemonAPIHandler`` and move the
generated ``RouteSpec`` into ``polylogue/daemon/route_contracts.py`` so the
route adapter and the OpenAPI renderer both derive from one declaration.
"""

from __future__ import annotations

from typing import Any


def handle_{module}(query: dict[str, Any]) -> dict[str, Any]:
    """Serve the scaffolded route. Returns the declared response contract."""

    raise NotImplementedError("TODO: implement /api/{answers.name}")


__all__ = ["handle_{module}"]
'''
    contract = f'''"""Route contract skeleton for ``/api/{answers.name}``.

The generated declaration is pushed through the production declaration
diagnostics, not a local validator: an unresolved handler, a missing owner
path, or an incomplete record is reported as one actionable diagnostic.

Anti-vacuity: blank the declaration's handler or output and this test goes red.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

from polylogue.declarations import DeclarationRegistry
from polylogue.declarations.diagnostics import diagnose_registry

BUNDLE = Path(__file__).resolve().parent
ROOT = next(parent for parent in BUNDLE.parents if (parent / "pyproject.toml").exists())


def _declaration():
    spec = importlib.util.spec_from_file_location("scaffold_declaration", BUNDLE / "declaration.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.DECLARATION


def test_declaration_resolves_through_production_diagnostics() -> None:
    registry = DeclarationRegistry()
    registry.register(_declaration())
    diagnostics = diagnose_registry(registry, root=ROOT)
    assert not diagnostics, [item.message for item in diagnostics]
'''
    return (
        ScaffoldFile("declaration.py", declaration),
        ScaffoldFile("adapter.py", adapter),
        ScaffoldFile(f"test_{module}_route_contract.py", contract),
    )


FAMILIES: tuple[ScaffoldFamily, ...] = (
    ScaffoldFamily(
        name="mcp-tool",
        description="An MCP tool declaration, registration stub, and production-adapter contract skeleton.",
        registry=_mcp_registry,
        render=_render_mcp,
        instructions=(
            "Move DECLARATION into polylogue/mcp/declarations/registry.py as a new _ToolRow.",
            "Register the handler through DeclaredToolRegistrar in polylogue/mcp/server_cutover.py.",
            "Add the tool name to tests/infra/mcp.py EXPECTED_TOOL_NAMES.",
            "Run: devtools render agent-manual",
            "Run: devtools test tests/unit/mcp/test_tool_declarations.py",
        ),
        owner_path="polylogue/mcp/declarations/registry.py",
    ),
    ScaffoldFamily(
        name="daemon-route",
        description="A daemon HTTP route declaration, handler stub, and declaration-diagnostics contract skeleton.",
        registry=_daemon_registry,
        render=_render_daemon_route,
        instructions=(
            "Move DECLARATION into polylogue/daemon/route_contracts.py as a RouteSpec.",
            "Implement the handler on polylogue.daemon.http.DaemonAPIHandler.",
            "Run: devtools render openapi",
            "Run: devtools test tests/unit/daemon",
        ),
        owner_path="polylogue/daemon/route_contracts.py",
    ),
)

FAMILY_BY_NAME: dict[str, ScaffoldFamily] = {family.name: family for family in FAMILIES}


def compatible_family(registry: DeclarationRegistryProtocol, compatibility: CompatibilityKey) -> str | None:
    """Return an existing family whose compatibility key matches exactly."""

    for family in registry.families():
        if not family.compatibility.differences(compatibility):
            return family.family_id
    return None


def build_plan(
    family_name: str,
    name: str,
    *,
    compatibility: CompatibilityKey,
    reuse_family: str | None = None,
    justification: str = "",
    output_root: Path = DEFAULT_OUTPUT_ROOT,
) -> ScaffoldPlan:
    """Answer the unification questions, refuse or reuse, and plan the files."""

    family = FAMILY_BY_NAME.get(family_name)
    if family is None:
        raise ScaffoldError(
            f"unknown scaffold family {family_name!r}; declared families: {', '.join(sorted(FAMILY_BY_NAME))}"
        )
    missing = [dimension for dimension in COMPATIBILITY_DIMENSIONS if not getattr(compatibility, dimension)]
    if missing:
        raise ScaffoldError(
            "the unification interview is incomplete; answer "
            + ", ".join(f"--{dimension.replace('_', '-')}" for dimension in missing)
        )

    registry = family.registry()
    existing = compatible_family(registry, compatibility)
    if reuse_family is not None:
        known = {item.family_id for item in registry.families()}
        if reuse_family not in known:
            raise ScaffoldError(
                f"--reuse-family {reuse_family!r} is not a declared family in {family.owner_path}; "
                f"declared families: {', '.join(sorted(known))}"
            )
        member = next(item for item in registry.families() if item.family_id == reuse_family)
        differences = member.compatibility.differences(compatibility)
        if differences:
            detail = ", ".join(f"{field}: {left!r} != {right!r}" for field, left, right in differences)
            raise ScaffoldError(
                f"--reuse-family {reuse_family!r} is incompatible with the answered interview ({detail}); "
                "either match the family or justify a new one with --justification"
            )
    elif existing is not None and not justification:
        raise ScaffoldError(
            f"family {existing!r} already declares this exact compatibility key; reuse it with "
            f"--reuse-family {existing} or record why a new declaration is needed with --justification"
        )
    elif compatibility.durability in DURABLE_ANSWERS and not justification:
        raise ScaffoldError(
            f"durability {compatibility.durability!r} asserts a new durable object or registry; "
            "record why with --justification before generating it"
        )

    answers = ScaffoldAnswers(
        family=family.name,
        name=name,
        compatibility=compatibility,
        reuse_family=reuse_family,
        justification=justification,
    )
    target = output_root / family.name / _module_name(name)
    files = list(family.render(answers, str(target)))
    plan_lines = [
        f"# Landing plan: {family.name} / {name}",
        "",
        "## Recorded unification answers",
        "",
        "```json",
        json.dumps(answers.as_dict(), indent=2, sort_keys=True),
        "```",
        "",
        "## Generated outputs",
        "",
        *(f"- `{target}/{item.relative_path}`" for item in files),
        "",
        "## Steps",
        "",
        *(f"{index}. {step}" for index, step in enumerate(family.instructions, start=1)),
        "",
    ]
    files.append(ScaffoldFile("PLAN.md", "\n".join(plan_lines)))
    return ScaffoldPlan(
        answers=answers,
        output_root=str(target),
        files=tuple(files),
        instructions=family.instructions,
    )


def apply_plan(plan: ScaffoldPlan, *, root: Path = ROOT) -> tuple[Path, ...]:
    """Write a planned bundle, refusing collisions and rolling back partials.

    A collision is refused before the first byte is written. If any later write
    fails, every file this call created is removed, so a failed scaffold never
    leaves a half-written bundle behind.
    """

    target = root / plan.output_root
    collisions = [item.relative_path for item in plan.files if (target / item.relative_path).exists()]
    if collisions:
        raise ScaffoldError(
            f"refusing to overwrite existing scaffold output in {target}: {', '.join(sorted(collisions))}"
        )
    written: list[Path] = []
    try:
        target.mkdir(parents=True, exist_ok=True)
        for item in plan.files:
            path = target / item.relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(item.content, encoding="utf-8")
            written.append(path)
    except OSError:
        for path in written:
            path.unlink(missing_ok=True)
        raise
    return tuple(written)


#: Which registry in ``devtools.verify_declaration_bindings`` owns each family.
_REGISTRY_NAME_BY_FAMILY: dict[str, str] = {"mcp-tool": "mcp", "daemon-route": "daemon-route"}


def validate_owner_registry(family_name: str, *, root: Path = ROOT) -> tuple[str, ...]:
    """Return actionable diagnostics for the family's live owning registry.

    Delegates to the ``declaration-bindings`` gate so the scaffold and the gate
    cannot disagree about what a complete registration means.
    """

    from devtools.verify_declaration_bindings import run as run_bindings

    family = FAMILY_BY_NAME.get(family_name)
    if family is None:
        raise ScaffoldError(f"unknown scaffold family {family_name!r}")
    return run_bindings(root=root)[_REGISTRY_NAME_BY_FAMILY[family.name]]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="devtools schema new",
        description="Generate a typed declaration, adapter stub, contract skeleton, and landing plan.",
    )
    parser.add_argument("family", nargs="?", help="Scaffold family (omit with --list to see the declared families).")
    parser.add_argument("name", nargs="?", help="Public name of the new declaration.")
    parser.add_argument("--list", action="store_true", help="List the declared scaffold families and exit.")
    for dimension in COMPATIBILITY_DIMENSIONS:
        parser.add_argument(
            f"--{dimension.replace('_', '-')}",
            default="",
            help=f"Unification answer for the {dimension} compatibility dimension.",
        )
    parser.add_argument("--reuse-family", default=None, help="Join this existing declaration family.")
    parser.add_argument("--justification", default="", help="Why a new family or durable object is needed.")
    parser.add_argument("--dry-run", action="store_true", help="Print the plan without writing any file.")
    parser.add_argument("--json", action="store_true", help="Emit the plan as JSON.")
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Report actionable diagnostics for the family's live owning registry and exit.",
    )
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT), help="Directory that receives the bundle.")
    args = parser.parse_args(argv)

    if args.list or args.family is None:
        for family in FAMILIES:
            print(f"{family.name}: {family.description}")
        return 0 if args.list or args.family is None else 1

    try:
        if args.validate:
            diagnostics = validate_owner_registry(args.family)
            for line in diagnostics:
                print(line, file=sys.stderr)
            if diagnostics:
                return 1
            print(f"devtools schema new: {args.family}: owning registry is complete")
            return 0

        if args.name is None:
            raise ScaffoldError("a public name is required: devtools schema new <family> <name>")
        plan = build_plan(
            args.family,
            args.name,
            compatibility=CompatibilityKey(
                identity=args.identity,
                lifecycle=args.lifecycle,
                authority=args.authority,
                access_result_shape=args.access_result_shape,
                durability=args.durability,
            ),
            reuse_family=args.reuse_family,
            justification=args.justification,
            output_root=Path(args.output_root),
        )
    except ScaffoldError as exc:
        print(f"devtools schema new: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(plan.as_dict(), indent=2, sort_keys=True))
    else:
        print(f"devtools schema new: plan for {plan.answers.family}/{plan.answers.name} in {plan.output_root}")
        for item in plan.files:
            print(f"devtools schema new:   {plan.output_root}/{item.relative_path}")
        for index, step in enumerate(plan.instructions, start=1):
            print(f"devtools schema new:   {index}. {step}")
    if args.dry_run:
        print("devtools schema new: dry run; nothing written")
        return 0
    try:
        written = apply_plan(plan)
    except ScaffoldError as exc:
        print(f"devtools schema new: {exc}", file=sys.stderr)
        return 1
    print(f"devtools schema new: wrote {len(written)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
