"""Local/test-focused validation lane declarations."""

from __future__ import annotations

from devtools.validation_lane_base import devtools_lane, pytest_lane

CONTRACT_LANES = {
    "machine-contract": pytest_lane(
        "machine-contract",
        "Root CLI JSON success/failure envelopes and runtime-health machine surfaces",
        180,
        "-q",
        "-n",
        "0",
        "-m",
        "machine_contract",
    ),
    "query-routing": pytest_lane(
        "query-routing",
        "Query-first CLI route planning, integration, and streamed read-surface proofs",
        240,
        "-q",
        "-n",
        "0",
        "-m",
        "query_routing",
    ),
    "showcase-baselines": devtools_lane(
        "showcase-baselines",
        "Registry-derived tier-0 CLI help/source showcase baselines",
        180,
        "verify-showcase",
    ),
    "pipeline-probe-chatgpt": devtools_lane(
        "pipeline-probe-chatgpt",
        "Synthetic ChatGPT parse-stage pipeline probe under explicit runtime and RSS budgets",
        180,
        "pipeline-probe",
        "--provider",
        "chatgpt",
        "--count",
        "5",
        "--stage",
        "parse",
        "--max-total-ms",
        "10000",
        "--max-peak-rss-mb",
        "512",
    ),
    "semantic-stack": pytest_lane(
        "semantic-stack",
        "Unified harmonization, semantic facts/profile convergence, proof, and contract inventory coverage",
        360,
        "-q",
        "-n",
        "0",
        "tests/unit/core/test_semantic_facts.py",
        "tests/unit/core/test_filters_schemas.py",
        "tests/unit/sources/test_unified_semantic_laws.py",
        "tests/integration/test_extraction_db.py",
        "tests/unit/core/test_semantic_proof.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/showcase/test_qa_runner.py",
        "tests/unit/showcase/test_report.py",
        "tests/unit/core/test_conversation_semantics.py",
    ),
    "source-provider-fidelity": pytest_lane(
        "source-provider-fidelity",
        "Source traversal, Drive/runtime source boundaries, parser decoding, and provider-ingest fidelity",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/sources/test_drive_ops.py",
        "tests/unit/sources/test_source_laws.py",
        "tests/unit/sources/test_acquisition_encoding.py",
        "tests/unit/storage/test_parse_tracking.py",
        "tests/unit/pipeline/test_ingestion_chaos.py",
        "tests/integration/test_security.py",
    ),
    "maintenance-control-plane": pytest_lane(
        "maintenance-control-plane",
        "Health, maintenance selection, cache/live provenance, publication maintenance summaries, and machine output",
        480,
        "-q",
        "-n",
        "0",
        "tests/unit/core/test_health_core.py",
        "tests/unit/storage/test_fts5.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/cli/test_source_selection_helpers.py",
        "tests/unit/cli/test_deterministic_output.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/site/test_builder.py",
        "tests/unit/cli/test_site.py",
        "tests/integration/test_health.py",
    ),
    "archive-data-products": pytest_lane(
        "archive-data-products",
        "Durable archive products, external consumer contracts, product-aware grouped stats, and health/governance surfaces",
        600,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_query_exec.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/cli/test_click_app.py",
        "tests/unit/core/test_health_core.py",
        "tests/integration/test_health.py",
    ),
    "semantic-product-normalization": pytest_lane(
        "semantic-product-normalization",
        "Semantic/session product normalization, operator/toolchain narrowing, schema contracts, and provider parser cleanup",
        900,
        "-q",
        "-n",
        "0",
        "tests/unit/core/test_project_normalization.py",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/core/test_schema_registry.py",
        "tests/unit/core/test_schema_generation.py",
        "tests/unit/core/test_operator_models.py",
        "tests/integration/test_schema_operator_workflow.py",
        "tests/unit/storage/test_search_misc.py",
        "tests/unit/sources/test_parsers_base.py",
        "tests/unit/sources/test_parsers_drive.py",
        "tests/unit/devtools/test_validation_lanes.py",
    ),
    "retrieval-dogfood": pytest_lane(
        "retrieval-dogfood",
        "Action-aware query truth, grouped retrieval stats, archive health, and MCP retrieval payload coverage",
        480,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_query_exec.py",
        "tests/unit/cli/test_query_exec_laws.py",
        "tests/unit/storage/test_store_ops.py",
        "tests/unit/core/test_filters_props.py",
        "tests/unit/core/test_health_core.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_source_selection_helpers.py",
    ),
    "embeddings-coverage": pytest_lane(
        "embeddings-coverage",
        "Embedding coverage/readiness stats, health exposure, and embed command contracts",
        300,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_embed.py",
        "tests/unit/storage/test_embedding_stats.py",
        "tests/unit/core/test_health_core.py",
        "tests/unit/cli/test_source_selection_helpers.py",
        "tests/unit/mcp/test_tool_contracts.py",
    ),
    "evidence-tier-contracts": pytest_lane(
        "evidence-tier-contracts",
        "Explicit evidence-tier product contracts, chronology fields, and durable evidence payload/query surfaces",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/storage/test_backend.py",
        "tests/unit/pipeline/test_prepare_semantic.py",
    ),
    "inference-tier-contracts": pytest_lane(
        "inference-tier-contracts",
        "Inference-tier work-event/phase/profile contracts with confidence/provenance-bearing semantic payloads",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/pipeline/test_prepare_semantic.py",
    ),
    "mixed-consumer-contracts": pytest_lane(
        "mixed-consumer-contracts",
        "CLI, facade, MCP, and health surfaces consuming the same evidence/inference product model",
        480,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_check.py",
        "tests/integration/test_health.py",
    ),
    "retrieval-band-readiness": pytest_lane(
        "retrieval-band-readiness",
        "Transcript/evidence/inference retrieval-band readiness, embedding stats, and health exposure",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_embed.py",
        "tests/unit/storage/test_embedding_stats.py",
        "tests/unit/core/test_health_core.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/mcp/test_tool_contracts.py",
    ),
    "heuristic-inference-contracts": pytest_lane(
        "heuristic-inference-contracts",
        "Heuristic session/work/phase contract hardening with explicit support metadata and consumer parity",
        600,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/core/test_semantic_facts.py",
        "tests/unit/pipeline/test_prepare_semantic.py",
        "tests/unit/core/test_health_core.py",
    ),
    "probabilistic-enrichment-contracts": pytest_lane(
        "probabilistic-enrichment-contracts",
        "Durable session-enrichment product contracts across CLI, facade, MCP, storage, and retrieval-band status",
        720,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/storage/test_embedding_stats.py",
        "tests/unit/storage/test_backend.py",
        "tests/unit/core/test_health_core.py",
    ),
    "governed-cleanup-contracts": pytest_lane(
        "governed-cleanup-contracts",
        "Cleanup lineage, health/debt governance, and maintenance control-plane contract coverage",
        900,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/core/test_health_core.py",
        "tests/integration/test_health.py",
    ),
    "tui": pytest_lane(
        "tui",
        "Textual Mission Control screens and interaction-state coverage",
        240,
        "-q",
        "-n",
        "0",
        "-m",
        "tui",
    ),
    "chaos": pytest_lane(
        "chaos",
        "Hostility, interruption, and chronology integration coverage",
        900,
        "-q",
        "-n",
        "0",
        "-m",
        "chaos",
    ),
    "scale-fast": devtools_lane(
        "scale-fast",
        "Fast storage scale budgets",
        120,
        "run-scale-lanes",
        "--lane",
        "fast",
    ),
    "scale-slow": devtools_lane(
        "scale-slow",
        "Slow local storage scale budgets",
        360,
        "run-scale-lanes",
        "--lane",
        "slow",
    ),
    "long-haul-small": devtools_lane(
        "long-haul-small",
        "Small reproducible benchmark/long-haul campaign",
        1800,
        "run-benchmark-campaigns",
        "--scale",
        "small",
    ),
}


__all__ = ["CONTRACT_LANES"]
