"""Composite validation lane declarations."""

from __future__ import annotations

from devtools.validation_lane_base import composite_lane

COMPOSITE_LANES = {
    "source-runtime-governance": composite_lane(
        "source-runtime-governance",
        "Local source/provider fidelity plus runtime maintenance/control-plane convergence",
        1800,
        "source-provider-fidelity",
        "maintenance-control-plane",
    ),
    "live-archive-small": composite_lane(
        "live-archive-small",
        "Bounded live archive retrieval/readiness/health dogfood lane",
        480,
        "live-embed-stats",
        "live-retrieval-dogfood",
        "live-products-status",
        "live-health-json",
    ),
    "live-products-small": composite_lane(
        "live-products-small",
        "Bounded live archive durable-product and grouped-stats dogfood lane",
        480,
        "live-products-status",
        "live-products-tags",
        "live-project-stats",
    ),
    "live-governance-small": composite_lane(
        "live-governance-small",
        "Bounded live archive governance lane for health, maintenance preview, and maintenance memory budget",
        720,
        "live-health-json",
        "live-maintenance-preview",
        "maintenance-memory-budget",
    ),
    "live-archive-slow": composite_lane(
        "live-archive-slow",
        "Broader live archive dogfood lane including retrieval/readiness and live QA exercises",
        2400,
        "live-archive-small",
        "live-exercises",
    ),
    "archive-intelligence": composite_lane(
        "archive-intelligence",
        "Local archive-intelligence closure lane for retrieval, embedding readiness, and schema roundtrip",
        1800,
        "retrieval-dogfood",
        "embeddings-coverage",
        "schema-roundtrip",
    ),
    "archive-data-products-live": composite_lane(
        "archive-data-products-live",
        "Local durable-product contract lane plus bounded live archive product dogfooding",
        1800,
        "archive-data-products",
        "live-products-small",
    ),
    "domain-read-model-contracts": composite_lane(
        "domain-read-model-contracts",
        "Local domain-read-model closure lane for analytics/products, consumer contracts, and archive-debt governance surfaces",
        2400,
        "archive-data-products",
        "maintenance-control-plane",
    ),
    "domain-read-model-live": composite_lane(
        "domain-read-model-live",
        "Bounded live archive lane for durable products, analytics/debt products, and maintenance governance",
        1800,
        "live-products-small",
        "live-products-analytics",
        "live-products-debt",
        "live-governance-small",
    ),
    "domain-read-model-stewardship": composite_lane(
        "domain-read-model-stewardship",
        "Full domain-read-model and live-archive stewardship closure lane",
        3600,
        "domain-read-model-contracts",
        "domain-read-model-live",
    ),
    "runtime-substrate-contracts": composite_lane(
        "runtime-substrate-contracts",
        "Local runtime-substrate closure lane across query, semantic proof, durable products, and maintenance control-plane contracts",
        2400,
        "query-routing",
        "semantic-stack",
        "maintenance-control-plane",
        "archive-data-products",
    ),
    "runtime-substrate-live": composite_lane(
        "runtime-substrate-live",
        "Bounded live archive lane for runtime-substrate dogfooding, governance, and memory budgets",
        1800,
        "live-archive-small",
        "live-governance-small",
        "memory-budget",
    ),
    "runtime-substrate-hardening": composite_lane(
        "runtime-substrate-hardening",
        "Full runtime-substrate validation lane covering local contracts plus bounded live archive checks",
        3600,
        "runtime-substrate-contracts",
        "runtime-substrate-live",
    ),
    "semantic-product-live": composite_lane(
        "semantic-product-live",
        "Bounded live archive lane for normalized product surfaces, governance preview, and maintenance budgets",
        1800,
        "live-products-status",
        "live-products-tags",
        "live-products-day-summaries",
        "live-products-debt",
        "live-governance-small",
    ),
    "semantic-product-hardening": composite_lane(
        "semantic-product-hardening",
        "Full semantic-product normalization and toolchain convergence lane",
        3600,
        "semantic-product-normalization",
        "semantic-product-live",
    ),
    "evidence-stewardship-contracts": composite_lane(
        "evidence-stewardship-contracts",
        "Evidence/inference contract closure lane across explicit evidence, inferred semantics, consumer parity, and retrieval readiness",
        2400,
        "evidence-tier-contracts",
        "inference-tier-contracts",
        "mixed-consumer-contracts",
        "retrieval-band-readiness",
    ),
    "evidence-stewardship-live": composite_lane(
        "evidence-stewardship-live",
        "Bounded live archive lane for tiered product views, live migration, health, and retrieval-band budgets",
        2400,
        "live-session-product-repair",
        "live-products-status",
        "live-products-profiles-evidence",
        "live-products-profiles-inference",
        "live-products-work-events",
        "live-products-phases",
        "live-embed-stats",
        "live-health-json",
        "maintenance-memory-budget",
    ),
    "evidence-stewardship-hardening": composite_lane(
        "evidence-stewardship-hardening",
        "Full evidence/stewardship closure lane covering tiered contracts plus bounded live archive migration and retrieval readiness",
        4800,
        "evidence-stewardship-contracts",
        "evidence-stewardship-live",
    ),
    "probabilistic-enrichment-live": composite_lane(
        "probabilistic-enrichment-live",
        "Bounded live archive lane for enrichment products, retrieval bands, and health surfaces",
        2400,
        "live-session-product-repair",
        "live-products-status",
        "live-products-profiles-inference",
        "live-products-enrichments",
        "live-embed-stats",
        "live-health-json",
        "memory-budget",
    ),
    "governed-cleanup-live": composite_lane(
        "governed-cleanup-live",
        "Bounded live archive lane for cleanup debt preview/validation governance and maintenance budgets",
        2400,
        "live-products-debt",
        "live-maintenance-preview",
        "maintenance-memory-budget",
    ),
    "probabilistic-enrichment-hardening": composite_lane(
        "probabilistic-enrichment-hardening",
        "Full probabilistic-enrichment and governed-cleanup closure lane",
        5400,
        "heuristic-inference-contracts",
        "probabilistic-enrichment-contracts",
        "governed-cleanup-contracts",
        "probabilistic-enrichment-live",
        "governed-cleanup-live",
    ),
    "frontier-local": composite_lane(
        "frontier-local",
        "Non-live local closure lane for machine/query/semantic/TUI/chaos validation",
        1500,
        "machine-contract",
        "query-routing",
        "semantic-stack",
        "tui",
        "chaos",
    ),
    "frontier-extended": composite_lane(
        "frontier-extended",
        "Local closure lane plus fast scale and small long-haul campaign",
        3600,
        "frontier-local",
        "scale-fast",
        "long-haul-small",
    ),
}


__all__ = ["COMPOSITE_LANES"]
