"""Local/test-focused validation lane declarations plus composite lanes."""

from __future__ import annotations

from devtools.lane_models import LaneEntry
from polylogue.scenarios import (
    CorpusRequest,
    PipelineProbeRequest,
    composite_execution,
    devtools_execution,
    pipeline_probe_execution,
    pytest_execution,
)
from polylogue.scenarios.assertions import AssertionClass, AssertionSpec

# ---------------------------------------------------------------------------
# Contract lanes
# ---------------------------------------------------------------------------

CONTRACT_LANES: dict[str, LaneEntry] = {
    "machine-contract": LaneEntry(
        name="machine-contract",
        description="Root CLI JSON success/failure envelopes and runtime-health machine surfaces",
        timeout_s=180,
        category="contract",
        execution=pytest_execution("-q", "-n", "0", "-m", "machine_contract"),
        operation_targets=("cli.json-contract",),
        tags=("contract", "json", "cli"),
    ),
    "verification-substrate-contracts": LaneEntry(
        name="verification-substrate-contracts",
        description="Shared test fixture contracts for JSON metadata, scenario content blocks, and semantic facts",
        timeout_s=180,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/infra/test_storage_records.py",
            "tests/infra/test_archive_scenarios.py",
            "tests/infra/test_json_contracts.py",
        ),
        path_targets=("verification-fixture-substrate",),
        artifact_targets=("archive_scenario_fixtures", "storage_record_fixtures", "json_contract_helpers"),
        operation_targets=("seed-archive-scenarios", "build-storage-record-fixtures"),
        tags=("contract", "fixtures", "semantic-precision"),
    ),
    "query-routing": LaneEntry(
        name="query-routing",
        description="Query-first CLI route planning, integration, and streamed read checks",
        timeout_s=240,
        category="contract",
        execution=pytest_execution("-q", "-n", "0", "-m", "query_routing"),
    ),
    "demo-visual": LaneEntry(
        name="demo-visual",
        description="Deterministic demo seed/verify commands plus reader visual DOM evidence",
        timeout_s=300,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_demo_command.py",
            "tests/unit/demo/test_demo_seed_verify.py",
            "tests/visual",
        ),
        operation_targets=("cli.help", "seed-demo-archive", "verify-demo-archive", "reader-visual-dom"),
        tags=("contract", "demo", "visual"),
    ),
    "pipeline-probe-chatgpt": LaneEntry(
        name="pipeline-probe-chatgpt",
        description="Synthetic ChatGPT parse-stage pipeline probe under explicit runtime and RSS budgets",
        timeout_s=180,
        category="contract",
        execution=pipeline_probe_execution(
            PipelineProbeRequest(
                stage="parse",
                corpus_request=CorpusRequest(providers=("chatgpt",), count=5, messages_min=4, messages_max=12, seed=42),
                max_total_ms=10000,
                max_peak_rss_mb=512,
            )
        ),
        assertion=AssertionSpec(
            stdout_min_lines=3,
            classification_override=AssertionClass.SMOKE_PROCESS,
        ),
    ),
    "semantic-stack": LaneEntry(
        name="semantic-stack",
        description="Unified harmonization, semantic facts/profile convergence, and contract inventory coverage",
        timeout_s=360,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/core/test_semantic_facts.py",
            "tests/unit/core/test_schema_semantic_inference.py",
            "tests/unit/cli/test_check.py",
            "tests/unit/core/test_session_semantics.py",
        ),
    ),
    "schema-list-contract": LaneEntry(
        name="schema-list-contract",
        description="Devtools schema package catalog list surface and runtime projection coverage",
        timeout_s=120,
        category="contract",
        execution=devtools_execution("lab schema list", "--json"),
        tags=("contract", "schema", "devtools"),
    ),
    "schema-explain-contract": LaneEntry(
        name="schema-explain-contract",
        description="Devtools schema package explanation surface and runtime projection coverage",
        timeout_s=120,
        category="contract",
        execution=devtools_execution("lab schema explain", "--provider", "chatgpt", "--json"),
        tags=("contract", "schema", "devtools"),
    ),
    "source-provider-fidelity": LaneEntry(
        name="source-provider-fidelity",
        description="Source traversal, Drive/runtime source boundaries, parser decoding, and provider-ingest fidelity",
        timeout_s=420,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/sources/test_drive_ops.py",
            "tests/unit/sources/test_source_laws.py",
            "tests/unit/sources/test_acquisition_encoding.py",
            "tests/unit/storage/test_parse_tracking.py",
            "tests/unit/pipeline/test_ingestion_chaos.py",
            "tests/integration/test_security.py",
        ),
        path_targets=("source-acquisition-loop",),
        artifact_targets=(
            "configured_sources",
            "source_payload_stream",
            "raw_validation_state",
            "artifact_observation_rows",
        ),
        operation_targets=("acquire-raw-sessions",),
        tags=("contract", "sources", "acquisition"),
    ),
    "maintenance-workflows": LaneEntry(
        name="maintenance-workflows",
        description="Health, maintenance selection, cache/live provenance, and machine output",
        timeout_s=480,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/core/test_health_core.py",
            "tests/unit/storage/test_fts5.py",
            "tests/unit/cli/test_check.py",
            "tests/unit/cli/test_source_selection_helpers.py",
            "tests/unit/cli/test_deterministic_output.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/integration/test_health.py",
        ),
        tags=("contract", "maintenance"),
    ),
    "archive-data-insights": LaneEntry(
        name="archive-data-insights",
        description="Archive insights, consumer contracts, grouped stats, and readiness/debt surfaces",
        timeout_s=600,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/unit/cli/test_query_verbs_runtime.py",
            "tests/unit/cli/test_check.py",
            "tests/unit/cli/test_click_app.py",
            "tests/unit/core/test_health_core.py",
            "tests/integration/test_health.py",
        ),
    ),
    "semantic-insight-normalization": LaneEntry(
        name="semantic-insight-normalization",
        description="Semantic/session insight normalization, operator/toolchain narrowing, schema contracts, and provider parser cleanup",
        timeout_s=900,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/core/test_repo_identity.py",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/unit/cli/test_check.py",
            "tests/unit/core/test_schema_registry.py",
            "tests/unit/core/test_schema_generation.py",
            "tests/unit/core/test_operator_models.py",
            "tests/integration/test_schema_operator_workflow.py",
            "tests/unit/storage/test_search_misc.py",
            "tests/unit/sources/test_parsers_base.py",
            "tests/unit/sources/test_parsers_drive.py",
            "tests/unit/devtools/test_validation_lanes.py",
        ),
        assertion=AssertionSpec(
            classification_override=AssertionClass.SMOKE_PROCESS,
        ),
    ),
    "retrieval-checks": LaneEntry(
        name="retrieval-checks",
        description="Action-aware query truth, grouped retrieval stats, archive readiness, and MCP retrieval payload coverage",
        timeout_s=480,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_query_verbs_runtime.py",
            "tests/unit/cli/test_query_exec_laws.py",
            "tests/unit/storage/test_store_ops.py",
            "tests/unit/core/test_filters_props.py",
            "tests/unit/core/test_health_core.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/unit/cli/test_source_selection_helpers.py",
        ),
        path_targets=("session-query-loop", "message-fts-readiness-loop"),
        artifact_targets=("message_fts", "session_query_results", "archive_readiness"),
        operation_targets=("query-sessions", "project-archive-readiness"),
        tags=("contract", "retrieval", "readiness"),
    ),
    "embeddings-coverage": LaneEntry(
        name="embeddings-coverage",
        description="Embedding coverage/readiness stats, readiness exposure, and embed command contracts",
        timeout_s=300,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_embed.py",
            "tests/unit/storage/test_embedding_stats.py",
            "tests/unit/core/test_health_core.py",
            "tests/unit/cli/test_source_selection_helpers.py",
            "tests/unit/mcp/test_tool_contracts.py",
        ),
        path_targets=("embedding-materialization-loop", "embedding-status-query-loop", "retrieval-band-readiness-loop"),
        artifact_targets=(
            "archive_session_rows",
            "embedding_metadata_rows",
            "embedding_status_rows",
            "message_embedding_vectors",
            "retrieval_band_readiness",
            "embedding_status_results",
        ),
        operation_targets=(
            "materialize-transcript-embeddings",
            "project-retrieval-band-readiness",
            "query-embedding-status",
        ),
        tags=("contract", "embeddings", "retrieval"),
    ),
    "evidence-tier-contracts": LaneEntry(
        name="evidence-tier-contracts",
        description="Explicit evidence-tier insight contracts, chronology fields, and evidence payload/query surfaces",
        timeout_s=420,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/storage/test_store_ops.py",
            "tests/unit/pipeline/test_prepare_semantic.py",
        ),
    ),
    "inference-tier-contracts": LaneEntry(
        name="inference-tier-contracts",
        description="Inference-tier work-event/phase/profile contracts with confidence/provenance-bearing semantic payloads",
        timeout_s=420,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/unit/pipeline/test_prepare_semantic.py",
        ),
    ),
    "mixed-consumer-contracts": LaneEntry(
        name="mixed-consumer-contracts",
        description="CLI, facade, MCP, and readiness surfaces consuming the same evidence/inference insight model",
        timeout_s=480,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/unit/cli/test_check.py",
            "tests/integration/test_health.py",
        ),
    ),
    "retrieval-band-readiness": LaneEntry(
        name="retrieval-band-readiness",
        description="Transcript/evidence/inference retrieval-band readiness, embedding stats, and readiness exposure",
        timeout_s=420,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_embed.py",
            "tests/unit/storage/test_embedding_stats.py",
            "tests/unit/core/test_health_core.py",
            "tests/unit/cli/test_check.py",
            "tests/unit/mcp/test_tool_contracts.py",
        ),
        path_targets=("embedding-status-query-loop", "retrieval-band-readiness-loop", "message-fts-readiness-loop"),
        artifact_targets=(
            "embedding_metadata_rows",
            "embedding_status_rows",
            "message_embedding_vectors",
            "retrieval_band_readiness",
            "embedding_status_results",
            "archive_readiness",
        ),
        operation_targets=("project-retrieval-band-readiness", "query-embedding-status", "project-archive-readiness"),
        tags=("contract", "retrieval", "embeddings", "readiness"),
    ),
    "heuristic-inference-contracts": LaneEntry(
        name="heuristic-inference-contracts",
        description="Heuristic session/work/phase contract hardening with explicit supporting metadata and consumer parity",
        timeout_s=600,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/core/test_semantic_facts.py",
            "tests/unit/pipeline/test_prepare_semantic.py",
            "tests/unit/core/test_health_core.py",
        ),
    ),
    "probabilistic-enrichment-contracts": LaneEntry(
        name="probabilistic-enrichment-contracts",
        description="Session-enrichment contracts across CLI, facade, MCP, storage, and retrieval-band status",
        timeout_s=720,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/core/test_facade_api.py",
            "tests/unit/mcp/test_tool_contracts.py",
            "tests/unit/storage/test_embedding_stats.py",
            "tests/unit/storage/test_store_ops.py",
            "tests/unit/core/test_health_core.py",
        ),
    ),
    "cleanup-contracts": LaneEntry(
        name="cleanup-contracts",
        description="Cleanup lineage, readiness/debt views, and maintenance workflow coverage",
        timeout_s=900,
        category="contract",
        execution=pytest_execution(
            "-q",
            "-n",
            "0",
            "tests/unit/cli/test_insights.py",
            "tests/unit/cli/test_check.py",
            "tests/unit/core/test_health_core.py",
            "tests/integration/test_health.py",
        ),
    ),
    "tui": LaneEntry(
        name="tui",
        description="Textual dashboard screens and interaction-state coverage",
        timeout_s=240,
        category="contract",
        execution=pytest_execution("-q", "-n", "0", "-m", "tui"),
    ),
    "chaos": LaneEntry(
        name="chaos",
        description="Hostility, interruption, and chronology integration coverage",
        timeout_s=900,
        category="contract",
        execution=pytest_execution("-q", "-n", "0", "-m", "chaos"),
    ),
    "scale-fast": LaneEntry(
        name="scale-fast",
        description="Fast storage scale budgets",
        timeout_s=120,
        category="contract",
        execution=pytest_execution("-v", "tests/unit/storage/test_scale.py", "-x", "--timeout=30"),
    ),
    "scale-slow": LaneEntry(
        name="scale-slow",
        description="Slow local storage scale budgets",
        timeout_s=360,
        category="contract",
        execution=pytest_execution("-v", "-m", "slow", "tests/unit/storage/", "--timeout=120"),
    ),
    "long-haul-small": LaneEntry(
        name="long-haul-small",
        description="Small reproducible benchmark/long-haul campaign",
        timeout_s=1800,
        category="contract",
        execution=devtools_execution("bench synthetic", "--scale", "small"),
    ),
}

# ---------------------------------------------------------------------------
# Composite lanes (flattened from former validation_family_models DSL +
# standalone composite declarations)
# ---------------------------------------------------------------------------

_COMPOSITE_ORIGIN = "authored.validation-lane.composite"

COMPOSITE_LANES: dict[str, LaneEntry] = {
    # --- Family-generated composites ---
    "domain-read-model-contracts": LaneEntry(
        name="domain-read-model-contracts",
        description="Local domain read-model lane for analytics/insights, consumer contracts, and debt views",
        timeout_s=2400,
        category="composite",
        family="domain-read-model",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("archive-data-insights", "maintenance-workflows"),
    ),
    "domain-read-model-live": LaneEntry(
        name="domain-read-model-live",
        description="Bounded live archive lane for insights, analytics/debt views, and maintenance checks",
        timeout_s=1800,
        category="composite",
        family="domain-read-model",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "live-insights-small", "live-insights-coverage-provider", "live-insights-debt", "live-maintenance-small"
        ),
    ),
    "domain-read-model-hardening": LaneEntry(
        name="domain-read-model-hardening",
        description="Full domain read-model lane with local contracts and bounded live checks",
        timeout_s=3600,
        category="composite",
        family="domain-read-model",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("domain-read-model-contracts", "domain-read-model-live"),
    ),
    "runtime-substrate-contracts": LaneEntry(
        name="runtime-substrate-contracts",
        description="Local runtime-substrate lane across query, semantic checks, archive insights, and maintenance workflows",
        timeout_s=2400,
        category="composite",
        family="runtime-substrate",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "query-routing", "semantic-stack", "maintenance-workflows", "archive-data-insights"
        ),
    ),
    "runtime-substrate-live": LaneEntry(
        name="runtime-substrate-live",
        description="Bounded live archive lane for runtime-substrate checks, maintenance checks, and memory budgets",
        timeout_s=1800,
        category="composite",
        family="runtime-substrate",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("live-archive-small", "live-maintenance-small", "memory-budget"),
    ),
    "runtime-substrate-hardening": LaneEntry(
        name="runtime-substrate-hardening",
        description="Full runtime-substrate validation lane covering local contracts plus bounded live archive checks",
        timeout_s=3600,
        category="composite",
        family="runtime-substrate",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("runtime-substrate-contracts", "runtime-substrate-live"),
    ),
    "evidence-contracts": LaneEntry(
        name="evidence-contracts",
        description="Evidence/inference contract lane across explicit evidence, inferred semantics, consumer parity, and retrieval readiness",
        timeout_s=2400,
        category="composite",
        family="evidence",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "evidence-tier-contracts",
            "inference-tier-contracts",
            "mixed-consumer-contracts",
            "retrieval-band-readiness",
        ),
    ),
    "evidence-live": LaneEntry(
        name="evidence-live",
        description="Bounded live archive lane for tiered insight views, live repair, health, and retrieval-band budgets",
        timeout_s=2400,
        category="composite",
        family="evidence",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "live-session-insight-repair",
            "live-insights-status",
            "live-insights-profiles-evidence",
            "live-insights-profiles-inference",
            "live-insights-work-events",
            "live-insights-phases",
            "live-embed-stats",
            "live-readiness-json",
            "maintenance-memory-budget",
        ),
    ),
    "evidence-hardening": LaneEntry(
        name="evidence-hardening",
        description="Full evidence lane with contracts and bounded live checks",
        timeout_s=4800,
        category="composite",
        family="evidence",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("evidence-contracts", "evidence-live"),
    ),
    "semantic-insight-live": LaneEntry(
        name="semantic-insight-live",
        description="Bounded live archive lane for normalized insights, maintenance preview, and memory budgets",
        timeout_s=1800,
        category="composite",
        family="semantic-insight",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "live-insights-status",
            "live-insights-tags",
            "live-insights-coverage-day",
            "live-insights-debt",
            "live-maintenance-small",
        ),
    ),
    "semantic-insight-hardening": LaneEntry(
        name="semantic-insight-hardening",
        description="Full semantic-insight normalization and toolchain convergence lane",
        timeout_s=3600,
        category="composite",
        family="semantic-insight",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("semantic-insight-normalization", "semantic-insight-live"),
    ),
    "probabilistic-enrichment-live": LaneEntry(
        name="probabilistic-enrichment-live",
        description="Bounded live archive lane for enrichment insights, retrieval bands, and readiness surfaces",
        timeout_s=2400,
        category="composite",
        family="probabilistic-enrichment",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "live-session-insight-repair",
            "live-insights-status",
            "live-insights-profiles-inference",
            "live-embed-stats",
            "live-readiness-json",
            "memory-budget",
        ),
    ),
    "probabilistic-enrichment-cleanup-live": LaneEntry(
        name="probabilistic-enrichment-cleanup-live",
        description="Bounded live archive lane for cleanup/debt preview and maintenance budgets",
        timeout_s=2400,
        category="composite",
        family="probabilistic-enrichment",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("live-insights-debt", "live-maintenance-preview", "maintenance-memory-budget"),
    ),
    "probabilistic-enrichment-hardening": LaneEntry(
        name="probabilistic-enrichment-hardening",
        description="Full probabilistic-enrichment and cleanup lane",
        timeout_s=5400,
        category="composite",
        family="probabilistic-enrichment",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "heuristic-inference-contracts",
            "probabilistic-enrichment-contracts",
            "cleanup-contracts",
            "probabilistic-enrichment-live",
            "probabilistic-enrichment-cleanup-live",
        ),
    ),
    # --- Standalone composites ---
    "source-runtime-alignment": LaneEntry(
        name="source-runtime-alignment",
        description="Local source/provider fidelity plus runtime maintenance alignment",
        timeout_s=1800,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("source-provider-fidelity", "maintenance-workflows"),
    ),
    "live-archive-small": LaneEntry(
        name="live-archive-small",
        description="Bounded live archive retrieval/readiness/health dogfood lane",
        timeout_s=480,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "live-embed-stats", "live-retrieval-checks", "live-insights-status", "live-readiness-json"
        ),
    ),
    "live-insights-small": LaneEntry(
        name="live-insights-small",
        description="Bounded live archive insight and grouped-stats lane",
        timeout_s=480,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("live-insights-status", "live-insights-tags", "live-project-stats"),
    ),
    "live-archive-slow": LaneEntry(
        name="live-archive-slow",
        description="Broader live archive dogfood lane including retrieval/readiness and live QA exercises",
        timeout_s=2400,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("live-archive-small", "live-exercises"),
    ),
    "archive-intelligence": LaneEntry(
        name="archive-intelligence",
        description="Local archive-intelligence closure lane for retrieval and embedding readiness",
        timeout_s=1800,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("retrieval-checks", "embeddings-coverage"),
    ),
    "archive-data-insights-live": LaneEntry(
        name="archive-data-insights-live",
        description="Local insight-contract lane plus bounded live archive insight checks",
        timeout_s=1800,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("archive-data-insights", "live-insights-small"),
    ),
    "live-maintenance-small": LaneEntry(
        name="live-maintenance-small",
        description="Bounded live archive lane for health, maintenance preview, and maintenance memory budget",
        timeout_s=720,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("live-readiness-json", "live-maintenance-preview", "maintenance-memory-budget"),
    ),
    "scale-stretch": LaneEntry(
        name="scale-stretch",
        description="Combined fast and slow storage scale budgets",
        timeout_s=600,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("scale-fast", "scale-slow"),
    ),
    "frontier-local": LaneEntry(
        name="frontier-local",
        description="Non-live local closure lane for machine/query/semantic/TUI/chaos validation",
        timeout_s=1500,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution(
            "machine-contract",
            "query-routing",
            "demo-visual",
            "semantic-stack",
            "tui",
            "chaos",
        ),
    ),
    "frontier-extended": LaneEntry(
        name="frontier-extended",
        description="Local closure lane plus fast scale and small long-haul campaign",
        timeout_s=3600,
        category="composite",
        origin=_COMPOSITE_ORIGIN,
        execution=composite_execution("frontier-local", "pipeline-probe-chatgpt", "scale-fast", "long-haul-small"),
    ),
}

__all__ = ["COMPOSITE_LANES", "CONTRACT_LANES"]
