"""Composite validation lane declarations."""

from __future__ import annotations

from functools import partial

from devtools.validation_lane_base import composite_lane as _composite_lane

composite_lane = partial(_composite_lane, category="composite")

COMPOSITE_LANES = {
    "source-runtime-alignment": composite_lane(
        "source-runtime-alignment",
        "Local source/provider fidelity plus runtime maintenance alignment",
        1800,
        "source-provider-fidelity",
        "maintenance-workflows",
    ),
    "live-archive-small": composite_lane(
        "live-archive-small",
        "Bounded live archive retrieval/readiness/health dogfood lane",
        480,
        "live-embed-stats",
        "live-retrieval-checks",
        "live-products-status",
        "live-health-json",
    ),
    "live-products-small": composite_lane(
        "live-products-small",
        "Bounded live archive product and grouped-stats lane",
        480,
        "live-products-status",
        "live-products-tags",
        "live-project-stats",
    ),
    "live-archive-slow": composite_lane(
        "live-archive-slow",
        "Broader live archive dogfood lane including retrieval/readiness and live QA exercises",
        2400,
        "live-archive-small",
        "live-exercises",
    ),
    "archive-intelligence": composite_lane(
        "archive-intelligence",
        "Local archive-intelligence closure lane for retrieval and embedding readiness",
        1800,
        "retrieval-checks",
        "embeddings-coverage",
    ),
    "archive-data-products-live": composite_lane(
        "archive-data-products-live",
        "Local product-contract lane plus bounded live archive product checks",
        1800,
        "archive-data-products",
        "live-products-small",
    ),
    "live-maintenance-small": composite_lane(
        "live-maintenance-small",
        "Bounded live archive lane for health, maintenance preview, and maintenance memory budget",
        720,
        "live-health-json",
        "live-maintenance-preview",
        "maintenance-memory-budget",
    ),
    "domain-read-model-contracts": composite_lane(
        "domain-read-model-contracts",
        "Local domain read-model lane for analytics/products, consumer contracts, and debt views",
        2400,
        "archive-data-products",
        "maintenance-workflows",
    ),
    "domain-read-model-live": composite_lane(
        "domain-read-model-live",
        "Bounded live archive lane for products, analytics/debt views, and maintenance checks",
        1800,
        "live-products-small",
        "live-products-analytics",
        "live-products-debt",
        "live-maintenance-small",
    ),
    "domain-read-model-hardening": composite_lane(
        "domain-read-model-hardening",
        "Full domain read-model lane with local contracts and bounded live checks",
        3600,
        "domain-read-model-contracts",
        "domain-read-model-live",
    ),
    "runtime-substrate-contracts": composite_lane(
        "runtime-substrate-contracts",
        "Local runtime-substrate lane across query, semantic checks, archive products, and maintenance workflows",
        2400,
        "query-routing",
        "semantic-stack",
        "maintenance-workflows",
        "archive-data-products",
    ),
    "runtime-substrate-live": composite_lane(
        "runtime-substrate-live",
        "Bounded live archive lane for runtime-substrate checks, maintenance checks, and memory budgets",
        1800,
        "live-archive-small",
        "live-maintenance-small",
        "memory-budget",
    ),
    "runtime-substrate-hardening": composite_lane(
        "runtime-substrate-hardening",
        "Full runtime-substrate validation lane covering local contracts plus bounded live archive checks",
        3600,
        "runtime-substrate-contracts",
        "runtime-substrate-live",
    ),
    "semantic-product-live": composite_lane(
        "semantic-product-live",
        "Bounded live archive lane for normalized products, maintenance preview, and memory budgets",
        1800,
        "live-products-status",
        "live-products-tags",
        "live-products-day-summaries",
        "live-products-debt",
        "live-maintenance-small",
    ),
    "semantic-product-hardening": composite_lane(
        "semantic-product-hardening",
        "Full semantic-product normalization and toolchain convergence lane",
        3600,
        "semantic-product-normalization",
        "semantic-product-live",
    ),
    "evidence-contracts": composite_lane(
        "evidence-contracts",
        "Evidence/inference contract lane across explicit evidence, inferred semantics, consumer parity, and retrieval readiness",
        2400,
        "evidence-tier-contracts",
        "inference-tier-contracts",
        "mixed-consumer-contracts",
        "retrieval-band-readiness",
    ),
    "evidence-live": composite_lane(
        "evidence-live",
        "Bounded live archive lane for tiered product views, live migration, health, and retrieval-band budgets",
        2400,
        "live-session-product-repair",
        "live-products-status",
        "live-products-profiles-evidence",
        "live-products-profiles-inference",
        "live-products-work-events",
        "live-products-phases",
        "live-embed-stats",
        "live-health-json",
        "maintenance-memory-budget",
    ),
    "evidence-hardening": composite_lane(
        "evidence-hardening",
        "Full evidence lane with contracts and bounded live checks",
        4800,
        "evidence-contracts",
        "evidence-live",
    ),
    "probabilistic-enrichment-live": composite_lane(
        "probabilistic-enrichment-live",
        "Bounded live archive lane for enrichment products, retrieval bands, and health surfaces",
        2400,
        "live-session-product-repair",
        "live-products-status",
        "live-products-profiles-inference",
        "live-products-enrichments",
        "live-embed-stats",
        "live-health-json",
        "memory-budget",
    ),
    "cleanup-live": composite_lane(
        "cleanup-live",
        "Bounded live archive lane for cleanup/debt preview and maintenance budgets",
        2400,
        "live-products-debt",
        "live-maintenance-preview",
        "maintenance-memory-budget",
    ),
    "probabilistic-enrichment-hardening": composite_lane(
        "probabilistic-enrichment-hardening",
        "Full probabilistic-enrichment and cleanup lane",
        5400,
        "heuristic-inference-contracts",
        "probabilistic-enrichment-contracts",
        "cleanup-contracts",
        "probabilistic-enrichment-live",
        "cleanup-live",
    ),
    "frontier-local": composite_lane(
        "frontier-local",
        "Non-live local closure lane for machine/query/semantic/TUI/chaos validation",
        1500,
        "machine-contract",
        "query-routing",
        "showcase-baselines",
        "semantic-stack",
        "tui",
        "chaos",
    ),
    "frontier-extended": composite_lane(
        "frontier-extended",
        "Local closure lane plus fast scale and small long-haul campaign",
        3600,
        "frontier-local",
        "pipeline-probe-chatgpt",
        "scale-fast",
        "long-haul-small",
    ),
}


__all__ = ["COMPOSITE_LANES"]
