"""Local/test-focused validation lane declarations."""

from __future__ import annotations

from functools import partial

from devtools.validation_lane_base import devtools_lane as _devtools_lane
from devtools.validation_lane_base import pipeline_probe_lane as _pipeline_probe_lane
from devtools.validation_lane_base import pytest_lane as _pytest_lane
from polylogue.scenarios import CorpusRequest

devtools_lane = partial(_devtools_lane, category="contract")
pipeline_probe_lane = partial(_pipeline_probe_lane, category="contract")
pytest_lane = partial(_pytest_lane, category="contract")

CONTRACT_LANES = {
    "machine-contract": pytest_lane(
        "machine-contract",
        "Root CLI JSON success/failure envelopes and runtime-health machine surfaces",
        180,
        "-q",
        "-n",
        "0",
        "-m",
        "machine_contract",
        operation_targets=("cli.json-contract",),
        tags=("contract", "json", "cli"),
    ),
    "query-routing": pytest_lane(
        "query-routing",
        "Query-first CLI route planning, integration, and streamed read checks",
        240,
        "-q",
        "-n",
        "0",
        "-m",
        "query_routing",
    ),
    "showcase-baselines": devtools_lane(
        "showcase-baselines",
        "Registry-derived tier-0 CLI help/source showcase baselines",
        180,
        "verify-showcase",
        operation_targets=("cli.help",),
        tags=("contract", "showcase", "help"),
    ),
    "pipeline-probe-chatgpt": pipeline_probe_lane(
        "pipeline-probe-chatgpt",
        "Synthetic ChatGPT parse-stage pipeline probe under explicit runtime and RSS budgets",
        180,
        stage="parse",
        corpus_request=CorpusRequest(providers=("chatgpt",), count=5, messages_min=4, messages_max=12, seed=42),
        max_total_ms=10000,
        max_peak_rss_mb=512,
    ),
    "semantic-stack": pytest_lane(
        "semantic-stack",
        "Unified harmonization, semantic facts/profile convergence, and contract inventory coverage",
        360,
        "-q",
        "-n",
        "0",
        "tests/unit/core/test_semantic_facts.py",
        "tests/unit/core/test_filters_schemas.py",
        "tests/unit/sources/test_unified_semantic_laws.py",
        "tests/integration/test_extraction_db.py",
        "tests/unit/core/test_schema_semantic_inference.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/showcase/test_qa_runner.py",
        "tests/unit/showcase/test_report.py",
        "tests/unit/core/test_conversation_semantics.py",
    ),
    "source-provider-fidelity": pytest_lane(
        "source-provider-fidelity",
        "Source traversal, Drive/runtime source boundaries, parser decoding, and provider-ingest fidelity",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/sources/test_drive_ops.py",
        "tests/unit/sources/test_source_laws.py",
        "tests/unit/sources/test_acquisition_encoding.py",
        "tests/unit/storage/test_parse_tracking.py",
        "tests/unit/pipeline/test_ingestion_chaos.py",
        "tests/integration/test_security.py",
        path_targets=("source-acquisition-loop",),
        artifact_targets=("configured_sources", "source_payload_stream", "raw_validation_state", "artifact_observation_rows"),
        operation_targets=("acquire-raw-conversations",),
        tags=("contract", "sources", "acquisition"),
    ),
    "maintenance-workflows": pytest_lane(
        "maintenance-workflows",
        "Health, maintenance selection, cache/live provenance, publication summaries, and machine output",
        480,
        "-q",
        "-n",
        "0",
        "tests/unit/core/test_health_core.py",
        "tests/unit/storage/test_fts5.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/cli/test_source_selection_helpers.py",
        "tests/unit/cli/test_deterministic_output.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/site/test_builder.py",
        "tests/unit/cli/test_site.py",
        "tests/integration/test_health.py",
        path_targets=("site-publication-loop",),
        artifact_targets=(
            "conversation_render_projection",
            "site_conversation_pages",
            "site_publication_manifest",
            "publication_records",
        ),
        operation_targets=("publish-site",),
        tags=("contract", "maintenance", "publication"),
    ),
    "archive-data-products": pytest_lane(
        "archive-data-products",
        "Archive products, consumer contracts, grouped stats, and health/debt surfaces",
        600,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_query_exec.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/cli/test_click_app.py",
        "tests/unit/core/test_health_core.py",
        "tests/integration/test_health.py",
    ),
    "semantic-product-normalization": pytest_lane(
        "semantic-product-normalization",
        "Semantic/session product normalization, operator/toolchain narrowing, schema contracts, and provider parser cleanup",
        900,
        "-q",
        "-n",
        "0",
        "tests/unit/core/test_repo_identity.py",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/core/test_schema_registry.py",
        "tests/unit/core/test_schema_generation.py",
        "tests/unit/core/test_operator_models.py",
        "tests/integration/test_schema_operator_workflow.py",
        "tests/unit/storage/test_search_misc.py",
        "tests/unit/sources/test_parsers_base.py",
        "tests/unit/sources/test_parsers_drive.py",
        "tests/unit/devtools/test_validation_lanes.py",
    ),
    "retrieval-checks": pytest_lane(
        "retrieval-checks",
        "Action-aware query truth, grouped retrieval stats, archive health, and MCP retrieval payload coverage",
        480,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_query_exec.py",
        "tests/unit/cli/test_query_exec_laws.py",
        "tests/unit/storage/test_store_ops.py",
        "tests/unit/core/test_filters_props.py",
        "tests/unit/core/test_health_core.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_source_selection_helpers.py",
        path_targets=("conversation-query-loop", "message-fts-health-loop"),
        artifact_targets=("message_fts", "conversation_query_results", "archive_health"),
        operation_targets=("query-conversations", "project-archive-health"),
        tags=("contract", "retrieval", "health"),
    ),
    "embeddings-coverage": pytest_lane(
        "embeddings-coverage",
        "Embedding coverage/readiness stats, health exposure, and embed command contracts",
        300,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_embed.py",
        "tests/unit/storage/test_embedding_stats.py",
        "tests/unit/core/test_health_core.py",
        "tests/unit/cli/test_source_selection_helpers.py",
        "tests/unit/mcp/test_tool_contracts.py",
        path_targets=("embedding-materialization-loop", "embedding-status-query-loop", "retrieval-band-health-loop"),
        artifact_targets=(
            "archive_conversation_rows",
            "embedding_metadata_rows",
            "embedding_status_rows",
            "message_embedding_vectors",
            "retrieval_band_health",
            "embedding_status_results",
        ),
        operation_targets=(
            "materialize-transcript-embeddings",
            "project-retrieval-band-health",
            "query-embedding-status",
        ),
        tags=("contract", "embeddings", "retrieval"),
    ),
    "evidence-tier-contracts": pytest_lane(
        "evidence-tier-contracts",
        "Explicit evidence-tier product contracts, chronology fields, and evidence payload/query surfaces",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/storage/test_backend.py",
        "tests/unit/pipeline/test_prepare_semantic.py",
    ),
    "inference-tier-contracts": pytest_lane(
        "inference-tier-contracts",
        "Inference-tier work-event/phase/profile contracts with confidence/provenance-bearing semantic payloads",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/pipeline/test_prepare_semantic.py",
    ),
    "mixed-consumer-contracts": pytest_lane(
        "mixed-consumer-contracts",
        "CLI, facade, MCP, and health surfaces consuming the same evidence/inference product model",
        480,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/cli/test_check.py",
        "tests/integration/test_health.py",
    ),
    "retrieval-band-readiness": pytest_lane(
        "retrieval-band-readiness",
        "Transcript/evidence/inference retrieval-band readiness, embedding stats, and health exposure",
        420,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_embed.py",
        "tests/unit/storage/test_embedding_stats.py",
        "tests/unit/core/test_health_core.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/mcp/test_tool_contracts.py",
        path_targets=("embedding-status-query-loop", "retrieval-band-health-loop", "message-fts-health-loop"),
        artifact_targets=(
            "embedding_metadata_rows",
            "embedding_status_rows",
            "message_embedding_vectors",
            "retrieval_band_health",
            "embedding_status_results",
            "archive_health",
        ),
        operation_targets=("project-retrieval-band-health", "query-embedding-status", "project-archive-health"),
        tags=("contract", "retrieval", "embeddings", "health"),
    ),
    "heuristic-inference-contracts": pytest_lane(
        "heuristic-inference-contracts",
        "Heuristic session/work/phase contract hardening with explicit supporting metadata and consumer parity",
        600,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/core/test_semantic_facts.py",
        "tests/unit/pipeline/test_prepare_semantic.py",
        "tests/unit/core/test_health_core.py",
    ),
    "probabilistic-enrichment-contracts": pytest_lane(
        "probabilistic-enrichment-contracts",
        "Session-enrichment contracts across CLI, facade, MCP, storage, and retrieval-band status",
        720,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/core/test_facade_api.py",
        "tests/unit/mcp/test_tool_contracts.py",
        "tests/unit/storage/test_embedding_stats.py",
        "tests/unit/storage/test_backend.py",
        "tests/unit/core/test_health_core.py",
    ),
    "cleanup-contracts": pytest_lane(
        "cleanup-contracts",
        "Cleanup lineage, health/debt views, and maintenance workflow coverage",
        900,
        "-q",
        "-n",
        "0",
        "tests/unit/cli/test_products.py",
        "tests/unit/cli/test_check.py",
        "tests/unit/core/test_health_core.py",
        "tests/integration/test_health.py",
    ),
    "tui": pytest_lane(
        "tui",
        "Textual dashboard screens and interaction-state coverage",
        240,
        "-q",
        "-n",
        "0",
        "-m",
        "tui",
    ),
    "chaos": pytest_lane(
        "chaos",
        "Hostility, interruption, and chronology integration coverage",
        900,
        "-q",
        "-n",
        "0",
        "-m",
        "chaos",
    ),
    "scale-fast": pytest_lane(
        "scale-fast",
        "Fast storage scale budgets",
        120,
        "-v",
        "tests/unit/storage/test_scale.py",
        "-x",
        "--timeout=30",
    ),
    "scale-slow": pytest_lane(
        "scale-slow",
        "Slow local storage scale budgets",
        360,
        "-v",
        "-m",
        "slow",
        "tests/unit/storage/",
        "--timeout=120",
    ),
    "long-haul-small": devtools_lane(
        "long-haul-small",
        "Small reproducible benchmark/long-haul campaign",
        1800,
        "run-benchmark-campaigns",
        "--scale",
        "small",
    ),
}


__all__ = ["CONTRACT_LANES"]
