"""Storage-layer materializer and schema version constants."""

from __future__ import annotations

MAX_ATTACHMENT_SIZE = 1024 * 1024 * 1024 * 1024
MAX_RAW_CONTENT_SIZE = 900 * 1024 * 1024
ACTION_EVENT_MATERIALIZER_VERSION = 1
SESSION_PRODUCT_MATERIALIZER_VERSION = 3
SESSION_INFERENCE_VERSION = 1
SESSION_INFERENCE_FAMILY = "heuristic_session_semantics"
SESSION_ENRICHMENT_VERSION = 1
SESSION_ENRICHMENT_FAMILY = "scored_session_enrichment"


__all__ = [
    "ACTION_EVENT_MATERIALIZER_VERSION",
    "MAX_ATTACHMENT_SIZE",
    "MAX_RAW_CONTENT_SIZE",
    "SESSION_ENRICHMENT_FAMILY",
    "SESSION_ENRICHMENT_VERSION",
    "SESSION_INFERENCE_FAMILY",
    "SESSION_INFERENCE_VERSION",
    "SESSION_PRODUCT_MATERIALIZER_VERSION",
]
