"""Storage-layer materializer and schema version constants."""

from __future__ import annotations

ACTION_EVENT_MATERIALIZER_VERSION = 1
SESSION_PRODUCT_MATERIALIZER_VERSION = 4
SESSION_INFERENCE_VERSION = 1
SESSION_INFERENCE_FAMILY = "heuristic_session_semantics"
SESSION_ENRICHMENT_VERSION = 1
SESSION_ENRICHMENT_FAMILY = "scored_session_enrichment"


__all__ = [
    "ACTION_EVENT_MATERIALIZER_VERSION",
    "SESSION_ENRICHMENT_FAMILY",
    "SESSION_ENRICHMENT_VERSION",
    "SESSION_INFERENCE_FAMILY",
    "SESSION_INFERENCE_VERSION",
    "SESSION_PRODUCT_MATERIALIZER_VERSION",
]
