#!/usr/bin/env python3
"""Timestamp-aware guard around bd's post-checkout/post-merge auto-reimport.

bd's own post-checkout/post-merge hooks reimport whichever branch's
.beads/issues.jsonl just landed in the working tree, using plain upsert
semantics (no timestamp comparison -- confirmed via `bd import --help`
and empirically on 2026-07-09): a `bd close` made live-but-uncommitted in
one worktree can be silently reverted by an ordinary `git pull` in a
totally different worktree sharing the same live Dolt DB, because the
older checked-out branch's committed status for that id "wins" the
blind upsert.

This script does not replace bd's own hook logic (which may do more than
importing, and is regenerated by `bd hooks install`/upgrades). It wraps
it: snapshot every live bead's updated_at before the normal hook runs,
let the normal hook do whatever it does, snapshot again after, and for
any bead where the "before" state is strictly newer than "after" (i.e.
the reimport clobbered something newer with something older), restore
the "before" row via a targeted `bd import`.

Wired from OUTSIDE the "BEGIN/END BEADS INTEGRATION" markers in
.beads-hooks/post-checkout and .beads-hooks/post-merge, which bd's own
docs state are preserved across `bd hooks install`/upgrades.

Usage:
  bd-reimport-guard.py snapshot <hook-name>
  bd-reimport-guard.py check-and-repair <hook-name>
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def _snapshot_path(hook_name: str) -> Path:
    return Path(tempfile.gettempdir()) / f"polylogue-bd-guard-snapshot-{hook_name}.jsonl"


def _export_live_state() -> dict[str, dict]:
    """Return {id: full_row_dict} for every issue currently live.

    Uses default `bd export` filtering (excludes infra beads/memories) --
    consistently applied to both before/after snapshots, so the exclusion
    itself introduces no asymmetry.
    """
    with tempfile.NamedTemporaryFile(suffix=".jsonl", delete=False) as tf:
        path = tf.name
    try:
        subprocess.run(
            ["bd", "export", "-o", path],
            capture_output=True,
            text=True,
            timeout=30,
        )
        result: dict[str, dict] = {}
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                issue_id = row.get("id")
                if issue_id:
                    result[issue_id] = row
        return result
    finally:
        Path(path).unlink(missing_ok=True)


def cmd_snapshot(hook_name: str) -> int:
    state = _export_live_state()
    snap_path = _snapshot_path(hook_name)
    with open(snap_path, "w") as f:
        json.dump(state, f)
    return 0


def cmd_check_and_repair(hook_name: str) -> int:
    snap_path = _snapshot_path(hook_name)
    if not snap_path.exists():
        # No "before" snapshot (e.g. snapshot step failed/skipped) -- nothing
        # to compare against, so there's nothing safe to do. Not an error.
        return 0

    try:
        with open(snap_path) as f:
            before = json.load(f)
    except (json.JSONDecodeError, OSError):
        snap_path.unlink(missing_ok=True)
        return 0
    finally:
        snap_path.unlink(missing_ok=True)

    after = _export_live_state()

    to_restore: list[tuple[str, dict, str]] = []
    for issue_id, before_row in before.items():
        after_row = after.get(issue_id)
        before_ts = before_row.get("updated_at") or ""
        if after_row is None:
            # Vanished entirely across the reimport -- restore defensively.
            to_restore.append((issue_id, before_row, "vanished"))
            continue
        after_ts = after_row.get("updated_at") or ""
        if before_ts > after_ts:
            to_restore.append((issue_id, before_row, "reverted-to-older-state"))

    if not to_restore:
        return 0

    print(
        f"beads-guard: {hook_name} reimport clobbered {len(to_restore)} "
        f"issue(s) with older state -- restoring newer live values:",
        file=sys.stderr,
    )
    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as tf:
        restore_path = tf.name
        for issue_id, row, reason in to_restore:
            title = row.get("title", "")
            print(f"  {issue_id} ({reason}): {title!r}", file=sys.stderr)
            tf.write(json.dumps(row) + "\n")

    try:
        subprocess.run(
            ["bd", "import", restore_path],
            capture_output=True,
            text=True,
            timeout=30,
        )
        # Re-export so the working tree's issues.jsonl matches the restored
        # live state (avoids the restore looking like a phantom git diff).
        subprocess.run(["bd", "export"], capture_output=True, text=True, timeout=30)
    finally:
        Path(restore_path).unlink(missing_ok=True)

    return 0


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(f"usage: {argv[0]} <snapshot|check-and-repair> <hook-name>", file=sys.stderr)
        return 1
    command, hook_name = argv[1], argv[2]
    if command == "snapshot":
        return cmd_snapshot(hook_name)
    if command == "check-and-repair":
        return cmd_check_and_repair(hook_name)
    print(f"unknown command: {command}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
