// Generated by `devtools render webui-client`. Do not edit by hand.
// Source: tests/fixtures/openapi/webui-client.yaml

import {
  FetchTransport,
  iteratePages,
  type ClientTransport,
  type Page,
  type RequestOptions,
} from "./runtime.js";

export type ErrorEnvelope = {
  readonly detail?: string | null;
  readonly error: string;
};

export type Item = {
  readonly id: string;
  readonly tags: ReadonlyArray<string>;
};

export type ItemEnvelope = {
  readonly continuation?: string | null;
  readonly items: ReadonlyArray<Item>;
  readonly query_ref?: string | null;
  readonly result_ref?: string | null;
  readonly total: number;
};

export type QueryItemsParameters = {
  readonly bucket: string;
  readonly continuation?: string;
  readonly expression?: string;
  readonly limit?: number;
};
export type QueryItemsResponse = ItemEnvelope;
export type QueryItemsError = ErrorEnvelope;
export type QueryParameters = Omit<QueryItemsParameters, "bucket" | "continuation" | "expression"> & { readonly bucket: string } & { readonly expression: string };
export type QueryPage = Page<Item, ItemEnvelope>;

function isItemEnvelope(value: unknown): value is ItemEnvelope {
  return (
    typeof value === "object" &&
    value !== null &&
    Array.isArray((value as { readonly items?: unknown }).items)
  );
}

export class PolylogueClient {
  readonly #transport: ClientTransport;

  constructor(transport: ClientTransport = new FetchTransport()) {
    this.#transport = transport;
  }

  queryItems(
    parameters: QueryItemsParameters,
    options: RequestOptions = {},
  ): Promise<QueryItemsResponse> {
    return this.#transport.request<QueryItemsResponse, QueryItemsError>(
      {
        method: "GET",
        path: `/api/items/${encodeURIComponent(String(parameters.bucket))}`,
        query: {
          continuation: parameters.continuation,
          expression: parameters.expression,
          limit: parameters.limit,
        },
      },
      options,
    );
  }

  query(
    parameters: QueryParameters,
    options: RequestOptions = {},
  ): AsyncIterable<QueryPage> {
    return iteratePages<QueryPage>(async (cursor) => {
      const requestParameters =
        cursor === null ? parameters : { bucket: parameters.bucket, continuation: cursor };
      const envelope = await this.queryItems(requestParameters, options);
      if (!(isItemEnvelope(envelope))) {
        throw new TypeError("queryItems returned a non-page envelope");
      }
      const coverage = {
        kind: "qualified" as const,
        total: typeof envelope.total === "number" ? envelope.total : null,
        qualification: "page" as const,
      };
      return {
        items: envelope.items,
        cursor: envelope.continuation ?? null,
        coverage,
        queryRef: envelope.query_ref ?? null,
        resultRef: envelope.result_ref ?? null,
        envelope: envelope as ItemEnvelope,
      };
    });
  }
}
