"""Classify runtime artifacts that providers serialize as message text.

``context`` is model-visible substrate: system/developer/environment/skill
instructions that can appear in export streams but are not authored dialogue.
``protocol`` is runtime/UI transport: command wrappers, task notifications,
local command caveats, and similar control-plane payloads that may be encoded
through ordinary text channels by a provider.
"""

from __future__ import annotations

import re

from polylogue.archive.message.types import MessageType

_SYSTEM_REMINDER_PATTERN = re.compile(r"<system-reminder>.*?</system-reminder>\s*", re.DOTALL)

_CONTEXT_START_MARKERS = (
    "<environment_context>",
    "<permissions instructions>",
    "<subagent_notification>",
    "<system>",
    "<developer>",
    "Base directory for this skill:",
)

_CLAUDE_CODE_PROTOCOL_START_MARKERS = (
    "Caveat: The messages below were generated by the user while running local commands.",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "<channel-message>",
    "<command-args>",
    "<command-message>",
    "<command-name>",
    "<cross-session-message>",
    "<github-webhook-activity>",
    "<local-command-caveat>",
    "<local-command-stderr>",
    "<local-command-stdout>",
    "<new-diagnostics>",
    "<remote-review>",
    "<remote-review-progress>",
    "<task-notification>",
    "<teammate-message>",
    "<tick>",
    "<ultraplan>",
)

_CONTENTS_OF_LINE_RE = re.compile(r"^Contents of .+:", re.MULTILINE)


def strip_system_reminders(text: str) -> str:
    """Remove Claude Code system-reminder blocks from mixed message text."""
    return _SYSTEM_REMINDER_PATTERN.sub("", text).strip()


def strip_leading_system_reminders(text: str) -> str:
    """Remove only leading Claude Code system-reminder blocks."""
    remainder = text.lstrip()
    while remainder.startswith("<system-reminder>"):
        match = _SYSTEM_REMINDER_PATTERN.match(remainder)
        if match is None:
            break
        remainder = remainder[match.end() :].lstrip()
    return remainder


def classify_text_message_type(text: str | None) -> MessageType | None:
    """Classify full-message text that represents runtime context/protocol.

    Used at materialization time to persist ``message_type``, and as a
    resilience fallback at read time for pre-#839 archive rows.
    """
    if not text:
        return None

    stripped = strip_leading_system_reminders(text)
    if not stripped:
        return MessageType.CONTEXT
    if stripped.startswith(_CONTEXT_START_MARKERS):
        return MessageType.CONTEXT
    if stripped.startswith(_CLAUDE_CODE_PROTOCOL_START_MARKERS):
        return MessageType.PROTOCOL

    # Additional context heuristics beyond start-of-text markers.
    if "<system>" in stripped and "</system>" in stripped:
        return MessageType.CONTEXT
    if _CONTENTS_OF_LINE_RE.search(stripped):
        return MessageType.CONTEXT
    if stripped.startswith("<file path="):
        return MessageType.CONTEXT

    return None


__all__ = [
    "classify_text_message_type",
    "strip_leading_system_reminders",
    "strip_system_reminders",
]
