"""Classify runtime artifacts that providers serialize as message text.

``context`` is model-visible substrate: system/developer/environment/skill
instructions that can appear in export streams but are not authored dialogue.
``protocol`` is runtime/UI transport: command wrappers, task notifications,
local command caveats, and similar control-plane payloads that may be encoded
through ordinary text channels by a provider.
"""

from __future__ import annotations

import re

from polylogue.archive.message.types import MessageType
from polylogue.core.enums import BlockType, MaterialOrigin, Role

_SYSTEM_REMINDER_PATTERN = re.compile(r"<system-reminder>.*?</system-reminder>\s*", re.DOTALL)

_CONTEXT_START_MARKERS = (
    "<environment_context>",
    "<permissions instructions>",
    "<subagent_notification>",
    "<system>",
    "<developer>",
    "Base directory for this skill:",
    "# AGENTS.md instructions for ",
    "<INSTRUCTIONS>",
    "This session is being continued from a previous conversation that ran out of context.",
)

_CLAUDE_CODE_PROTOCOL_START_MARKERS = (
    "[Request interrupted by user]",
    "[Request interrupted by user for tool use]",
    "Caveat: The messages below were generated by the user while running local commands.",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "<channel-message>",
    "<command-args>",
    "<command-message>",
    "<command-name>",
    "<cross-session-message>",
    "<github-webhook-activity>",
    "<local-command-caveat>",
    "<local-command-stderr>",
    "<local-command-stdout>",
    "<new-diagnostics>",
    "<remote-review>",
    "<remote-review-progress>",
    "<task-notification>",
    "<teammate-message>",
    "<tick>",
    "<ultraplan>",
)

_CONTENTS_OF_LINE_RE = re.compile(r"^Contents of .+:", re.MULTILINE)
_FILE_PATH_LINE_RE = re.compile(r"^<file path=", re.MULTILINE)
_GENERATED_CONTEXT_PACK_START_MARKERS = (
    "# Commit ",
    "Generate all artifacts",
)
_GENERATED_ANALYSIS_PACK_START_MARKERS = (
    "Generate a retrospective for:",
    "Generate retrospective for:",
)
_OPERATOR_COMMAND_MARKERS = (
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<bash-input>",
)


def strip_system_reminders(text: str) -> str:
    """Remove Claude Code system-reminder blocks from mixed message text."""
    return _SYSTEM_REMINDER_PATTERN.sub("", text).strip()


def strip_leading_system_reminders(text: str) -> str:
    """Remove only leading Claude Code system-reminder blocks."""
    remainder = text.lstrip()
    while remainder.startswith("<system-reminder>"):
        match = _SYSTEM_REMINDER_PATTERN.match(remainder)
        if match is None:
            break
        remainder = remainder[match.end() :].lstrip()
    return remainder


def classify_text_message_type(text: str | None) -> MessageType | None:
    """Classify full-message text that represents runtime context/protocol.

    Used at materialization time to persist ``message_type``, and as a
    resilience fallback at read time for pre-#839 archive rows.
    """
    if not text:
        return None

    stripped = strip_leading_system_reminders(text)
    if not stripped:
        return MessageType.CONTEXT
    if stripped.startswith(_CONTEXT_START_MARKERS):
        return MessageType.CONTEXT
    if stripped.startswith(_CLAUDE_CODE_PROTOCOL_START_MARKERS):
        return MessageType.PROTOCOL

    # Additional context heuristics beyond start-of-text markers.
    if "<system>" in stripped and "</system>" in stripped:
        return MessageType.CONTEXT
    if _CONTENTS_OF_LINE_RE.search(stripped):
        return MessageType.CONTEXT
    # <file path=...> markers often appear on a non-first line in multiline
    # context-dump messages. Scan all lines rather than just the first.
    if _FILE_PATH_LINE_RE.search(stripped):
        return MessageType.CONTEXT

    return None


def classify_block_message_type(block_types: tuple[BlockType, ...]) -> MessageType | None:
    """Classify messages whose semantic type is carried by structured blocks."""
    if not block_types:
        return None
    if all(block_type is BlockType.TOOL_RESULT for block_type in block_types):
        return MessageType.TOOL_RESULT
    if any(block_type is BlockType.TOOL_USE for block_type in block_types):
        return MessageType.TOOL_USE
    return None


def classify_material_origin(
    *,
    role: Role,
    message_type: MessageType,
    text: str | None,
    block_types: tuple[BlockType, ...] = (),
) -> MaterialOrigin:
    """Classify authoredness/material origin independently from provider role."""
    normalized_role = role
    normalized_type = MessageType.normalize(message_type)
    stripped = strip_leading_system_reminders(text or "")

    if normalized_role is Role.TOOL or normalized_type is MessageType.TOOL_RESULT:
        return MaterialOrigin.TOOL_RESULT
    if block_types and all(block_type is BlockType.TOOL_RESULT for block_type in block_types):
        return MaterialOrigin.TOOL_RESULT
    if stripped.startswith(_GENERATED_ANALYSIS_PACK_START_MARKERS):
        return MaterialOrigin.GENERATED_ANALYSIS_PACK
    if stripped.startswith(_GENERATED_CONTEXT_PACK_START_MARKERS):
        return MaterialOrigin.GENERATED_CONTEXT_PACK
    if normalized_type is MessageType.SUMMARY:
        return MaterialOrigin.GENERATED_CONTEXT_PACK
    if normalized_type is MessageType.CONTEXT:
        return MaterialOrigin.RUNTIME_CONTEXT
    if normalized_type is MessageType.PROTOCOL:
        if any(marker in stripped for marker in _OPERATOR_COMMAND_MARKERS):
            return MaterialOrigin.OPERATOR_COMMAND
        return MaterialOrigin.RUNTIME_PROTOCOL
    if normalized_role is Role.ASSISTANT and normalized_type is MessageType.MESSAGE:
        # The assistant role IS positive evidence of model authorship: it is the
        # model's output channel. Unlike the user channel, nothing else is
        # injected through it once context/protocol/tool-result shapes are ruled
        # out above.
        return MaterialOrigin.ASSISTANT_AUTHORED
    # Deliberately NO `Role.USER + MESSAGE -> HUMAN_AUTHORED` fall-through.
    # The branches above are an allowlist of *known non-human* shapes; failing
    # to match one of them is "no known robot marker," which is NOT positive
    # evidence that a human typed this. Agent-runtime user turns (Claude Code,
    # Codex) routinely carry tool results, hook injections, pasted corpora, and
    # provider-injected context whose framing is not in the marker lists. Human
    # authorship is a fact we cannot derive from text shape alone, so it stays
    # UNKNOWN here; HUMAN_AUTHORED is reserved for rows backed by positive
    # human-input evidence (e.g. an explicit hook/correction assertion).
    return MaterialOrigin.UNKNOWN


__all__ = [
    "classify_block_message_type",
    "classify_material_origin",
    "classify_text_message_type",
    "strip_leading_system_reminders",
    "strip_system_reminders",
]
