from __future__ import annotations

from pathlib import Path

from devtools import render_quality_reference
from devtools.quality_registry import (
    BenchmarkCampaignEntry,
    MutationCampaignEntry,
    QualityRegistry,
    ValidationLaneEntry,
)


def test_build_document_includes_live_registry_sections() -> None:
    registry = QualityRegistry(
        contract_lanes=(
            ValidationLaneEntry(
                name="machine-contract",
                description="Machine-readable CLI surface.",
                timeout_s=120,
                category="contract",
            ),
        ),
        live_lanes=(
            ValidationLaneEntry(
                name="live-exercises",
                description="Read-only live archive exercises.",
                timeout_s=300,
                category="live",
            ),
        ),
        composite_lanes=(
            ValidationLaneEntry(
                name="frontier-local",
                description="Composite local frontier lane.",
                timeout_s=900,
                category="composite",
                sub_lanes=("machine-contract",),
            ),
        ),
        mutation_campaigns=(
            MutationCampaignEntry(
                name="filters",
                description="Filter semantics.",
                paths_to_mutate=("polylogue/lib/filters.py",),
                tests=("tests/unit/core/test_filters.py",),
            ),
        ),
        benchmark_campaigns=(
            BenchmarkCampaignEntry(
                name="search-filters",
                description="Search latency domain.",
                tests=("tests/benchmarks/test_search_filters.py",),
                warn_pct=10.0,
                fail_pct=20.0,
            ),
        ),
    )

    rendered = render_quality_reference.build_document(registry)

    assert "Generated by scripts/render-quality-reference" in rendered
    assert "## Validation Lane Catalog" in rendered
    assert "`machine-contract`" in rendered
    assert "`frontier-local`" in rendered
    assert "`filters`" in rendered
    assert "`search-filters`" in rendered


def test_write_if_changed_reuses_existing_output(tmp_path: Path) -> None:
    output_path = tmp_path / "test-quality-workflows.md"
    content = "hello\n"
    render_quality_reference.write_if_changed(output_path, content)
    original_mtime = output_path.stat().st_mtime_ns

    render_quality_reference.write_if_changed(output_path, content)

    assert output_path.read_text(encoding="utf-8") == content
    assert output_path.stat().st_mtime_ns == original_mtime
