from __future__ import annotations

import json
from pathlib import Path

import pytest

from devtools import render_verification_catalog
from polylogue.proof.catalog import VerificationCatalog, build_verification_catalog
from polylogue.proof.models import (
    BreakerMetadata,
    Claim,
    EnvironmentContract,
    Kind,
    RunnerBinding,
    SourceSpan,
    SubjectRef,
    TrustMetadata,
)
from polylogue.proof.rendering import build_catalog_markdown


def _small_catalog() -> VerificationCatalog:
    subject = SubjectRef(
        kind="cli.command",
        id="polylogue",
        attrs={"display_name": "polylogue"},
        source_span=SourceSpan("polylogue/cli/click_app.py", line=51, symbol="polylogue.cli.click_app.cli"),
    )
    claim = Claim(
        id="cli.command.help",
        description="help works",
        subject_query=Kind("cli.command"),
        evidence_schema={"type": "object"},
        bug_classes=("cli.help.regression",),
        breaker=BreakerMetadata("help failure"),
        runner_classes=("cli_visual",),
        observed_facts=("help_exit_code",),
        staleness_conditions=("command registration changes",),
    )
    runner = RunnerBinding(
        id="runner:cli.command.help",
        claim_id=claim.id,
        runner="static",
        evidence_class="smoke",
        cost_tier="static",
        freshness_policy="test",
        environment=EnvironmentContract(
            required_commands=("polylogue",),
            controlled_dimensions=("timezone=UTC",),
        ),
        trust=TrustMetadata(
            producer="tests",
            reviewed_at="2026-04-22T00:00:00+00:00",
            code_revision="test",
            dirty_state=False,
            schema_version=1,
            environment_fingerprint="test",
            runner_version="test",
            freshness="test",
            origin="test",
        ),
    )
    return build_verification_catalog(subjects=(subject,), claims=(claim,), runner_bindings=(runner,))


def test_build_catalog_markdown_renders_kernel_sections() -> None:
    rendered = build_catalog_markdown(_small_catalog())

    assert "Generated by `devtools render-verification-catalog`" in rendered
    assert "## Command Subjects" in rendered
    assert "## Claims" in rendered
    assert "## Runner Bindings" in rendered
    assert "## Proof Obligations" in rendered
    assert "`cli.command.help`" in rendered


def test_main_writes_and_checks_catalog(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    monkeypatch.setattr(render_verification_catalog, "build_verification_catalog", _small_catalog)
    output_path = tmp_path / "verification-catalog.md"

    assert render_verification_catalog.main(["--output", str(output_path)]) == 0
    assert render_verification_catalog.main(["--output", str(output_path), "--check"]) == 0

    captured = capsys.readouterr()
    assert "sync OK" in captured.out


def test_main_json_emits_full_catalog_payload(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    monkeypatch.setattr(render_verification_catalog, "build_verification_catalog", _small_catalog)

    assert render_verification_catalog.main(["--json"]) == 0
    payload = json.loads(capsys.readouterr().out)

    assert payload["summary"]["subject_count"] == 1
    assert payload["claims"][0]["id"] == "cli.command.help"
