from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from devtools import demo_shelf

GENERATED_SHELF_FILES = (
    "MANIFEST.readable.json",
    "SUMMARY_INDEX.json",
    "README.md",
    "CURATED_CATALOG.md",
)


def _git(repository: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repository), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _repository_shelf(tmp_path: Path) -> tuple[Path, Path]:
    repository = tmp_path / "repository"
    repository.mkdir()
    _git(repository, "init", "--quiet")
    _git(repository, "config", "user.email", "demo-shelf@example.invalid")
    _git(repository, "config", "user.name", "Demo Shelf Test")
    (repository / ".gitignore").write_text(".agent/demos/ignored-demo/\nprivate-output/\n")
    root = repository / ".agent" / "demos"
    (root / "tracked-demo").mkdir(parents=True)
    (root / "tracked-demo" / "README.md").write_text("# Tracked Demo\n")
    (root / "tracked-demo" / "summary.json").write_text(
        json.dumps(
            {
                "artifact": "tracked-demo",
                "claim": "Tracked evidence is included.",
                "non_claim": "This fixture does not use private evidence.",
                "proofs": ["README.md"],
                "caveats": ["Synthetic fixture"],
            }
        )
    )
    _git(repository, "add", ".gitignore", ".agent/demos/tracked-demo")
    _git(repository, "commit", "--quiet", "-m", "seed tracked demo")
    assert demo_shelf.main(["--root", str(root)]) == 0
    _git(repository, "add", ".agent/demos")
    _git(repository, "commit", "--quiet", "-m", "add shelf projections")
    return repository, root


def test_demo_shelf_writes_manifest_and_summary_index(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    root = tmp_path / "demos"
    (root / "01-demo").mkdir(parents=True)
    (root / "01-demo" / "README.md").write_text("# Demo\n\nReadable.\n")
    (root / "01-demo" / "payload.bin").write_bytes(b"\x00\x01")
    (root / "01-demo" / "summary.json").write_text(
        json.dumps(
            {
                "artifact": "01-demo",
                "claim": "Readable artifact exists.",
                "non_claim": "Binary payload is not included in generated indexes.",
                "proofs": ["README.md included"],
                "caveats": ["Synthetic fixture"],
                "index_schema_version": 18,
            }
        )
    )

    exit_code = demo_shelf.main(["--root", str(root)])

    assert exit_code == 0
    output = capsys.readouterr().out
    assert "demo shelf refreshed" in output
    manifest = json.loads((root / "MANIFEST.readable.json").read_text())
    assert manifest["contract"] == "current-curated-demo-set"
    assert "append-only" in manifest["curation_policy"]
    assert "read-package" in manifest["packaging"]
    assert manifest["file_count"] == 3
    assert manifest["readable_count"] == 2
    paths = {item["path"]: item for item in manifest["files"]}
    assert paths["01-demo/README.md"]["readable"] is True
    assert paths["01-demo/summary.json"]["readable"] is True
    assert paths["01-demo/payload.bin"]["readable"] is False
    assert "MANIFEST.readable.json" not in paths
    assert "README.md" not in paths
    assert "CURATED_CATALOG.md" not in paths
    assert "CONCATENATED_READABLE.md" not in paths
    assert "SUMMARY_INDEX.json" not in paths
    assert not (root / "CONCATENATED_READABLE.md").exists()
    assert "Generated by `devtools workspace demo-shelf`." in (root / "README.md").read_text()
    assert "Generated by `devtools workspace demo-shelf`." in (root / "CURATED_CATALOG.md").read_text()
    summary_index = json.loads((root / "SUMMARY_INDEX.json").read_text())
    assert summary_index["summary_count"] == 1
    assert summary_index["coverage"]["without_claim"] == []
    assert summary_index["coverage"]["without_non_claim"] == []
    assert summary_index["coverage"]["unsummarized_demos"] == []
    assert summary_index["records"][0]["proof_fields"] == ["proofs"]
    assert summary_index["records"][0]["caveat_fields"] == ["caveats"]


def test_demo_shelf_check_reports_drift(tmp_path: Path) -> None:
    root = tmp_path / "demos"
    root.mkdir()
    (root / "README.md").write_text("# Demo\n")

    assert demo_shelf.main(["--root", str(root)]) == 0
    (root / "README.md").write_text("# Demo\n\nchanged\n")

    assert demo_shelf.main(["--root", str(root), "--check"]) == 1


def test_demo_shelf_check_json_reports_current_state(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    root = tmp_path / "demos"
    root.mkdir()
    (root / "README.md").write_text("# Demo\n")
    assert demo_shelf.main(["--root", str(root)]) == 0
    capsys.readouterr()

    exit_code = demo_shelf.main(["--root", str(root), "--check", "--json"])

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is True
    assert payload["mode"] == "check"
    assert payload["file_count"] == 0
    assert payload["readable_count"] == 0
    assert payload["summary_count"] == 0


def test_demo_shelf_summary_index_reports_coverage_gaps(tmp_path: Path) -> None:
    root = tmp_path / "demos"
    (root / "01-demo").mkdir(parents=True)
    (root / "01-demo" / "summary.json").write_text(json.dumps({"artifact": "01-demo"}))

    assert demo_shelf.main(["--root", str(root)]) == 0

    summary_index = json.loads((root / "SUMMARY_INDEX.json").read_text())
    assert summary_index["summary_count"] == 1
    assert summary_index["coverage"]["without_claim"] == ["01-demo/summary.json"]
    assert summary_index["coverage"]["without_non_claim"] == ["01-demo/summary.json"]
    assert summary_index["coverage"]["without_proof_fields"] == ["01-demo/summary.json"]
    assert summary_index["coverage"]["without_caveat_fields"] == ["01-demo/summary.json"]
    assert summary_index["coverage"]["unsummarized_demos"] == []


def test_demo_shelf_reports_unsummarized_current_entries(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    root = tmp_path / "demos"
    (root / "summarized").mkdir(parents=True)
    (root / "summarized" / "summary.json").write_text(
        json.dumps(
            {
                "artifact": "summarized",
                "claim": "Claim.",
                "non_claim": "Non-claim.",
                "proofs": ["proof"],
                "caveats": ["caveat"],
            }
        )
    )
    (root / "unsummarized").mkdir()
    (root / "unsummarized" / "README.md").write_text("# Unsummarized\n")
    assert demo_shelf.main(["--root", str(root)]) == 0
    capsys.readouterr()

    exit_code = demo_shelf.main(["--root", str(root), "--check", "--json"])

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["unsummarized_demos"] == ["unsummarized"]
    summary_index = json.loads((root / "SUMMARY_INDEX.json").read_text())
    assert summary_index["coverage"]["unsummarized_demos"] == ["unsummarized"]


def test_demo_shelf_require_summary_coverage_fails_check(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    root = tmp_path / "demos"
    (root / "01-demo").mkdir(parents=True)
    (root / "01-demo" / "summary.json").write_text(json.dumps({"artifact": "01-demo"}))
    assert demo_shelf.main(["--root", str(root)]) == 0
    capsys.readouterr()

    exit_code = demo_shelf.main(
        [
            "--root",
            str(root),
            "--check",
            "--json",
            "--require-summary-coverage",
            "claim,non_claim,proof_fields,caveat_fields",
        ]
    )

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    assert payload["summary_coverage_failures"] == {
        "caveat_fields": ["01-demo/summary.json"],
        "claim": ["01-demo/summary.json"],
        "non_claim": ["01-demo/summary.json"],
        "proof_fields": ["01-demo/summary.json"],
    }


def test_demo_shelf_require_summary_coverage_passes_check(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    root = tmp_path / "demos"
    (root / "01-demo").mkdir(parents=True)
    (root / "01-demo" / "summary.json").write_text(
        json.dumps(
            {
                "artifact": "01-demo",
                "claim": "Claim.",
                "non_claim": "Non-claim.",
                "proofs": ["proof"],
                "caveats": ["caveat"],
            }
        )
    )
    assert demo_shelf.main(["--root", str(root)]) == 0
    capsys.readouterr()

    exit_code = demo_shelf.main(
        [
            "--root",
            str(root),
            "--check",
            "--json",
            "--require-summary-coverage",
            "claim,non_claim,proof_fields,caveat_fields",
        ]
    )

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is True
    assert payload["summary_coverage_failures"] == {}


def test_demo_shelf_require_index_schema_version_fails_stale_claim(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root = tmp_path / "demos"
    (root / "01-demo").mkdir(parents=True)
    (root / "01-demo" / "summary.json").write_text(
        json.dumps(
            {
                "artifact": "01-demo",
                "claim": "Claim.",
                "non_claim": "Non-claim.",
                "proofs": ["proof"],
                "caveats": ["caveat"],
                "index_schema_version": 21,
            }
        )
    )
    assert demo_shelf.main(["--root", str(root)]) == 0
    capsys.readouterr()

    exit_code = demo_shelf.main(
        [
            "--root",
            str(root),
            "--check",
            "--json",
            "--require-index-schema-version",
            "23",
        ]
    )

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    assert payload["required_index_schema_version"] == 23
    assert payload["summary_schema_mismatches"] == [
        {
            "summary_path": "01-demo/summary.json",
            "observed": 21,
            "required": 23,
        }
    ]


def test_repository_closure_rejects_ignored_demo_with_bounded_accounting(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    repository, root = _repository_shelf(tmp_path)
    capsys.readouterr()
    baseline = {name: (root / name).read_bytes() for name in GENERATED_SHELF_FILES}
    ignored_root = root / "ignored-demo"
    ignored_root.mkdir()
    for index in range(25):
        (ignored_root / f"private-{index:02}.json").write_text(json.dumps({"artifact": "private evidence"}))

    exit_code = demo_shelf.main(["--root", str(root), "--json"])

    assert exit_code == 1
    payload = json.loads(capsys.readouterr().out)
    assert payload["undeclared_inputs"] is True
    assert payload["input_closure"] == {
        "mode": "git-tracked",
        "included_count": 2,
        "excluded_count": 25,
        "exclusion_reason_counts": {"not_git_tracked": 25},
    }
    assert len(payload["exclusion_samples"]) == demo_shelf.MAX_EXCLUSION_SAMPLES
    assert payload["exclusion_samples"][0] == {
        "path": "ignored-demo/private-00.json",
        "reason": "not_git_tracked",
    }
    assert {name: (root / name).read_bytes() for name in GENERATED_SHELF_FILES} == baseline
    assert _git(repository, "status", "--short") == ""


def test_private_projection_keeps_ignored_demo_accessible(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    repository, root = _repository_shelf(tmp_path)
    capsys.readouterr()
    ignored = root / "ignored-demo" / "summary.json"
    ignored.parent.mkdir()
    ignored.write_text(json.dumps({"artifact": "private evidence"}))
    private_output = repository / "private-output"

    exit_code = demo_shelf.main(["--root", str(root), "--private-output", str(private_output), "--json"])

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["input_closure"] == {
        "mode": "filesystem-private",
        "included_count": 3,
        "excluded_count": 0,
        "exclusion_reason_counts": {},
    }
    manifest = json.loads((private_output / "MANIFEST.readable.json").read_text())
    assert "ignored-demo/summary.json" in {record["path"] for record in manifest["files"]}
    assert _git(repository, "status", "--short") == ""


def test_tracked_projection_is_byte_identical_in_clean_clone(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    repository, root = _repository_shelf(tmp_path)
    capsys.readouterr()
    clone = tmp_path / "clone"
    subprocess.run(["git", "clone", "--quiet", str(repository), str(clone)], check=True)
    cloned_root = clone / ".agent" / "demos"

    exit_code = demo_shelf.main(["--root", str(cloned_root), "--check", "--json"])

    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["changed"] == dict.fromkeys(("manifest", "summary_index", "readme", "catalog"), False)
    for name in GENERATED_SHELF_FILES:
        assert (cloned_root / name).read_bytes() == (root / name).read_bytes()


def test_current_repository_closure_keeps_uplift_corpus_indexed() -> None:
    root = Path(".agent/demos")

    rendered = demo_shelf.render_demo_shelf(root)

    manifest = json.loads(rendered.manifest_text)
    paths = {record["path"] for record in manifest["files"]}
    assert "uplift-two-arm/current/report.md" in paths
    assert "uplift-two-arm/current/arms/pair1-handoff-pack-output.md" in paths
    assert "uplift-two-arm/current/metrics/score.json" in paths
    assert "uplift-two-arm" in rendered.unsummarized_demos
