from __future__ import annotations

from devtools import render_docs_surface


def test_build_docs_readme_groups_docs_by_reader_task() -> None:
    rendered = render_docs_surface.build_docs_readme()

    assert "Generated by `devtools render-docs-surface`" in rendered
    assert "## Orientation" in rendered
    assert "[Architecture](architecture.md)" in rendered
    assert "## User and Integration Surfaces" in rendered
    assert "[CLI Reference](cli-reference.md)" in rendered
    assert "[Browser Capture](browser-capture.md)" in rendered
    assert "## Verification and Quality" in rendered
    assert "[Verification Lab](verification-lab.md)" in rendered
    assert "[Developer Tools](devtools.md)" in rendered
    assert "## Contributor Workflow" in rendered
    assert "[Contributing](../CONTRIBUTING.md)" in rendered
    assert ".cache/README.md" not in rendered
    assert ".local/README.md" not in rendered


def test_replace_marked_section_swaps_generated_block() -> None:
    source = "\n".join(
        [
            "before",
            "<!-- BEGIN GENERATED: docs-surface -->",
            "old",
            "<!-- END GENERATED: docs-surface -->",
            "after",
        ]
    )

    updated = render_docs_surface.replace_marked_section(
        source,
        marker="docs-surface",
        replacement="<!-- BEGIN GENERATED: docs-surface -->\nnew\n<!-- END GENERATED: docs-surface -->",
    )

    assert "before" in updated
    assert "\nnew\n" in updated
    assert "after" in updated
