from __future__ import annotations

from pathlib import Path

from devtools import render_agents


def test_render_document_expands_includes_recursively(tmp_path: Path) -> None:
    nested = tmp_path / "nested.md"
    nested.write_text("nested body\n", encoding="utf-8")
    include = tmp_path / "include.md"
    include.write_text(f"before\n@{nested.name}\nafter\n", encoding="utf-8")
    claude = tmp_path / "CLAUDE.md"
    claude.write_text(f"root\n@{include.name}\n", encoding="utf-8")
    output = tmp_path / "AGENTS.md"

    rendered = render_agents.render_document(input_path=claude, output_path=output)

    assert "Generated by `python -m devtools render-agents`" in rendered
    assert "<!-- begin include:" in rendered
    assert "nested body" in rendered
    assert rendered.count("<!-- begin include:") == 2
    assert rendered.count("<!-- end include:") == 2


def test_render_document_skips_includes_inside_code_fences(tmp_path: Path) -> None:
    include = tmp_path / "include.md"
    include.write_text("included\n", encoding="utf-8")
    claude = tmp_path / "CLAUDE.md"
    claude.write_text(
        f"```md\n@{include.name}\n```\n@{include.name}\n",
        encoding="utf-8",
    )

    rendered = render_agents.render_document(input_path=claude, output_path=tmp_path / "AGENTS.md")

    assert f"@{include.name}" in rendered
    assert rendered.count("\nincluded\n") == 1


def test_expand_rejects_circular_includes(tmp_path: Path) -> None:
    first = tmp_path / "first.md"
    second = tmp_path / "second.md"
    first.write_text(f"@{second.name}\n", encoding="utf-8")
    second.write_text(f"@{first.name}\n", encoding="utf-8")

    try:
        render_agents.expand(first, [])
    except RuntimeError as exc:
        assert "circular include detected" in str(exc)
    else:
        raise AssertionError("expected circular include detection")
