from __future__ import annotations

from pathlib import Path

from devtools import render_demo_corpus_datasheet
from polylogue.demo import DemoSeedResult, DemoVerifyResult
from polylogue.demo.constructs import DemoConstructCoverage


def _seed_result() -> DemoSeedResult:
    return DemoSeedResult(
        archive_root=Path("/archive"),
        source_root=Path("/archive/source"),
        session_count=2,
        message_count=4,
        session_ids=("a", "b"),
        overlays_seeded=True,
        assertion_count=4,
        construct_coverage=(
            DemoConstructCoverage("session_profiles", "Session profiles", 2, 1, True),
            DemoConstructCoverage("compaction_events", "Compaction events", 1, 1, True),
        ),
    )


def _verify_result() -> DemoVerifyResult:
    return DemoVerifyResult(
        archive_root=Path("/archive"),
        ok=True,
        session_count=2,
        message_count=4,
        query_hits=("a",),
        overlays_present=True,
        absolute_path_leaks=(),
        construct_coverage=_seed_result().construct_coverage,
        problems=(),
    )


def test_build_document_is_generated_from_families_and_measurements() -> None:
    rendered = render_demo_corpus_datasheet.build_document(
        _seed_result(),
        _verify_result(),
        render_demo_corpus_datasheet.DemoCorpusMeasurement(
            blocks=6,
            origins=("chatgpt-export", "codex-session"),
            run_rows=2,
            observed_event_rows=3,
            context_snapshot_rows=2,
        ),
    )

    assert "Generated by `devtools render demo-corpus-datasheet`" in rendered
    assert "| Sessions | 2 |" in rendered
    assert "| Blocks | 6 |" in rendered
    assert "`agent-lineage-matrix`" in rendered
    assert "Compaction events (`compaction_events`) | 1 | 1 | `ok`" in rendered
    assert "fork-vs-resume" in rendered


def test_main_check_reports_out_of_sync(tmp_path: Path) -> None:
    output = tmp_path / "datasheet.md"
    output.write_text("stale\n", encoding="utf-8")

    assert render_demo_corpus_datasheet.main(["--output", str(output), "--work-root", str(tmp_path / "work")]) == 0
    assert (
        render_demo_corpus_datasheet.main(["--output", str(output), "--work-root", str(tmp_path / "work"), "--check"])
        == 0
    )

    output.write_text("stale\n", encoding="utf-8")
    assert (
        render_demo_corpus_datasheet.main(["--output", str(output), "--work-root", str(tmp_path / "work"), "--check"])
        == 1
    )
