from __future__ import annotations

import json
from pathlib import Path

from devtools import render_webui_design_system as renderer
from polylogue.core.enums import Origin


def test_generated_contract_exactly_tracks_public_origins() -> None:
    rendered = renderer.render_contracts_ts()

    for origin in Origin:
        expected = f'"{origin.value}"'
        if origin is Origin.UNKNOWN_EXPORT:
            assert expected not in rendered
        else:
            assert expected in rendered
    assert rendered.count('  "') >= 15

    css = renderer.render_tokens_css()
    for origin in renderer.PUBLIC_ORIGIN_TOKENS:
        assert f".pl-origin-badge[data-origin='{origin.value}']" in css
    assert "data-origin='unknown-export'" not in css


def test_contrast_report_passes_text_and_focus_thresholds() -> None:
    report = renderer.build_contrast_report()

    assert report["minimum_text_ratio"] >= 4.5
    assert report["minimum_focus_ratio"] >= 3.0
    assert all(pair["passes"] for pair in report["pairs"])


def test_renderer_check_detects_and_then_accepts_outputs(tmp_path: Path) -> None:
    assert renderer.main(["--output-dir", str(tmp_path), "--check"]) == 1
    assert renderer.main(["--output-dir", str(tmp_path)]) == 0
    assert renderer.main(["--output-dir", str(tmp_path), "--check"]) == 0

    report = json.loads((tmp_path / "contrast-report.json").read_text())
    assert report["schema_version"] == 1
    assert (tmp_path / "tokens.css").read_text().startswith("/* Generated by")
