from __future__ import annotations

from pathlib import Path

from devtools import render_quality_reference
from devtools.benchmark_catalog import BenchmarkCampaignEntry
from devtools.mutation_catalog import MutationCampaignEntry
from devtools.quality_registry import QualityRegistry
from devtools.scenario_coverage import RuntimePathCoverage, RuntimeScenarioCoverage, ScenarioCoverageRef
from devtools.validation_catalog import ValidationLaneEntry
from polylogue.scenarios import (
    ScenarioProjectionEntry,
    ScenarioProjectionSourceKind,
)


def test_build_document_includes_live_registry_sections() -> None:
    registry = QualityRegistry(
        contract_lanes=(
            ValidationLaneEntry(
                name="machine-contract",
                description="Machine-readable CLI surface.",
                timeout_s=120,
                category="contract",
            ),
        ),
        live_lanes=(
            ValidationLaneEntry(
                name="live-exercises",
                description="Read-only live archive exercises.",
                timeout_s=300,
                category="live",
            ),
        ),
        composite_lanes=(
            ValidationLaneEntry(
                name="frontier-local",
                description="Composite local frontier lane.",
                timeout_s=900,
                category="composite",
                sub_lanes=("machine-contract",),
            ),
        ),
        mutation_campaigns=(
            MutationCampaignEntry(
                name="filters",
                description="Filter semantics.",
                paths_to_mutate=("polylogue/lib/filters.py",),
                tests=("tests/unit/core/test_filters.py",),
            ),
        ),
        benchmark_campaigns=(
            BenchmarkCampaignEntry(
                name="search-filters",
                description="Search latency domain.",
                tests=("tests/benchmarks/test_search_filters.py",),
                warn_pct=10.0,
                fail_pct=20.0,
            ),
        ),
        synthetic_benchmark_campaigns=(
            BenchmarkCampaignEntry(
                name="startup-health",
                description="Synthetic startup-health benchmark.",
                tests=(),
            ),
        ),
        scenario_projections=(
            ScenarioProjectionEntry(
                source_kind=ScenarioProjectionSourceKind.EXERCISE,
                name="json-doctor-action-event-preview",
                description="Action-event doctor preview.",
                origin="generated.json-contract",
                path_targets=("action-event-repair-loop",),
                artifact_targets=("action_event_rows",),
                operation_targets=("project-action-event-health",),
                tags=("generated", "json-contract"),
            ),
            ScenarioProjectionEntry(
                source_kind=ScenarioProjectionSourceKind.BENCHMARK_CAMPAIGN,
                name="search-filters",
                description="Search latency domain.",
                origin="authored.benchmark-domain",
                artifact_targets=("message_fts",),
                operation_targets=("benchmark.query.search-filters",),
                tags=("benchmark", "search"),
            ),
        ),
    )

    rendered = render_quality_reference.build_document(registry)

    assert "Generated by `devtools render-quality-reference`" in rendered
    assert "## Validation Lane Catalog" in rendered
    assert "`machine-contract`" in rendered
    assert "`frontier-local`" in rendered
    assert "`filters`" in rendered
    assert "`search-filters`" in rendered
    assert "`startup-health`" in rendered
    assert "## Synthetic Benchmark Campaign Catalog" in rendered
    assert "- scenario projections: `2`" in rendered
    assert "  - benchmark-campaign: `1`" in rendered
    assert "  - exercise: `1`" in rendered
    assert "## Scenario Projection Catalog" in rendered
    assert "| `exercise` | `json-doctor-action-event-preview` |" in rendered
    assert "`action-event-repair-loop`" in rendered


def test_build_document_includes_runtime_coverage_section() -> None:
    registry = QualityRegistry(
        contract_lanes=(),
        live_lanes=(),
        composite_lanes=(),
        mutation_campaigns=(),
        benchmark_campaigns=(),
        synthetic_benchmark_campaigns=(),
        scenario_projections=(),
    )
    coverage = RuntimeScenarioCoverage(
        artifacts={
            "action_event_rows": (
                ScenarioCoverageRef(
                    source="exercise",
                    name="json-doctor-action-event-preview",
                    origin="generated.json-contract",
                ),
            ),
        },
        operations={},
        paths={
            "action-event-repair-loop": RuntimePathCoverage(
                name="action-event-repair-loop",
                refs=(
                    ScenarioCoverageRef(
                        source="exercise",
                        name="json-doctor-action-event-preview",
                        origin="generated.json-contract",
                    ),
                ),
                uncovered_artifacts=("tool_use_source_blocks",),
                uncovered_operations=("materialize-action-events",),
            ),
        },
        uncovered_artifacts=("tool_use_source_blocks",),
        uncovered_operations=("materialize-action-events",),
    )

    rendered = render_quality_reference.build_document(registry, runtime_coverage=coverage)

    assert "## Runtime Coverage" in rendered
    assert "- covered runtime paths: `0`" in rendered
    assert "- covered runtime artifacts: `1`" in rendered
    assert "- uncovered runtime paths: `action-event-repair-loop`" in rendered
    assert "- uncovered runtime artifacts: `tool_use_source_blocks`" in rendered
    assert "- uncovered runtime operations: `materialize-action-events`" in rendered
    assert "devtools artifact-graph" in rendered


def test_write_if_changed_reuses_existing_output(tmp_path: Path) -> None:
    output_path = tmp_path / "test-quality-workflows.md"
    content = "hello\n"
    render_quality_reference.write_if_changed(output_path, content)
    original_mtime = output_path.stat().st_mtime_ns

    render_quality_reference.write_if_changed(output_path, content)

    assert output_path.read_text(encoding="utf-8") == content
    assert output_path.stat().st_mtime_ns == original_mtime
