from __future__ import annotations

from pathlib import Path

from devtools import render_cli_reference


def test_build_document_includes_sections() -> None:
    rendered = render_cli_reference.build_document(
        [
            ("Top-Level Command", "Usage: polylogue [OPTIONS] COMMAND [ARGS]..."),
            ("Run", "Usage: polylogue run [OPTIONS] COMMAND1 [ARGS]..."),
        ]
    )

    assert "Generated by `devtools render-cli-reference`" in rendered
    assert "## Top-Level Command" in rendered
    assert "Usage: polylogue [OPTIONS] COMMAND [ARGS]..." in rendered
    assert "## Run" in rendered


def test_write_if_changed_reuses_existing_output(tmp_path: Path) -> None:
    output_path = tmp_path / "cli-reference.md"
    content = "hello\n"
    render_cli_reference.write_if_changed(output_path, content)
    original_mtime = output_path.stat().st_mtime_ns

    render_cli_reference.write_if_changed(output_path, content)

    assert output_path.read_text(encoding="utf-8") == content
    assert output_path.stat().st_mtime_ns == original_mtime
