from __future__ import annotations

from pathlib import Path

from devtools import render_docs_surface


def test_build_docs_readme_groups_docs_by_reader_tier() -> None:
    rendered = render_docs_surface.build_docs_readme()

    assert "Generated by `devtools render docs-surface`" in rendered
    assert "## Guides" in rendered
    assert "[Architecture](architecture.md)" in rendered
    assert "[Archive Backup](archive-backup.md)" in rendered
    assert "## Reference" in rendered
    assert "[CLI Reference](cli-reference.md)" in rendered
    assert "[Browser Capture](browser-capture.md)" in rendered
    assert "## Operations and Contributor Workflow" in rendered
    assert "[Developer Tools](devtools.md)" in rendered
    assert "[Visual Evidence](visual-evidence.md)" in rendered
    assert "Synthetic reader DOM/media evidence lanes" in rendered
    assert "## Contributor Workflow" in rendered
    assert "[Contributing](../CONTRIBUTING.md)" in rendered
    assert ".cache/README.md" not in rendered
    assert ".local/README.md" not in rendered


def test_undocumented_paths_reports_an_unregistered_doc(tmp_path: Path) -> None:
    docs_root = tmp_path / "docs"
    docs_root.mkdir()
    (docs_root / "new-guide.md").write_text("# New guide\n", encoding="utf-8")

    assert render_docs_surface.undocumented_paths((), docs_root=docs_root) == {"docs/new-guide.md"}


def test_replace_marked_section_swaps_generated_block() -> None:
    source = "\n".join(
        [
            "before",
            "<!-- BEGIN GENERATED: docs-surface -->",
            "old",
            "<!-- END GENERATED: docs-surface -->",
            "after",
        ]
    )

    updated = render_docs_surface.replace_marked_section(
        source,
        marker="docs-surface",
        replacement="<!-- BEGIN GENERATED: docs-surface -->\nnew\n<!-- END GENERATED: docs-surface -->",
    )

    assert "before" in updated
    assert "\nnew\n" in updated
    assert "after" in updated
