"""Public parser contracts and shared extraction helpers."""

from __future__ import annotations

from polylogue.archive.message.roles import normalize_role

from .base_models import (
    AdmissionDisposition,
    AdmissionOutcome,
    AdmissionRefusalReason,
    AdmissionUnit,
    AdmissionUnknownReason,
    ParseAccounting,
    ParsedAttachment,
    ParsedContentBlock,
    ParsedFileEdit,
    ParsedMessage,
    ParsedPasteEvidence,
    ParsedSession,
    ParsedSessionEvent,
    ParsedSessionRef,
    ParsedWebConstruct,
    RawSessionData,
)
from .base_support import (
    AdmissionLedger,
    attachment_from_meta,
    content_blocks_from_segments,
    extract_messages_from_list,
    fill_linear_parent_chain,
    human_authored_override,
    mark_last_occurrence_as_active_leaf,
    parser_admission,
    synthetic_message_id,
    text_blocks_prose,
    typed_unknown,
    typed_unknown_block,
)

__all__ = [
    "AdmissionDisposition",
    "AdmissionOutcome",
    "AdmissionRefusalReason",
    "AdmissionUnit",
    "AdmissionUnknownReason",
    "AdmissionLedger",
    "ParseAccounting",
    "ParsedContentBlock",
    "ParsedFileEdit",
    "ParsedMessage",
    "ParsedAttachment",
    "ParsedPasteEvidence",
    "ParsedWebConstruct",
    "ParsedSession",
    "ParsedSessionEvent",
    "ParsedSessionRef",
    "RawSessionData",
    "normalize_role",
    "content_blocks_from_segments",
    "extract_messages_from_list",
    "attachment_from_meta",
    "fill_linear_parent_chain",
    "human_authored_override",
    "mark_last_occurrence_as_active_leaf",
    "synthetic_message_id",
    "text_blocks_prose",
    "typed_unknown",
    "typed_unknown_block",
    "parser_admission",
]
