"""Hermes NeMo Relay ATIF observer-trajectory importer (fs1.2).

Imports a Hermes NeMo Relay Agent Trajectory Interchange Format (ATIF)
export as runtime-evidence: tool-call steps become tool-execution spans,
message-only steps become LLM-response evidence, and ``subagent_trajectories``
entries become subagent-delegation evidence.

Review-fix note (2026-07-14, replaces the original honesty caveat): a
reviewer found the originally-shipped detector could only ever match a
synthetic ``polylogue_artifact: "hermes_atif_trace"`` marker key invented by
this repo's own test helper -- no real, unmodified Hermes/NeMo Relay export
could ever reach this parser. That gap is now closed: ``looks_like_atif_payload``
checks the real, externally-published ATIF top-level document shape
(``schema_version`` prefixed ``"ATIF"``, ``session_id``, ``steps``), sourced
from NVIDIA's own NeMo Relay documentation:

- https://docs.nvidia.com/nemo/relay/nemo-relay-cli/hermes (Hermes hook
  vocabulary NeMo Relay captures: pre/post_api_request, pre/post_tool_call,
  subagent_start/stop, api_request_error, etc.)
- https://docs.nvidia.com/nemo/relay/about-nemo-relay/concepts/events (ATOF
  event envelope: ``atof_version``, ``kind`` in {scope, mark}, ``category``,
  ``scope_category``)
- https://github.com/HexLab98/hermes-agent-fork/blob/main/plugins/observability/nemo_relay/README.md
  (ATIF top-level shape: ``schema_version: "ATIF-v1.7"``, ``session_id``,
  ``agent``, ``steps``, ``subagent_trajectories``; step fields ``source``,
  ``tool_calls`` (``function_name``/``arguments``/``tool_call_id``),
  ``observation``, ``message``)

A redacted real ATIF document generated by the bundled Hermes NeMo Relay plugin
is checked into ``tests/fixtures/hermes/atif/``. It confirms the exported
top-level shape, the message-only step mapping, and (as of 2026-07-18, using a
real step drawn from a separate live trajectory export) the ``tool_calls``/
``observation`` step shape: ``import_fidelity_declaration`` marks
``llm_request_spans`` and ``tool_execution_spans`` ``exact``. No real
``subagent_trajectories`` evidence has been observed yet (every live
trajectory sampled so far has an empty list), so subagent delegation mapping
intentionally remains ``inferred`` rather than being promoted from
documentation alone.

ATIF's documented step schema (``source``/``tool_calls``/``observation``/
``message``) carries no approval/error-hook data, so those capabilities remain
honestly ``absent`` for ATIF-only imports. The separately-ingested raw ATOF
JSONL route groups producer events by Hermes session id and preserves LLM,
tool, approval, error, subagent, context, and unknown-event evidence as
observer events. It still does not physically merge either observer source
into the state-db transcript session.

Payload hygiene: unlike a raw ATOF hook (ids/timings/outcomes only), a real
ATIF step's ``message``/``observation`` fields carry actual response text --
that is ATIF's purpose (replay/evaluation). To keep this importer consistent
with the payload-hygiene rule the rest of the Hermes bridge enforces
(``sources.hooks._reject_duplicated_transcript``: evidence, never a second
copy of conversation text), this parser deliberately records only bounded,
non-content evidence about that text (presence, character length) rather
than copying it. Full-transcript ATIF import (treating steps as real
session messages) is a distinct, larger product decision -- deferred to
fs1.2.1, not assumed here.

Session correlation (design's "join key: Hermes session id ->
sessions.native_id"): this parser produces its own artifact-qualified
observer-evidence session identities (``observer:atif:<hermes_session_id>
[@profile-<key>]`` for ATIF, ``observer:atof:<hermes_session_id>
[@profile-<key>]`` for ATOF -- see :func:`atif_session_provider_id` /
:func:`atof_session_provider_id`) rather than physically merging trajectory
evidence into the state-db-ingested conversational session's message tree --
a physical merge across three independently-acquired artifacts for the same
logical Hermes session is a session-identity/lineage design decision
(topology_edges / session_links) that is explicitly deferred, not silently
assumed. Read-side correlation by the shared Hermes session id remains
possible today via :func:`hermes_atif_session_id_for` /
:func:`hermes_atof_session_id_for`, and is composed across every Hermes
artifact class (conversational, ATIF, ATOF, verification ledger) by
``polylogue.insights.hermes_topology_projection.project_hermes_topology``.

TOPOLOGY PROJECTION FIX (polylogue-fs1.14): the raw Hermes session id alone
is not a safe archive join key -- two separate Hermes installs (profiles)
can legitimately reuse the same raw session id, and the original
``observer:<raw_id>`` identity (with no profile qualifier at all) silently
collapsed ATIF and ATOF evidence from different installs onto one archive
session whenever that happened, and made the read-side correlation helpers'
reverse lookup strip the profile qualifier off a real conversational session
id, discarding the very information that would have prevented the collision.
Both artifact families now thread ``profile_root`` (the directory the raw
ATIF/ATOF artifact was acquired from -- the same convention
``hermes_state.parse_state_db`` already uses) through to
``hermes_identity.profile_key``, the single shared helper both this module
and ``hermes_state.py`` call, so each artifact-qualified observer session
identity and the ``session_links`` parent edge asserted back to the
state-db conversational session use the exact same qualifier.
``parent_session_provider_id`` is only ever set when the profile root is
known -- an unqualified raw id is not asserted as a parent, which is the
fail-closed side of the same fix: no edge is safer than a wrong one. Once
asserted, the generic ``session_links`` write/resolution machinery
(``archive_tiers/write.py``, unchanged by this pass) resolves the edge when
the target conversational session is ingested and leaves it explicitly
``unresolved`` (visible debt, never silently dropped) otherwise.

LIVE INGESTION FIX (polylogue-flxh, confirmed 2026-07-18, fixed same day):
the real ATOF producer writes ONE shared ``events.jsonl`` file across every
Hermes session on an install (live-verified: 3+ distinct session ids
interleaved in one file), unlike Claude Code/Codex where one JSONL file is
always exactly one session. A growth batch can therefore span a Hermes
session boundary. Two changes: (1) the live watcher (``live/batch.py``)
never attempts incremental append for the Hermes ATOF source class, always
routing it through the full/bundle ingest path, which already handles
multi-session grouping correctly (Fable-adjudicated Direction 3); (2) the
real root cause -- the ATOF/ATIF summary message text below used to embed
live event/step counts, which changed on every reparse and broke the
archive's membership-classifier invariant that message content must be an
unchanging prefix across revisions to safely recognize append-only growth,
causing a genuinely-monotonic growth batch to look non-monotonic and get
silently rejected in favor of the stale revision. The summary text is now
session-id-only and permanently stable; counts remain fully queryable from
session_events / ``import_fidelity_declaration``. Regression proof:
``tests/unit/sources/test_live_watcher.py::test_live_append_atof_shared_file_multi_session_boundary_retains_all_events``
(also proves idempotent replay of a growth batch).

ATIF+ATOF IDENTITY COLLISION FIX (polylogue-fs1.14): before this fix, both
:func:`parse_atif_document` and :func:`parse_atof_stream` minted the SAME
observer-evidence session identity for a given raw Hermes session id
(``observer:<hermes_session_id>``, via a single shared
``observer_session_provider_id`` helper). Since ``sessions.session_id`` is
computed from ``origin`` plus this native id, an ATIF trajectory export and
an ATOF event stream for the same Hermes session physically collided on one
archive row: whichever artifact was ingested second silently replaced the
first's session_events under the archive's content-hash full-replace rule
(see ``docs/architecture.md``'s "Content-hash idempotency"), destroying that
artifact's evidence rather than retaining both independently -- the ATIF+ATOF
"collapse" this bead fixes. Each artifact family now gets its own
artifact-qualified identity (:func:`atif_session_provider_id` ->
``observer:atif:<hermes_session_id>``, :func:`atof_session_provider_id` ->
``observer:atof:<hermes_session_id>``), so ingesting both for the same
Hermes session retains two independent, non-colliding archive rows. Read-side
correlation across every Hermes artifact class for one raw session id
(conversational state.db session, ATIF, ATOF, verification ledger) is
composed without any physical merge by
``polylogue.insights.hermes_topology_projection.project_hermes_topology``,
which also renders an unpaired ATIF/ATOF trace and a conflicting
producer-reported subagent identity as explicit, visible evidence rather than
silently picking one side.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Literal, TypeAlias

from polylogue.archive.message.roles import Role
from polylogue.core.enums import BlockType, BranchType, MaterialOrigin, Provider
from polylogue.core.json import JSONDocument, JSONValue, json_document

from .base import ParsedContentBlock, ParsedMessage, ParsedSession, ParsedSessionEvent
from .hermes_identity import profile_key as _profile_key
from .hermes_identity import qualified_session_id as _qualified_session_id
from .hermes_identity import split_qualified_session_id as _split_qualified_session_id
from .hermes_state import HermesFidelityCapability, HermesFidelityStatus, HermesImportFidelity

# Real, externally-published ATIF schema-version prefix (NVIDIA NeMo Relay's
# Hermes plugin emits e.g. "ATIF-v1.7") -- see module docstring for sources.
ATIF_SCHEMA_VERSION_PREFIX = "ATIF"

HermesSpanEventType: TypeAlias = Literal[
    "hermes_llm_request_span",
    "hermes_tool_execution_span",
    "hermes_subagent_span",
    "hermes_decision_span",
    "hermes_error_span",
    "hermes_context_span",
    "hermes_observer_span",
    "hermes_atof_unpaired_scope",
    "hermes_subagent_delegation_evidence",
]


def atif_session_provider_id(hermes_session_id: str, profile_key: str | None = None) -> str:
    """Return the ATIF-trajectory observer-evidence session identity.

    Deliberately distinct from both the state-db-ingested conversational
    session id (``<raw_id>@profile-<key>``, see ``hermes_state.py``) and the
    ATOF observer-evidence session id (:func:`atof_session_provider_id`):
    this parser never claims to physically merge into either (see module
    docstring). Consumers correlate the three via
    :func:`hermes_atif_session_id_for` / :func:`hermes_atof_session_id_for`,
    or the composed read model in ``insights.hermes_topology_projection``.

    ``profile_key`` -- when known -- is folded into the identity using the
    exact same qualifier scheme the state.db parser uses
    (``hermes_identity.qualified_session_id``). This is a correctness fix,
    not cosmetic: two separate Hermes installs (profiles) can legitimately
    reuse the same raw session id, and an unqualified ``observer:atif:<raw_id>``
    identity silently collapsed their evidence onto one archive session
    (polylogue-fs1.14). When the profile root is not known at parse time
    (``profile_key=None``), the identity stays unqualified rather than
    guessing -- the fail-closed side of that same fix.
    """
    if profile_key:
        return f"observer:atif:{_qualified_session_id(hermes_session_id, profile_key)}"
    return f"observer:atif:{hermes_session_id}"


def atof_session_provider_id(hermes_session_id: str, profile_key: str | None = None) -> str:
    """Return the ATOF-stream observer-evidence session identity.

    See :func:`atif_session_provider_id` -- an artifact-qualified sibling
    with the same non-collision rationale (both the artifact-family
    qualifier and, when known, the profile qualifier), distinguished by the
    ``atof`` segment rather than ``atif``.
    """
    if profile_key:
        return f"observer:atof:{_qualified_session_id(hermes_session_id, profile_key)}"
    return f"observer:atof:{hermes_session_id}"


def hermes_atif_session_id_for(conversational_session_id: str) -> str:
    """Map a state-db-ingested Hermes session id to its ATIF counterpart.

    Preserves whatever ``@profile-<key>`` qualifier the conversational id
    carries (see :func:`atif_session_provider_id` docstring for why this
    matters) so a reader holding the qualified conversational session id
    looks up the ATIF observer evidence for the *same install*, not merely
    the same raw session id. Falls back to an unqualified id only when the
    conversational id itself carries no profile qualifier.
    """
    raw_id, profile_key = _split_qualified_session_id(conversational_session_id)
    return atif_session_provider_id(raw_id, profile_key)


def hermes_atof_session_id_for(conversational_session_id: str) -> str:
    """Map a state-db-ingested Hermes session id to its ATOF counterpart.

    Mirrors :func:`hermes_atif_session_id_for` for the ATOF artifact family.
    """
    raw_id, profile_key = _split_qualified_session_id(conversational_session_id)
    return atof_session_provider_id(raw_id, profile_key)


def marker_payload(
    hermes_session_id: str,
    steps: Sequence[JSONValue],
    *,
    schema_version: str = "ATIF-v1.7",
    agent: JSONDocument | None = None,
    subagent_trajectories: Sequence[JSONValue] = (),
) -> JSONDocument:
    """Return a real-shaped ATIF trajectory document, for producers/tests.

    Field names match NVIDIA's published NeMo Relay ATIF schema (see module
    docstring): top-level ``schema_version``/``session_id``/``agent``/
    ``steps``/``subagent_trajectories``. ``steps`` accepts any
    ``Sequence[JSONValue]`` (``Sequence`` is covariant, unlike ``list``) on
    purpose: a real acquisition can hand this a malformed stream (a
    non-object entry), and :func:`parse_atif_document` must handle that
    deterministically rather than assuming a caller always validates first.
    """
    return {
        "schema_version": schema_version,
        "session_id": hermes_session_id,
        "agent": agent or {"name": "hermes", "version": "unknown", "model_name": "unknown"},
        "steps": list(steps),
        "subagent_trajectories": list(subagent_trajectories),
    }


def looks_like_atif_payload(payload: JSONDocument) -> bool:
    """Return whether ``payload`` is a real ATIF trajectory document.

    Checks the externally-published top-level shape (module docstring):
    ``schema_version`` prefixed ``"ATIF"``, a string ``session_id``, and a
    ``steps`` list. Unlike the prior version of this function, this matches
    a real, unmodified Hermes/NeMo Relay export -- it does not require any
    Polylogue-specific marker key.
    """
    schema_version = payload.get("schema_version")
    return (
        isinstance(schema_version, str)
        and schema_version.upper().startswith(ATIF_SCHEMA_VERSION_PREFIX)
        and isinstance(payload.get("session_id"), str)
        and isinstance(payload.get("steps"), list)
    )


def looks_like_atof_payload(payload: JSONDocument) -> bool:
    """Return whether ``payload`` is one NeMo Relay ATOF event envelope.

    The bundled Hermes plugin emits ``atof_version: "0.1"`` records with a
    ``scope`` or ``mark`` kind, a stable UUID, timestamp, and event name.  The
    structural check intentionally permits unfamiliar names/categories: those
    are retained as generic observer evidence instead of being discarded when
    the producer evolves.
    """
    return (
        isinstance(payload.get("atof_version"), str)
        and isinstance(payload.get("kind"), str)
        and payload["kind"] in {"scope", "mark"}
        and isinstance(payload.get("uuid"), str)
        and isinstance(payload.get("timestamp"), str)
        and isinstance(payload.get("name"), str)
    )


def parse_atof_stream(
    records: Iterable[object],
    fallback_id: str,
    *,
    profile_root: Path | None = None,
) -> list[ParsedSession]:
    """Normalize a raw Hermes NeMo Relay ATOF JSONL stream by session id.

    This is deliberately observer evidence rather than a transcript import.
    It keeps only correlation/outcome fields that the producer emits
    structurally; prompts, tool arguments, outputs, headers, and error text
    remain in the retained raw blob rather than being copied into index rows.
    Replayed append windows are de-duplicated by the producer's UUID plus the
    scope phase, because a scope's start and end intentionally share a UUID.

    A ``kind=scope`` UUID that never sees both its ``start`` and ``end``
    phase (e.g. a crashed request, or a truncated/rotated file cutting a
    pending scope in half) is real acquisition debt: the span is real but
    incomplete evidence, not indistinguishable from a normal completed pair.
    Those are surfaced as explicit ``hermes_atof_unpaired_scope`` events
    rather than silently left as an ordinary-looking single-phase span.

    ``profile_root`` -- the directory the raw ATOF artifact was acquired
    from, mirroring ``hermes_state.parse_state_db``'s own convention (see
    ``sources/source_parsing.py``/``sources/live/batch.py``) -- is the
    producer-positive evidence used to profile-qualify both this stream's
    own observer session identity and the ``session_links`` parent edge it
    asserts back to the matching state-db conversational session (fs1.14).
    When ``profile_root`` is ``None`` (unknown at parse time), no parent
    edge is asserted: a wrong guess would silently correlate this evidence
    with the wrong install's conversational session, which is worse than
    leaving the correlation unresolved.

    SUBAGENT DELEGATION (polylogue-fs1.14 residual scope): a real
    ``hermes.subagent.start``/``hermes.subagent.stop`` mark carries a
    producer-positive ``data.child_session_id`` -- the raw Hermes session id
    Hermes itself assigned to the spawned subagent. When that child id is
    known AND ``profile_root`` is known AND the child is not the delegating
    session itself (a structurally impossible self-reference), this function
    materializes a real ``session_links`` parent edge (``branch_type=subagent``)
    from the child's own ATOF observer session to the delegating parent's ATOF
    observer session (its *composed* ``observer:atof:<id>[@profile-<key>]``
    identity, not the generic conversational-session correlation edge every
    other ATOF session asserts). If the child's own records also appear in
    this same shared stream (fs1.14's confirmed one-shared-``events.jsonl``-
    per-install shape), the delegation edge supersedes that session's routine
    self-correlation edge; otherwise a minimal delegation-evidence-only
    session is materialized so the edge exists in the archive even before the
    child's own trace evidence is separately ingested. Ambiguous evidence
    (unknown profile, missing/self-referential child id, or the same child id
    claimed by two different parents in one batch) asserts no edge -- visible
    as ``delegation_edge_asserted: false`` on the observing parent's own
    ``hermes_subagent_span`` event, never a guessed link.
    """
    grouped: dict[str, list[ParsedSessionEvent]] = {}
    seen: dict[str, set[tuple[str, str | None]]] = {}
    skipped: dict[str, int] = {}
    scope_phases: dict[str, dict[str, dict[str, tuple[str | None, str | None]]]] = {}
    delegation_claims: dict[str, set[str]] = {}

    for raw_record in records:
        record = json_document(raw_record)
        if not record or not looks_like_atof_payload(record):
            continue
        session_id = _atof_session_id(record) or fallback_id
        uuid = str(record["uuid"])
        scope_category = _optional_str(record.get("scope_category"))
        event_key = (uuid, scope_category)
        session_seen = seen.setdefault(session_id, set())
        if event_key in session_seen:
            continue
        session_seen.add(event_key)
        if record.get("kind") == "scope" and scope_category in {"start", "end"}:
            phases = scope_phases.setdefault(session_id, {}).setdefault(uuid, {})
            phases[scope_category] = (_optional_str(record.get("category")), _optional_str(record.get("timestamp")))
        name = _optional_str(record.get("name")) or ""
        if name.startswith("hermes.subagent."):
            data = json_document(record.get("data")) or {}
            child_session_id = _optional_str(data.get("child_session_id"))
            if child_session_id and child_session_id != session_id:
                delegation_claims.setdefault(child_session_id, set()).add(session_id)
        event = _atof_event(record)
        if event is None:
            skipped[session_id] = skipped.get(session_id, 0) + 1
            continue
        grouped.setdefault(session_id, []).extend(event)

    unpaired_events = {session_id: _unpaired_scope_events(phases) for session_id, phases in scope_phases.items()}
    session_ids = sorted(set(grouped) | set(unpaired_events))
    profile_key_value = _profile_key(profile_root) if profile_root is not None else None

    # Only a producer-positive, unambiguous (single-parent) child id with a
    # known profile qualifies for edge materialization -- fail closed on a
    # conflicting or unqualified claim rather than guessing which parent (if
    # any) is correct.
    delegation_targets: dict[str, str] = (
        {child: next(iter(parents)) for child, parents in delegation_claims.items() if len(parents) == 1}
        if profile_key_value is not None
        else {}
    )
    _mark_delegation_edges_on_subagent_events(grouped, delegation_targets)

    sessions = [
        _atof_session(
            session_id,
            [*grouped.get(session_id, []), *unpaired_events.get(session_id, [])],
            skipped.get(session_id, 0),
            profile_key=profile_key_value,
            delegation_parent_raw_id=delegation_targets.get(session_id),
        )
        for session_id in session_ids
    ]
    stub_children = sorted(child for child in delegation_targets if child not in session_ids)
    sessions.extend(
        _atof_subagent_delegation_stub_session(child, delegation_targets[child], profile_key_value)
        for child in stub_children
    )
    return sessions


def _mark_delegation_edges_on_subagent_events(
    grouped: dict[str, list[ParsedSessionEvent]], delegation_targets: dict[str, str]
) -> None:
    """Record whether each observed subagent mark actually materialized an edge.

    Mutates the already-built ``hermes_subagent_span`` events in place (the
    per-mark materialization decision -- unambiguous single parent, known
    profile -- is only known after every record has been scanned), so the
    *observing parent's own* fidelity declaration can report how many of its
    subagent references actually became real ``session_links`` edges, without
    needing cross-session lookups.

    ``delegation_targets`` is keyed by CHILD session id, so membership alone
    (``child_session_id in delegation_targets``) is not sufficient here: a
    session can emit a ``hermes_subagent_span`` whose ``child_session_id``
    happens to equal a DIFFERENT session's (unambiguously claimed) child --
    e.g. a self-referential mark from session S (S names itself as its own
    child, correctly excluded from ``delegation_targets`` by the
    self-reference guard) coexisting with an unrelated session P that
    legitimately claims S as ITS child (``delegation_targets["S"] == "P"``).
    Checking membership alone would mark S's own self-referential span
    ``delegation_edge_asserted=True`` merely because "S" is a key in the map
    -- contradicting the fail-closed self-reference guarantee. The owning
    session id (the record's own ``session_id``, carried in the event's
    ``session_id`` payload field via ``base_payload``) must match the
    resolved parent for THIS specific child before the flag is set.
    """
    for owning_session_id, events in grouped.items():
        for event in events:
            if event.event_type != "hermes_subagent_span":
                continue
            child_session_id = event.payload.get("child_session_id")
            event.payload["delegation_edge_asserted"] = bool(
                isinstance(child_session_id, str)
                and child_session_id
                and delegation_targets.get(child_session_id) == owning_session_id
            )


def _unpaired_scope_events(phases: dict[str, dict[str, tuple[str | None, str | None]]]) -> list[ParsedSessionEvent]:
    events: list[ParsedSessionEvent] = []
    for uuid, seen_phases in phases.items():
        missing = {"start", "end"} - seen_phases.keys()
        if not missing:
            continue
        (present_phase, (category, timestamp)) = next(iter(seen_phases.items()))
        events.append(
            ParsedSessionEvent(
                event_type="hermes_atof_unpaired_scope",
                timestamp=timestamp,
                payload={
                    "event_uuid": uuid,
                    "category": category,
                    "phase_observed": present_phase,
                    "phase_missing": sorted(missing)[0],
                },
            )
        )
    return events


def _atof_session_id(record: JSONDocument) -> str | None:
    metadata = json_document(record.get("metadata")) or {}
    data = json_document(record.get("data")) or {}
    return _optional_str(metadata.get("session_id")) or _optional_str(data.get("session_id"))


def _atof_event(record: JSONDocument) -> list[ParsedSessionEvent] | None:
    metadata = json_document(record.get("metadata")) or {}
    data = json_document(record.get("data")) or {}
    category = _optional_str(record.get("category"))
    name = _optional_str(record.get("name")) or "unknown"
    scope_category = _optional_str(record.get("scope_category"))
    base_payload: dict[str, object] = {
        "atof_version": record["atof_version"],
        "event_uuid": record["uuid"],
        "event_name": name,
        "event_kind": record["kind"],
        "category": category,
        "scope_category": scope_category,
        "session_id": _atof_session_id(record),
        "task_id": _optional_str(metadata.get("task_id")),
        "turn_id": _optional_str(metadata.get("turn_id")),
        "parent_event_uuid": _optional_str(record.get("parent_uuid")),
    }
    timestamp = _optional_str(record.get("timestamp"))

    if record["kind"] == "scope" and category == "llm":
        payload = {
            **base_payload,
            "model": _optional_str(metadata.get("model")),
            "provider": _optional_str(metadata.get("provider")),
            "has_error": "error" in data,
            "reason": _optional_str(metadata.get("reason")),
        }
        events = [ParsedSessionEvent(event_type="hermes_llm_request_span", timestamp=timestamp, payload=payload)]
        if payload["has_error"]:
            events.append(
                ParsedSessionEvent(
                    event_type="hermes_error_span",
                    timestamp=timestamp,
                    payload={**base_payload, "operation": "llm", "has_error": True},
                )
            )
        return events

    if record["kind"] == "scope" and category == "tool":
        return [
            ParsedSessionEvent(
                event_type="hermes_tool_execution_span",
                timestamp=timestamp,
                payload={
                    **base_payload,
                    "tool_call_id": _optional_str(metadata.get("tool_call_id")),
                    "status": _optional_str(metadata.get("status")),
                },
            )
        ]

    if record["kind"] == "scope" and category == "agent":
        # The outermost scope wrapping the whole Hermes session/agent run
        # (start/end pair sharing one UUID, same mechanism as the llm/tool
        # scopes above but marking session lifetime, not a request). Real
        # events.jsonl evidence: `kind=scope,category=agent` records with
        # `scope_category` start/end and `name` set to the session's own
        # identifier, never a stable event key -- synthesize one so this
        # reads consistently alongside the `hermes.turn.*`/`hermes.session.*`
        # mark-based context events below.
        boundary = f"hermes.session.{scope_category}" if scope_category else "hermes.session.boundary"
        return [
            ParsedSessionEvent(
                event_type="hermes_context_span",
                timestamp=timestamp,
                payload={**base_payload, "context_event": boundary},
            )
        ]

    if name.startswith("hermes.approval."):
        return [
            ParsedSessionEvent(
                event_type="hermes_decision_span",
                timestamp=timestamp,
                payload={
                    **base_payload,
                    "approval_id": _optional_str(data.get("approval_id")),
                    "approved": data.get("approved") if isinstance(data.get("approved"), bool) else None,
                },
            )
        ]

    if name.startswith("hermes.subagent."):
        return [
            ParsedSessionEvent(
                event_type="hermes_subagent_span",
                timestamp=timestamp,
                payload={
                    **base_payload,
                    "child_session_id": _optional_str(data.get("child_session_id")),
                    "child_role": _optional_str(data.get("child_role")),
                    "status": _optional_str(data.get("status")) or _optional_str(metadata.get("status")),
                    # Overwritten by _mark_delegation_edges_on_subagent_events once every
                    # record in the batch has been scanned -- an unambiguous, profile-known
                    # child session_id materializes a real session_links edge; anything else
                    # (unknown profile, missing/self-referential id, contested by two
                    # different parents) leaves this False, visible acquisition debt.
                    "delegation_edge_asserted": False,
                },
            )
        ]

    if name in {"hermes.api.error", "hermes.api.response.unmatched", "hermes.tool.response.unmatched"}:
        operation = "tool" if ".tool." in name else "llm"
        return [
            ParsedSessionEvent(
                event_type="hermes_error_span",
                timestamp=timestamp,
                payload={
                    **base_payload,
                    "operation": operation,
                    "outcome": "unmatched_response" if name.endswith(".unmatched") else "error",
                    "has_error": True,
                },
            )
        ]

    if name.startswith("hermes.turn.") or name.startswith("hermes.session."):
        return [
            ParsedSessionEvent(
                event_type="hermes_context_span",
                timestamp=timestamp,
                payload={**base_payload, "context_event": name},
            )
        ]

    return [
        ParsedSessionEvent(
            event_type="hermes_observer_span",
            timestamp=timestamp,
            payload={**base_payload, "shape": "unrecognized_atof_event"},
        )
    ]


def _atof_session(
    session_id: str,
    events: list[ParsedSessionEvent],
    skipped: int,
    *,
    profile_key: str | None,
    delegation_parent_raw_id: str | None = None,
) -> ParsedSession:
    del skipped  # counts live in session_events/import_fidelity_declaration, never in message text
    # Deliberately stable across every replay/revision of this session (never
    # embeds live event counts): the archive's membership classifier
    # (session_revision_membership.classify_membership_revisions) requires
    # message content to be an unchanging prefix across revisions to safely
    # recognize append-only growth. A count-bearing summary that gets
    # rewritten on every reparse breaks that invariant and makes new events
    # for an already-observed session look like a non-monotonic edit,
    # silently discarding them.
    summary_text = f"Hermes ATOF observer stream: {session_id}"
    provider_session_id = atof_session_provider_id(session_id, profile_key)
    branch_type: BranchType | None = None
    if delegation_parent_raw_id and profile_key:
        # Subagent-delegation edge (fs1.14 residual scope): a real
        # hermes.subagent.* mark named this session as a child of another
        # session in the same batch. That edge supersedes the routine
        # self-correlation edge below -- both remain read-side derivable via
        # hermes_atof_session_id_for, so nothing is lost, only the single
        # session_links parent slot is spent on the more specific claim.
        parent_session_provider_id: str | None = atof_session_provider_id(delegation_parent_raw_id, profile_key)
        branch_type = BranchType.SUBAGENT
        correlation_note = (
            "ATOF runtime evidence is stored as its own observer session (observer:atof:<id>"
            "[@profile-<key>]), not merged into the transcript. A real hermes.subagent.* mark named "
            "this session as a subagent delegated from the parent observer session referenced above; "
            "correlate with that parent's own conversational/ATIF/ATOF evidence and this session's own "
            "state-db conversational counterpart (hermes_atof_session_id_for) separately."
        )
    else:
        # The parent join key: asserting it makes the generic session_links write
        # path (archive_tiers/write.py::_write_session_link, unchanged by this
        # parser) resolve this observer session against the profile-qualified
        # state-db conversational session sharing the same raw id -- resolvable
        # once that session is ingested, visible as unresolved debt otherwise.
        # Only asserted when the profile is known (see parse_atof_stream
        # docstring): an unqualified raw id is not a safe cross-profile join key.
        parent_session_provider_id = _qualified_session_id(session_id, profile_key) if profile_key else None
        correlation_note = (
            "ATOF runtime evidence is stored as its own observer session (observer:atof:<id>"
            "[@profile-<key>]), not merged into the transcript; correlate with the "
            "state-db-ingested conversational session and any ATIF observer session "
            "(observer:atif:<id>[@profile-<key>]) sharing this raw Hermes session id."
        )
    return ParsedSession(
        source_name=Provider.HERMES,
        provider_session_id=provider_session_id,
        title=f"Hermes ATOF observer stream: {session_id}",
        messages=[
            ParsedMessage(
                provider_message_id=f"{provider_session_id}:atof-summary",
                role=Role.SYSTEM,
                text=summary_text,
                blocks=[ParsedContentBlock(type=BlockType.TEXT, text=summary_text)],
                position=0,
                variant_index=0,
                is_active_path=True,
                material_origin=MaterialOrigin.RUNTIME_CONTEXT,
            )
        ],
        session_events=[
            ParsedSessionEvent(
                event_type="hermes_observer_trace_correlation",
                payload={
                    "hermes_conversation_session_id_prefix": session_id,
                    "join_key": "sessions.native_id",
                    "profile_qualified": profile_key is not None,
                    "asserted_parent_session_provider_id": parent_session_provider_id,
                    "delegated_from_session_id": delegation_parent_raw_id,
                    "note": correlation_note,
                },
            ),
            *events,
        ],
        parent_session_provider_id=parent_session_provider_id,
        branch_type=branch_type,
        ingest_flags=["hermes:atof-observer"],
    )


def _atof_subagent_delegation_stub_session(
    child_session_id: str, parent_raw_id: str, profile_key: str | None
) -> ParsedSession:
    """Materialize a minimal delegation-evidence session for a subagent whose
    own ATOF/ATIF records were not present in this batch.

    The edge itself -- a real ``hermes.subagent.start`` mark naming this raw
    session id as a child of ``parent_raw_id`` -- is producer-positive
    evidence even without the child's own trace content, so this session
    exists purely to carry the ``session_links`` parent edge into the
    archive. If the child's own trace evidence is separately ingested later
    (a different ATOF/ATIF batch), the archive's content-hash full-replace
    rule updates this same computed session id in place rather than
    duplicating it -- ``provider_session_id`` is identical either way.
    """
    provider_session_id = atof_session_provider_id(child_session_id, profile_key)
    parent_session_provider_id = atof_session_provider_id(parent_raw_id, profile_key)
    summary_text = f"Hermes ATOF subagent delegation evidence: {child_session_id}"
    return ParsedSession(
        source_name=Provider.HERMES,
        provider_session_id=provider_session_id,
        title=summary_text,
        messages=[
            ParsedMessage(
                provider_message_id=f"{provider_session_id}:atof-delegation-summary",
                role=Role.SYSTEM,
                text=summary_text,
                blocks=[ParsedContentBlock(type=BlockType.TEXT, text=summary_text)],
                position=0,
                variant_index=0,
                is_active_path=True,
                material_origin=MaterialOrigin.RUNTIME_CONTEXT,
            )
        ],
        session_events=[
            ParsedSessionEvent(
                event_type="hermes_subagent_delegation_evidence",
                payload={
                    "child_session_id": child_session_id,
                    "parent_session_id": parent_raw_id,
                    "note": (
                        "This session's own ATOF/ATIF trace records were not present in the batch "
                        "that observed the delegation mark; only the delegation edge itself is "
                        "materialized here, never fabricated content."
                    ),
                },
            )
        ],
        parent_session_provider_id=parent_session_provider_id,
        branch_type=BranchType.SUBAGENT,
        ingest_flags=["hermes:atof-observer", "hermes:atof-subagent-delegation-stub"],
    )


def parse_atif_document(
    payload: JSONDocument,
    fallback_id: str,
    *,
    profile_root: Path | None = None,
) -> list[ParsedSession]:
    """Parse one Hermes ATIF trajectory document into a parent session plus
    any materialized subagent-delegation child sessions.

    Ambiguous input is handled deterministically: a step with none of the
    documented shapes (``tool_calls``, ``message``, ``observation``) becomes
    a generic ``hermes_observer_span`` event rather than being dropped; a
    non-object step, or a ``tool_calls`` entry missing its required
    ``tool_call_id``/``function_name``, is skipped and counted (see
    :func:`import_fidelity_declaration`), never silently coerced. Message
    and observation text is never copied verbatim (see module docstring
    payload-hygiene note) -- only bounded evidence (presence, character
    length) is recorded.

    ``profile_root`` mirrors :func:`parse_atof_stream`'s parameter of the
    same name: producer-positive evidence (the directory this ATIF document
    was acquired from) used to profile-qualify the observer session identity
    and the ``session_links`` parent edge asserted back to the matching
    state-db conversational session. ``None`` fails closed -- no parent edge
    is asserted rather than guessing.

    SUBAGENT DELEGATION (polylogue-fs1.14 residual scope): each
    ``subagent_trajectories`` entry with a producer-positive, non-empty
    ``session_id`` distinct from this document's own ``session_id`` (a
    structurally impossible self-reference is never materialized) becomes a
    real child :class:`ParsedSession`, parsed from that entry's own ``steps``
    the same way the parent document's ``steps`` are, with a
    ``session_links`` parent edge (``branch_type=subagent``) back to this
    document's composed ATIF observer identity -- only asserted when
    ``profile_root`` is also known, the same fail-closed rule
    :func:`parse_atof_stream` uses. No real ATIF fixture observed so far
    carries any ``subagent_trajectories`` evidence (every live trajectory
    sampled has an empty/absent list -- see module docstring), so this is
    implemented and unit-tested against the documented schema, but the
    fidelity capability stays ``inferred``, never ``exact``, until real bytes
    prove it (see :func:`import_fidelity_declaration`).
    """
    session_id = str(payload.get("session_id") or fallback_id)
    agent = json_document(payload.get("agent")) or {}
    model_name = _optional_str(agent.get("model_name"))
    steps_value = payload.get("steps")
    raw_steps: list[JSONValue] = steps_value if isinstance(steps_value, list) else []
    subagents_value = payload.get("subagent_trajectories")
    raw_subagents: list[JSONValue] = subagents_value if isinstance(subagents_value, list) else []

    events: list[ParsedSessionEvent] = []
    skipped = 0
    for index, raw_step in enumerate(raw_steps):
        step = json_document(raw_step)
        # `json_document()` returns `{}` (falsy), never `None`, for a
        # non-object entry -- `not step` is the real "malformed" check
        # (also matches a genuinely empty step object: neither case carries
        # a recognizable shape, so both are skipped and counted the same way
        # `_events_for_step`'s tool_call entries are).
        if not step:
            skipped += 1
            continue
        step_events, step_skipped = _events_for_step(step, index, model_name)
        events.extend(step_events)
        skipped += step_skipped

    # Deliberately stable across every replay/revision of this session (never
    # embeds live step/event counts): see _atof_session's identical note --
    # the archive's membership classifier requires message content to be an
    # unchanging prefix across revisions to safely recognize append-only
    # growth. Counts remain fully queryable from session_events /
    # import_fidelity_declaration.
    summary_text = f"Hermes ATIF trajectory: {session_id}"
    profile_key_value = _profile_key(profile_root) if profile_root is not None else None
    provider_session_id = atif_session_provider_id(session_id, profile_key_value)
    parent_session_provider_id = _qualified_session_id(session_id, profile_key_value) if profile_key_value else None

    child_sessions: list[ParsedSession] = []
    for index, raw_subagent in enumerate(raw_subagents):
        subagent = json_document(raw_subagent)
        if not subagent:
            skipped += 1
            continue
        subagent_session_id = _optional_str(subagent.get("session_id"))
        delegation_edge_asserted = bool(profile_key_value and subagent_session_id and subagent_session_id != session_id)
        events.append(_subagent_span_event(subagent, index, delegation_edge_asserted=delegation_edge_asserted))
        if delegation_edge_asserted and subagent_session_id is not None:
            child_sessions.append(
                _atif_subagent_child_session(
                    subagent,
                    subagent_session_id,
                    parent_provider_session_id=provider_session_id,
                    profile_key=profile_key_value,
                )
            )

    parent_session = ParsedSession(
        source_name=Provider.HERMES,
        provider_session_id=provider_session_id,
        title=f"Hermes ATIF trajectory: {session_id}",
        messages=[
            ParsedMessage(
                provider_message_id=f"{provider_session_id}:trace-summary",
                role=Role.SYSTEM,
                text=summary_text,
                blocks=[ParsedContentBlock(type=BlockType.TEXT, text=summary_text)],
                position=0,
                variant_index=0,
                is_active_path=True,
                material_origin=MaterialOrigin.RUNTIME_CONTEXT,
            )
        ],
        session_events=[
            ParsedSessionEvent(
                event_type="hermes_observer_trace_correlation",
                payload={
                    "hermes_conversation_session_id_prefix": session_id,
                    "join_key": "sessions.native_id",
                    "profile_qualified": profile_key_value is not None,
                    "asserted_parent_session_provider_id": parent_session_provider_id,
                    "note": (
                        "This session carries ATIF trajectory evidence only (observer:atif:<id>"
                        "[@profile-<key>]); correlate with the state-db-ingested conversational session "
                        "and any ATOF observer session (observer:atof:<id>[@profile-<key>]) sharing this "
                        "raw Hermes session id."
                    ),
                },
            ),
            *events,
        ],
        parent_session_provider_id=parent_session_provider_id,
        ingest_flags=["hermes:atif-trajectory"],
    )
    return [parent_session, *child_sessions]


def _atif_subagent_child_session(
    subagent: JSONDocument,
    subagent_session_id: str,
    *,
    parent_provider_session_id: str,
    profile_key: str | None,
) -> ParsedSession:
    """Materialize one ``subagent_trajectories`` entry as its own ATIF child session.

    Parsed from the entry's own ``steps`` with the exact same step-shape
    handling :func:`parse_atif_document` uses for the top-level document
    (ambiguous/malformed steps skipped-and-counted, never dropped silently),
    so a real subagent trajectory's evidence is retained with the same
    fidelity as its parent's, never a bare summary stub.
    """
    agent = json_document(subagent.get("agent")) or {}
    model_name = _optional_str(agent.get("model_name"))
    steps_value = subagent.get("steps")
    raw_steps: list[JSONValue] = steps_value if isinstance(steps_value, list) else []

    events: list[ParsedSessionEvent] = []
    for index, raw_step in enumerate(raw_steps):
        step = json_document(raw_step)
        if not step:
            continue
        step_events, _skipped = _events_for_step(step, index, model_name)
        events.extend(step_events)

    summary_text = f"Hermes ATIF subagent trajectory: {subagent_session_id}"
    provider_session_id = atif_session_provider_id(subagent_session_id, profile_key)
    return ParsedSession(
        source_name=Provider.HERMES,
        provider_session_id=provider_session_id,
        title=summary_text,
        messages=[
            ParsedMessage(
                provider_message_id=f"{provider_session_id}:trace-summary",
                role=Role.SYSTEM,
                text=summary_text,
                blocks=[ParsedContentBlock(type=BlockType.TEXT, text=summary_text)],
                position=0,
                variant_index=0,
                is_active_path=True,
                material_origin=MaterialOrigin.RUNTIME_CONTEXT,
            )
        ],
        session_events=[
            ParsedSessionEvent(
                event_type="hermes_observer_trace_correlation",
                payload={
                    "hermes_conversation_session_id_prefix": subagent_session_id,
                    "join_key": "sessions.native_id",
                    "profile_qualified": profile_key is not None,
                    "asserted_parent_session_provider_id": parent_provider_session_id,
                    "note": (
                        "This session carries ATIF subagent-trajectory evidence delegated from the "
                        "parent observer session referenced above (a subagent_trajectories entry); "
                        "correlate with that parent's own conversational/ATOF evidence and this "
                        "session's own state-db conversational counterpart separately."
                    ),
                },
            ),
            *events,
        ],
        parent_session_provider_id=parent_provider_session_id,
        branch_type=BranchType.SUBAGENT,
        ingest_flags=["hermes:atif-trajectory", "hermes:atif-subagent-child"],
    )


def _events_for_step(step: JSONDocument, index: int, model_name: str | None) -> tuple[list[ParsedSessionEvent], int]:
    tool_calls = step.get("tool_calls")
    message = step.get("message")
    observation = step.get("observation")
    events: list[ParsedSessionEvent] = []
    skipped = 0

    if isinstance(tool_calls, list) and tool_calls:
        for tool_call_raw in tool_calls:
            tool_call = json_document(tool_call_raw)
            tool_call_id = tool_call.get("tool_call_id") if tool_call else None
            function_name = tool_call.get("function_name") if tool_call else None
            # `json_document()` returns `{}` (falsy), never `None`, for a
            # non-document entry -- `not tool_call` catches that case.
            if not tool_call or not isinstance(tool_call_id, str) or not isinstance(function_name, str):
                skipped += 1
                continue
            arguments = tool_call.get("arguments")
            events.append(
                ParsedSessionEvent(
                    event_type="hermes_tool_execution_span",
                    payload={
                        "step_index": index,
                        "tool_call_id": tool_call_id,
                        "function_name": function_name,
                        "has_arguments": arguments is not None,
                        "has_observation": observation is not None,
                    },
                )
            )
        return events, skipped

    if isinstance(message, str) and message:
        events.append(
            ParsedSessionEvent(
                event_type="hermes_llm_request_span",
                payload={
                    "step_index": index,
                    "model": model_name,
                    "message_char_len": len(message),
                },
            )
        )
        return events, skipped

    if observation is not None:
        events.append(
            ParsedSessionEvent(
                event_type="hermes_observer_span",
                payload={"step_index": index, "shape": "observation_only"},
            )
        )
        return events, skipped

    # No recognized shape (no tool_calls, no message, no observation): ambiguous
    # input is never dropped, per AC -- surfaced as a generic observer span.
    events.append(
        ParsedSessionEvent(
            event_type="hermes_observer_span",
            payload={"step_index": index, "shape": "unrecognized", "source": step.get("source")},
        )
    )
    return events, skipped


def _subagent_span_event(
    subagent: JSONDocument, index: int, *, delegation_edge_asserted: bool = False
) -> ParsedSessionEvent:
    agent = json_document(subagent.get("agent")) or {}
    steps = subagent.get("steps")
    return ParsedSessionEvent(
        event_type="hermes_subagent_span",
        payload={
            "subagent_index": index,
            "subagent_session_id": _optional_str(subagent.get("session_id")),
            "subagent_agent_name": _optional_str(agent.get("name")),
            "subagent_step_count": len(steps) if isinstance(steps, list) else None,
            # Whether this subagent_trajectories entry's own session_id was
            # producer-positive, distinct from this document's own id, and
            # backed by a known profile root -- the exact conditions under
            # which parse_atif_document materialized a real session_links
            # child session for it. False is visible acquisition debt, never
            # silently indistinguishable from "no evidence at all".
            "delegation_edge_asserted": delegation_edge_asserted,
        },
    )


def import_fidelity_declaration(session: ParsedSession) -> HermesImportFidelity:
    """Declare the fidelity this ATIF importer can substantiate.

    A redacted ATIF-v1.7 export generated by the bundled Hermes NeMo Relay
    plugin confirms the top-level wire shape and message-only step mapping.
    Those observed LLM spans are ``exact``; shapes not present in that run
    remain ``inferred``. ``decision_points``/``error_taxonomy`` are honestly
    ``absent`` -- ATIF carries no approval/error-hook vocabulary (that lives
    only in the separate raw ATOF event stream, not ingested by this pass).
    """
    if "hermes:atof-observer" in session.ingest_flags:
        return _atof_import_fidelity_declaration(session)

    span_events = [
        event
        for event in session.session_events
        if event.event_type
        in {"hermes_llm_request_span", "hermes_tool_execution_span", "hermes_subagent_span", "hermes_observer_span"}
    ]
    total = len(span_events)
    llm_spans = sum(1 for event in span_events if event.event_type == "hermes_llm_request_span")
    tool_spans = sum(1 for event in span_events if event.event_type == "hermes_tool_execution_span")
    subagent_spans = sum(1 for event in span_events if event.event_type == "hermes_subagent_span")
    generic_spans = sum(1 for event in span_events if event.event_type == "hermes_observer_span")
    materialized_delegation_edges = sum(
        1
        for event in span_events
        if event.event_type == "hermes_subagent_span" and event.payload.get("delegation_edge_asserted") is True
    )
    is_delegated_child_session = session.branch_type == BranchType.SUBAGENT
    topology_edges_observed = materialized_delegation_edges + (1 if is_delegated_child_session else 0)

    def capability(
        observed: int,
        detail: str,
        *,
        verified_by_real_fixture: bool = False,
    ) -> HermesFidelityCapability:
        status: HermesFidelityStatus = (
            "exact" if observed and verified_by_real_fixture else "inferred" if observed else "absent"
        )
        return HermesFidelityCapability(
            status=status, observed=observed, expected=max(total, 1), counts={}, detail=detail
        )

    capabilities = {
        "llm_request_spans": capability(
            llm_spans,
            "Message-only trajectory steps mapped to LLM response evidence (text length only, no content); "
            "confirmed by the real NeMo Relay ATIF-v1.7 fixture.",
            verified_by_real_fixture=True,
        ),
        "tool_execution_spans": capability(
            tool_spans,
            "tool_calls entries mapped to tool execution spans (ids/names, arguments presence only); "
            "confirmed by a real ATIF-v1.7 step with 4 parallel tool_calls plus correlated observation.results.",
            verified_by_real_fixture=True,
        ),
        "subagent_delegation": capability(
            subagent_spans,
            "subagent_trajectories entries recorded as delegation evidence and, when a "
            "producer-positive child session_id and a known profile root are both present, "
            "materialized as a real child ATIF session with a session_links parent edge "
            "(branch_type=subagent, see topology_edges) -- also surfaced read-side by "
            "insights.hermes_topology_projection.",
        ),
        "decision_points": HermesFidelityCapability(
            status="absent",
            observed=0,
            expected=max(total, 1),
            counts={},
            detail="ATIF's documented step schema carries no approval-hook vocabulary; that evidence "
            "exists only in the raw ATOF event stream, not ingested by this pass (see fs1.2.1).",
        ),
        "error_taxonomy": HermesFidelityCapability(
            status="absent",
            observed=0,
            expected=max(total, 1),
            counts={},
            detail="ATIF's documented step schema carries no error-hook vocabulary; that evidence "
            "exists only in the raw ATOF event stream, not ingested by this pass (see fs1.2.1).",
        ),
        "topology_edges": HermesFidelityCapability(
            status="inferred" if topology_edges_observed else "absent",
            observed=topology_edges_observed,
            expected=max(subagent_spans, 1) if not is_delegated_child_session else 1,
            counts={},
            detail=(
                "subagent_trajectories entries with a producer-positive session_id, distinct from "
                "this session's own id, and a known profile root are materialized as real "
                "session_links parent edges (branch_type=subagent) on the child's own ATIF observer "
                "session. No real ATIF fixture observed so far carries any subagent_trajectories "
                "evidence, so this mapping remains unverified against real bytes -- inferred, never "
                "exact, until proven (unlike the ATOF hermes.subagent.* route, see "
                "_atof_import_fidelity_declaration)."
            ),
        ),
        "parent_session_link": _parent_session_link_capability(session),
    }
    if generic_spans:
        capabilities["unrecognized_step_shapes"] = HermesFidelityCapability(
            status="degraded",
            observed=generic_spans,
            expected=max(total, 1),
            counts={},
            detail="Steps matching none of the documented shapes (tool_calls/message/observation) are "
            "retained as generic evidence, never dropped.",
        )
    caveats = tuple(f"{name}: {cap.detail}" for name, cap in capabilities.items() if cap.status != "exact")
    return HermesImportFidelity(
        producer="Hermes NeMo Relay ATIF trajectory export (live-generated ATIF-v1.7 fixture verified)",
        schema_version=1,
        profile_namespace=None,
        acquisition_method="json_fallback",
        retained_blob_reproducibility=HermesFidelityCapability(
            status="exact",
            observed=1,
            expected=1,
            counts={},
            detail="The raw ATIF document bytes are retained before parsing, like every other origin.",
        ),
        capabilities=capabilities,
        caveats=caveats,
    )


def _atof_import_fidelity_declaration(session: ParsedSession) -> HermesImportFidelity:
    """Declare fidelity for the real producer-shaped ATOF stream route."""
    events = session.session_events

    def observed(event_type: str) -> int:
        return sum(event.event_type == event_type for event in events)

    def exact_if_observed(count: int, detail: str) -> HermesFidelityCapability:
        return HermesFidelityCapability(
            status="exact" if count else "absent",
            observed=count,
            expected=max(len(events) - 1, 1),
            counts={},
            detail=detail,
        )

    llm = observed("hermes_llm_request_span")
    tool = observed("hermes_tool_execution_span")
    decisions = observed("hermes_decision_span")
    errors = observed("hermes_error_span")
    subagent_marks = observed("hermes_subagent_span")
    delegation_stub_evidence = observed("hermes_subagent_delegation_evidence")
    subagents = subagent_marks + delegation_stub_evidence
    context = observed("hermes_context_span")
    generic = observed("hermes_observer_span")
    materialized_delegation_edges = sum(
        1
        for event in events
        if event.event_type == "hermes_subagent_span" and event.payload.get("delegation_edge_asserted") is True
    )
    is_delegated_child_session = session.branch_type == BranchType.SUBAGENT
    topology_edges_observed = materialized_delegation_edges + (1 if is_delegated_child_session else 0)
    capabilities = {
        "llm_request_spans": exact_if_observed(
            llm,
            "ATOF LLM scope start/end records retain correlation, model/provider, and structural error presence only.",
        ),
        "tool_execution_spans": exact_if_observed(
            tool,
            "ATOF tool scope start/end records retain tool-call correlation and producer status, never arguments/output.",
        ),
        "decision_points": exact_if_observed(
            decisions,
            "ATOF hermes.approval.* marks retain approval correlation and boolean decision outcome.",
        ),
        "error_taxonomy": exact_if_observed(
            errors,
            "ATOF LLM scope ends with a structural error field become error evidence without copying error text.",
        ),
        "subagent_delegation": exact_if_observed(
            subagents,
            "ATOF hermes.subagent.* marks retain child-session correlation and role/status evidence.",
        ),
        "context_events": exact_if_observed(
            context,
            "ATOF hermes.turn.*/hermes.session.* marks and the outer session-scope "
            "start/end pair retain context-event identity without duplicating context content.",
        ),
        "topology_edges": HermesFidelityCapability(
            status="exact" if topology_edges_observed else "absent",
            observed=topology_edges_observed,
            expected=max(subagent_marks, 1) if not is_delegated_child_session else 1,
            counts={},
            detail=(
                "A real hermes.subagent.* mark's producer-positive child_session_id, with a known "
                "profile root and no conflicting parent claim, is materialized as a real session_links "
                "parent edge (branch_type=subagent) on the child's own ATOF observer session -- "
                "confirmed end-to-end against the real NeMo Relay ATOF fixture's hermes.subagent.start "
                "mark. Ambiguous evidence (unknown profile, missing/self-referential/contested child id) "
                "asserts no edge, visible as delegation_edge_asserted=false on the observing session's "
                "own hermes_subagent_span event."
            ),
        ),
        "parent_session_link": _parent_session_link_capability(session),
    }
    if generic:
        capabilities["unrecognized_atof_events"] = HermesFidelityCapability(
            status="degraded",
            observed=generic,
            expected=max(len(events) - 1, 1),
            counts={},
            detail="Structurally valid but unknown ATOF names/categories are retained as generic observer evidence.",
        )
    unpaired = observed("hermes_atof_unpaired_scope")
    if unpaired:
        capabilities["unpaired_scope_debt"] = HermesFidelityCapability(
            status="degraded",
            observed=unpaired,
            expected=max(len(events) - 1, 1),
            counts={},
            detail="A scope UUID that never saw both its start and end phase (crashed request, or a "
            "truncated/rotated file cutting a pending scope in half) is surfaced as explicit acquisition "
            "debt, not silently indistinguishable from a normal completed pair.",
        )
    caveats = tuple(f"{name}: {cap.detail}" for name, cap in capabilities.items() if cap.status != "exact")
    return HermesImportFidelity(
        producer="Hermes NeMo Relay ATOF stream (live-generated v0.1 fixture verified)",
        schema_version=1,
        profile_namespace=None,
        acquisition_method="jsonl_stream",
        retained_blob_reproducibility=HermesFidelityCapability(
            status="exact",
            observed=1,
            expected=1,
            counts={},
            detail="The complete ATOF JSONL byte stream is retained before normalization.",
        ),
        capabilities=capabilities,
        caveats=caveats,
    )


def _parent_session_link_capability(session: ParsedSession) -> HermesFidelityCapability:
    """Declare fidelity for the ``session_links`` parent edge to the conversational session.

    This is the correlation the module docstring's "Session correlation"
    section used to describe as read-side-only (``hermes_atif_session_id_for``
    / ``hermes_atof_session_id_for``). fs1.14 also asserts it as a real
    ``parent_session_provider_id`` at parse
    time when the profile root is known -- ``inferred`` (not ``exact``)
    because the archive has not yet confirmed the target conversational
    session was actually ingested; that confirmation is the generic
    ``session_links`` resolution machinery's job, not this parser's.
    """
    if session.parent_session_provider_id and session.branch_type == BranchType.SUBAGENT:
        return HermesFidelityCapability(
            status="inferred",
            observed=1,
            expected=1,
            counts={},
            detail=(
                "A profile-qualified session_links parent edge was asserted to the DELEGATING "
                "session's own observer evidence (subagent delegation), superseding the routine "
                "conversational-session correlation edge for this child session; resolution against "
                "an actually-ingested session happens generically at write time."
            ),
        )
    if session.parent_session_provider_id:
        return HermesFidelityCapability(
            status="inferred",
            observed=1,
            expected=1,
            counts={},
            detail=(
                "A profile-qualified session_links parent edge was asserted to the state-db "
                "conversational session sharing this raw Hermes session id and profile root; "
                "resolution against an actually-ingested session happens generically at write time."
            ),
        )
    return HermesFidelityCapability(
        status="absent",
        observed=0,
        expected=1,
        counts={},
        detail=(
            "No profile root was available at ingest time, so no session_links parent edge was "
            "asserted -- an unqualified raw session id is not a safe cross-profile join key "
            "(fails closed rather than guessing)."
        ),
    )


def _optional_str(value: object) -> str | None:
    return value if isinstance(value, str) and value else None


__all__ = [
    "ATIF_SCHEMA_VERSION_PREFIX",
    "HermesSpanEventType",
    "atif_session_provider_id",
    "atof_session_provider_id",
    "hermes_atif_session_id_for",
    "hermes_atof_session_id_for",
    "import_fidelity_declaration",
    "looks_like_atof_payload",
    "looks_like_atif_payload",
    "marker_payload",
    "parse_atif_document",
    "parse_atof_stream",
]
