"""Hermes NeMo Relay ATIF observer-trajectory importer (fs1.2).

Imports a Hermes NeMo Relay Agent Trajectory Interchange Format (ATIF)
export as runtime-evidence: tool-call steps become tool-execution spans,
message-only steps become LLM-response evidence, and ``subagent_trajectories``
entries become subagent-delegation evidence.

Review-fix note (2026-07-14, replaces the original honesty caveat): a
reviewer found the originally-shipped detector could only ever match a
synthetic ``polylogue_artifact: "hermes_atif_trace"`` marker key invented by
this repo's own test helper -- no real, unmodified Hermes/NeMo Relay export
could ever reach this parser. That gap is now closed: ``looks_like_atif_payload``
checks the real, externally-published ATIF top-level document shape
(``schema_version`` prefixed ``"ATIF"``, ``session_id``, ``steps``), sourced
from NVIDIA's own NeMo Relay documentation:

- https://docs.nvidia.com/nemo/relay/nemo-relay-cli/hermes (Hermes hook
  vocabulary NeMo Relay captures: pre/post_api_request, pre/post_tool_call,
  subagent_start/stop, api_request_error, etc.)
- https://docs.nvidia.com/nemo/relay/about-nemo-relay/concepts/events (ATOF
  event envelope: ``atof_version``, ``kind`` in {scope, mark}, ``category``,
  ``scope_category``)
- https://github.com/HexLab98/hermes-agent-fork/blob/main/plugins/observability/nemo_relay/README.md
  (ATIF top-level shape: ``schema_version: "ATIF-v1.7"``, ``session_id``,
  ``agent``, ``steps``, ``subagent_trajectories``; step fields ``source``,
  ``tool_calls`` (``function_name``/``arguments``/``tool_call_id``),
  ``observation``, ``message``)

A redacted real ATIF document generated by the bundled Hermes NeMo Relay plugin
is checked into ``tests/fixtures/hermes/atif/``. It confirms the exported
top-level shape and the message-only step mapping used by this parser:
``import_fidelity_declaration`` marks that capability ``exact``. The live
sample contained no ``tool_calls``, observation, or subagent trajectory shape,
so those mappings intentionally remain ``inferred`` rather than being promoted
from documentation alone.

Scope narrowing (disclosed, not silent): ATIF's *documented* step schema
(``source``/``tool_calls``/``observation``/``message``) carries no
approval-hook or error-hook data -- that vocabulary exists only in the raw
ATOF event stream (JSONL, one Hermes hook per line), which this importer
does not ingest. ``decision_points``/``error_taxonomy`` fidelity capabilities
are honestly declared ``absent`` rather than fabricated from hook types this
schema doesn't carry. Ingesting the raw ATOF stream is a materially larger,
differently-shaped change (JSONL grouped by session, not a single document)
and is intentionally outside this ATIF importer; it must be designed as its
own JSONL/session-grouping acquisition path rather than silently fabricated
from trajectory documents.

Payload hygiene: unlike a raw ATOF hook (ids/timings/outcomes only), a real
ATIF step's ``message``/``observation`` fields carry actual response text --
that is ATIF's purpose (replay/evaluation). To keep this importer consistent
with the payload-hygiene rule the rest of the Hermes bridge enforces
(``sources.hooks._reject_duplicated_transcript``: evidence, never a second
copy of conversation text), this parser deliberately records only bounded,
non-content evidence about that text (presence, character length) rather
than copying it. Full-transcript ATIF import (treating steps as real
session messages) is a distinct, larger product decision -- deferred to
fs1.2.1, not assumed here.

Session correlation (design's "join key: Hermes session id ->
sessions.native_id"): this parser produces its own observer-evidence session
identity (``observer:<hermes_session_id>``) rather than physically merging
trajectory evidence into the state-db-ingested conversational session's
message tree -- a physical merge across two independently-acquired artifacts
for the same logical Hermes session is a session-identity/lineage design
decision (topology_edges / session_links) that is explicitly deferred, not
silently assumed. Read-side correlation by the shared Hermes session id
remains possible today via ``hermes_observer_session_id_for``.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, TypeAlias

from polylogue.archive.message.roles import Role
from polylogue.core.enums import BlockType, MaterialOrigin, Provider
from polylogue.core.json import JSONDocument, JSONValue, json_document

from .base import ParsedContentBlock, ParsedMessage, ParsedSession, ParsedSessionEvent
from .hermes_state import HermesFidelityCapability, HermesFidelityStatus, HermesImportFidelity

# Real, externally-published ATIF schema-version prefix (NVIDIA NeMo Relay's
# Hermes plugin emits e.g. "ATIF-v1.7") -- see module docstring for sources.
ATIF_SCHEMA_VERSION_PREFIX = "ATIF"

HermesSpanEventType: TypeAlias = Literal[
    "hermes_llm_request_span",
    "hermes_tool_execution_span",
    "hermes_subagent_span",
    "hermes_observer_span",
]


def observer_session_provider_id(hermes_session_id: str) -> str:
    """Return the observer-evidence session identity for a Hermes session id.

    Deliberately distinct from the state-db-ingested conversational session
    id (``<raw_id>@profile-<key>``, see ``hermes_state.py``): this parser
    never claims to physically merge into that session's message tree (see
    module docstring). Consumers correlate the two via
    ``hermes_observer_session_id_for``.
    """
    return f"observer:{hermes_session_id}"


def hermes_observer_session_id_for(conversational_session_id: str) -> str:
    """Map a state-db-ingested Hermes session id to its observer counterpart.

    Strips the ``@profile-<key>`` qualifier (observer traces carry no
    profile-root context of their own) so a reader holding the qualified
    conversational session id can look up its observer evidence.
    """
    raw_id = conversational_session_id.split("@profile-", 1)[0]
    return observer_session_provider_id(raw_id)


def marker_payload(
    hermes_session_id: str,
    steps: Sequence[JSONValue],
    *,
    schema_version: str = "ATIF-v1.7",
    agent: JSONDocument | None = None,
    subagent_trajectories: Sequence[JSONValue] = (),
) -> JSONDocument:
    """Return a real-shaped ATIF trajectory document, for producers/tests.

    Field names match NVIDIA's published NeMo Relay ATIF schema (see module
    docstring): top-level ``schema_version``/``session_id``/``agent``/
    ``steps``/``subagent_trajectories``. ``steps`` accepts any
    ``Sequence[JSONValue]`` (``Sequence`` is covariant, unlike ``list``) on
    purpose: a real acquisition can hand this a malformed stream (a
    non-object entry), and :func:`parse_atif_document` must handle that
    deterministically rather than assuming a caller always validates first.
    """
    return {
        "schema_version": schema_version,
        "session_id": hermes_session_id,
        "agent": agent or {"name": "hermes", "version": "unknown", "model_name": "unknown"},
        "steps": list(steps),
        "subagent_trajectories": list(subagent_trajectories),
    }


def looks_like_atif_payload(payload: JSONDocument) -> bool:
    """Return whether ``payload`` is a real ATIF trajectory document.

    Checks the externally-published top-level shape (module docstring):
    ``schema_version`` prefixed ``"ATIF"``, a string ``session_id``, and a
    ``steps`` list. Unlike the prior version of this function, this matches
    a real, unmodified Hermes/NeMo Relay export -- it does not require any
    Polylogue-specific marker key.
    """
    schema_version = payload.get("schema_version")
    return (
        isinstance(schema_version, str)
        and schema_version.upper().startswith(ATIF_SCHEMA_VERSION_PREFIX)
        and isinstance(payload.get("session_id"), str)
        and isinstance(payload.get("steps"), list)
    )


def parse_atif_document(payload: JSONDocument, fallback_id: str) -> ParsedSession:
    """Parse one Hermes ATIF trajectory document into a session.

    Ambiguous input is handled deterministically: a step with none of the
    documented shapes (``tool_calls``, ``message``, ``observation``) becomes
    a generic ``hermes_observer_span`` event rather than being dropped; a
    non-object step, or a ``tool_calls`` entry missing its required
    ``tool_call_id``/``function_name``, is skipped and counted (see
    :func:`import_fidelity_declaration`), never silently coerced. Message
    and observation text is never copied verbatim (see module docstring
    payload-hygiene note) -- only bounded evidence (presence, character
    length) is recorded.
    """
    session_id = str(payload.get("session_id") or fallback_id)
    agent = json_document(payload.get("agent")) or {}
    model_name = _optional_str(agent.get("model_name"))
    steps_value = payload.get("steps")
    raw_steps: list[JSONValue] = steps_value if isinstance(steps_value, list) else []
    subagents_value = payload.get("subagent_trajectories")
    raw_subagents: list[JSONValue] = subagents_value if isinstance(subagents_value, list) else []

    events: list[ParsedSessionEvent] = []
    skipped = 0
    for index, raw_step in enumerate(raw_steps):
        step = json_document(raw_step)
        # `json_document()` returns `{}` (falsy), never `None`, for a
        # non-object entry -- `not step` is the real "malformed" check
        # (also matches a genuinely empty step object: neither case carries
        # a recognizable shape, so both are skipped and counted the same way
        # `_events_for_step`'s tool_call entries are).
        if not step:
            skipped += 1
            continue
        step_events, step_skipped = _events_for_step(step, index, model_name)
        events.extend(step_events)
        skipped += step_skipped

    for index, raw_subagent in enumerate(raw_subagents):
        subagent = json_document(raw_subagent)
        if not subagent:
            skipped += 1
            continue
        events.append(_subagent_span_event(subagent, index))

    llm_events = sum(1 for e in events if e.event_type == "hermes_llm_request_span")
    tool_events = sum(1 for e in events if e.event_type == "hermes_tool_execution_span")
    subagent_events = sum(1 for e in events if e.event_type == "hermes_subagent_span")
    generic_events = sum(1 for e in events if e.event_type == "hermes_observer_span")

    summary_text = (
        f"Hermes ATIF trajectory: {len(raw_steps)} step(s) "
        f"({tool_events} tool call span(s), {llm_events} message span(s), "
        f"{subagent_events} subagent trajectory(ies), {generic_events} unrecognized, "
        f"{skipped} unparseable)."
    )
    provider_session_id = observer_session_provider_id(session_id)
    return ParsedSession(
        source_name=Provider.HERMES,
        provider_session_id=provider_session_id,
        title=f"Hermes ATIF trajectory: {session_id}",
        messages=[
            ParsedMessage(
                provider_message_id=f"{provider_session_id}:trace-summary",
                role=Role.SYSTEM,
                text=summary_text,
                blocks=[ParsedContentBlock(type=BlockType.TEXT, text=summary_text)],
                position=0,
                variant_index=0,
                is_active_path=True,
                material_origin=MaterialOrigin.RUNTIME_CONTEXT,
            )
        ],
        session_events=[
            ParsedSessionEvent(
                event_type="hermes_observer_trace_correlation",
                payload={
                    "hermes_conversation_session_id_prefix": session_id,
                    "join_key": "sessions.native_id",
                    "note": (
                        "This session carries observer-layer evidence only; correlate with the "
                        "state-db-ingested conversational session sharing this raw Hermes session id."
                    ),
                },
            ),
            *events,
        ],
        ingest_flags=["hermes:atif-trajectory"],
    )


def _events_for_step(step: JSONDocument, index: int, model_name: str | None) -> tuple[list[ParsedSessionEvent], int]:
    tool_calls = step.get("tool_calls")
    message = step.get("message")
    observation = step.get("observation")
    events: list[ParsedSessionEvent] = []
    skipped = 0

    if isinstance(tool_calls, list) and tool_calls:
        for tool_call_raw in tool_calls:
            tool_call = json_document(tool_call_raw)
            tool_call_id = tool_call.get("tool_call_id") if tool_call else None
            function_name = tool_call.get("function_name") if tool_call else None
            # `json_document()` returns `{}` (falsy), never `None`, for a
            # non-document entry -- `not tool_call` catches that case.
            if not tool_call or not isinstance(tool_call_id, str) or not isinstance(function_name, str):
                skipped += 1
                continue
            arguments = tool_call.get("arguments")
            events.append(
                ParsedSessionEvent(
                    event_type="hermes_tool_execution_span",
                    payload={
                        "step_index": index,
                        "tool_call_id": tool_call_id,
                        "function_name": function_name,
                        "has_arguments": arguments is not None,
                        "has_observation": observation is not None,
                    },
                )
            )
        return events, skipped

    if isinstance(message, str) and message:
        events.append(
            ParsedSessionEvent(
                event_type="hermes_llm_request_span",
                payload={
                    "step_index": index,
                    "model": model_name,
                    "message_char_len": len(message),
                },
            )
        )
        return events, skipped

    if observation is not None:
        events.append(
            ParsedSessionEvent(
                event_type="hermes_observer_span",
                payload={"step_index": index, "shape": "observation_only"},
            )
        )
        return events, skipped

    # No recognized shape (no tool_calls, no message, no observation): ambiguous
    # input is never dropped, per AC -- surfaced as a generic observer span.
    events.append(
        ParsedSessionEvent(
            event_type="hermes_observer_span",
            payload={"step_index": index, "shape": "unrecognized", "source": step.get("source")},
        )
    )
    return events, skipped


def _subagent_span_event(subagent: JSONDocument, index: int) -> ParsedSessionEvent:
    agent = json_document(subagent.get("agent")) or {}
    steps = subagent.get("steps")
    return ParsedSessionEvent(
        event_type="hermes_subagent_span",
        payload={
            "subagent_index": index,
            "subagent_session_id": _optional_str(subagent.get("session_id")),
            "subagent_agent_name": _optional_str(agent.get("name")),
            "subagent_step_count": len(steps) if isinstance(steps, list) else None,
        },
    )


def import_fidelity_declaration(session: ParsedSession) -> HermesImportFidelity:
    """Declare the fidelity this ATIF importer can substantiate.

    A redacted ATIF-v1.7 export generated by the bundled Hermes NeMo Relay
    plugin confirms the top-level wire shape and message-only step mapping.
    Those observed LLM spans are ``exact``; shapes not present in that run
    remain ``inferred``. ``decision_points``/``error_taxonomy`` are honestly
    ``absent`` -- ATIF carries no approval/error-hook vocabulary (that lives
    only in the separate raw ATOF event stream, not ingested by this pass).
    """
    span_events = [
        event
        for event in session.session_events
        if event.event_type
        in {"hermes_llm_request_span", "hermes_tool_execution_span", "hermes_subagent_span", "hermes_observer_span"}
    ]
    total = len(span_events)
    llm_spans = sum(1 for event in span_events if event.event_type == "hermes_llm_request_span")
    tool_spans = sum(1 for event in span_events if event.event_type == "hermes_tool_execution_span")
    subagent_spans = sum(1 for event in span_events if event.event_type == "hermes_subagent_span")
    generic_spans = sum(1 for event in span_events if event.event_type == "hermes_observer_span")

    def capability(
        observed: int,
        detail: str,
        *,
        verified_by_real_fixture: bool = False,
    ) -> HermesFidelityCapability:
        status: HermesFidelityStatus = (
            "exact" if observed and verified_by_real_fixture else "inferred" if observed else "absent"
        )
        return HermesFidelityCapability(
            status=status, observed=observed, expected=max(total, 1), counts={}, detail=detail
        )

    capabilities = {
        "llm_request_spans": capability(
            llm_spans,
            "Message-only trajectory steps mapped to LLM response evidence (text length only, no content); "
            "confirmed by the real NeMo Relay ATIF-v1.7 fixture.",
            verified_by_real_fixture=True,
        ),
        "tool_execution_spans": capability(
            tool_spans, "tool_calls entries mapped to tool execution spans (ids/names, arguments presence only)."
        ),
        "subagent_delegation": capability(
            subagent_spans,
            "subagent_trajectories entries recorded as delegation evidence; NOT materialized into "
            "topology_edges/session_links in this pass -- deferred, see module docstring.",
        ),
        "decision_points": HermesFidelityCapability(
            status="absent",
            observed=0,
            expected=max(total, 1),
            counts={},
            detail="ATIF's documented step schema carries no approval-hook vocabulary; that evidence "
            "exists only in the raw ATOF event stream, not ingested by this pass (see fs1.2.1).",
        ),
        "error_taxonomy": HermesFidelityCapability(
            status="absent",
            observed=0,
            expected=max(total, 1),
            counts={},
            detail="ATIF's documented step schema carries no error-hook vocabulary; that evidence "
            "exists only in the raw ATOF event stream, not ingested by this pass (see fs1.2.1).",
        ),
        "topology_edges": HermesFidelityCapability(
            status="absent",
            observed=0,
            expected=max(subagent_spans, 1),
            counts={},
            detail="Physical topology_edges materialization from subagent_trajectories is out of scope for this pass.",
        ),
    }
    if generic_spans:
        capabilities["unrecognized_step_shapes"] = HermesFidelityCapability(
            status="degraded",
            observed=generic_spans,
            expected=max(total, 1),
            counts={},
            detail="Steps matching none of the documented shapes (tool_calls/message/observation) are "
            "retained as generic evidence, never dropped.",
        )
    caveats = tuple(f"{name}: {cap.detail}" for name, cap in capabilities.items() if cap.status != "exact")
    return HermesImportFidelity(
        producer="Hermes NeMo Relay ATIF trajectory export (live-generated ATIF-v1.7 fixture verified)",
        schema_version=1,
        profile_namespace=None,
        acquisition_method="json_fallback",
        retained_blob_reproducibility=HermesFidelityCapability(
            status="exact",
            observed=1,
            expected=1,
            counts={},
            detail="The raw ATIF document bytes are retained before parsing, like every other origin.",
        ),
        capabilities=capabilities,
        caveats=caveats,
    )


def _optional_str(value: object) -> str | None:
    return value if isinstance(value, str) and value else None


__all__ = [
    "ATIF_SCHEMA_VERSION_PREFIX",
    "HermesSpanEventType",
    "hermes_observer_session_id_for",
    "import_fidelity_declaration",
    "looks_like_atif_payload",
    "marker_payload",
    "observer_session_provider_id",
    "parse_atif_document",
]
